### ISSUE TITLE
Environment of proof does not work?

### ISSUE THREAD

**Issue by opt-gaobin** [mohuangrui/ucasthesis#100]

**Comment by opt-gaobin** [comment]
I observe that 'artratex.sty' does not support 'amsthm' package in 'Math packages' setting, which is essential package for proof environment. 
When I added it to my 'artratex.sty', the compile will success.

**Comment by mohuangrui** [comment]
Yes, amsthm is not included as default. I will load it as default at next update. Thank you very much for your suggestion.
