### ISSUE TITLE
paflatex编译，标题中的英文和数字不是times？

### ISSUE THREAD

**Issue by xiaoyaoE** [mohuangrui/ucasthesis#101]

**Comment by zepinglee** [comment]
MWE? 截图？

**Comment by mohuangrui** [comment]
@xiaoyaoE  pdflatex 编译器对字体的设定功能比较有限，若需要完整的字体样式，请使用 xelatex 编译器。

**Comment by xiaoyaoE** [comment]
@zepinglee 

这是用pdflatex编译的结果
![image](https://user-images.githubusercontent.com/12393719/52514589-1604df00-2c4e-11e9-9c38-8484ecc30681.png)

这是用xelatex编译的结果
![image](https://user-images.githubusercontent.com/12393719/52514630-827fde00-2c4e-11e9-99f3-ae718a7770b0.png)

@mohuangrui 
关于字体的问题，抱歉，我对latex的半生不熟，但是根据我的经验，在linux平台下，使用中文时，pdflatex+zhmCJK编译速度应该是快于xelatex+Ctex的，正式的文章对字体的要求一般不会超出中易这套字体范围，所以在很多情况下，我一般会倾向于选择pdflatex

另外，模版使用中易这套字体时(fontset=windows), xelatex编译后文档无法复制的问题，我发现在不使用黑体出粗体的情况下可以屏蔽AutoFakeBold解决，
`\setCJKmainfont[BoldFont={SimHei},ItalicFont={KaiTi}]{SimSun}`

不知这样做是否有其他影响？

最后请教一下如何修改目录的字体？

**Comment by mohuangrui** [comment]
@xiaoyaoE 
1. 正常情况下，编译速度上的差异应该不至于成为这般重要的因素。pdflatex+zhmCJK 大致相当于 xelatex+xeCJK。无论pdflatex还是xelatex，文档结构元素的汉化仍是靠ctex来实现的，除非你自己把ctex做的再做一遍。pdflatex下标题中的数字似乎被判定为汉字，导致\sffamily给数字调用的是黑体而不是times，具体缘由和如何修正我也不知道该怎么做。。。xelatex时\sffamily对中英字体调用正常。

2. 之所以启用autofakebold就是为了解决加粗宋体和加粗黑体的问题，若可以不在乎使用黑体替换粗宋体，又何须在意标题中的数字不是times呢。目前而言，若想遵从所要求的字体样式，能实现的折中的办法就是使用xelatex编译，并安装调用adobe或是mac中文字体，具体见 [字体配置](https://github.com/mohuangrui/ucasthesis/wiki/字体配置)

3. 目录字体的修改请见 ucasthesis.cls 底部的 Configure table of contents。

**Comment by xiaoyaoE** [comment]
@mohuangrui 

这个呀，很多时候真不是我们自己能决定的，能用微软这套字体还是尽量使用。

1.  首先我们的论文标题并没有粗黑体的要求，所以我可以在整篇论文里不使用粗黑体。
2. 对于喜欢挑格式的老师们来说，标题是不是times是能一眼能看出来的，至于在正文里偶尔使用黑体表示强调，好像就没人管了。
3. adobe字体虽然整体看起来基本微软这套字体很相似，但是符号部分的区别还是能一眼看出来的，被人挑了都没法说理
4. 我知道`pdflatex+zhmCJK`等同的概念是`xelatex+xeCJK`，其实我想说的是`pdflatex+Ctex`，为了明确区分底层字体的不同所以用zhmCJK表示，我猜测使用`pdflatex+Ctex`时，`Ctex`应该使用了类似于`zhmCJK`类似的字体选择机制。。。其实如果使用微软这套字体，用pdflatex也挺方便的，仅个人感觉
5. 我今天发现[xiaoyao9933](https://github.com/xiaoyao9933/UCASthesis)这个UCASthesis实现，pdflatex编译标题是数字是times的，但是实现好像相对底层，我并没有看懂
6.  编译速度我觉得很重要啊，latex不是美改动一部分就编译看看吗？我一般都这么做的，方便排错，这时候使用1s编译和5s编译感觉还是很明显的。难道你们不是这么做，我太弱鸡了？有什么好技巧？

**Comment by xiaoyaoE** [comment]
ucasthesis.cls 的 Configure table of contents里三个`renewcommand`
```
\renewcommand*{\@dottedtocline}
\renewcommand*{\l@part}[2]
\renewcommand*{\l@chapter}[2]
```
然而我并没有看到如何分别设置chapter、section、subsection等目录的字体格式，实在如法下手，不知有什么推荐的文档？

**Comment by mohuangrui** [comment]
@xiaoyaoE 
你好，
1. 关于黑体和宋体加粗的问题，请参考官方发布的Word文档，如：
```
博士/硕士学位论文 黑体加粗
论文题目 黑体小三号加粗,单倍行距
作者姓名 宋体四号加粗
各章标题 黑体四号加粗
图标标题  宋体五号加粗
```
等等，不一而足。至于按照你说的那样，哪些可以遵守哪些不可以遵守就好，这样的双标讨论似乎并无实质意义。关于adobe字体，中文字体自重的样式不是微软说了算，按照你的意思，方正字体等都是伪中文？

2. 据我的测试，pdflatex+ctex 与 xelatex+ctex 在编译速度上并无确定的优劣，似乎更无法实现你所说的 1s 和 5s 之差。关于编译速度的提升，若是小于20页的paper，基本无需考虑编译延迟的问题。若是大型文档，最有效的就是选择性加载，只编译当前的编辑文件而不是整个文档，这个在ucasthesis有两种实现，即：

2.1 通过 `Mainmatter.tex` 来控制当前所加载的章节文件，无需加载的章节只需注释掉即可：
```
%---------------------------------------------------------------------------%
%->> Main content
%---------------------------------------------------------------------------%
\input{Tex/Chap_Intro}
\input{Tex/Chap_Guide}
%---------------------------------------------------------------------------%
```
2.2 通过 `Thesis.tex` 中的 `\includeonly` 命令来控制加载
```
%---------------------------------------------------------------------------%
%->> Document inclusion
%---------------------------------------------------------------------------%
%\includeonly{Tex/Chap_1,...,Tex/Chap_N}% selected files compilation
```
至于详细的使用方法，则请了解 `\includeonly` 命令。

3. 关于你说的 “casthesis.cls 的 Configure table of contents里三个`renewcommand`“，这些命令位于LaTeX基本类的原始定义里。若需了解，请阅读LaTeX基本类：article，book等的定义文件，以及 `The LaTeX Companion`书籍。

4. 最后，关于pdflatex+ctex的章节标题数字不为times的问题，根据你的Git ID 和 Email 签名，似乎你就是 Xiao Yao，即  xiaoyao9933 的作者，所以，若你知道如何修正，请不吝赐教，同时，不知你能否在pdflatex+微软字体的配置下，解决国科大官方中英文字体的所有要求，同时保证文档可以被正常copy。感谢～

**Comment by xiaoyaoE** [comment]
@mohuangrui 

你好！

感谢你的回复和解答，以及你无私开源的ucasthesis模版。

首先说明的是，Xiao Yao确实是我的名字，单我并不是xiaoyao9933，这是巧合，所以你所说的赐教，目前我能力不及，抱歉。如果后续我找到解决在pdflatex+微软字体的配置下，解决中英文字体的的办法，会给你发邮件。

我不是中科院的学生，我们学校的毕业论文格式要求与中科院的有区别，各章标题以及图标题注并没有粗体的要求。我现在是基于你的模版改成符合我们学校要求的格式，当然封面等几个地方会少量用到粗体，目前我也没有什么办法，先想办法把正文格式改好。

我并没有adobe字体或者方正字体等是伪中文的意思，而且如果可以，我也不想去碰这种字重不足问题导致需要认为硬生生hack的问题。我实际上认真比较过adboe和微软的字体渲染结果，以我的渣审美，并没有看不出什么明显的区别，比较明显的区别是符号特别是用的很多的逗号。至于符号部分的与微软这套字体的区别，格式审查的老师是否允许使用，我也不知道，我们能做的就是尽量与word版本的看起来一致，所以能用微软这套字体尽量使用。

关于latex的编译速度问题，有时真是个迷，毕竟底层的东西我没那么了解，纯粹是我的经验而已：
pdflatex比xelatex快是我之前比较得到的经验，我一致觉得是因为xelatex调用字体机制问题产生的，另一方面，我自己实验的结果，xelatex在windows和linux平台上的编译速度也是差异巨大，同一台电脑，linux平台比windows快5倍以上是有可能的。因为xelatex存在的各种问题，国内有人做了[ptex-ng](https://github.com/clerkma/ptex-ng)，是挺快的，但是因为ptex-ng使用度不够高，我不确定会不会碰到无法解决的bug，所以目前我还是使用pdflatex或者xelatex，你要是有兴趣可以看看。

我重新在我的电脑上分别使用pdflatex+ctex 与 xelatex+ctex编译casthesis模版，发现速度差别并不明显，让我对xelatex慢的印象有些改观。当然我最近升级了texlive2018，不确定跟这个有没有关系。

目录字体的问题，我在瞎试之下把dottedtocline里的字体改了，才发现原来是指定2级标题之上的目录格式，说实话，单从dottedtocline这个名字确实没有想到。

目前我正文部分我还需要解决图表中英文题注之间行间距问题（1.2倍），试了几种命令，并没有达到我的要求，如果你知道如何改，请赐教。谢谢

最后，这种长篇的讨论已经超出本issues主题范围，而且相关问题也不算bug，如果后续有需要帮助，能否给你直接发邮件？

**Comment by mohuangrui** [comment]
@xiaoyaoE 

嗯，编译速度上，是和操作系统以及LaTeX编译器有关，一般而言，Linux比Windows快，texlive比miktex快。

那些目录相关的命令，你多试试就知道，用LaTeX就是那样的，多试试就明白了，我也是这么整的。

图标标题行间距的问题，可见 caption package，即：

```
 the caption will be type- set with single spacing as default. This can be changed by specifying either font=onehalf- spacing, font=doublespacing, or font={stretch=⟨amount⟩}
```

具体例子如下：
```
\RequirePackage[font={small,bf,stretch=1.2},skip=8pt,labelsep=space]{caption}% options: [margin=10pt,labelfont=bf]
```
好的，以后邮件沟通～

**Comment by xiaoyaoE** [comment]
@mohuangrui 
谢谢解答！

**Comment by mohuangrui** [comment]
@xiaoyaoE  你好，标题的那个问题找到解决方案了，问题不在ctex，因为常规排版下，章节标题调用的\sffamily 就应该是 sans 字体，而不应该是 times 类的serif字体。xelatex 之所以会是 times 是因为通过 fontspec 手动将 \sffamily  改为了 times。在 pdflatex 下，若需将标题的英文改为 times，方法可以很复杂，因为 pdflatex 的英文字体调用一半都嵌套在 font package 里。但也可以很简单，即在 artratex.sty 中使用：
```
    \RequirePackage{newtxtext}% main font
    \renewcommand{\sfdefault}{\rmdefault}% sans font
```
原理为通过
```
    \renewcommand{\sfdefault}{\rmdefault}% sans font
```
将 \sffamily 全替换为 \rmfamily 从而使标题英文改为调用 times 字体。

**Comment by xiaoyaoE** [comment]
@mohuangrui 
谢谢！

其实从排版的角度，标题使用sans的话，数字和英文也应该统一用sans，而我们国内通用的英文和数字全局使用Times更多的是历史遗留问题，Times本身又属于serif，造成了不统一，本身也不是很符合latex的排版原则的，这种问题确实很无奈，说实话，最近我都是放弃了使用pdflatex而使用xelatex。

再次谢谢你的工作！

**Comment by mohuangrui** [comment]
是的，“从排版的角度，标题使用sans的话，数字和英文也应该统一用sans”。只是我们大多数人的排版认知似乎局限在对Word的初浅使用里，导致出现这种times一统全文的用法，实为无奈。
