### ISSUE TITLE
傅里叶变换符号显示感觉不对

### ISSUE THREAD

**Issue by DRjy** [mohuangrui/ucasthesis#102]
![image](https://user-images.githubusercontent.com/46476977/52528664-dd810600-2d1e-11e9-8c68-63ae0a5406b9.png)
我用的命令\mathcal{F}，想问一下该如何调？谢谢了

**Comment by zepinglee** [comment]
哪里不对？

**Comment by mohuangrui** [comment]
你好,

1. \mathcal{F} 所产生的是符合规范的，如：

<img width="187" alt="screen shot 2019-02-10 at 20 16 19" src="https://user-images.githubusercontent.com/7518165/52542719-bce19c00-2d70-11e9-96d1-7c922a8fbf08.png">

2. 如果你想要手写的样式的，则在 `artracom.sty` 中添加：
```
%---------------------------------------------------------------------------%
%->> User defined commands
%---------------------------------------------------------------------------%
\RequirePackage{mathrsfs}% script style math symbols
```
然后使用
```
$\mathscr{F}$, $\mathscr{L}$
```
产生的就是：
<img width="187" alt="screen shot 2019-02-10 at 20 18 48" src="https://user-images.githubusercontent.com/7518165/52542760-15b13480-2d71-11e9-841f-a71eddf5d57e.png">

祝好

**Comment by DRjy** [comment]
![image](https://user-images.githubusercontent.com/46476977/52542978-3fee0b00-2de0-11e9-900c-c8d03016dc6c.png)
其实我是想要这样的符号。
我是通过在user defined commands中添加了如下包解决的：
\usepackage[cal=cm]{mathalfa} % To get the right classical Fourier symbol

弱弱地问一下，感觉一般教科书或者是文献上傅里叶符号用如上截图的比较多吧？像这个模板提供的默认的符号，感觉很少见吧。

**Comment by mohuangrui** [comment]
既然你找到你想要的样式，那就好了～
我不知道你们所接触的教科书，记得我当年读的，大多都是用的：
![image](https://user-images.githubusercontent.com/7518165/52545654-0c32c700-2d87-11e9-90d9-09f863fd278c.png)
总而言之，用哪一个样式并不重要，重要的是你自己一致地使用一个样式。祝好～

**Comment by xiaoyaoE** [comment]
模版用newtxmath是为了让公式字体看起来更接近times，但我觉得latex默认的`\mathcal`字体好像也广泛用于论文以及教材，反而newtxmath的`\mathcal`看起来优点怪

`\usepackage[cal=cm]{mathalfa}`感觉是一种又额外引入一个包的折衷办法，但查了newtx文档很奇怪没找到将切换`\mathcal`到默认字体的方法，不知道有没有其他办法呢（不引入其他包）？

**Comment by mohuangrui** [comment]
@xiaoyaoE 使用LaTeX不同于写操作系统，不必忧心多加载一个package的问题，通过加载package来实现需要的功能就是latex的工作理念。

**Comment by zepinglee** [comment]
两种风格的字母都是“Script letters”，只是两种不同的 style，在 unicode 的编码里甚至不作区分。所以，全文统一使用一种风格就可以了。

@mohuangrui 数学字体这里有很多坑，不建议载入过多宏包。

**Comment by mohuangrui** [comment]
@zepinglee  是的，数学字体有太多的变种和样式了，确实不宜使用过多的宏包。正如 @xiaoyaoE 所说，使用 newtxmath 是为了让公式字体更接近times，但其会导致 \mathcal 的样式产生些变化。

\mathcal 被称作 “calligraphic alphabet ”，\mathscr 为 “math script”，特点都是带些艺术性的书写体，在英文里实际意义的区别我也弄不清楚，也正如你所说，两者在unicode里的编码常不做区分，只是不同的样式（style），在语义（schematic）上是一致的。

总而言之，用哪一个样式并不重要，重要的是一致地使用一个样式。

**Comment by mohuangrui** [comment]
刚读了下 newtxmath，mathrsfs，和 mathalfa 的 package 文档，发现它们都承担着不同的角色和任务，而且并无重复和冲突，所以同时使用这三者以实现所需的样式是可行的，即：

newtxmath: 使数学公式字体接近 times 字体。
mathrsfs：提供 \mathscr 命令以产生 math script 样式。
mathalfa：为 \mathcal, \mathbb, \mathfrak 和 \mathscr 加载特定的字体样式并修复一些数学字体映射的问题。
大家可以根据自己的切实需要作出抉择。
