### ISSUE TITLE
如何修改英文封面信息

### ISSUE THREAD

**Issue by conwaylee** [mohuangrui/ucasthesis#103]
A thesis submitted to the
University of Chinese Academy of Sciences
in partial fulfillment of the requirement

想要去掉第一行最后一个单词 the, 请问在哪里修改? 非常感谢

**Comment by conwaylee** [comment]
找到了, 修改Style文件夹下的ucasthesis.cfg问卷

**Comment by conwaylee** [comment]
找到了, 修改Style文件夹下的ucasthesis.cfg文件

**Comment by mohuangrui** [comment]
嗯，是的，那个the是特意加的，这个是一个纠缠的问题，请见 #16
