### ISSUE TITLE
一行排列两个图，即子图排列问题

### ISSUE THREAD

**Issue by DRjy** [mohuangrui/ucasthesis#104]
以前习惯用subfig包中的\subfloat命令。但是引入\subfig包后发现与artratex.sty中的subcaption包冲突。我把这个包注释掉以后，\subfloat命令可以使用。但是不知道会不会引发其它问题。

另外，感觉subfigure，已经被subfig替代了。作者考虑更新到最新的包吗？谢谢了

**Comment by xiaoyaoE** [comment]
` \subfig` 也已经deprecated 了，ucasthesis用的是`\caption` 和` \subcaption`组合

**Comment by mohuangrui** [comment]
是的，正是如此，推荐用subcaption而不是subfig
