### ISSUE TITLE
【感谢大佬分享】请问跟学校2019年2月学校给出的论文格式规范说明是一致的吗？

### ISSUE THREAD

**Issue by cld378632668** [mohuangrui/ucasthesis#107]
【感谢大佬分享】请问跟学校2019年2月学校给出的论文格式规范说明是一致的吗？

**Comment by mohuangrui** [comment]
呃，我不知道19年2月又有新的规范呃。不是2018年2月才发布的新版么，现在还在过年吧，又会有新版？

**Comment by mohuangrui** [comment]
若有的话，麻烦你对照一下，并提供下新版和当前版的差异，感谢～

**Comment by cld378632668** [comment]
![default](https://user-images.githubusercontent.com/14916170/52766884-9a4ace00-3063-11e9-91f1-49ffc30bec34.png)

上图（使用指南）中提到的 最新的中国科学院大学学位论文 要是能标注具体的年月时期 的话，真是非常棒！

**Comment by cld378632668** [comment]
> 
> 
> 呃，我不知道19年2月又有新的规范呃。不是2018年2月才发布的新版么，现在还在过年吧，又会有新版？

[附件17：中国科学院大学研究生学位论文撰写规范指导意见.pdf](https://github.com/mohuangrui/ucasthesis/files/2863609/17.pdf)

附件是 2019年2月我们学院的老师发给我们的 《中国科学院大学研究生学位论文撰写规范指导意见》

**Comment by mohuangrui** [comment]
呃，那个就是2018年2月发布的。。。文档里没必要给出时间，国科大官方样式的修改多年才可能有一次，而且18年2月发布的基本就是国科大终版了。若是指明时间，国科大各所协调不一致，像你现在提出的，所老师发一遍文件就是出了新版，则更是难以说清楚。

**Comment by yunyun2019** [comment]
> > 呃，我不知道19年2月又有新的规范呃。不是2018年2月才发布的新版么，现在还在过年吧，又会有新版？
> 
> [附件17：中国科学院大学研究生学位论文撰写规范指导意见.pdf](https://github.com/mohuangrui/ucasthesis/files/2863609/17.pdf)
> 
> 附件是 2019年2月我们学院的老师发给我们的 《中国科学院大学研究生学位论文撰写规范指导意见》

我们所2018年11月30日就发布了新规定，主要不一样的地方就是在参考文献部分。

**Comment by mohuangrui** [comment]
你好，请问可以明确地给出不一样的地方吗？根据你提供的那个包含规范的PDF：
 ```
(四)参考文献
各学科群可根据需要制定相应的参考文献格式规范，可参照国际刊物通行的参考文献格式，或者参照 GB/T 7714—2015《信息与文献参考文献著录规则》执行。”
```
```
著录项目与 GB/T 7714—2015《信息与文献 参考文献著录规则》 中规定的顺序编码制基本相同，不同的仅为出版年份排于编著者之 后。
```
不太清楚当前ucasthesis所采用的和上述要求有和冲突？
