### ISSUE TITLE
中文指导老师没有居中？

### ISSUE THREAD

**Issue by zhxing001** [mohuangrui/ucasthesis#109]
刚开始学 啊，中文指导老师没有居中啊发现？

**Comment by mohuangrui** [comment]
由于下划线前有标头文字，居中只能是页面居中或是下划线居中。出于美观，模版采用的是页面居中。

**Comment by ZR-Huang** [comment]
请问如何设置下划线居中呢？因为研究所的名字较长，左边就覆盖了“指导老师”这几个字

**Comment by mohuangrui** [comment]
@ZR-Huang  见 https://github.com/mohuangrui/ucasthesis/wiki/常见问题#为何封面下划线上的文本不居中下划线
