### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by ShijieLi** [mohuangrui/ucasthesis#11]
如下图所示
![jietu](https://cloud.githubusercontent.com/assets/866777/14343153/97407750-fcd1-11e5-864c-0b24bdf6f1f1.png)

左边的书签栏里，Abstract和表格列表之间是不是应该加个“目录”？

**Comment by mohuangrui** [comment]
Hi, thank you very much for this suggestion, I have fixed it, please have a try with the latest one.

Thanks!
