### ISSUE TITLE
编译出现error：! LaTeX Error: \CJKunderlinecolor undefined.

### ISSUE THREAD

**Issue by niasw** [mohuangrui/ucasthesis#110]
使用版本：branch master fb4bb7961a56239a011d0f1575109ed5fae8c420
编译环境：Win10, CTEX v2.9.2.164
编译运行：artratex.bat
编译记录：
> This is XeTeX, Version 3.1415926-2.3-0.9997.5 (MiKTeX 2.9) (preloaded format=xelatex 2019.2.19)  21 FEB 2019 18:05
> entering extended mode
> **Thesis
> (D:\IOP2\Thesis\ucasthesis-master\Thesis.tex
> LaTeX2e <2011/06/27>
> Babel <v3.8m> and hyphenation patterns for loaded.
> (D:\IOP2\Thesis\ucasthesis-master\Style/ucasthesis.cls
> 
> ...省略一堆无关紧要的包引用log...
> 
> ! LaTeX Error: \CJKunderlinecolor undefined.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.124     \renewcommand{\CJKunderlinecolor}
>                                            {\color[rgb]{0,0,0}}% set underli...
> 
> ? x
>  
> Here is how much of TeX's memory you used:
>  14669 strings out of 430478
>  312025 string characters out of 3191502
>  304635 words of memory out of 3000000
>  17668 multiletter control sequences out of 15000+200000
>  3688 words of font info for 20 fonts, out of 3000000 for 9000
>  14 hyphenation exceptions out of 8191
>  63i,0n,37p,932b,150s stack positions out of 5000i,500n,10000p,200000b,50000s
> No pages of output.

**Comment by niasw** [comment]
方才注意到不推荐CTEX环境了，更换为最新texlive应该就好了。

**Comment by GitatHub** [comment]
texlive 2017 没有这个问题，texlive 2020 这个问题重现了
