### ISSUE TITLE
LaTex Error: \CJKunderlinecolor undefined

### ISSUE THREAD

**Issue by August15** [mohuangrui/ucasthesis#111]
Window 双击artratex.bat脚本或者用xeLaTex编译都会出现LaTex Error: \CJKunderlinecolor undefined
而用PDFLaTex编译会出现 \LaTex Error: \proofname undefined.

**Comment by mohuangrui** [comment]
你好，请查看使用说明：

“模板每次发布前，都已在 Windows，Linux，MacOS 系统上测试通过。下载模板后，若编译出现错误，则请见 ucasthesis 知识小站的 [编译指南](https://github.com/mohuangrui/ucasthesis/wiki/编译指南)。”

你还可以看下： #110
