### ISSUE TITLE
An complete english word at the end of line will be extended out of boundary

### ISSUE THREAD

**Issue by colleenfyj** [mohuangrui/ucasthesis#112]
This kind of situation is shown in the following figure.
![default](https://user-images.githubusercontent.com/30891518/53284979-18128600-3796-11e9-9136-100f76c28799.PNG)

**Comment by mohuangrui** [comment]
please remember to use a space between monsoon and \citep{}. That is,
```
monsoon \citep{papado...}
```

**Comment by colleenfyj** [comment]
OK, a space solve this problem related with citation. 
But for an normal line, it still happens, as shown in the figure.
![default](https://user-images.githubusercontent.com/30891518/53294883-6c674580-382a-11e9-9b3c-45a7b5cf43fc.PNG)

**Comment by mohuangrui** [comment]
Please try with a space between 64 and 位 too. By the way, formatting a paragraph with a variety of elements is challenging, there is no guarantee that LaTeX can always produce a perfect length for each line. Therefore, there will be small variations.

At last, keeping you LaTeX compiler and packages up-to-date may help produce better results.

Cheers.

**Comment by mohuangrui** [comment]
Does adding a space improve the situation? In general, you can add a space **before** and **after** a non-Chinese character, such as:
1. An English word.
2. A command like \citep{}, \citet{}, \href{}.
3. A number
to help LaTeX break lines more properly.

**Comment by colleenfyj** [comment]
a space between 64 and 位 does help. Thank you very much for your support.

**Comment by colleenfyj** [comment]
I think this case could be closed
