### ISSUE TITLE
关于国科大Logo的问题？

### ISSUE THREAD

**Issue by lyuyilong** [mohuangrui/ucasthesis#116]
您好，根据我们所老师发给我们的最新word模板中，国科大的Logo和该Latex模板中的Logo字体不一样，请问能更改一下么？改地址最下面有模板，谢谢！http://onestop.ucas.edu.cn/home/info/abc167cb-4589-4e05-b014-052fa9291d0c/1

**Comment by mohuangrui** [comment]
你好，上述链接所给模版为2013年的，当前ucasthesis采用的为2018的样式。

**Comment by lyuyilong** [comment]
谢谢，那就是我们所老师的模板没有更新。
