### ISSUE TITLE
正文的字体有时候突然自动加粗

### ISSUE THREAD

**Issue by jindongwang** [mohuangrui/ucasthesis#117]
你好：
我在用模版的时候，发现正文的字体有时候突然自动加粗，把这个部分换个位置就又正常了，不知道是啥原因。。。

**Comment by mohuangrui** [comment]
你好，不太清楚你的问题的具体情形，请提供相应的源代码，谢谢

**Comment by jindongwang** [comment]
就是正文里没有加粗，然后编译渲染以后有的段落就莫名其妙加粗了

**Comment by mohuangrui** [comment]
你好，不太清楚你的问题的具体情形，请提供相应的源代码，谢谢

**Comment by jindongwang** [comment]
你看图中，下面的正文突然就被加粗了，源码的话，就是普通的正文，上面和下面是一样的
![qq 20190307214651](https://user-images.githubusercontent.com/6158206/53961007-953ce400-4122-11e9-97e3-05c218b9ba55.png)

**Comment by mohuangrui** [comment]
你好，你若无法提供我所需要的信息，我将无法帮你解决任何问题。请提供上述截图的相应地源代码，谢谢！

**Comment by jindongwang** [comment]
请看下图源代码：
![qq 20190307215604](https://user-images.githubusercontent.com/6158206/53961556-d41f6980-4123-11e9-9110-5afe57e4c990.png)

**Comment by mohuangrui** [comment]
请提供完整的源代码。。。若你再次不能提供相应的信息，请恕我实在无法再继续回答你的问题。

**Comment by mohuangrui** [comment]
你好，鉴于你不再提供相应信息，我将关闭此issue。可以肯定的是问题与 ucasthesis 或 LaTeX 无关，若问题仍然存在，请检查你对
```
\textbf{}, {}
```
等命令的使用。祝好！

**Comment by nihaomiao** [comment]
您好，学长，我也是泛在中心，我最近写论文也遇到这个突然加粗的问题，请问您找到原因了吗？ @jindongwang

**Comment by muzimuzhi** [comment]
需要
 - 提供一个完整的 latex 文档
 - 这个文档在你的电脑上能编译，编译结果能复现你的问题
 - 文档里和复现问题无关的内容尽可能少
@nihaomiao

**Comment by jindongwang** [comment]
我没用这个模板了，迷之调不出来。我用的另一个模板，没啥问题

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Haomiao Ni <notifications@github.com>
发送时间: Sunday, April 14, 2019 9:02:38 PM
收件人: mohuangrui/ucasthesis
抄送: Jindong Wang; Mention
主题: Re: [mohuangrui/ucasthesis] 正文的字体有时候突然自动加粗 (#117)


您好，学长，我也是泛在中心，我最近写论文也遇到这个突然加粗的问题，请问您找到原因了吗？ @jindongwang<https://github.com/jindongwang>

―

**Comment by mohuangrui** [comment]
@jindongwang 你问了一个难以复现的问题，并对提供问题描述和代码的要求多次置之不理，实难以判断问题出在哪里，只能认为是你的错误使用 LaTeX 命令所致。

@nihaomiao 若想问有效的问题，请：

1. 将编译生成的 `Thesis.log` 文件拖入网页上的 `issue 文本框`。

2. 将出现问题处的截图照片拖入网页上的 `issue 文本框` 。

3. 将出现问题附近的代码粘贴入网页上的 `issue 文本框` 。

谢谢。

**Comment by mohuangrui** [comment]
@muzimuzhi 谢谢你一直关注和帮忙～真是热心的好心人～

**Comment by nihaomiao** [comment]
莫学长您好，我把可以复现错误的代码发您github显示的outlook邮箱了，谢谢您的帮助！ @mohuangrui

**Comment by mohuangrui** [comment]
@nihaomiao 你好，非常感谢你发过来的文件，可惜的是我这没能复现你的问题。这样看来，这个问题和特定的编译环境有关，包括 `操作系统`、`LaTeX 编译器及其版本号`、`LaTeX 编译引擎（pdflatex 、xelatex）` 以及 `系统字体配置`。

就我以前的经验，特定情形下，使用 `xelatex` 编译时可能会出现 `.pdf` 格式图片自动加粗，这主要是因为 `ucasthesis` 为了实现国科大指导文件中所要求的`图表标题`为 `加粗宋体`，而 Windows 系统又不具有原生的`加粗宋体`，从而只能启用`伪粗体`，而`伪粗体`容易出现异常。至于 @jindongwang 所说的 [xiaoyao9933](https://github.com/xiaoyao9933/UCASthesis)，其版本用 `ctex` 默认的用 `黑体` 作为 `加粗宋体`，因而回避了此问题。

我推测你使用的 `Windows` + `xelatex` 编译，虽然无法复现你的问题，但也许如下方式可以帮你解决问题：

1.  在 artratex.sty 中注释掉：
```
        \setCJKmainfont[AutoFakeBold,ItalicFont=KaiTi]{SimSun}%
        \setCJKsansfont[AutoFakeBold]{SimHei}%
        \setCJKmonofont{FangSong}%
```
这样应该就好了，但由此将启用 `ctex` 默认的用 `黑体` 作为 `加粗宋体`。

或者

2. 虽然出现过图片加粗，但很少出现文本异常加粗，推测你的问题的出现与过多使用 `\textbf` 命令有关。如果你不想采用方案1，那就请将所有的 `\textbf{}` 特别是制表格中的那些，都改为 `$\mathbf{}$`；而对于不可改的，就用 `{\textbf{}}` 替换 `\textbf{}` 以限定作用域。这样也应该可以解决你的问题。

推荐的是方案2，至于原因，请继续往下看：

仔细检查了一遍你的 LaTeX 源代码，有如下几个小建议以供参考：

1. 具有数学分析意义的数字，诸如 `4.69\%` 应使用 inline math 数学环境，即 `$4.69\%$`，同样的，诸如 `\textbf{70.39}` 应为 `$\mathbf{70.39}$`。

2. 你的制表命令，如
```
\caption{DeepLab-HA和DeepLab的实验结果}
\label{tab:ha}
\begin{tabular}{|l|cccc|c|}
```
不太符合学术规范，学术制表一般要求使用三线表，即只有三横线且不要有竖线。

3. `代码~\cite{chen2018deeplab}` 应为 `代码 \cite{chen2018deeplab}`，不要过度使用 `~` 替代 ` ` 作为空格，因为 `~` 可能导致断行异常。

**Comment by nihaomiao** [comment]
@mohuangrui 
您好，非常感谢您的回复！我尝试了方案2，换mathbf或textbf加作用域，但还是不起作用，我发现我把正文加粗字体放到表格上面时就不会出现正文加粗问题了。（之前是表格在正文加粗字体上面）。我感觉可能跟表格里面的textbf命令有关，但我检查了下感觉没有问题。只能先这样解决吧~

另外，非常感谢您的小建议。

**Comment by mohuangrui** [comment]
@nihaomiao 感谢你的反馈。我也复现了 mathbf 的问题。`\textbf` 的问题是由 Windows 系统无原生加粗宋体所导致的，而 `\mathbf` 的问题则是由国科大不分区分地要求所有英文和数字皆为 Times 字体所导致（实际上章节标题中的英文和数字应为 sans-serif 字体，而非 Times 这样的 serif 字体）。

种种过多的约束，导致若实现这些约束就会导致产生一些异常情形，实在难以找到一种全策。

我将标记这些问题，看以后能不能找到合理的方案。

**Comment by nihaomiao** [comment]
@mohuangrui 原来如此，谢谢您了，加油！

**Comment by mohuangrui** [comment]
@nihaomiao 你好，我在 Windows 系统中复现了你提出的 自动加粗 和 `\mathbf`的问题。 它们已在最新版中修复。本来只想着修复`\mathbf`的问题，但后来发现，修复后自动加粗也消失了。

若有时间，请测试，谢谢

**Comment by nihaomiao** [comment]
你好，感谢您的修复，mathbf确实可以运行了，但是自动加粗问题还是存在。。。，我尝试过去掉所有的bf，然而不能解决这个问题，目前我使用的方法是在表格下面加一个图，这样操作之后，表格下面的文字就不会加粗了。 @mohuangrui

**Comment by nihaomiao** [comment]
你好，我发现我把caption改成bicaption之后就不会出现这个自动加粗问题了 @mohuangrui

**Comment by mohuangrui** [comment]
@nihaomiao 默认的就是 bicaption 啊？

**Comment by nihaomiao** [comment]
对，我之前只想写中文，用的caption，改完就好了 @mohuangrui

**Comment by mohuangrui** [comment]
好的，如果你仍想只用 caption，就可以看看 https://github.com/mohuangrui/ucasthesis/wiki/字体配置 的最底部。即

异常加粗主要缘于加粗图标题文字所导致，从而，则可考虑取消对标题加粗即可，即在 artratex.sty 中将
\RequirePackage[font={small,bf},skip=8pt,labelsep=space]{caption}%

改为

\RequirePackage[font={small},skip=8pt,labelsep=space]{caption}%

**Comment by nihaomiao** [comment]
好的，谢谢！

**Comment by caimingxue** [comment]
你好，我按照说明配置好Auto Build 之后，编译一次Thesis，需要一分多钟，请问这是什么问题

**Comment by muzimuzhi** [comment]
@caimingxue 
你的问题和当前 issue 的已有讨论没有关联，是一个新的问题。新问题建议新建 issue 提问。

**Comment by muzimuzhi** [comment]
> 需要
> 
> * 提供一个完整的 latex 文档
> * 这个文档在你的电脑上能编译，编译结果能复现你的问题
> * 文档里和复现问题无关的内容尽可能少
> 
> （引用自 https://github.com/mohuangrui/ucasthesis/issues/117#issuecomment-482991693 ）

@zoushucai 
以及，强烈建议开一个新 issue。

**Comment by LynnHo** [comment]
@mohuangrui @muzimuzhi 我也发现有些表格或图片后面的某段正文会自行变粗，或者是某两个连着的图片中第二张图片的文字自动变粗。

无意中发现如果在异常变粗内容上方的图或表的caption尾部加一个引用，异常变粗就消失了。所以我们可以添加一个“白色”的引用解决这个问题，如下

`\textcolor{white}{\hypersetup{nolinks=true,citecolor=white}\cite{a}\hypersetup{nolinks=true,citecolor=blue}}`

或者新建一个命令并使用\citew{a}

`\newcommand{\citew}[1]{\textcolor{white}{\hypersetup{nolinks=true,citecolor=white}\cite{#1}\hypersetup{nolinks=true,citecolor=blue}}}
`

注意一定要以引用“结尾”。不知道这是什么bug，但能解决问题

**Comment by gustaavv** [comment]
我是在 windows + xelatex 编译，论文中莫名其妙地有两页文字全是粗体。而 overleaf 中一切正常。

我尝试了设置 `font=adobe`，依旧不行。下面的方法就成功了，十分感谢。

> 在 artratex.sty 中注释掉：
>       \setCJKmainfont[AutoFakeBold,ItalicFont=KaiTi]{SimSun}%
>      \setCJKsansfont[AutoFakeBold]{SimHei}%
>      \setCJKmonofont{FangSong}%
