### ISSUE TITLE
求助：图的中文标题加footnote报错Undefined control sequence。

### ISSUE THREAD

**Issue by gsp2014** [mohuangrui/ucasthesis#118]
您好，在给图的标题加footnote时，英文标题上加没问题，但中文标题上加，会报错Undefined control sequence。

**Comment by mohuangrui** [comment]
你好，似乎 bicaption 不支持 footnote 功能，这个我也没有办法。建议不必在图表题上加脚注。

**Comment by gsp2014** [comment]
好的，谢谢哈。

**Comment by mohuangrui** [comment]
@gsp2014 谢谢你的反馈～直到你提出之前，这个问题从没有被测试过，从而不知道此bug的存在。不管，最后的建议仍是不建议在caption中使用footnote，而是选择更清晰的表达方式。除非特定的学科，footnote一般是不被建议使用的。

**Comment by gsp2014** [comment]
好哒，谢谢您的建议。
