### ISSUE TITLE
关于目录的建议

### ISSUE THREAD

**Issue by ShijieLi** [mohuangrui/ucasthesis#12]
如图所示
![qq20160413-0](https://cloud.githubusercontent.com/assets/866777/14488651/d2522766-019b-11e6-8290-04d17c14bf29.png)

麻烦了，多谢！

**Comment by mohuangrui** [comment]
Hi,
You're perfectionism... Please have a try with the latest version : D 
Thank you very much for your suggestions.
Sincerely,
Mo

**Comment by ShijieLi** [comment]
哈哈，多谢！
