### ISSUE TITLE
求助：编译的时候出现错误“Latex Error: \proofname undefined”

### ISSUE THREAD

**Issue by weili-ict** [mohuangrui/ucasthesis#120]

**Comment by mohuangrui** [comment]
你好，你的 LaTeX 编译器需要安装 `amsthm` 宏包。编译问题详见： (编译指南)[https://github.com/mohuangrui/ucasthesis/wiki/编译指南]

**Comment by mohuangrui** [comment]
@weili-ict 你好，发现这个问题是我判断不够准确，通过另一同学的反馈，推断出问题应是不同年代的 LaTeX 编译器所导致的。\proofname 命令可能是 2015 年后才被 ctex 所引入，导致早期的 LaTeX 编译器找不到该命令。而我的编译器是2018年的，从而检测不出该问题。如今已发布了一个修正版，请测试，谢谢～

**Comment by weili-ict** [comment]
非常感谢！！！
