### ISSUE TITLE
中文封面: 标题中有顿号"、"

### ISSUE THREAD

**Issue by opt-gaobin** [mohuangrui/ucasthesis#121]
您好, 我查看了 "ucasthesis.cls" 中的 \maketitle 定义, 并没有发现不兼容中文标点, 不知道如下是什么原因?

![WX20190311-165758](https://user-images.githubusercontent.com/28487802/54111771-a4bc7580-441f-11e9-8c80-237eacc817b9.png)

**Comment by mohuangrui** [comment]
你好，这个问题的解决请见： [ctex issue #338](https://github.com/CTeX-org/ctex-kit/issues/338)。我后来忘记修正了，现已修改并发布，感谢提醒～
