### ISSUE TITLE
参考文献 引用维基百科的网页链接的latex的样式

### ISSUE THREAD

**Issue by yumh** [mohuangrui/ucasthesis#122]
例如下面是引用book的latex的样式，我想知道引用维基百科的网页链接的latex的样式。
@book{webber2018programmatic,
  title={A programmatic introduction to neo4j},
  author={Webber, Jim and Robinson, Ian},
  year={2018},
  publisher={Addison-Wesley Professional}
}

**Comment by mohuangrui** [comment]
你好，[LaTeX Wikibook](https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management) 给出了详细的清单，如: 

```
If you have to cite a website you can use @misc, for example:

@misc{website:fermentas-lambda,
      author = "Fermentas Inc.",
      title = "Phage Lambda: description \& restriction map",
      month = "November",
      year = "2008",
      url = "http://www.fermentas.com/techinfo/nucleicacids/maplambda.htm"
}
```
