### ISSUE TITLE
粗楷体下的汉字 与粗宋体效果一致？

### ISSUE THREAD

**Issue by e71828** [mohuangrui/ucasthesis#123]
如图：
![image](https://user-images.githubusercontent.com/24602820/54325209-fd685a00-463b-11e9-978f-f56a1e2f247d.png)
**使用fc-list:lang=zh-cn命令** 后得到的可能相关系统字体
`C:\Users\61240>fc-list :lang=zh-cn

C:/Windows/fonts/msyhl.ttc: Microsoft YaHei,Microsoft YaHei Light:style=Light,Regular

C:/Windows/fonts/simfang.ttf: FangSong:style=Regular,Normaa

C:/Windows/fonts/simkai.ttf: KaiTi:style=Regular,Normaali

C:/Windows/fonts/msyh.ttc: Microsoft YaHei UI:style=Normal

C:/texlive/2018/texmf-dist/fonts/truetype/public/arphic-ttf/gkai00mp.ttf: AR PL KaitiM GB:style=Regular

C:/texlive/2018/texmf-dist/fonts/opentype/public/fandol/FandolHei-Regular.otf: FandolHei:style=Regular

C:/Windows/fonts/msyh.ttc: Microsoft YaHei:style=Normal

C:/texlive/2018/texmf-dist/fonts/opentype/public/fandol/FandolSong-Bold.otf: FandolSong:style=Bold

C:/texlive/2018/texmf-dist/fonts/opentype/public/fandol/FandolKai-Regular.otf: FandolKai:style=Regular

C:/texlive/2018/texmf-dist/fonts/opentype/public/fandol/FandolHei-Bold.otf: FandolHei:style=Bold

C:/Windows/fonts/FZSTK.TTF: FZShuTi:style=Regular`

**Comment by mohuangrui** [comment]
你好，主字体 （mainfont ）的设定可以有如下选项：
```
\setCJKmainfont[BoldFont=font1, ItalicFont=font2, BoldItalicFont=font3]{font name}%
```
因为 windows 字体里的 宋体（ SimSun） 没有原生粗宋体，所以 BoldFont 选项无法指定合适的字体，从而用了 AutoFakeBold。同时因为中文里用 楷体 作为 mainfont 的 斜体（italic） 字体形式，从而 ItalicFont指定为 Kaiti，即当前Windows字体的设定为：
```
\setCJKmainfont[AutoFakeBold,ItalicFont=KaiTi]{SimSun}%
```
类似的，你指出的问题则是由于 Windows没有原生粗楷体，从而 BoldItalicFont 无法指定合适的字体，也无法直接为 Kaiti 给定 AutoFakeBold ，从而会被系统自动退回调用 mainfont 即 SimSun 作为替换。

从而当前问题不知该如何在 windowns 字体框架内解决。如果你一定需要加粗楷体，请安装 Mac font，然后 [启用 fontset=mac 选项](https://github.com/mohuangrui/ucasthesis/wiki/字体配置)即可，因为mac 字体是很完备的。

**Comment by e71828** [comment]
非常感谢及时又准确的回复，能否**为windows安装mac字体**再具体介绍下，网上在windows下搞mac字体，我搜到相关是使用[mactpye](https://www.mactype.net/)来安装，我觉得这个对于latex肯定不行，参考 [用 MacType 拯救你的 Windows](https://sspai.com/post/35119)和[MacType 文字之美 – 让 Windows 字体更漂亮](https://www.jianshu.com/p/265df2bd6db5) 得知。
本人水平太渣，也希望大佬能为Windows用户提出更便捷的操作。

**Comment by mohuangrui** [comment]
你好，在 Windows 上安装mac字体会比较麻烦，你需要在 Mac 电脑上收集齐全所需要的字体，然后对部分特定格式的字体进行格式转换，然后再在Windows上安装，并且这一过程存在侵权的风险。

若不想折腾，则不用加粗楷体最好，若是坚持要用，也可以考虑直接在 Mac 电脑上安装 LaTeX 并编译即可。

**Comment by e71828** [comment]
嗯 好吧 谢谢！

**Comment by e71828** [comment]
@mohuangrui 老哥 对于修改模板的话，中文title存在换行的需求，在frontpages里给title加上`\\`，可以实现换行，但是再加下划线`\ulenhance`就gg了。
如果用零宽度盒子加下划线的话，没办法加两条对齐的下划线。
估计只能把标题内容导入class文件手动单行下划线，个人用还行，但是模板的话感觉我有强迫症。
此外，我对于希望模板能对于fontpages里的英文实现定制化修改，即使人名或者Bachelor首字母小写了，尤其是标题和单位，也能通过calss里的代码帮助纠正回来。我尝试Uppercase和MakeUpperCase，MaketextUppercase，哪怕是最简单的情况，都没出现想要的效果。
希望大佬有空时试试。

**Comment by e71828** [comment]
还有cfg里，密级lable后的冒号是英文状态下的。

**Comment by mohuangrui** [comment]
你好，

1. title 里可以自动换行也可以用 `\\` 强制换行，并且换行后下划线显示正常。若你的title的两行文本长度不同但换行后还是想产生一样长度的两条下划线，虽不知道你为什么要这么做，但并非不能很容易的实现：
```
\title{中国科学院大学学位论文\LaTeX{}模板 {$~^{\pi}\pi^{\pi}$} \\ \hspace*{+0.8em} 中国科学院大学学位论文\LaTeX{}模板\hspace*{+0.7em}}% 论文中文题目
```
效果如下：

![image](https://user-images.githubusercontent.com/7518165/54434616-aa8cc080-4769-11e9-8560-84964120fa10.png)


2. 暗地里给人修改对错并不是好的编程原则。

3. 英文冒号是特意的，若想知缘由，请见： [附件：中国科学院大学学位论文中、英文封面.docx](http://onestop.ucas.edu.cn/home/info/abc167cb-4589-4e05-b014-052fa9291d0c/1)

祝好

**Comment by e71828** [comment]
@mohuangrui `\renewcommand{\CJKunderlinebasesep}{0.3em}`似乎不起作用;
再多问几个问题，为什么在class写makeuppercase对于FrontPag定义的文本不生效，而单独另测试文本有效;
章节设定，`ctexset>chapter<Pagestyle=plain>`，该怎么理解;
linespread在class文件里控制行距似乎也有点问题，在thesis里控制行距得加`\selectfont`。

**Comment by e71828** [comment]
deactivate uppercase effect 好吧 我看到这行代码了

**Comment by mohuangrui** [comment]
@e71828 是的，自动大写缩窄了样式范围，即总是被大写，有时会违背用户的意图。所以，不推荐那样做，要大写样式直接输入即可。那我关闭此 issue了。祝好～
