### ISSUE TITLE
请教如何添加英文目录？

### ISSUE THREAD

**Issue by xiaoyaoE** [mohuangrui/ucasthesis#124]
[这儿](https://blog.csdn.net/techcrunch/article/details/2261981)有一个方法，但是我尝试发现，第一个echapter会出错，很奇怪，如果在第一个echapter之前先定义了一个esection后续的就不会有问题。

**Comment by mohuangrui** [comment]
你好，这个问题已超出了 UCAS / ucasthesis 所要考虑的范畴。自动生成需要较多的额外工作，由于能力有限，我无法提供修改帮助。也许你可参考 [texse](https://tex.stackexchange.com/questions/170912/contents-page-in-two-different-languages/170963#170963)

祝好！

**Comment by xiaoyaoE** [comment]
我现在用了比较难看的hack大概能生成一个目录，但是引出了其他问题

```
\newcommand\addengcontents[2]{
        \addcontentsline{toe}{#1}{\protect\numberline{\csname the#1\endcsname}#2}
}
    
\newcommand\echapter[1]{\addengcontents{chapter}{#1}}
```
然后只需要在\chapter{中文标题} 后再加一句\echapter{english title}
这个看起来并没有往tex中添加实质性的内容，但是会导致标题和中文之间有额外垂直空白，我没想明白，如果你能看出问题的话，请指教。

谢谢！

注：hack是指用`addcontentsline`添加完内容之后，硬调用`@starttoc`加目录

**Comment by xiaoyaoE** [comment]
我已经找到了，是`\protect`的问题，但是我生成的目录中，中英文摘要加了编号0，不得已又hack了一个不加编号的`echapter`。请教一下不知道中文目录怎么实现摘要不加编号的？没从代码里看出来？

谢谢

**Comment by mohuangrui** [comment]
有三种方案：
1. 将摘要置于 `\frontmatter` 和 `\mainmatter` 之间。
2. 使用 `\chapter*{摘要}`
3. 自定义一个 \begin{abstract} \end{abstract} 环境。
