### ISSUE TITLE
请问如何修改url字体为黑色，目前所有url都是红色字体

### ISSUE THREAD

**Issue by nextonr** [mohuangrui/ucasthesis#125]
如题

**Comment by e71828** [comment]
colorlinks=true,% false: boxed links; true: colored links

    linkcolor=black,% color of internal links

    citecolor=blue,% color of links to bibliography

    %filecolor=magenta,% color of file links

    urlcolor=red,% color of external links

style里改

**Comment by nextonr** [comment]
感谢楼上的回复，具体来说是在.../Style/artratex.sty文件中修改

**Comment by mohuangrui** [comment]
@e71828 @nextonr 那此issue准备关闭了。因此不只一人问过这个问题，就单独开了一个 wiki page： [链接设置](https://github.com/mohuangrui/ucasthesis/wiki/链接设置) 方便以后的人定位。
