### ISSUE TITLE
您好，图注/表注中如何设定中英文的段前段后距离?模板中和我们研究所的要求不一样？

### ISSUE THREAD

**Issue by levelzhang** [mohuangrui/ucasthesis#126]
图序、图名、图注：置于图的下方，宋体五号居中（英文用Times New Roman体），**1.5倍行距，段前6磅，段后12磅，**图序与图名文字之间空一个汉字符位，图序加粗。图注位于图名下方，标题加粗，左缩进两个汉字符，续行悬挂缩进左对齐

表序、表名、表注：置于表的上方，宋体五号居中（英文用Times New Roman体），**1.5倍行距，段前6磅，段后6磅，**表序与表名文字之间空一个汉字符位，表序和表注标题加粗，表注左缩进两个汉字符，续行悬挂缩进左对齐

谢谢！

**Comment by e71828** [comment]
你需要 图表标题宏包caption

**Comment by levelzhang** [comment]
> 
> 
> 你需要 图表标题宏包caption

option中没找到相关设置，求助
\RequirePackage{graphicx}% packages for including graphics
\RequirePackage[font={small,bf},skip=8pt,labelsep=space]{caption}% options: [margin=10pt,labelfont=bf]
\RequirePackage{subcaption}% package for subfigures
\RequirePackage[list=off]{bicaption}% package for binary captions
\captionsetup[figure][bi-first]{format=hang,hangindent=-0.5em}%
\captionsetup[figure][bi-second]{format=hang,hangindent=-2em,name=Figure}%
\captionsetup[table][bi-first]{format=hang,hangindent=-0.5em}%
\captionsetup[table][bi-second]{format=hang,hangindent=-2em,name=Table}%
\RequirePackage[section]{placeins}% prevent floats from being moved over section

**Comment by e71828** [comment]
点这里，看宏包介绍[caption-English](http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/caption/caption-eng.tex)
如果每导入一个宏包，把每一个选项都讲一下，不是把用户先累死，就是把程序猿先逼死。
看不懂，借本[LaTeX2e 完全学习手册](https://item.jd.com/11445149193.html)。

**Comment by levelzhang** [comment]
> 
> 
> @levelzhang 点这里，看宏包介绍[caption-English](https://gitlab.com/axelsommerfeldt/caption/tree/3.3/doc)
> 其实latex装完自带帮助的，win+R 输入texdoc caption，即可打开caption的说明，同理texdoc ctex 打开ctex宏包说明。
> 如果每导入一个宏包，把每一个选项都讲一下，不是把用户先累死，就是把程序猿先逼死。
> 看不懂英文的话，借本[LaTeX2e 完全学习手册](https://item.jd.com/11445149193.html)。

谢谢！

**Comment by e71828** [comment]
@levelzhang 
win+R 输入texdoc thuthesis，你会有意外收获。你装latex的时候，清华大学的模板就也装进去了。目录大概在。
`~~~texlive\2018\texmf-dist\doc\latex\thuthesis`

**Comment by mohuangrui** [comment]
当前 ucasthesis 的设定综合了很多因素，特别是 bicaption 宏包的一些特殊性。若你坚持要修改，正如 @e71828 所提示的，在
```
\RequirePackage[font={small,bf},skip=8pt,labelsep=space]{caption}% options [margin=10pt,labelfont=bf]
```
内添加相应的设定即可，设定参数可以参见 `caption` 宏包。祝好

**Comment by levelzhang** [comment]
> 
> 
> 当前 ucasthesis 的设定综合了很多因素，特别是 bicaption 宏包的一些特殊性。若你坚持要修改，正如 @e71828 所提示的，在
> 
> ```
> \RequirePackage[font={small,bf},skip=8pt,labelsep=space]{caption}% options [margin=10pt,labelfont=bf]
> ```
> 
> 内添加相应的设定即可，设定参数可以参见 `caption` 宏包。祝好

非常感谢！
