### ISSUE TITLE
 如何给中英文摘要添加书签？

### ISSUE THREAD

**Issue by DRjy** [mohuangrui/ucasthesis#127]
![image](https://user-images.githubusercontent.com/46476977/54533491-47976580-49c5-11e9-9e5b-ec22e5d36544.png)

如何给中文 摘要 和 Abstract生成目录？
像下表这样的结果
![image](https://user-images.githubusercontent.com/46476977/54533730-d7d5aa80-49c5-11e9-9da6-254a3a8f9ef9.png)

**Comment by mohuangrui** [comment]
国科大给定Word模版规定那些不放入目录。如果你想，把 `\chapter*{摘要/Abstract}` 中的 `*` 去掉即可。

**Comment by muzimuzhi** [comment]
如果你想让「摘要」
 - 在目录中不显示，同时
 - 在 pdf 书签中显示，

就需要手动添加书签，用到的命令参见 `hyperref` 宏包文档的 4.1 节。

**Comment by DRjy** [comment]
如果想要目录，和书签中都显示，改怎么弄？谢谢了。

**Comment by mohuangrui** [comment]
@DRjy 

1. 目录和书签中都显示:

把
```
\chapter*{摘\quad 要}\chaptermark{摘\quad 要}% 摘要标题
```
和
```
\chapter*{Abstract}\chaptermark{Abstract}% 摘要标题
```
中的  `*`  去掉即可

2. 只在书签中显示不在目录中显示，按照 @muzimuzhi 所提示的，用：
```
\chapter*{摘\quad 要}\chaptermark{摘\quad 要}% 摘要标题
\pdfbookmark[1]{摘要}{bmk:zhaiyao}% 加入书签但不加入目录
```
和
```
\chapter*{Abstract}\chaptermark{Abstract}% 摘要标题
\pdfbookmark[1]{Abstract}{bmk:abstract}% 加入书签但不加入目录
```

**Comment by DRjy** [comment]
谢谢！完美解决。
不过调节一下这个上下顺序，可能更好看（强迫症啊）
>\chapter*{摘\quad 要}\chaptermark{摘\quad 要}% 摘要标题
\pdfbookmark[1]{摘要}{bmk:zhaiyao}% 加入书签但不加入目录

变为：

>\pdfbookmark[1]{摘要}{bmk:zhaiyao}% 加入书签但不加入目录
\chapter*{摘\quad 要}\chaptermark{摘\quad 要}% 摘要标题

**Comment by mohuangrui** [comment]
@DRjy 
如果要调节顺序，那就必须要多加一个命令，即：
```
\cleardoublepage\pdfbookmark[1]{摘要}{bmk:zhaiyao}% 加入书签但不加入目录
\chapter*{摘\quad 要}\chaptermark{摘\quad 要}% 摘要标题
```
和
```
\cleardoublepage\pdfbookmark[1]{Abstract}{bmk:abstract}% 加入书签但不加入目录
\chapter*{Abstract}\chaptermark{Abstract}% 摘要标题
```

**Comment by muzimuzhi** [comment]
因为章节标题自成一段，且这个段落的前后往往有额外的纵向间距。所以，手动添加的书签，其跳转位置是不准确的。

写了篇[知乎文章](https://zhuanlan.zhihu.com/p/59655379)来介绍如何避开这个问题，希望能帮到。
