### ISSUE TITLE
`ifstrequal`对`\frontmatter`的重定义遇到的bug

### ISSUE THREAD

**Issue by e71828** [mohuangrui/ucasthesis#128]
`ifstrequal`对`\frontmatter`的重定义中，`\ucas@value@en@degree`的值是`{}`而不是`Bachelor`。因为无论`\DEGREE`是`Bachelor`还是`Master`，结果前文区的style都是`\pagestyle{frontmatterstyle}`请问大佬这是由于什么问题？
```
%- Redefine \frontmatter to include the change
	\providecommand{\frontmatter}{}% compatibility for non-book classes
	\let\myfrontmatter\frontmatter%
	\renewcommand{\frontmatter}{%
		\myfrontmatter%
		\ucasifstreq{\ucas@value@en@degree}{Bachelor}{\pagestyle{withlogo}}{\pagestyle{frontmatterstyle}}%
	}%head with logo for Bachelor
```
页眉那块代码无论放在sty还是class里，` \expandafter\ifstrequal\expandafter`后面的`\ucas@value@en@degree`不是`\DEGREE`传进去的值，而似乎是`\def\ucas@value@en@degree{}`定义的空。导致`\ifstrequal{}{Bachelor}{<true>}{<false>}`总是执行`false`，
大佬，两天前我给你发邮件了，能帮忙抽空看一下为什么不能根据条件对`\frontmatter`重定义么

**Comment by mohuangrui** [comment]
本科生的logo要不一样？

这样的状况是因为你过于追求信息背后的“自动化”，而导致信息利用的顺序不。在写模版的时候，你是无法得知用户到底是不是 Bachelor，只有到用户给定 \Degree 命令时才会知道，而\frontmatter总会发生在\Degree之前。。。

对了，实在抱歉因为个人时间有限，实在不方便再一一回答你的个人想法的问题了，请见谅。

**Comment by muzimuzhi** [comment]
@e71828 
建议
 * 完整叙述你的原始需求、需求和默认输出的差异、你的尝试、尝试的结果，不要只抛出「问题的核心」。例如，在你的问题里，为什么要再次重定义 `\frontmatter`，想达到什么效果？
 * 提供完整的、可编译的例子

@mohuangrui 
也许我可以提供一定支持

**Comment by mohuangrui** [comment]
@muzimuzhi 好的，谢谢你的热心帮助：D

**Comment by e71828** [comment]
@muzimuzhi  其实主要是想兼容一下我手上的本科生和研究生的模板，本科生页眉有logo，而研究生没有；

你可以这样试一下，看看摘要页和目录页的页眉在`Bachelor`下会不会变
```
%- Redefine \frontmatter to include the change
	\providecommand{\frontmatter}{}% compatibility for non-book classes
	\let\myfrontmatter\frontmatter%
	\renewcommand{\frontmatter}{%
		\myfrontmatter%
		\ucasifstreq{\ucas@value@en@degree}{Bachelor}{\pagestyle{empty}}{\pagestyle{frontmatterstyle}}%
	}%
```

**Comment by mohuangrui** [comment]
@e71828 你好，这样的尝试应是不行的，因为信息利用的顺序不对，违背了因果律：因为只有到用户给定 \Degree 命令时才会给定\ucas@value@en@degree的值，而\frontmatter总会发生在\Degree之前。也即是说\frontmatter无法得到\ucas@value@en@degree的准确值。

你应该考虑的方案是通过类选项的方式，即 \documentclass[Bachelor]{ucasthesis.cls}这样的方案来实行，这样用户就会在最开始的地方给出信息，而后你就可以再利用这个信息。

**Comment by e71828** [comment]
@mohuangrui ok明白了谢谢

**Comment by e71828** [comment]
@mohuangrui 老哥，能再请教一下关于下划线与文本的间距的问题么
```
\setlength{\ULdepth}{5pt}% set depth
\renewcommand{\CJKunderlinebasesep}{0.3em}% set underline basesep
```
这两个命令真的有作用么

**Comment by mohuangrui** [comment]
有用的，可以调整文本到下划线的距离。ucasthesis最新版使用的是\uline不再使用\cjkunderline了，所以间距调整是基于的局部设定的uldepth，你可以看下.cls文件的相关部分

________________________________

**Comment by e71828** [comment]
可是修改参数之后，我看不出来变化啊。
容易出问题的地方在英文标题的下划线，例如字母p之类，盒子基线以下与下划线部分重合

**Comment by muzimuzhi** [comment]
@e71828 新问题建议单开 issue，提问时建议带上完整例子。

**Comment by e71828** [comment]
@mohuangrui 哦，我发现你删了之前cjkunderline的代码，cjk那个调下划线间距感觉没有变化，似乎不起作用，今天试了新代码uline，发现有效果，非常感谢。
@muzimuzhi 多谢大佬的关心，以后会注意的。
