### ISSUE TITLE
xelatex和bibtex怎么安装？网上查不到？

### ISSUE THREAD

**Issue by furrybear** [mohuangrui/ucasthesis#129]
xelatex和bibtex怎么安装？网上查不到？

**Comment by muzimuzhi** [comment]
你是什么操作系统，安装了哪个 latex 发行版？

**Comment by furrybear** [comment]
> 你是什么操作系统，安装了哪个 latex 发行版？

Windows上是要安装TexLive吗？Ubuntu上能用apt安装吗？安装什么？

**Comment by muzimuzhi** [comment]
> Windows上是要安装TexLive吗？

推荐 texlive。

> Ubuntu上能用apt安装吗？安装什么？

不了解，建议搜索。

**Comment by furrybear** [comment]
> > Windows上是要安装TexLive吗？
> 
> 推荐 texlive。
> 
> > Ubuntu上能用apt安装吗？安装什么？
> 
> 不了解，建议搜索。

TexLive自带xelatex？

**Comment by mohuangrui** [comment]
@furrybear ubuntu可以apt install texlive-full。texlive包含后xelatex和bibtex等一些列latex元素。这些信息皆可从网上轻易搜索得到，请珍惜大家的时间。
