### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by ShijieLi** [mohuangrui/ucasthesis#13]
哈哈，我又来了，希望哥们不要觉得我烦
1. 如图
![qq20160419-0](https://cloud.githubusercontent.com/assets/866777/14631100/547db834-0644-11e6-9ae0-cc6c1fd99991.png)

2. 这两个建议不具有普遍性，您可以告诉我修改的方法
   1）关于“论文独创性声明”那一页，我看研究生院提供的模版还有我们所里往年的论文都没有这一页，能     不能去掉这一页？
   2）关于““简历及发表文章目录”，能不能把这两个拆开？

**Comment by ShijieLi** [comment]
还忘了一个，就是“致谢”的位置，研究生院模版以及所里往年论文都是把致谢放在中文摘要前面

**Comment by mohuangrui** [comment]
Hi, “致谢”的位置, 简历及发表文章目录” You can adjust the position and content of these items whatever you want. You see, they are just defined by "\chapter{xxxx}", you can do this at any place you want, with any times you need and with any title : D

关于“论文独创性声明”那一页 this is generated by the command "\makedeclaration" in the Frontpage.tex. You just need to comment that command if you don't want it : D

Thank you for your suggestions ~

**Comment by ShijieLi** [comment]
多谢！都改好了！
不过第一个问题别忘了，不仅是左侧的书签中的“表格”和“图表”跟文中的顺序相反，文中目录里的这两个的顺序和实际的顺也相反

**Comment by mohuangrui** [comment]
Hi, Sorry for forgetting to fix that. Yes, now I have fixed that sequence : D
Thanks a lot! The 1.1.1 problem is that I won't recommend you to do that. It's absolutely unnecessary : D

**Comment by ShijieLi** [comment]
OK! 多谢
