### ISSUE TITLE
[页面尺寸] 错误设置了 \voffset，建议用 geometry 宏包改写

### ISSUE THREAD

**Issue by muzimuzhi** [mohuangrui/ucasthesis#130]
页面尺寸部分，目前是手动设置的，其中的
https://github.com/mohuangrui/ucasthesis/blob/abe6a928d2f3cb73f4b02293e7cb24d2b689afb1/Style/ucasthesis.cls#L101
是不合理的，在特殊情况下会带来问题。

控制页面尺寸的诸多 dimension 内部包含一定的勾契关系，直接设定比较费事，建议换用 `geometry` 宏包。

如果有具体的页面尺寸要求（例如左侧页边距 xx mm），我可以用 `geometry` 改写后提交 push request。

------
特殊情况举例：使用 `pdfpages` 宏包的 `\includepdf` 插入一个整页时，插入的页面会整体上移 `-\voffset` (17.4mm) 的距离。

```latex
% a4-insersion.tex
\documentclass[a4paper]{article}
\usepackage[margin=0pt]{geometry}
\usepackage{xcolor}
\pagecolor{blue!60!green!60}

\begin{document}
\noindent
\rule{\textwidth}{\dimexpr17.4mm + 5pt\relax}
\end{document}

% thesis-test.tex
\documentclass{Style/ucasthesis}
\usepackage{pdfpages}

\begin{document}
\includepdf{a4-insertion}
\end{document}
```

说明：
  * `a4-insertion.tex` 生成待插入页面 `a4-insertion.pdf`，页面淡蓝底色，上部有一高为 14.7mm + 5pt 的黑块
  * `thesis-test.tex` 使用模板，插入 `a4-insertion.pdf` 

![image](https://user-images.githubusercontent.com/6376638/54869363-4ce41e00-4dd2-11e9-87d0-392c474f6733.png)

**Comment by mohuangrui** [comment]
你好，ucas 的页面尺寸与 latex 的默认设置不一致，从而需要手动设置，不清楚 latex 该如何自动完成这一问题。

页面尺寸的各个参数是紧密耦合的，若要实现 ucas 的尺寸要求，如页眉页脚页码位置，文本长度宽度距页面各边的距离凡此种种，需要调用到 page layout 的各个参数并细心的计算调校。geometry 只是对 latex kernel 的一些 layout 参数进行了封装，却无法避免需要改写 voffset 以缩短默认的1 inch顶部空白的问题，从而用 geometry 写一遍只是相当于将原本用英格兰英文的表达换成了苏格兰英文一般。。。

至于你说的插入一整页原尺寸 a4 pdf的问题，虽不明白这在论文写作里的价值，但修正的方法很简单，即使用：
 ```
\includepdf[offset=0 -17.4mm]{a4-insertion}
```
替换你的
```
\includepdf{a4-insertion}
```
`\includepdf{}` 会被多种参数所影响，从而单纯的调用往往是天真的，调校参数早已被设计者所考虑。

祝好

**Comment by mohuangrui** [comment]
对了，强迫症者也可以用：
```
\includepdf[offset= 0 \voffset]{a4-insertion}
```

**Comment by muzimuzhi** [comment]
> geometry 只是对 latex kernel 的一些 layout 参数进行了封装，却无法避免需要改写 voffset 以缩短默认的1 inch顶部空白的问题

并非如此。geometry 无法突破 latex kernal 的限制是真，必须令 `\voffset` 不为零才能满足模板要求可能是假。

以下例子参考[附件17：中国科学院大学研究生学位论文撰写规范指导意见.pdf](https://github.com/mohuangrui/ucasthesis/files/2863609/17.pdf)（从 #107 获取）中对页面设置的要求进行了配置，并加入「调整版心页边距、调整页眉页脚位置」的页面设置作为参照，发现始终有 `\voffset = 0` 。

例子
```latex
\documentclass[a4paper]{article}
\usepackage[showframe]{geometry}
\geometry{margin={3.17cm, 2.54cm},headsep=1.04cm,footskip=1.5cm,headheight=9bp}
\def\check{\texttt{\textbackslash voffset = \the\voffset}}
\def\ensureFont{\fontsize{30pt}{36pt}\linespread{1.3}\selectfont}
\begin{document}
\ensureFont
\begin{verbatim}
standard setting (according
to the regulation):
  margin  = {3.17cm, 2.54cm},
  headsep = 1.04cm,
  footskip= 1.5cm,
  headheight=9bp
\end{verbatim}
\check\newpage

\newgeometry{margin={3.17cm, 2.54cm}, headsep=2cm, footskip=2cm, headheight=.1cm}
\ensureFont
\begin{verbatim}
change headsep, footskip, 
and headheight
  margin  = {3.17cm, 2.54cm},
  headsep = 2cm,
  footskip= 2cm,
  headheight=.1cm
\end{verbatim}
\check\newpage

\newgeometry{margin={3.17cm, 10cm}, headsep=2cm, footskip=2cm, headheight=.1cm}
\ensureFont
\begin{verbatim}
change vmargin further
  margin  = {3.17cm, 10cm},
  headsep = 2cm,
  footskip= 2cm,
  headheight=.1cm
\end{verbatim}
\check
\end{document}
```
例子输出
![image](https://user-images.githubusercontent.com/6376638/54884804-21cffc00-4eb0-11e9-9c0d-59556c33a42d.png)

据此，我觉得是可以在满足《规范指导意见》页面设置要求的同时，保持 `\voffset = 0` 的。

**Comment by muzimuzhi** [comment]
上条回复围绕「不必」修改，本条回复，以 The LaTeX Companion 书中的一段，来佐证「不应」修改 `\voffset` 的值。

![image](https://user-images.githubusercontent.com/6376638/54884868-f0a3fb80-4eb0-11e9-9f4b-75f305b9a905.png)

**Comment by mohuangrui** [comment]
你好，你是对的，可以不修改 \voffset 的默认值。模版已修正，感谢指教！

**Comment by muzimuzhi** [comment]
感谢更新。
