### ISSUE TITLE
数学公式的字体为何和经典的Computer Modern 差别很大 能自行调整么

### ISSUE THREAD

**Issue by ShunhuiYao** [mohuangrui/ucasthesis#131]

**Comment by muzimuzhi** [comment]
> 为什么数学字体 computer modern 不同

因为用了不同的字体，相关配置见
https://github.com/mohuangrui/ucasthesis/blob/72c75cf5a941ef918221088d388f43ae95ac7bed/Style/artratex.sty#L284-L305

> 能自行调整吗

0. 技术上，能改
1. 效果上，请自主确认校方能接受 computer modern 风格的数学字体
2. 操作上，把上述代码块直接注释，就差不多了。

**Comment by ShunhuiYao** [comment]
好的，非常感谢您的帮助

**Comment by mohuangrui** [comment]
@muzimuzhi 谢谢帮忙。 Computer Morden是默认的，只需注释掉那些设定即可，事实上，为了将数学公式及数字字体改成times，还费了很多周章才大体弄出来。

**Comment by muzimuzhi** [comment]
> 为了将数学公式及数字字体改成times，还费了很多周章才大体弄出来。

看出来了。既然已经用了 xelatex + fontspec，unicode-math 也可以用了。可以试试 times 风格的 TeX Gyre Termes Math 字体。可能的成本在于，
* 是否接受 Termes Math 的字符主要笔画（stem）的粗细
* unicode-math 宏包的配置
