### ISSUE TITLE
引用一个作者一年内的两篇文章

### ISSUE THREAD

**Issue by zzxihep** [mohuangrui/ucasthesis#132]
当引用的两篇文献发表于同一年且文章一作是同一人时，请问怎么添加额外的字符标示区别。如
![选区_556](https://user-images.githubusercontent.com/12471308/54935502-64024780-4f5b-11e9-9d0b-92338ce0a5c2.png)
的显示结果是
![选区_557](https://user-images.githubusercontent.com/12471308/54935567-85633380-4f5b-11e9-91e0-fa1c5d68eb1a.png)
能否把显示结果变成 tran et al., 1995a, 1995b, 1999 这种形式。
发现直接把 bib 中的日期改成 1995a 会报错。

**Comment by hushidong** [comment]
tran和tran etal是不同的，所以合不到一起。

如果一定要和一起，那么可以在bib中，在tran1995a文献的作者中加上and others,
但这样自己把文献作者改了，就是把单作者变成了单作者等。

**Comment by mohuangrui** [comment]
@zzxihep 正如 @hushidong 所指出的，只有当“两篇文献发表于同一年且文章是同样的作者”才可以，而你所给出的例子，并不满足要求，不同的作者，就是不同的文献，不能只按一作评判。

**Comment by zzxihep** [comment]
哦，之前没注意到这个，多谢

**Comment by mohuangrui** [comment]
好的，那我close了。
