### ISSUE TITLE
增加新的声明页

### ISSUE THREAD

**Issue by hardcookies** [mohuangrui/ucasthesis#135]
学长，你好！我们单位要求在国科大原创声明和授权使用声明后添加科研道德和知识产权声明，我知道需要编辑`ucasthesis.cfg`文件，但不知道具体如何添加和使用。
新增的声明页如下图所示：
![Jietu20190401-102649](https://user-images.githubusercontent.com/31724669/55300401-e01ff200-5469-11e9-8b87-d24957a06cab.png)

**Comment by e71828** [comment]
是cfg而不是fig，里面是声明内容，你用记事本都能打开改，要精细调整位置的话得去cls文档改

**Comment by hardcookies** [comment]
嗯，我不小心打错了。我基本明白了，在`.cfg`编辑内容，在`.cls`添加到`makedeclaration`命令中。

**Comment by hardcookies** [comment]
已经参照声明命令编辑修改完成，谢谢！
![Jietu20190401-113242](https://user-images.githubusercontent.com/31724669/55302040-00ec4580-5472-11e9-893a-cdf09617fd06.png)

**Comment by mohuangrui** [comment]
那我关闭此issue了 ：D

**Comment by e71828** [comment]
@hardcookies 老哥，一点就通，你太厉害了
