### ISSUE TITLE
与模版字体不一致问题

### ISSUE THREAD

**Issue by hardcookies** [mohuangrui/ucasthesis#136]
我使用的MacOS发现黑体加粗部分与模版字体不一致，具体效果如下图所示：
模版字体：
![Jietu20190401-150955](https://user-images.githubusercontent.com/31724669/55310042-16716780-5492-11e9-93c4-2227983fa212.png)
我的字体：
![Jietu20190401-150925](https://user-images.githubusercontent.com/31724669/55310537-3c4b3c00-5493-11e9-9897-3408f24422d5.png)
请问这是我的黑体选择的是`细体`而不是`中等`造成的吗？

**Comment by mohuangrui** [comment]
是的，和字体的选择有关系，但不必花费时间在这些无意义的细枝末节上

**Comment by hardcookies** [comment]
好的，谢谢！如果需要保持一致，我可以使用别人的电脑编译。还想请教学长一个问题，如何在研究成果那节取消缩进？

**Comment by mohuangrui** [comment]
官方文件只规定了字体类型和是否加粗，但并没有制定具体的字体源。所以，不一定要与ucasthesis模版的完全一致，因为ucasthesis的并不是绝对标准。

想取消缩进，就在你的当前段落前用：
```
\noindent
```

**Comment by hardcookies** [comment]
谢谢学长！我是需要对研究成果这一章节全部取消缩进，所以使用了的以下命令：
```
\setlength{\parindent}{0em}
```

**Comment by mohuangrui** [comment]
那你最好使用：
```
{
\setlength{\parindent}{0em}

你的研究成果
}
```

否则研究成果后的内容可能被影响到。
