### ISSUE TITLE
some suggestions about ucas latex template

### ISSUE THREAD

**Issue by Solenyalyl** [mohuangrui/ucasthesis#139]
Dear authors:
I am a ucas student, using English to write these issues is just for zhuangbi. I think there are some places can be improved in this template.
(1)the blank page should be less according to the standard.
(2)bicaption cannot be used in the longtable, and there need a solution to solve this problem.
(3) the blue/red url or links in the article should be changed into black, or when we print out the article will cost more money in colorful.
(4)pandoc cannot transform this Latex article into doc, but we need doc article to duplicate checking, because pdf format checking article may cause unpredictable problems, so there also need a solution.
thank you for your patience.
best regards.

**Comment by e71828** [comment]
@Solenyalyl 腰都不扶  就服你   第四条我也也关心

**Comment by mohuangrui** [comment]
（1)"中文摘要、英文摘要、目录、 论文正文、参考文献、附录、致谢等均须由另页右页开始"。也就是说论文需采用正式的双面排版。那些空白页的存在是为了满足“由另页右页开始”这一条件而自动生成的。这是一种排版规范。

（2）“2019-03-28 根据 zssasa, allenwoods, issue #49 ，修复 bicaption 对 longtable 的兼容性。” 以及 [跨页长表](https://github.com/mohuangrui/ucasthesis/wiki/跨页长表)。即问题已经解决。

（3）电子档的论文会倾向链接是有颜色的，这也是为什么ucasthesis默认设定有颜色。至于你想打印版设定为黑色，可见 [链接设置](https://github.com/mohuangrui/ucasthesis/wiki/链接设置)  和 [issue 125](https://github.com/mohuangrui/ucasthesis/issues/125)  。头一次听说因为链接有颜色，所以就要去彩色打印。

（4） pandoc 能做的或能做好的极其有限，这不是ucasthesis的问题。至于查重，那些系统本就是为pdf文件而设计的。关于 windows 系统编译生成的 pdf 查重异常，那是因为windows字体导致的，解决办法见 [字体配置](https://github.com/mohuangrui/ucasthesis/wiki/字体配置)

问问题之前建议多了解相关常识和读读相关文档

**Comment by Solenyalyl** [comment]
谢谢谢谢，
前面三条赞同，
最后一点有疑问，知网查重里面推荐的是用word，不推荐使用pdf。在网上搜索到的原因有在输入pdf 文档进行查重时公式图片等也会转换成文字，引用的地方也会进行查重，而word中这些问题不会存在。你看一下这些问题是否会存在。

**Comment by mohuangrui** [comment]
不知道知网的使用细节，我熟悉的是 ithenticate。但：
1. “输入pdf 文档进行查重时公式图片等也会转换成文字”，这不是很好么，那些元素的查重是十分关键的。

2. “引用的地方也会进行查重”，一般查重软件应是可以选择取消参考文献部分的重复率，如果知网不行，你就把参考文献页删掉即可，或是编译时不用 bibtex，就不会有参考文献。

**Comment by songchunlin** [comment]
> 谢谢谢谢，
> 前面三条赞同，
> 最后一点有疑问，知网查重里面推荐的是用word，不推荐使用pdf。在网上搜索到的原因有在输入pdf 文档进行查重时公式图片等也会转换成文字，引用的地方也会进行查重，而word中这些问题不会存在。你看一下这些问题是否会存在。

我们所也是用知网查重，可以提交 PDF，所以我觉得知网那边 PDF 不会有什么问题。

如果确实需要 Word 版，可以用 Word 2013 及以上版本直接打开 PDF 转为Word，文字图片等内容都在，只是格式会乱。

**Comment by Solenyalyl** [comment]
是呀，就是转为word会乱，不知道检测系统里面后台是怎么运行的，它自己使用pdf进行转换的过程不知道会不会使得格式发生问题，这是我在知网学术不端系统利用pdf检测的时候的两张截图。这个问题如果能解决肯定更好啦~~ 谢谢
<img width="639" alt="1" src="https://user-images.githubusercontent.com/33305699/55663704-8007c200-5854-11e9-9c82-98b7b0876c19.png">
<img width="957" alt="2" src="https://user-images.githubusercontent.com/33305699/55663706-826a1c00-5854-11e9-8363-7d71ba101f57.png">

**Comment by mohuangrui** [comment]
1. 那是系统提示
2. 如果你用windows 系统编译并出现乱码，再次提醒请见 https://github.com/mohuangrui/ucasthesis/wiki/字体配置

**Comment by Solenyalyl** [comment]
我去问了一下知网的老师，可以通过添加\usepackage{ccmap}解决Latex中pdf乱码的问题。
发件人: mohuangrui
发送时间: 2019年4月6日 15:44
收件人: mohuangrui/ucasthesis
抄送: Solenyalyl; Mention
主题: Re: [mohuangrui/ucasthesis] some suggestions about ucas latextemplate (#139)

1. 那是系统提示
2. 如果你用windows 系统编译并出现乱码，再次提醒请见 https://github.com/mohuangrui/ucasthesis/wiki/字体配置

**Comment by Solenyalyl** [comment]
同时，知网的老师说pdf进行检测与word进行检测查重得到的结果会有差异，如果Latex转word比较麻烦，可以把这一点差异放在文档里面。后面的同学用的时候也可以留意到这个可能出现的问题。
发件人: mohuangrui
发送时间: 2019年4月6日 15:44
收件人: mohuangrui/ucasthesis
抄送: Solenyalyl; Mention
主题: Re: [mohuangrui/ucasthesis] some suggestions about ucas latextemplate (#139)

1. 那是系统提示
2. 如果你用windows 系统编译并出现乱码，再次提醒请见 https://github.com/mohuangrui/ucasthesis/wiki/字体配置

**Comment by mohuangrui** [comment]
1. 结果有差异并不是什么有用的信息。问题是怎样的差异？是不是有意义的差异？你若十分在意这个问题，何不做一个合理的对比，比如用一个word文档，一个latex生成的pdf文档（注意windows系统不能直接用默认字体查重 https://github.com/mohuangrui/ucasthesis/wiki/字体配置 ），一个word转成的pdf文档。三个文档皆具有同样的内容。

2. 不是 latex 转 word 有问题，而是任何图文混排的文档转 word 都有问题，这是微软设定的信息壁垒，是他们的权利。其实你倒是应该去质疑质疑知网，为何拿钱办事却连基本的事都办不好，pdf从来才是文献类文档标准。

**Comment by Solenyalyl** [comment]
我问了，知网的老师没有回复是什么差异，我查到的是重复率会更高。
我觉得你说的很对，知网这一点没有做好，pdf文档的查重得出来的结果会有差异。只是他们在上传文档的时候说明了这一点，不推荐使用pdf。
你要不要在说明文档说一下这一点？因为我们在最开始使用的时候，不会想到后面查重的这一步可能会遇到结果有差异的问题。
发件人: mohuangrui
发送时间: 2019年4月7日 10:45
收件人: mohuangrui/ucasthesis
抄送: Solenyalyl; Mention
主题: Re: [mohuangrui/ucasthesis] some suggestions about ucas latextemplate (#139)

1. 结果有差异并不是什么有用的信息。问题是怎样的差异？是不是有意义的差异？你若十分在意这个问题，何不做一个合理的对比，比如用一个word文档，一个latex生成的pdf文档（注意windows系统不能直接用默认字体查重 https://github.com/mohuangrui/ucasthesis/wiki/字体配置 ），一个word转成的pdf文档。三个文档皆具有同样的内容。
2. 不是 latex 转 word 有问题，而是任何图文混排的文档转 word 都有问题，这是微软设定的信息壁垒，是他们的权利。其实你倒是应该去质疑质疑知网，为何拿钱办事却连基本的事都办不好，pdf从来才是文献类文档标准。

**Comment by muzimuzhi** [comment]
> 我问了，知网的老师没有回复是什么差异，我查到的是重复率会更高。

抛开对查重结果的（过多）关注，我对于「差异会使重复率更高」仍然抱有怀疑。

技术上，
 - 如果差异的产生是随机的，重复率就会有的更高、有的更低
 - 如果差异的产生不是随机的，也无法解释为何一定会导致更高的重复率。文献库里的内容是「专业化的、有意义的文本」，同一篇文章，PDF 格式并不会比 Word 格式更有意义。

合理的猜测是，知网用于查重的文献库中有一定比例的「无意义文本」，例如制表符、多余的空格、换行符等。而 PDF 格式在查重系统中会比 Word 产生更多的此类无意义文本，导致同一篇文章的 PDF 格式比 Word 格式「总是」重复率更高。

综上，在有具体例子（一篇文章两种格式、两种重复率、重复内容差异）之前，很难作出有意义的后续讨论。
