### ISSUE TITLE
mac 编译问题

### ISSUE THREAD

**Issue by halois** [mohuangrui/ucasthesis#14]
mac 用compile.sh无法编译

**Comment by mohuangrui** [comment]
Hi, may you please tell me the error information?
It is suggested that the compile.sh should work since Mac is inherently Linux.
Thanks!

**Comment by liuguiyangnwpu** [comment]
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "SimSun" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!............................................... 
```

I use the mac os to compile.sh to run.

**Comment by liuguiyangnwpu** [comment]
@mohuangrui

**Comment by liuguiyangnwpu** [comment]
missing font log

```
mktextfm SimSun/OT
mktextfm SimSun/OT
mktextfm KaiTi/OT
mktextfm KaiTi/B/OT
mktextfm SimHei/OT
mktextfm SimHei/I/OT
mktextfm SimSun/OT
mktextfm SimSun/BI/OT
mktextfm SimSun/OT
mktextfm SimSun/OT
mktextfm SimHei/OT
mktextfm SimHei/OT
mktextfm KaiTi/OT
mktextfm KaiTi/OT
mktextfm SimSun/OT
mktextfm SimSun/OT
mktextfm SimSun/OT
mktextfm SimSun/BI/OT
mktextfm SimSun/OT
mktextfm SimSun/B/OT
mktextfm SimSun/OT
mktextfm SimSun/I/OT
mktextfm SimSun/OT
mktextfm SimSun/OT
mktextfm SimSun/OT
mktextfm SimHei/OT
mktextfm SimHei/OT
mktextfm SimHei/OT
mktextfm SimHei/BI/OT
mktextfm SimHei/OT
mktextfm SimHei/B/OT
mktextfm SimHei/OT
mktextfm SimHei/I/OT
mktextfm SimHei/OT
mktextfm SimHei/OT
mktextfm SimHei/OT
mktextfm SimSun/OT
mktextfm SimSun/OT
mktextfm SimHei/OT
mktextfm SimSun/OT
mktextfm SimHei/OT
mktextfm FangSong/OT
mktextfm FangSong/OT
mktextfm FangSong/OT
mktextfm FangSong/BI/OT
mktextfm FangSong/OT
mktextfm FangSong/B/OT
mktextfm FangSong/OT
mktextfm FangSong/I/OT
mktextfm FangSong/OT
mktextfm FangSong/OT
mktextfm SimHei/OT
mktextfm SimHei/OT
mktextfm SimHei/OT
mktextfm SimSun/OT
mktextfm FangSong/OT
```

**Comment by liuguiyangnwpu** [comment]
```
[1] [2]
*************************************************
* ctex warning: "deprecated-command"
* 
* Command \CTEXunderline is deprecated.
* You can use the command with prefix \CJK instead.
*************************************************
[3] [4]
! Undefined control sequence.
\UCASspace ->\protect \CTEX@spaceChar 
                                      \protect \CTEX@spaceChar 
l.44 \begin{abstract}
```

**Comment by mohuangrui** [comment]
@liuguiyangnwpu 你好， Mac系统下编译的常见问题及解决方案如下：

1） Command \CTEXunderline is deprecated. ! Undefined control sequence. \CTEX@spaceChar
 
这很可能意味着你当前使用的 ucasthesis 版本不是最新版，从而与你更新后的 Texlive 系统不吻合。 请下载并更新ucasthesisi的样式文件。 当前 ucasthesis 已在 Mac OS （Texlive 2015 及 Texlive 2016）上测试通过。

2） missing Mac font or fontspec error: "font-not-found" ! The font "SimSun" cannot be found.

出现字体错误时，请 

a) 确定使用 xelatex 编译器而不是 pdflatex 编译器，因为 ctex 文档类目前在 Linux 和 Mac 系统下只支持 xelatex 而不再支持 pdflatex。

b) Mac OS 在主系统升级后可能会连带清除旧字体，若使用 xelatex 编译器， 程序将显示缺乏字体并请求下载。 此时只需按照提示自动下载安装相应字体即可。

若问题还未解决，请提供更多信息，谢谢你的测试。

**Comment by liuguiyangnwpu** [comment]
@mohuangrui 感谢您这么细致的回复。我的编译成功了，但是其中的目录没法显示！求指导！

**Comment by mohuangrui** [comment]
@liuguiyangnwpu 推测是对编译脚本的使用的问题，我已经此部分内容添加如最新的用户文档，并复述如下：

• Windows 用户:双击运行 Compile.bat 此 Dos 脚本即可获得全编译后的 PDF 文档。在此脚本中可以设定编译器为 pdflatex(p)or xelatex(x)(默认设定, 推荐)。

• Linux 或 Mac OS 用户:在 terminal 中运行”./Compile.sh xa” 即可获得全编 译后的文档,运行”./Compile.sh x” 则进行快速编译。对于 Linux 或 Mac 用户, ctex 已只支持 xelatex 编译器,若使用 pdflatex 编译,则将出现无字体支持的错误。

全编译是指运行”xelatex+bibtex+xelatex+xelatex” 以正确生成所有的引用链接,如目录,参考文献及引用等。当文章在写作过程中,并无添加新的引用,则可用快速编译即只运行”xelatex” 以减少编译时间。

祝好!

**Comment by liuguiyangnwpu** [comment]
@mohuangrui 感谢楼主的回答！
顺便问下，你是校友么？
还有一个建议，问什么编译出来的每个模块之间有一页的空白页。

**Comment by mohuangrui** [comment]
Hello,

Yes, I did my master's degree in UCAS. That empty page is for 
double-sided format: every chapter shall begin at an odd page. If you 
want to know more, please read "HowToUse.pdf" and the wikibook :D

Best wishes,

Mo
