### ISSUE TITLE
长表格使用卧排方式的解决办法

### ISSUE THREAD

**Issue by yangia** [mohuangrui/ucasthesis#140]
近期写论文发现文章中出现了很长的表格，查阅了一下书写规范，发现可以使用卧排方式，如下：
![image](https://user-images.githubusercontent.com/34333375/55524511-3c7c4f00-56c0-11e9-9ce7-e78f0ab96fc8.png)
由于文档中并未发现卧排表格的使用方法，因此我自己查了一下实现方式，现给出如下：
首先在preamble里加上：
```
\usepackage{lscape}    
```
然后使用时：
```
\begin{landscape}
\begin{table}[!htbp]
……
\end{table}
\end{landscape}
```
最终可以达到一个长表格卧排占据一整页的效果。示例图：
![image](https://user-images.githubusercontent.com/34333375/55529521-6475ad80-56d4-11e9-8517-79a59d4a94a5.png)
隐私问题故隐去表格内容和标题。
PS：我在表格中使用了多行合并，用了`\usepackage{multirow}`
PS2：我使用的版本是2月20日修改后的。

更正：
之前表格朝向反了，故删去部分。

**Comment by mohuangrui** [comment]
你好，请见 [横排图表](https://github.com/mohuangrui/ucasthesis/wiki/横排图表)
