### ISSUE TITLE
页码字号为什么会变大？

### ISSUE THREAD

**Issue by guanpengchn** [mohuangrui/ucasthesis#142]
您好，请问下页码这里为什么和我们所里给的不一致？
如下面两张图，我已经标出来了。
除了不一致之外，为什么页码的字号变大了呢？

![WechatIMG44](https://user-images.githubusercontent.com/13995641/55677675-a09c4e80-591e-11e9-9d7d-7903bb461dbb.jpeg)
![WechatIMG43](https://user-images.githubusercontent.com/13995641/55677676-a09c4e80-591e-11e9-80a3-78cbb5491f80.png)

**Comment by mohuangrui** [comment]
1. 页码样式不一样是因为你们所给的不符合国科大指导的规定：

“(3)页码
页码从引言(或绪论)开始按阿拉伯数字(1，2，3......)连续 编排，页码应位居左页左下角、右页右下角;此前的部分(中英文摘 要、目录等)用大写罗马数字(I，II，III...)单独编排，页码位于页 面下方居中。”

2. 国科大指导文件对目录字体的规定为：

<img width="751" alt="Screen Shot 2019-04-07 at 10 49 08 AM" src="https://user-images.githubusercontent.com/7518165/55677889-db07ea80-5922-11e9-8d20-166afd08afbf.png">

ucasthesis 那些字体不是突然变大了，而是严格的执行了上述规定，即章主标题一行为 4 号字体，而节标题行为小4号字体。

祝好。

**Comment by guanpengchn** [comment]
好的，非常感谢，我去阅读一下，麻烦了，祝好。

**Comment by guanpengchn** [comment]
不好意思再问下指导意见有官网链接么？2019年有发么？

**Comment by mohuangrui** [comment]
你可以百度“中国科学院大学研究生学位论文撰写规范指导意见”，就可以找到如下类文件：

[研究生学位论文撰写规范指导意见.pdf](https://github.com/mohuangrui/ucasthesis/files/3051171/default.pdf)

[本科生毕业论文撰写规范指导意见.pdf](https://github.com/mohuangrui/ucasthesis/files/3051172/default.pdf)

国科大新版规定是从2018年2月开始颁发执行的。规定不会一年一发，很多年才会变一次。若国科大没新的变动，就不会再变了。

**Comment by SAMTRONG** [comment]
师兄你好，国科大发的“研究生学位论文撰写规范指导意见”里面规定目录section和subsection的名字大小不一样，但是目录对应的页码大小应该是保持相同的。求问这个需要怎么改呢？ 
![Inked页码_LI](https://user-images.githubusercontent.com/64763714/162745851-5474874a-a176-45e9-ad21-4d9ce86b2af5.jpg)
![页码](https://user-images.githubusercontent.com/64763714/162745873-83f47107-651b-4c5f-ba2d-2adf72771c43.png)
