### ISSUE TITLE
你好，请问如果想用顺序编码制应该怎么办？

### ISSUE THREAD

**Issue by liuy334** [mohuangrui/ucasthesis#143]
你好，我想在文中用顺序编码制，因而在thesis.tex中把
%\usepackage[authoryear,myhdr,list]{Style/artratex}% document settings替换为
\usepackage[super]{artratex}
然后系统报错，显示
 LaTeX Error: File `artratex.sty' not found.

另外，在文中使用\cite还是\citep呢？
之后把具体的参考文件信息也是粘贴到ref.bib中吗？

麻烦你啦

**Comment by mohuangrui** [comment]
关于 LaTeX 的知识性问题，请查阅 ucasthesis 知识小站 和 LaTeX Wikibook。
关于模板编译和样式设计的问题，请先仔细阅读 模板使用说明.pdf 并遵从提问流程。
