### ISSUE TITLE
你好，还是参考文献的问题

### ISSUE THREAD

**Issue by liuy334** [mohuangrui/ucasthesis#144]
你好，由于水平有限，我就放弃了顺序法，用模板里面的方法，但是发现模板里面的
\citet和\citep的引用都会显示为？，刚刚又下载了一遍模板，直接运行里面显示的也是？，但是文件夹里面的使用说明不是，而且最主要的是：使用说明里面专门有一页是参考文献，而模板里面没有，也就是，我在正文部分用了\citet之后，在ref.bi.中粘贴好后，依然没办法显示在文档中。。。

**Comment by Phoenix1327** [comment]
建议你先检查《模板使用说明》2.4小节 “常见使用问题”，对照检查自己是否正确配置、编译。

**Comment by mohuangrui** [comment]
1. 顺序引用是将 authoryear 改为 super，即
```
\usepackage[super,myhdr,list]{Style/artratex}% document settings
```
使用说明中用 [super]{artratex} 我是为了突出 super，不是让你把整个命令都复制了。。。

2. “全编译指运行xelatex+bibtex+xelatex+xelatex以正确生成所有的引用链接，如目录，参考文献及引用等。”

我的建议仍是：

关于 LaTeX 的知识性问题，请查阅 ucasthesis 知识小站 和 LaTeX Wikibook。
关于模板编译和样式设计的问题，请先仔细阅读 模板使用说明.pdf。

水平有限不是什么问题，每一个人都是这么过来的，问题是你自己愿不愿意去学。

因个人时间有限，恕无法再回答类似问题。祝好。

**Comment by liuy334** [comment]
你好，我刚刚又仔细的看了，我用的是texlive2018，我在新下载的文档里运行只有36页，而模板38页，请问这也是配置和编译的问题吗？

**Comment by Phoenix1327** [comment]
文件夹里的《使用说明》，是作者正确编译生成的文件；而你自己配置、编译不正确，产生的《Thesis.pdf》自然跟《使用说明》不同。”引用出问号“ 、”《Thesis.pdf》比《使用说明》少一页“ 都是由于没有正确的编译，没有”生成引用“，还是编译错误的问题。
推荐使用texmaker，按照《使用说明》2.4章，”4. Texmaker使用简介“ (a)(b)(c)，一步步对照进行编译。
