### ISSUE TITLE
符号列表中，术语过长换行时文字缩进不对齐

### ISSUE THREAD

**Issue by Bruceeeee** [mohuangrui/ucasthesis#146]
您好，在术语列表中部分内容描述较长，换行后出现文字缩进不对齐的情况

<img width="688" alt="Screen Shot 2019-04-08 at 15 29 29" src="https://user-images.githubusercontent.com/22232832/55706232-416c3600-5a13-11e9-9587-74419db5b1e1.png">

**Comment by muzimuzhi** [comment]
已提交修改(#147 )，等待合并

**Comment by mohuangrui** [comment]
@Bruceeeee @muzimuzhi 

`\nomenclatureitem` 的开发初衷是用一个简单的命令来实现对符号列表的排版，从而避免调用对编译过程有特殊要求的 `nomencl` 宏包。因为简单，所以可自动处理好的情形较为有限，对于某些特殊情形需进行针对性的调整。

以如下情形为例：
```
\nomenclatureitem{BEDPOSTX}{Bayesian Estimation of Diffusion Parameters Obtained Using Sampling Techniques}
```

1. 首先在 `artratex.sty` 中将
```
\providecommand{\nomenclatureitem}[3][ ]{%
    \noindent\makebox[0.15\textwidth][l]{#2}{{#3}\hfill{#1}}\par
}
```
中的 `0.15` 改为 `0.18` 以适应字符串 `BEDPOSTX` 的长度。

2. 然后使用如下方法对原条目进行分解即可：
```
\nomenclatureitem{BEDPOSTX}{Bayesian Estimation of Diffusion Parameters Obtained Using Sampling}
\nomenclatureitem{}{Techniques}
```

**Comment by muzimuzhi** [comment]
> 将 ... 中的 `0.15` 改为 `0.18` 以适应字符串 BEDPOSTX 的长度。

 - `\makebox[0.15\textwidth][l]{#2}` 里的 `0.15`，这么设置的初衷、设置这个数值的理由是什么呢？
 - 修改后的 `0.18` 这个数字又是怎么来的呢？

**Comment by mohuangrui** [comment]
@muzimuzhi 

原来的 `0.15` 可适应绝大部分的情况，`BEDPOSTX` 这种很少见，所以用 `0.18` 以适应字符串 BEDPOSTX 的长度。这个是需要针对特定情形调整的。

**Comment by Bruceeeee** [comment]
@muzimuzhi @mohuangrui 
非常感谢，出现这种情况的条目确实不多，手动调整挺方便

**Comment by muzimuzhi** [comment]
> 原来的 `0.15` 可适应绝大部分的情况，`BEDPOSTX` 这种很少见，所以用 `0.18` 以适应字符串 BEDPOSTX 的长度。这个是需要针对特定情形调整的。

我理解「`BEDPOSTX` 这种情况很少见」的意思了，是我之前没有用题主的具体例子做测试。

看起来，需要的是一个可以跨页的表格，或者通过往 aux 记录最宽术语的信息，在第二次排版时读取并自动调整。

**Comment by Youguang** [comment]
> > 原来的 `0.15` 可适应绝大部分的情况，`BEDPOSTX` 这种很少见，所以用 `0.18` 以适应字符串 BEDPOSTX 的长度。这个是需要针对特定情形调整的。
> 
> 我理解「`BEDPOSTX` 这种情况很少见」的意思了，是我之前没有用题主的具体例子做测试。
> 
> 关于符号列表的实现建议（并列）
> 
> 1. 可跨页表格
> 2. 向 aux 输出（最大）宽度信息，在第二次排版时读取并自动调整
> 3. 增加一个实际输出符号列表的命令，`\nomenclatureitem` 仅用于收集信息

@muzimuzhi @mohuangrui 

我也遇到了类似的问题，比如 `\nomenclatureitem{SPACE}{Sampling Perfection with Application-optimized Contrasts using different flip angle Evolution}`

有没有可能像@muzimuzhi提出的方式，模版能够对不同情况自动适应？
有没有方式可以对符号列表自动按字母顺序排序？

**Comment by muzimuzhi** [comment]
> 有没有方式可以对符号列表自动按字母顺序排序？

用 `nomencl` 宏包，详见宏包文档。和排版索引相似，也就是通过 `makeindex` 来排序。

**Comment by jqbk** [comment]
> > 原来的 `0.15` 可适应绝大部分的情况，`BEDPOSTX` 这种很少见，所以用 `0.18` 以适应字符串 BEDPOSTX 的长度。这个是需要针对特定情形调整的。
> 
> 我理解「`BEDPOSTX` 这种情况很少见」的意思了，是我之前没有用题主的具体例子做测试。
> 
> 关于符号列表的实现建议（并列）
> 
> 1. 可跨页表格
> 2. 向 aux 输出（最大）宽度信息，在第二次排版时读取并自动调整
> 3. 增加一个实际输出符号列表的命令，`\nomenclatureitem` 仅用于收集信息

您好，请问具体怎么实现呢？您有实现的方法么？

**Comment by muzimuzhi** [comment]
@jqbk 画个表格是最简单的办法
