### ISSUE TITLE
某些行的文字不等长的问题

### ISSUE THREAD

**Issue by huangh12** [mohuangrui/ucasthesis#148]
如图（貌似是中英文混杂的句子容易出现此问题）：
![图片](https://user-images.githubusercontent.com/18748036/55849686-28cf5d80-5b84-11e9-9720-d34452bdedd4.png)

**Comment by mohuangrui** [comment]
中英文及 LaTeX 命令的混排易出现文本行不等长的情形，最简单有效的解决方案为：`使用空格分开中、英、LaTeX 命令`，如使用
```
测试。_\citet{xxx}_提出了_CNN_\citep{yyy}_理论，如表~ \ref{tab:zzz}_和方程~\eqref{eq:ns}。
```
而不是
```
测试。\citet{xxx}提出了CNN\citep{yyy}理论，如表~ \ref{tab:zzz}和方程~\eqref{eq:ns}。
```
其中 `_` 表示输入空格。这一规则对于`中英` 和 `LaTeX 命令` 之间尤为重要。

**Comment by huangh12** [comment]
给力！ 谢谢 😃
