### ISSUE TITLE
模板是否有审稿模式？

### ISSUE THREAD

**Issue by allenwoods** [mohuangrui/ucasthesis#149]
ucas-thesis模板是否有审稿模式呢？就是类似IEEE模板的peerreview设置，自动隐藏作者、单位、个人简历、致谢之类的信息。

**Comment by mohuangrui** [comment]
没有考虑这个

隐藏作者、单位：手动置空很简单，添加一个开关命令自动切换也很简单。
隐藏个人简历、致谢：因为ucasthesis是通过 \chapter{} ,\section{}这样的基础命令来实现这些以提供最大的灵活性，而不是对这些条目各定义了一个新命令，因此想通过一个开关命令自动切换就需要修改调整多个文件。

就算用一个宏开关选项来实现，你也得手动修改 Thesis.tex 去添加这个选项，而当前手动操作就已经很简单，即将如下命令置空：
```
\author{}% 论文作者
\advisor{}% 指导教师：姓名 专业技术职务 工作单位
\institute{}% 院系名称
\AUTHOR{}% 论文作者
\ADVISOR{}% 指导教师
\INSTITUTE{}% 院系名称
```
然后在 `Thesis.tex` 中注释掉如下一条即可：
```
%\input{Tex/Backmatter}% other information
```
