### ISSUE TITLE
Mainmatter.tex默认的插入文件的结构，在TeXStudio下会提示 File not found.

### ISSUE THREAD

**Issue by HaorenWang** [mohuangrui/ucasthesis#150]
- 系统环境：Win10x64 + TeXLive2018 + TexStudio 2.12.14.

可以通过模板的批处理文件编译。

但，在编辑器点击目录结构下的文件时，会提示“文件不存在，新建吗？”

![捕获](https://user-images.githubusercontent.com/13518568/56256842-ec0fe300-60fc-11e9-84f7-1c06cca691ee.PNG)

**Comment by mohuangrui** [comment]
可以不用管，直接编译主文件 Thesis.tex 即可。

**Comment by HaorenWang** [comment]
- OK, that's a point.

- 如果修改模板的示例为
```
\input{Chap_Intro}
\input{Chap_Guide}
```
怎么样？
