### ISSUE TITLE
newtmath.sty装不上

### ISSUE THREAD

**Issue by mengxibai** [mohuangrui/ucasthesis#152]
如图，电脑window 64同时装了tinytex和Miktex，
 .bat文件自动加载到tinytex的文件夹，我把miktex装好的newtx包（包含newtxmath)放到tinytex文件路径下，依旧显示newtxmath无法找到。
![tinytex](https://user-images.githubusercontent.com/48046007/56410355-6aac8200-62af-11e9-9116-e8bf36c21497.PNG)

**Comment by mohuangrui** [comment]
使用说明中已明确说明不要安装多个编译器。卸载 tinytex。祝好
