### ISSUE TITLE
windows下楷体编译

### ISSUE THREAD

**Issue by e71828** [mohuangrui/ucasthesis#153]
![image](https://user-images.githubusercontent.com/24602820/56481550-383e9700-64f2-11e9-976e-dde31364f01a.png)
顺便问一下，16号和19号的修改mathbf 和plain，具体做了什么修改，想学习一下

**Comment by e71828** [comment]
sorry    xelatex下粗楷体依然不正常，但是发现在pdflatex编译下，粗楷体正常，但粗宋体和黑体的英文不正常。

**Comment by mohuangrui** [comment]
还是同样的问题，如果需要粗楷体，请安装 mac 字体或在 mac 系统上编译。

**Comment by e71828** [comment]
上次那个issue就是我啊，学长。这次偶然发现pdflatex编译可以解决粗楷体，于是想请教一下

**Comment by mohuangrui** [comment]
pdflatex 和 xelatex 字体的调用机制不一样。如果你真的要在 windows 下用粗楷体，那你就按下面的做吧：

在 `artracom.sty` 中添加
```
\setCJKfamilyfont{zhkai}[AutoFakeBold]{KaiTi}%
\NewDocumentCommand \kaiti  { } { \CJKfamily { zhkai } }%
```
然后在需要粗楷体的地方，用
```
{\bfseries \kaiti 这是粗楷体}
```
祝好
