### ISSUE TITLE
ucasthesis文件夹的\chapter{}内无法写入\pi,\theta,\lambda等字符

### ISSUE THREAD

**Issue by hanzhangzhu** [mohuangrui/ucasthesis#154]
下载四月十九日更新的ucasthesis后，想在tex文件的\chaper{}内写入\Lambda等字符，但却出错说是不合适的字母常数，在之前的版本中却可以在\chapter{}插入类似\chapter{$\Lambda$超子和$\bar{\Lambda}$超子}形式的字母。

**Comment by muzimuzhi** [comment]
### 根本原因
这是 `hyperref` 的 bug，见 https://github.com/ho-tex/hyperref/issues/63。

### 具体原因
 - 4 月 19 日的提交 https://github.com/mohuangrui/ucasthesis/commit/4d420f7e8b988a5388b5d07fed1c7689d5da8c10 增加了逻辑，使得当文件 `XITS-Regular.otf` 存在时，调用 `unicode-math` 宏包管理数学字体
 - `unicode-math` 内部会 `\let` 很多命令，例如 `\let\Lambda=\mitLambda`
 - 模板一直使用 `hyperref` 宏包来生成 PDF bookmark（书签）。目前如果在书签文本中使用 `\let` 过的命令，`hyperref` 就会报错。在 XeLaTeX 引擎下，这个报错是
    ```
    ! Improper alphabetic constant.
    ````

### 临时方案
在 `hyperref` 的 bookmark 功能和 `unicode-math` 宏包之间，至少舍弃一项。
 - 如果选择舍弃 `hyperref` 的 bookmark 功能，则在 `Thesis.tex` 文件的 `\documentclass` 之前添加
    ```latex
    \PassOptionsToPackage{bookmarks=false}{hyperref}
    ```
 - 如果选择舍弃 `unicode-math` 宏包，则使用 4 月 19 日之前的版本。注意这时可能遇到 4 月 19 日版本修复的「文本异常加粗」问题。

------

PS
 - @hanzhangzhu 提问时，建议在文字描述问题的同时，给出完整可编译的、可复现问题的、精简的例子，同时提供原始的、具体的报错信息（不必翻译成中文）
 - @mohuangrui git commit message 里应当提供关于本次提交的描述性信息（[参考指南](https://zhuanlan.zhihu.com/p/46916705)），而非千篇一律的「New Release」。这样有助于项目的维护。github 支持在 commit message 里通过特定单词，把 commit 和 issue 关联起来，见 [Closing issues using keywords - GitHub Help](https://help.github.com/en/articles/closing-issues-using-keywords)。

**Comment by mohuangrui** [comment]
@muzimuzhi 谢谢解答和建议。
@hanzhangzhu 此问题由重新配置数学字体所导致，解决方案请见：https://github.com/mohuangrui/ucasthesis/wiki/常见问题

即：

使用 `\texorpdfstring{此为LaTeX编译内容}{此为书签内容}`，实例如下：

若需要
```
\section{测试公式编号 $\Lambda,\lambda,\theta$} \label{sec:testmath}
```
需使用
```
\section{测试公式编号 \texorpdfstring{$\Lambda,\lambda,\theta$}{$\textLambda,\textlambda,\texttheta$}} \label{sec:testmath}
```
即可避免报错问题。

**Comment by hanzhangzhu** [comment]
如果想在书签中插入\sqrt{s_{NN}}或者\bar{\Lambda}呢，该用\text.......怎么表示呢

**Comment by mohuangrui** [comment]
@hanzhangzhu 用
```
\section{测试公式编号 \texorpdfstring{$\Lambda,\lambda,\theta,\bar{\Lambda},\sqrt{S_{NN}}$}{$\textLambda,\textlambda,\texttheta,\bar{\textLambda},\sqrt{S_{NN}}$}} \label{sec:testmath}
```
但是上画线和根号并不会在书签中正常显示。只要不出错就好，没必要追求那些极端，书签终究只是书签而已。

**Comment by muzimuzhi** [comment]
书签只能显示普通文本，不支持公式。可以用 `S\_\{NN\}` 来「表示」公式 `S_{NN}`。

**Comment by zepinglee** [comment]
参考 https://github.com/ustctug/ustcthesis/issues/223 和 https://github.com/stone-zeng/fduthesis/commit/a59298d7a3d92d62d4e9e5ea7efebc81134674d0

**Comment by muzimuzhi** [comment]
抱歉我提供误导信息了。

**Comment by mohuangrui** [comment]
@muzimuzhi 不必介意，你读过的文档数已经足够让我惊奇了 ：D，还关注了那么多 repos， 而且每次都回复的这么及时，真是不容易，感谢！

**Comment by mohuangrui** [comment]
@zepinglee 根据 https://www.zhihu.com/question/30287181 ，感觉还是 `\texorpdfstring` 比较稳妥

**Comment by zepinglee** [comment]
最好还是在模板里面解决，`\mu` 的问题 patch 一下就好了

**Comment by muzimuzhi** [comment]
@mohuangrui 
> 根据 https://www.zhihu.com/question/30287181 ，感觉还是 `\texorpdfstring` 比较稳妥。
> 而且至今仍能复现 `\mu` 的报错。

`\mu` 的问题，hyperref v6.88h 2019-06-12 已经修复。可以考虑使用 zepinglee 在 https://github.com/mohuangrui/ucasthesis/issues/154#issuecomment-485831395 建议的方式了。具体分两步（如果同意做此修改，我可以提供 pull request。）
1. 使用两个选项
   ```latex
   \hypersetup{
     unicode, psdextra
   }
   ```

2. 为早于 v6.88 2019-06-12 的 hyperref 提供补丁
   ```latex
   \@ifpackagelater{hyperref}{2019/06/12}{}{%
     \g@addto@macro\psdmapshortnames{\let\mu\textmu}%
   }
   ```

参考提交 https://github.com/zepinglee/thuthesis/commit/d32e35c8de820eb227e2d0345fe70e67ef103ee6 和 issue https://github.com/ustctug/ustcthesis/issues/235 。

这样修改，可以尽可能自动地让latex 章节标题中的公式正常显示在 pdf 书签中，免去每次都手动使用 `\texorpdfstring` 的麻烦。（特殊情况，例如上下标，仍然免不了手动）

**Comment by mohuangrui** [comment]
@muzimuzhi 谢谢建议，但感觉意义不大：
1. 在章节标题中使用有问题的特殊字符的人非常非常少
2. texorpdfstring 能更好的满足特定需求，实现更多需求
再次谢谢你的建议～

**Comment by muzimuzhi** [comment]
好的
