### ISSUE TITLE
中文内容中“喆”字无法显示

### ISSUE THREAD

**Issue by Dicridon** [mohuangrui/ucasthesis#155]
代码如下
\chapter{致\quad 谢}
感谢计算所xx喆老师的帮助balabalabala

编译后显示结果如图：
![Screenshot from 2019-04-23 14-40-18](https://user-images.githubusercontent.com/24477137/56560009-d6575d80-65d5-11e9-90a0-29d30c349cb8.png)

Google后知道这个是由字体缺失导致的，我看到模板里面提到用的是fondal字体，这个字体里面恰好没有喆字，我自己不知道换了字体会不会影响查重所以没换字体，就用了两个只有正常字体一半大的"吉"字拼在一起解决了，但估计以后可能也会有同学遇到这个问题，不知道有没有什么更好的办法可以解决呢？

**Comment by mohuangrui** [comment]
请见 https://github.com/mohuangrui/ucasthesis/wiki/字体配置

**Comment by Dicridon** [comment]
已经解决了啦，非常感谢～
