### ISSUE TITLE
作者年份参考文献的显示问题

### ISSUE THREAD

**Issue by gsp2014** [mohuangrui/ucasthesis#157]
师兄好，按作者年份格式引用参考文献时，在pdf里显示的符号（括号和逗号）是英文的；而且按照英文的习惯，每个词后有个空格；另外，\citep的时候“等”字后面少一个“.”。例如：“Michael 等 (1995)”和“(Michael 等, 1995）”，而不是要求的“Michael等（1995）”和“（Michael等.，1995）”。求助！

**Comment by mohuangrui** [comment]
你好，你问的这些问题要么前人已经讨论过了要么是无效的，因时间关系，无法再一一作答，请见谅。

**Comment by gsp2014** [comment]
好的，辛苦师兄了。
