### ISSUE TITLE
貌似有一点小问题

### ISSUE THREAD

**Issue by BDZNH** [mohuangrui/ucasthesis#158]
不太能说清楚，如图：
![image](https://user-images.githubusercontent.com/17548735/56781052-3f2c1900-6814-11e9-869d-593a119eb1d4.png)
这个是2018.08我下载的仓库内模板使用说明，这里是正常的。

![image](https://user-images.githubusercontent.com/17548735/56781114-86b2a500-6814-11e9-8554-863bbd6ae633.png)
这是我刚刚下载的仓库内的模板使用说明，这里的内容有一些错位，我这里自行编译得到的pdf文件内也是一样的错误，我不太确定是哪里错了。

**Comment by mohuangrui** [comment]
你所说的错位是指 算法文本 与 算法表 的位置中间被隔断了吗？若是这样，请搜索了解一下 LaTeX 中的 float 概念

**Comment by BDZNH** [comment]
@mohuangrui  感谢解答，float的意思大概看了一下，如果这个地方我需要把
“2.3.5 算法 \n 如见算法1，详细使用方法见……”
这段字移动到算法体前面，也即下图中红框位置
![image](https://user-images.githubusercontent.com/17548735/56789921-b2925280-6835-11e9-996c-8307d2fd6ffd.png)
我可以怎么做呢，我尝试取消算法体的`[!htbp]`和图2.3的`[!htbp]`，或者移除`[!htbp]`，看起来没有生效。

**Comment by mohuangrui** [comment]
你好，你需要再仔细看看 float 的概念！！！！！

总而言之，你所关注的这个问题和采用的方法都是无意义和不应该的，若仍有问题，请继续读相关文献和资料。谢谢

**Comment by BDZNH** [comment]
可能我的表达方式有欠缺，为你带来了不愉快。
这里因为图2.3在上一页放不下，它浮动到下一页，而后面的“算法……”文本自动顶了上去。我觉得单独看着这里的话，文本在“算法体”前面可能更符合直觉一些，我尝试取消begin{figure}后面的[!htbp]是为了临时去掉这里的float属性，因为我这里不生效，所以才有了之前的回复。
不管怎么样，还是很感谢你的工作。

**Comment by mohuangrui** [comment]
你好，不是你的表达方式的问题，而是你没有去真正理解 LaTeX 的 float，你需要再多多相关的资料。等你真正明白了，就知道你现在考虑的这些是无意义的。祝好

**Comment by mohuangrui** [comment]
还有，我没有不愉快，那些叹号是用来强调你需要仔细读读，而不是大概看一下

**Comment by BDZNH** [comment]
好的，多谢。

**Comment by muzimuzhi** [comment]
@BDZNH 
https://liam.page/series/ 里的系列文章《LaTeX 中的浮动体》可以一看。
