### ISSUE TITLE
章节标题（包括论文中文标题）中的英文不是Times New Roman了

### ISSUE THREAD

**Issue by Carltonwei** [mohuangrui/ucasthesis#159]

**Comment by muzimuzhi** [comment]
短答案：
 - 这个修改是在提交  https://github.com/mohuangrui/ucasthesis/commit/4d420f7e8b988a5388b5d07fed1c7689d5da8c10 里作出的
 - 如果使用 xelatex，可以自己加上该提交删去的与 Time New Roman（下称 TNR）相关的两行

https://github.com/mohuangrui/ucasthesis/blob/84c1fbd8fe93b6d749044a2f991680c9e80131d8/Style/artratex.sty#L334-L335

从源码看，目前的英文字体配置是
1. 如果使用 pdflatex，则通过 `newtxtext` 宏包使用 TeX Gyre Termes 字体
1. 如果使用 xelatex，且字体文件 `XITS-Regular.otf` 不存在，同第一条
1. 如果使用 xelatex，且字体文件 `XITS-Regular.otf` 存在，则使用 XITS 字体

TeX Gyre Termes 和 XITS 两款字体都是 Times 风格的，长得和 TNR 有点像，但都不是 TNR。

从源码中能读到的内容就是这些。

**Comment by mohuangrui** [comment]
@Carltonwei 当前采用的都是 Times-like 字体，而不是严格意义上的 Times New Roman，原因是当前的配置可以跨三大类操作系统使用，并且让windows 系统上编译生的的PDF无需额外字体配置就可以不产生乱码，而且全文本（包括文本和数学公式）可无乱码复制。

至于 Times 和 Times New Romain 的讨论，可以 (tex.se)[https://tex.stackexchange.com/questions/211326/best-math-font-with-times-new-roman-in-xelatex]，正好也是我想对你的问题所作的回答，即：

"First Addendum: A personal comment on the mostly minuscule differences between Times (aka Times Roman) and Times New Roman. To the best of my knowledge, there are only two readily-noticeable differences among the two fonts when using Latin letters (more differences occur with Greek letters):

the italic lowercase letter z: it's "swashy" with Times Roman, but non-swashy with Times New Roman; and

the % symbol, in both upright and italic mode: the first, i.e., upper "0" symbol and the solidus (aka slash symbol) are not connected with Times New Roman, but they are connected with Times Roman.
enter image description here

Would you -- or anyone else who's not a rather serious font afficionado -- ever take note of these differences and say, "tut, tut, why is this document using Times if it should be using Times New Roman? (Some even less readily visible differences between the two fonts are listed on the Wikipedia page.)"

**Comment by Carltonwei** [comment]
谢谢学长的细心回答~

**Comment by mohuangrui** [comment]
@Carltonwei  对了，正如 @muzimuzhi 所总结的，

当前 ucasthesis 的英文字体详细配置如下

```
1. 若使用 pdflatex，为通过 newtxtext 宏包使用 TeX Gyre Termes 字体
2. 若使用 xelatex，且字体文件 XITS-Regular.otf 不存在，为通过 newtxtext 宏包使用 TeX Gyre Termes 字体
3. 若使用 xelatex，且字体文件 XITS-Regular.otf 存在，则使用 XITS 字体
```

需要指出的是，当出现 1. 和 2. 的情形时，ucasthesis 将不修改 sans font 为 times 字体，即标题中的英文文本将使用默认的 sans 字体，而不是像正文那样使用 times 字体。其解决办法为：

1. 使用 xelatex 编译而不是 pdflatex 编译。
2. 使用 xelatex 编译后标题中的英文仍不为 times 字体，则说明所使用的 LaTeX 编译器版本过旧，其解决办法为：
    1. 更新 LaTeX 编译器为最新版（推荐）。
    2. 若不更新编译器，则可手动设定英文字体采用 times 字体，即 `在标题中使用 {\rmfamily English Text}` 替换 `在标题中使用 English Text`。
