### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by e71828** [mohuangrui/ucasthesis#160]
artracom中的[数学字符](https://github.com/mohuangrui/ucasthesis/blob/67ed27be6f48a8ffa7965bc68d52414fb9e042b4/Style/artracom.sty#L64-L70)
```\providecommand{\Vector}[1]{\boldsymbol{#1}}% general vectors in bold italic
%\renewcommand{\vec}[1]{\Vector{#1}}% redefine predefined vector if needed
\providecommand{\unitVector}[1]{\boldsymbol{\mathbf{#1}}}% unit vectors in bold roman
\providecommand{\Tensor}[1]{\boldsymbol{\mathsf{#1}}}% tensor in sans-serif bold italic
\providecommand{\unitTensor}[1]{\boldsymbol{{\mathsf{#1}}}}% identity tensor in sans-serif bold
\providecommand{\Matrix}[1]{\boldsymbol{\mathbf{#1}}}% matrix in bold roman
\providecommand{\unitMatrix}[1]{\boldsymbol{\mathbf{#1}}}% identity matrix in bold roman
```
如何在矩阵两边加[]，向量两边加{}，而单位向量、单位矩阵加粗，保持不变。
张量的字体在Windows下区分度也不是很大。
空间算子，时序算子，求解算子又怎么理解。

**Comment by muzimuzhi** [comment]
> 如何在矩阵两边加[]，向量两边加{}，而单位向量、单位矩阵加粗，保持不变。

你引用的命令定义，是用于输出单个字母的。例如`向量 \vec{x}`，`张量 \Tensor{a}`。

你想要的，输出矩阵、向量具体内容的方式，见 [lshort-zh-cn](https://ctan.org/pkg/lshort-zh-cn), sec. 4.5。

> 张量的字体在Windows下区分度也不是很大。
等作者回应

> 空间算子，时序算子，求解算子又怎么理解。
这句没懂。

**Comment by mohuangrui** [comment]
最新使用说明内的Appendix 有各类数学命令的样式，可根据需要自行测试设定所需样式，至于区分度的问题，ucasthesis 要求英文全为 times，所以限定了sans和mono的样式选择。

关于括号的问题，请阅读数学公式相关的材料。

因时间原因，以后请勿再问这类知识性问题，谢谢

**Comment by e71828** [comment]
打扰了

**Comment by muzimuzhi** [comment]
补充

一般性到问题，可以到 https://github.com/CTeX-org/forum 提问。
