### ISSUE TITLE
关于编译环境的问题

### ISSUE THREAD

**Issue by StKlaas** [mohuangrui/ucasthesis#161]
您好， 我在texlive2015和2016的版本上都编译不通过， 请问是否是需要更新到texlive2018等最新版本。 
2015出现的错误是
! Undefined control sequence.
<recently read> \IfFontExistsTF 
                                
l.317     \IfFontExistsTF
                         {XITS-Regular.otf}{%
? 

先谢谢指教了！

**Comment by muzimuzhi** [comment]
需要更新。并且，建议更新到 texlive2018。

具体到你的这个错误，
 - 定义 `\ifFontExsistsTF` 的代码是 2016 年 12 月提交的，见 https://github.com/wspr/fontspec/commit/503acca4549cc87a37e75fb6dac6fedd1a7020ec
 - 包含该部分代码的最早 `fontspec` 版本
    - 在 github repo 上，是 v2.5c
    - 在 CTAN 上，是 2017 年 2 月的 v2.6, 见 [link](https://ctan.org/ctan-ann/id/mailman.3278.1487005048.17497.ctan-ann@ctan.org)
    - 在 texlive 上，是 2017 年 1 月 27 的 v2.5d
 - 能确定的是，texlive 2017 一定包含了该修改
 - 不大确定的是，texlive 2016 能否升级到 v2.5d

解决这个问题后，可能还会遇到因为版本旧而导致的其他问题。所以建议更新到新版。

刚发布的 texlive 2019 存在小问题，可以从[历史镜像](ftp://tug.org/historic/systems/texlive/) 下到 2018。

**Comment by StKlaas** [comment]
升级到texlive2018之后没有报错了。 建议在正文里面对编译环境版本做个说明，可以避免使用者做无所谓的debug。

**Comment by mohuangrui** [comment]
谢谢建议，使用说明中有对编译问题进行说明，并链接了 https://github.com/mohuangrui/ucasthesis/wiki/编译指南

**Comment by muzimuzhi** [comment]
@mohuangrui 
在模板里加载 latex2e 格式和宏包时，可以指定所需的最低版本，例如
```latex
\LoadClass[<options>]{<class>}[<date>]
\RequirePackage[<options>]{<package>}[<date>]

% <date> := YYYY/MM/DD, e.g. 2018/12/31
```
详见文档 `texdoc clsguide`, sec. 3.2。

如果用户加载的版本低于指定的版本，会触发警告。虽然不是错误，也比没有信息稍好一些。
![image](https://user-images.githubusercontent.com/6376638/57313826-f6813380-7122-11e9-8d50-48953ce194ec.png)

**Comment by mohuangrui** [comment]
@muzimuzhi 谢谢建议：D 不过能读到最开始的warning的人很少，再者，对于 \IfFontExistsTF 这样的问题，这个warning 最终也无济于事：D

尽管如此，若更新则考虑加进去
