### ISSUE TITLE
1.5倍行距英文乱码, pdflatex, windows

### ISSUE THREAD

**Issue by capsane** [mohuangrui/ucasthesis#162]
您好，我使用最新的模板，将Style/ucasthesis.cls文件中的行距修改为1.5，使用pdflatex编译后，所有的英文拷贝之后都是乱码，请问这种情况怎么处理？

**Comment by mohuangrui** [comment]
你好，请首先想想如何问一个逻辑合理的问题，否则就是在浪费所有人的时间

On May 11, 2019, at 12:32 PM, Capsane <notifications@github.com<mailto:notifications@github.com>> wrote:


您好，我使用最新的模板，将Style/ucasthesis.cls文件中的行距修改为1.5，使用pdflatex编译后，所有的英文拷贝之后都是乱码，请问这种情况怎么处理？

**Comment by capsane** [comment]
？？有逻辑问题可以直接说出来，写下这行字会让你舒适？

“考虑到许多同学可能缺乏 LaTeX 使用经验，ucasthesis 将 LaTeX 的复杂性高度封装，开放出简单的接口，以便轻易使用。同时，对用 LaTeX 撰写论文的一些主要难题，如制图、制表、文献索引等，进行了详细说明，并提供了相应的代码样本，理解了上述问题后，对于初学者而言，使用此模板撰写学位论文将不存在实质性的困难。所以，如果你是初学者，请不要直接放弃，因为同样为初学者的我，十分明白让 LaTeX 简单易用的重要性，而这正是 ucasthesis 所追求和体现的。”

我是初学者，很抱歉打扰到你。

**Comment by mohuangrui** [comment]
既是初学者，那就请
1. 认真读读 `模版使用说明.pdf`，然后你就知道，推荐使用 xelatax，编辑文档需采用 utf8 编码。
2. 读读 https://github.com/mohuangrui/ucasthesis/wiki ，就会看到建议：不要总是去想着如何去修改样式，而是应好好关注自己论文的内容。
3. 即使是初学者，你也需明白自己的错误并不是别人的责任。你下载模版，pdflatex编译后，可以正常拷贝文本吗？若是可以，而你修改后却不行了，那问题就是你自己的不正确修改不应修改的文件所引入的。

纯粹的行距的调整是不可能导致拷贝乱码的，我只能推测你可能编辑 ucasthesis 文件时没有确保 utf8 编码的使用。祝好
