### ISSUE TITLE
参考文献排版稀疏

### ISSUE THREAD

**Issue by cyx669521** [mohuangrui/ucasthesis#163]
提示如下：
Underfull \hbox (badness 10000) in paragraph
参考文献中出现很多大空格

**Comment by cyx669521** [comment]
> 提示如下：
> Underfull \hbox (badness 10000) in paragraph
> 参考文献中出现很多大空格

![image](https://user-images.githubusercontent.com/10829064/57577946-f8e1e580-74b4-11e9-8341-18fa179351d0.png)

**Comment by muzimuzhi** [comment]
具体问题的提问要求：提供 MWE
===
参考资料：如何准备 MWE
https://paste.ubuntu.com/p/Rn4D6pdVDb/

**Comment by mohuangrui** [comment]
将 MWE 加入了 

如何有效地问问题？https://github.com/mohuangrui/ucasthesis/wiki/常见问题

@cyx669521 请参照上述链接提供必要的信息

**Comment by bujianbusan** [comment]
这个大空格，应尝试检查bibtex库中的条目信息
