### ISSUE TITLE
封面字体问题

### ISSUE THREAD

**Issue by guokejieshao** [mohuangrui/ucasthesis#164]
中科院信息工程研究所今年要求的封面字体是宋体四号加粗，但是模板封面字体是黑体，其他研究所不清楚。原创新声明中多了一句“本文完全意识到本声明的法律结果由本人承担”，题目应该为“中国科学院大学  研究生学位论文原创性声明”

**Comment by mohuangrui** [comment]
1. "但是模板封面字体是黑体" 

你确定你看了？

2. 原创新声明中多了一句“本文完全意识到本声明的法律结果由本人承担”

你确定是 “本文完全意识“？

3. 题目应该为“中国科学院大学 研究生学位论文原创性声明”

根据这个信息，你参照的是过时的旧版

**Comment by guokejieshao** [comment]
您好，您是说我参考的论文格式是过时的版本？还是说我的latex模板是旧的版本？我是参考我们所下发的论文要求。


------------------ 原始邮件 ------------------
发件人: "mohuangrui"<notifications@github.com>;
发送时间: 2019年5月14日(星期二) 上午10:39
收件人: "mohuangrui/ucasthesis"<ucasthesis@noreply.github.com>;
抄送: "李杰"<1194859624@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [mohuangrui/ucasthesis] 封面字体问题 (#164)



 
"但是模板封面字体是黑体"
  
你确定你看了？
  
原创新声明中多了一句“本文完全意识到本声明的法律结果由本人承担”
  
你确定是 “本文完全意识“？
  
题目应该为“中国科学院大学 研究生学位论文原创性声明”
  
根据这个信息，你参照的是过时的旧版

**Comment by mohuangrui** [comment]
你们所下发的要求不是国科大最后的修订版，你所提出的那个问题，ucasthesis 所采用的是正确的，是由国科大学位办老师确认过的

**Comment by guokejieshao** [comment]
好的，了解了，那麻烦您了。至于封面字体的问题貌似是编译器的原因，MAC生成的是宋体，但是我知道的几个windows生成的是黑体。




------------------ 原始邮件 ------------------
发件人: "mohuangrui"<notifications@github.com>; 
发送时间: 2019年5月14日(星期二) 上午10:45
收件人: "mohuangrui/ucasthesis"<ucasthesis@noreply.github.com>; 
抄送: "李杰"<1194859624@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mohuangrui/ucasthesis] 封面字体问题 (#164)




你们所下发的要求不是国科大最后的修订版，你所提出的那个问题，ucasthesis 所采用的是正确的，是由国科大学位办老师确认过的

**Comment by mohuangrui** [comment]
基于你问问题时你自身引入的多处漏洞，建议你认真调研和阅读相关资料，包括你们所下发的信息和ucasthesis的使用信息。

比如Windows黑体的问题，如果你读了使用说明，就知道需要用 xelatex 而不是 pdflatex 编译

**Comment by mohuangrui** [comment]
祝好

**Comment by guokejieshao** [comment]
感谢。



------------------ 原始邮件 ------------------
发件人: "mohuangrui"<notifications@github.com>; 
发送时间: 2019年5月14日(星期二) 上午10:49
收件人: "mohuangrui/ucasthesis"<ucasthesis@noreply.github.com>; 
抄送: "李杰"<1194859624@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [mohuangrui/ucasthesis] 封面字体问题 (#164)




基于你问问题时你自身引入的多处漏洞，建议你认真调研和阅读相关资料，包括你们所下发的信息和ucasthesis的使用信息。
 
比如Windows黑体的问题，如果你读了使用说明，就知道需要用 xelatex 而不是 pdflatex 编译

**Comment by VitoChien** [comment]
Windows黑体的问题可以按照使用说明里提到的方法，安装adobe字体后改用xelatex编译。我用该方法解决了封面黑体的问题。

**Comment by guokejieshao** [comment]
嗯嗯，谢谢



------------------ 原始邮件 ------------------
发件人: "VitoChien"<notifications@github.com>; 
发送时间: 2019年5月14日(星期二) 中午11:29
收件人: "mohuangrui/ucasthesis"<ucasthesis@noreply.github.com>; 
抄送: "李杰"<1194859624@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [mohuangrui/ucasthesis] 封面字体问题 (#164)




Windows黑体的问题可以按照使用说明里提到的方法，安装adobe字体后改用xelatex编译。我用该方法解决了封面黑体的问题。
