### ISSUE TITLE
\href{URL}{text}中网址含有%怎么破，

### ISSUE THREAD

**Issue by e71828** [mohuangrui/ucasthesis#165]
%是注释标记，url含有%怎么办，如何实现href

**Comment by muzimuzhi** [comment]
0. 你的问题和这个模板无关，是一般性的 latex 使用问题。发在这里是错误的，建议发到 https://github.com/CTeX-org/forum
1. 包含 `%` 的 URL，正常输入即可。
2. 在任何情况下，都不要继续回复这个 issue。如需要回复，去上述 forum 发新 issue 提问，然后引用这个 issue。
