### ISSUE TITLE
Font 'Heiti SC' does not contain script 'CJK'

### ISSUE THREAD

**Issue by JepsonWong** [mohuangrui/ucasthesis#166]
Latex版本：Mac下的Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=LaTex)

具体warning：类似好多字体都报警告，请问该怎么解决呢？谢谢
*************************************************
* fontspec warning: "script-not-exist"
*
* Font 'Heiti SC' does not contain script 'CJK'.
*************************************************
*************************************************
* fontspec warning: "script-not-exist"
*
* Font 'Songti SC Light' does not contain script 'CJK'.
*************************************************

**Comment by mohuangrui** [comment]
你好，不用解决，latex的warning有其内在的复杂性，并不总是有效信息，没人能全部解决，特别是关于中文字体的

On May 20, 2019, at 9:35 PM, JepsonWong <notifications@github.com<mailto:notifications@github.com>> wrote:


Latex版本：Mac下的Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=LaTex)

具体warning：类似好多字体都报警告，请问该怎么解决呢？谢谢

________________________________

  *   fontspec warning: "script-not-exist"
  *
  *   Font 'Heiti SC' does not contain script 'CJK'.

________________________________
________________________________

  *   fontspec warning: "script-not-exist"
  *
  *   Font 'Songti SC Light' does not contain script 'CJK'.

________________________________

**Comment by JepsonWong** [comment]
好的，非常感谢！

**Comment by muzimuzhi** [comment]
1. 粗略的区分，错误（error）表示出现了影响程序正常运行的输入，警告（warning）表示出现了与程序作者预期不一致的输入。一般，需要解决遇到的每一个错误，但不一定需要完全清除每一个警告。
1. 这个 `fontspec` 的警告，只是提示「某字体文件中不包含 script "CJK"」，不影响宏包的功能，可以忽略。
1. 这个警告的具体文本，已经在提交 https://github.com/wspr/fontspec/commit/173769773d5397fbac5be3b99f58e9f492547c24 中改为
    ```
    Package fontspec Warning: Font "XXX" does not contain requested
    (fontspec)                Script "CJK".
    ```
    `fontspec` v2.7a 开始生效。
