### ISSUE TITLE
请教大神：在页面横排时，如何页眉页脚位于页面的长边上？

### ISSUE THREAD

**Issue by CDMA2019** [mohuangrui/ucasthesis#169]
在页面横排时，如何页眉页脚位于页面的长边上？
由于学位论文规定：如表较大需要横排，则页眉在左，页码在右（奇数页页眉在靠近书脊、装订侧，页码在外侧；偶数页页眉在外侧，页码在靠近书脊装订侧）。
我已尝试使用landscape宏包将页面旋转90度，但问题在于页眉也随之旋转，无法实现规定里要求的，页眉应位于页面的长边上。另外，试图将单个页面的尺寸修改，将宽变为长，长变为宽，但是\newgeometry无法修改页面尺寸。
因此请教大神如何解决此问题，已在百度、google进行搜索，没有比较满意的答案，请不吝赐教！

**Comment by mohuangrui** [comment]
1. 没有看到横排图表对页眉页脚的规定。
2. 你确定横排页眉页脚是需要的？打印成论文后那一页的页眉页脚排成那样能看？
3. 页眉页脚本就是个装饰功能，而且前后一致才合理。就算可以横排页眉页脚，那页眉上的下划线画多长？

**Comment by CDMA2019** [comment]
解释：
1.各高校在学位论文的细节规定上各不相同，因此只能服从。
2.个人感觉对横排页眉的规定不合理，但事实就是如此，仍需遵守。
3.我贴一张图，是已毕业师兄的word论文截图。
![2](https://user-images.githubusercontent.com/47963099/58366672-64da3a00-7f08-11e9-9e5f-2dc2c6c1c9e8.png)

**Comment by mohuangrui** [comment]
见更新：

* `2019-05-25` 根据 [CDMA2019, issue #169](https://github.com/mohuangrui/ucasthesis/issues/169) 提供横排图表环境下页眉页脚的横排，具体使用见 [横排图表](https://github.com/mohuangrui/ucasthesis/wiki/横排图表)。

**Comment by CDMA2019** [comment]
感谢大神指点！
