### ISSUE TITLE
bst file not standardized

### ISSUE THREAD

**Issue by GitatHub** [mohuangrui/ucasthesis#17]
there is a problem in the BST style
all 'dots' in names are removed,  and this is not standardized.
For example, J. Richard was changed to Richard J, in fact there should be a  comma after Richard.

in details:
1. all 'dots' in English names are removed, and this is not standardized.
2. all English names are printed in a wrong format, e.g. James RICHARD is RICHARD James with ',' missing!
and J. Richard is printed as Richard J with '.' missing.
The two gbt-7714-2015 bst files are really really bad.\\\

HAVE to use plainnat instead

**Comment by mohuangrui** [comment]
Hello,

Yes, you're right that there is a formatting issue with English names in 
the gbt-7714-2015 BST files. As you also have raised it to the BST 
developers, let's wait for the corrections.

Thanks

**Comment by GitatHub** [comment]
oh, man
don't tell me you have no idea to fix this....

as to the style of tile that should use 'emphasize', I think I have to manually add \emph{} to the tile of each entry.

**Comment by zepinglee** [comment]
你们的标准在GBT7714-2015的基础上做了些修改，那你们自己去改 bst 文件

**Comment by JunHuangUCAS** [comment]
Hi, 

I have a question on the style of the reference.

Read J, Pfahringer B, Holmes G, et al. Classifier chains for multi-label classification[C]. Proc. Eur. Conf. Mach. Learn. [S.l.], 2009: 254-269.

Here, what's the meaning of "[S.l.]", and how to remove it? thanks.

**Comment by mohuangrui** [comment]
Hello,

I haven't modified the bst file. I just updated it to the latest version 
maintained by you; however, the English name issue still exists. It 
would be great if you can fix that.

Thanks a lot,
Mo Huangrui

**Comment by mohuangrui** [comment]
Hello,
I guess the [S.I.] is a notation required by the GBT-2015 standard. 
Therefore, you're not supposed to remove it if you are writing a thesis 
in Chinese. The reference style is always a messy problem. However, I 
would like to suggest you avoid putting energy on those details, please 
just let them be the way they appear. The reference style is not a big 
deal, and you can change it anytime in the future once you find a 
suitable style.
Cheers

**Comment by zepinglee** [comment]
Seems that the bibliography style requested by UCAS's standard is slightly different from the [GB/T 7714-2015](https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style/files/153951/GBT.7714-2015.pdf) I implemented. So you need to make some modifications.

**Comment by GitatHub** [comment]
Hello, you may see the developer's reply.
That is not an issue in the BST file but an issue for the so called national standard.
I do not know why the standard was made like that.
However, the GB is obviously incompatible with the so called international academic standard, at least in English names.
I here suggest that you add an option for using another alternative style, e.g., plainnat.
Infact, I have changed it to plainnat.

Now we may know why PKU THU etc do not use the GB reference style. It indeed a ridiculous format, 
though the GBT bst file reproduced the style precisely which is a good job.
@mohuangrui

**Comment by GitatHub** [comment]
@JunHuangUCAS 
I suggest you do not use the GB bst file though the BST file is a good job.
Unless there is no English reference in your thesis, you will find just plainnat is good enough.
What you need to do is just manually modify the bbl file in the final compilation, to move those Chinese reference in front of all other references.

**Comment by GitatHub** [comment]
@zepinglee 
your bst file is an excellent job. However, the GB is not compatible with the so called academic community standard, and more and more professors are from abroad who always respect the so called academic community standard.

**Comment by mohuangrui** [comment]
Hello Zeping Lee,

I just had an opportunity to have a look at the GB/T 7714-2015 
<https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style/files/153951/GBT.7714-2015.pdf>, 
and now I completely agree with you. Your implementation strictly obeys 
the GB and is perfectly correct. I'm really sorry for my previous 
mistake to raise a question to you without thorough investigation but 
only using my personal experience. Sorry again and I greatly appreciate 
your efforts to implement the GB/T 7714-2015 
<https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style/files/153951/GBT.7714-2015.pdf> 
BST.

Thank you very much for your invaluable time.

Sincerely,
Mo Huangrui

**Comment by mohuangrui** [comment]
Hi,

The presented reference style conforms to the GB and is correct. As I 
suggested before, please avoid putting your energy on those as long as 
they obey the standard.

Cheers,
Mo Huangrui

**Comment by mohuangrui** [comment]
Hi,

Sorry that I cannot agree with you about your comments on the GB, please 
spend some time to understand things before you draw conclusions.

Bests

**Comment by GitatHub** [comment]
yes Lee's BST files are really good.
But is there a standard for those inline names, e.g., should the Webb inline be WEBB or Webb?
According to the GB, the names in reference list should be WEBB.

btw, http://blog.sciencenet.cn/home.php?mod=space&uid=3061&do=blog&id=376483
the standard is not so bad

**Comment by mohuangrui** [comment]
Hi,
I have updated the BST files to Lee's latest work, in which the 
appearance is correct.
As for the standard, every one may has his/her own opinions. In my 
opinion, it's important to standardize the reference style but it's 
nothing important about the appearance of the style. If you think that 
the western style is the only correct thing, you're free to hold your 
criticism about the GB. One basic fact is that even the western style is 
not unique.

Cheers

**Comment by zepinglee** [comment]
Actually I don't like the GB/T 7714 standard either. However, it is a recommended standard not a compulsory one (with a 'T' in in its name), you are allowed to use a modified version as a template.

BTW, the name format is not defined in GB/T 7714. I just followed the examples given in the standard. But you can easily change it to lower case, which is mentioned in a issue of my repository.

**Comment by mohuangrui** [comment]
So I am the loser of the game? Naive! Please go to the Springer website

http://www.springer.com/engineering/mechanical+engineering/journal/193?detailsPage=editorialBoard

choose "Instructions for Authors", then expand "Text", and then download 
the LaTeX macro package, and then test with the "spbasic.bst", finally, 
you will find the outputted reference style as:

1. Brehm C, Hader C, Fasel HF (2015) A locally stabilized
immersed boundary method for the compressible Navier-
Stokes equations. J Comput Phys 295:475–504
2. Fedkiw RP (2002) Coupling an Eulerian fluid calculation
to a Lagrangian solid calculation with the ghost fluid
method. J Comput Phys 175(1):200–224

Sorry....

**Comment by GitatHub** [comment]
The test Latex bst you got from springer may be outdated or for a "manual" mode.
You may find that the final style of reference in the journal you mentioned above, is in an "academic community"  accepted style:
https://link.springer.com/article/10.1007/s11207-017-1055-x

and so is the book style
https://link.springer.com/book/10.1007%2F978-1-4020-5604-8

Nevertheless, you and Lee are both doing wonderful jobs, in implementing the thesis format and the GB style.

Other users including me should thank you.
