### ISSUE TITLE
如何调整目录页，数字和文本之间的距离？

### ISSUE THREAD

**Issue by DRjy** [mohuangrui/ucasthesis#170]
![image](https://user-images.githubusercontent.com/46476977/58785387-fe47d100-8617-11e9-98f5-f828b3375e74.png)

现在想缩小这个数字和文字中间的距离，我该如何调整？

**Comment by e71828** [comment]
https://github.com/mohuangrui/ucasthesis/blob/2a60fde1356c1c1cd5cd4ee6359049ff15a57577/Style/ucasthesis.cls#L649-L653
\def\@dotsep{1.5mu}% 目录点距
\def\@pnumwidth{2em}% 页码字符盒子占用宽度
\def\@tocrmarg{2em}% 目录过长时的右侧空白宽带
\def\@chaptervspace{1ex}% 章级目录的间距


https://github.com/mohuangrui/ucasthesis/blob/2a60fde1356c1c1cd5cd4ee6359049ff15a57577/Style/ucasthesis.cls#L695
章级目录的间距

https://github.com/mohuangrui/ucasthesis/blob/2a60fde1356c1c1cd5cd4ee6359049ff15a57577/Style/ucasthesis.cls#L658
章以下级目录的间距

**Comment by muzimuzhi** [comment]
把以下部分加到 `Thesis.tex` 的 `\begin{document}` 之前。

```latex
\usepackage{xpatch}

\makeatletter
\ExplSyntaxOn
\xpatchcmd\CTEX@chapter@tocline
  {.3em}
  {0em}
  {}{\fail}
\ExplSyntaxOff

%% change the 3rd arg of \@dottedtocline
%% bofore
% \renewcommand*\l@section{\@dottedtocline{1}{1em}{2em}}
%\renewcommand*\l@subsection{\@dottedtocline{2}{2em}{3em}}
%% after
\renewcommand*\l@section{\@dottedtocline{1}{1em}{1.5em}}
\renewcommand*\l@subsection{\@dottedtocline{2}{2em}{2.5em}}
\makeatother
```

效果
![image](https://user-images.githubusercontent.com/6376638/58878147-282af180-8705-11e9-92a8-88aaf352ba7e.png)


涉及的源码
1. 本项目中的（有其他调整需求，也可以模范着改）
https://github.com/mohuangrui/ucasthesis/blob/2a60fde1356c1c1cd5cd4ee6359049ff15a57577/Style/ucasthesis.cls#L710-L717
2. ctex-kit 项目中的
https://github.com/CTeX-org/ctex-kit/blob/4449ab586987a4a86bc7a6210d84e018b3bd6190/ctex/ctex.dtx#L7866-L7874

**Comment by muzimuzhi** [comment]
@e71828 你评论里提及的那几个储存长度的宏，和当前 issue 问的「目录项中，数字部分和标题之间的横向空白，如何调整其宽度」都没有直接联系。你贴的注释部分，也能说明问题

> \def@dotsep{1.5mu}% 目录点距
> \def@pnumwidth{2em}% 页码字符盒子占用宽度
> \def@tocrmarg{2em}% 目录过长时的右侧空白宽带
> \def@chaptervspace{1ex}% 章级目录的间距

@mohuangrui 根据这个[评论](https://github.com/mohuangrui/ucasthesis/issues/142#issuecomment-480556536)里提供的国科大《学位/毕业论文撰写规定》，模板生成的「目录项数字部分和标题之间的间距」确实比规范文件末尾的的例子稍大。是否考虑调整模板？

**Comment by DRjy** [comment]
`\renewcommand*\l@section{\@dottedtocline{1}{1.5em}{2.0em}}
\renewcommand*\l@subsection{\@dottedtocline{2}{3.8em}{2.0em}}
\renewcommand*\l@subsubsection{\@dottedtocline{3}{7.0em}{2.0em}}`

我最后是通过这个方法解决的。
`% \renewcommand{\l@<typ>}{\@dottedtocline{<level>}%
% {<indentation>}%
% {<numwidth>}}`

**Comment by e71828** [comment]
@muzimuzhi 抱歉啊  我误导人了  一眼看到的vspace啥的就顾名思义了

**Comment by muzimuzhi** [comment]
> `\renewcommand*\l@section{\@dottedtocline{1}{1.5em}{2.0em}} \renewcommand*\l@subsection{\@dottedtocline{2}{3.8em}{2.0em}} \renewcommand*\l@subsubsection{\@dottedtocline{3}{7.0em}{2.0em}}`
> 
> 我最后是通过这个方法解决的。
> `% \renewcommand{\l@<typ>}{\@dottedtocline{<level>}% % {<indentation>}% % {<numwidth>}}`

是的，这样可以修改 section 及更低层级的目录项。我提供的 `\xpatchcmd\CTEX@chapter@tocline` 部分，是用来修改 chapter 目录项的（因为看你的截图里，把 chapter 目录项中的间距也圈出来了）。

**Comment by mohuangrui** [comment]
@muzimuzhi 谢谢建议，这个先标记着，如果需要，将来再改

**Comment by mohuangrui** [comment]
@DRjy 经复审，发现你的截图间距为旧版的间距，因此较大。 @muzimuzhi 测试发现每个减掉 0.5em 有些过多，导致图表列表排列异常。最后调整为减掉 0.2em ：D
