### ISSUE TITLE
如何将中英文双标题改为单中文标题

### ISSUE THREAD

**Issue by e71828** [mohuangrui/ucasthesis#171]
学长好：

虽然我写论文的时候用了中英文双标题，其实翻译得不太好；如果需要以纯中文模式提交，如何舍去英文标题。除了用caption替换之外，用其它快捷的命令组合么

**Comment by muzimuzhi** [comment]
这是与 latex 一般使用有关的问题，与当前项目无关。

建议维护者把当前 issue 挪到 https://github.com/CTeX-org/forum 项目中。操作说明见 [Transferring an issue to another repository - GitHub Help](https://help.github.com/en/articles/transferring-an-issue-to-another-repository)。

**Comment by mohuangrui** [comment]
@muzimuzhi 谢谢建议，这个还是麻烦 @e71828 直接前往 https://github.com/CTeX-org/forum 发问吧。

@e71828 目前没有什么好的想法，建议就用 caption 替换吧，你把 bicaption 的复制一遍然后用 caption 替换，最后把原来的注释掉作为记录保留。
