### ISSUE TITLE
全文只有一页的章节页眉是乱码

### ISSUE THREAD

**Issue by rexienanhai** [mohuangrui/ucasthesis#173]
您好，如题，生成的论文全篇只有一个章节中的页眉出现乱码（只有一页），生成了好几次都是如此，如下图所示，希望能得到您的回复，谢谢！
![LM](https://user-images.githubusercontent.com/41352474/58963131-35b4aa00-87df-11e9-95b7-51a5ee41e654.png)

**Comment by muzimuzhi** [comment]
请提供一个
 - 完整的（以 `\documentclass` 开始，以 `\end{document}` 结束）
 - 编译产生的 PDF 能复现问题
的例子。

**Comment by mohuangrui** [comment]
@rexienanhai  你好，请按照 @muzimuzhi 所建议的提供一个能复现你的问题的 .tex 文件，否则难以确定问题所在，谢谢

**Comment by mohuangrui** [comment]
你好，问题解决了没？建议仔细检查那一页及其附近的源代码中的特殊字符及编码，确定皆为正确的 uft-8 编码。

**Comment by xianshunw** [comment]
我也出现了这个问题，我发现把内容的里的两段合成一段写就变好了。
