### ISSUE TITLE
mathbb 与mathit

### ISSUE THREAD

**Issue by e71828** [mohuangrui/ucasthesis#176]
做了一点小修正
```
\DeclareCaptionLabelSeparator{enspace}{\enspace}%
\captionsetup{labelsep=enspace}%
```

```
\AtBeginDocument{
	  \DeclareSymbolFont{AMSb}{U}{msb}{m}{n}
	  \DeclareSymbolFontAlphabet{\mathbb}{AMSb}
	  \setmathfontface\mathit{XITS-Italic.otf}
}
```

之后，小写希腊字母没有斜体，大写希腊字母粗斜体和斜体一致，同为粗斜体

不过 是针对windows的，如果不用xits字体则没考虑

**Comment by muzimuzhi** [comment]
你「做小修正」的目的是什么？建议完整描述最初的需求。

**Comment by e71828** [comment]
@muzimuzhi 
第一  增大caption序号与图标题的间距，英文空格
第二  恢复mathbb原定义，用作张量的本构关系
第三  数学斜体的重定义，没什么用

**Comment by e71828** [comment]
还有三线表的粗细 heavyrulewidth  lightrulewidth

**Comment by mohuangrui** [comment]
@e71828 你好，谢谢建议，不过暂不会考虑修改，个人偏好可根据自身需求去设定：D

**Comment by muzimuzhi** [comment]
@e71828 不明白你开这个 issue 的目的。

1. issue 标题意义不明，标题对 issue 内容也不具有概括关系
1. 看不出是模板修改建议，还是个人定制方式展示。请明说
1. 你「第一」到「第三」的解释，尤其是后两条，是小修改的具体作用描述，而不是需求的描述。为什么希望恢复原定义？模板的默认设置，是不符合使用需求，还是不符合审美需求？

**Comment by e71828** [comment]
@muzimuzhi mathbb 我曾用它表示四阶张量，
关于修改建议，还是个人定制也不重要，我只是提出我的个人方案作为建议，是否采取就不是我能决定的了

**Comment by muzimuzhi** [comment]
> 关于修改建议，还是个人定制也不重要

这一点，很重要。模板是给提供给所有用户使用的，
 * 如果是对模板的修改建议，必须有足够的「所有用户都会需要它」的理由
 * 如果只是个人定制模板的一个尝试，建议说明「我想实现xx功能，我是这样做的，发在这里以供其他有类似需求的用户参考」
