### ISSUE TITLE
提供的命令，如\Vector等，并没有斜体；与bm包冲突；win下编译后，不再自动打开pdf。

### ISSUE THREAD

**Issue by HaorenWang** [mohuangrui/ucasthesis#177]
你好。我刚使用更新后的模板（6月9日）发现有如下情况：

1. 数学公式中，变量斜体问题。
- artracom.sty中提供的`\Vector`命令没有斜体效果。
- 且我使用\usepackage{bm}，无法通过编译，提示`! Extended mathchar used as mathchar (14799969).`。导致无法处理变量斜体问题。

2. Win下用批处理编译后，不能自动打开pdf了。原来的方式还是很方便的。虽然现在也可以手动修改批处理文件，取消对应行的注释。

使用系统：Win10_x64中文教育版，TeXLive 2018，TeXStudio。
---------------------------------------------------------------------------

今年查的严，所里又让改。所以还得麻烦师兄帮忙看看。

**Comment by HaorenWang** [comment]
补充：新模板的‘使用说明.pdf‘’中可以看到，向量没有斜体。但以前的模板的使用说明，都是斜体的。

**Comment by mohuangrui** [comment]
你好，
1. 因为国科大指导文件不区分 sans serif 和 serif 而是都用 serif type 的 times 字体，一些同学为了美观又要求数学字体也为 times，随后又更进一步要求数字字体在 text mode 和 math mode 也要统一为 times 字体。再考虑到又要跨平台 linux，windows，macos，进而又要考虑 vector，tensor，matrix之间的变化。凡此种种约束最后导致这个问题极为繁琐，已不知道尝试了多少方案。
今再次修改，也许已解决了你的问题，麻烦详细测试以下。
至于 bm，那个也什么意义，我没再测试了。

2. 这个注释掉是特意的，若需要则可自行取消注释。

祝好

**Comment by muzimuzhi** [comment]
`bm` 宏包的问题，你使用的是什么引擎？

**Comment by mohuangrui** [comment]
初步测试了以下，在 pdflatex 下 bm 貌似和 mathscr 冲突，在 xelatex 下和 unicode-math 冲突。

不管怎样，用 bm 是没有意义的，没必要在这上再浪费时间。

更新版已经解决了 粗斜体的问题，至于更多的设定，应参照 unicode-math 提供的 `\symbf` 系列字体样式，详见： 

http://mirrors.sjtug.sjtu.edu.cn/ctan/macros/latex/contrib/unicode-math/unicode-math.pdf

**Comment by HaorenWang** [comment]
> `bm` 宏包的问题，你使用的是什么引擎？

我用的应该是XeLaTeX

**Comment by HaorenWang** [comment]
一看更新时间是周五夜里。感谢师兄的辛苦工作。

现在已经可以斜体了。

另外，我发现“模版使用说明.pdf”好像一直没更新

**Comment by mohuangrui** [comment]
@HaorenWang 使用说明不再更新了，因为 PDF 为较大的 binary 文件，git 不断储存其历史，导致 package clone 的 size 过大。

感谢师弟测试确认，祝论文写作顺利。

若无问题，则可以关闭此 issue 了 ：D

**Comment by HaorenWang** [comment]
OK。

**Comment by wzh621** [comment]
你好，模板中公式样式能设置成 AMS 样式吗？

**Comment by sikouhjw** [comment]
> 你好，模板中公式样式能设置成 AMS 样式吗？

请你明确 AMS 样式是什么，如果你要的是所谓的『latex 原生字体』，请阅读
> 一些同学为了美观又要求数学字体也为 times，随后又更进一步要求数字字体在 text mode 和 math mode 也要统一为 times 字体

如果你执意要改，请修改
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L382-L417
为 `Latin Modern Math`

**Comment by wzh621** [comment]
非常感谢！
