### ISSUE TITLE
\section{}

### ISSUE THREAD

**Issue by lihui077** [mohuangrui/ucasthesis#178]
\usepackage[version=4]{mhchem}
\section{\ce{ F + H2(\upsilon)}} 不能够通过编译啊？
请问这种怎么解决？
谢谢！

**Comment by mohuangrui** [comment]
你好，刚基于 ucasthesis 当前版测试了，没有出现问题，可以正常编译和显示。

![image](https://user-images.githubusercontent.com/7518165/60312921-bfdfd080-998f-11e9-9f79-12a6cdb632db.png)

请仔细确认问题的真正所在。另外，你也可以尝试看看：“章节标题中的数学符号导致报错？” https://github.com/mohuangrui/ucasthesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by mohuangrui** [comment]
对了，记得使用 xelatex 编译而不是 pdflatex，我没有测试 pdflatex

**Comment by lihui077** [comment]
已解决，多谢！

**Comment by mohuangrui** [comment]
怎么解决的？留个记录吧～

**Comment by lihui077** [comment]
我换了个环境，win7下还是不行，overleaf和unix下面都可以正常使用。

**Comment by mohuangrui** [comment]
我刚在 windows 10 + miktex 的配置下进行了测试，pdflatex 没有问题，可以顺利编译并显示。但 xelatex 却会出现问题。而这一问题确实在 unix 上却又不存在。

至于解决方案，已在前面提及，即看:

“章节标题中的数学符号导致报错？” https://github.com/mohuangrui/ucasthesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

对于你的这个特定问题，就是用：
```
\section{\texorpdfstring{\ce{ F + H2(\upsilon)}}{F + H2(v)}} 
```
代替 
```
\section{\ce{F + H2(\upsilon)}} 
```
或者，你也可以选择在 `artratex.sty` 中取消对如下行的注释即可：

https://github.com/mohuangrui/ucasthesis/blob/3b895a2cc87e14411756688662e531f1f05c8a2b/Style/artratex.sty#L546

**Comment by lihui077** [comment]
取消注释这一句话，就可以了( psdextra=true,% extra support for math symbols in bookmarks)
多谢了！
