### ISSUE TITLE
参考文献URL如何另起一行显示

### ISSUE THREAD

**Issue by magicteddy** [mohuangrui/ucasthesis#179]
您好，请问如何将参考文献各条目中的URL信息另起一行显示？现在默认效果是URL紧跟着 年份呈现而未换行，有时会因为URL过长而拉伸文字不美观，例如：
[1] 国家计算机网络应急技术处理协调中心. 网络安全报告[EB/OL]. 2013. http://www.cert.
org.cn/publish/main/upload/File/2013%20Annual%20Report%20.pdf.

而其他文献中是如此显示：
[1] 国家计算机网络应急技术处理协调中心. 网络安全报告[EB/OL]. 2013.
http://www.cert.org.cn/publish/main/upload/File/2013%20Annual%
20Report%20.pdf.

尝试过https://timmurphy.org/2010/04/04/referencing-website-urls-with-latex-bibtex/ 等教程所讲方法，但依旧没有效果。

**Comment by mohuangrui** [comment]
请提供明确信息以支持你的要求是符合国标的

**Comment by magicteddy** [comment]
国标gbt7714-2005里我没有找到具体要求。但我看历届用老模板生成大论文里，参考文献条目URL都是换行显示的，比较美观。但我用最新模板生成的参考文献，都是紧跟着呈现。能麻烦告诉我如何手动调整吗？

**Comment by mohuangrui** [comment]
@zepinglee 请问有简单有效的方法吗？

**Comment by muzimuzhi** [comment]
试试在导言区添加
```latex
\AtBeginDocument{
  \let\oldurl\url
  \def\url{\newline\oldurl}
}
```

对于同时有超链接和 doi 的文献，这样会比较奇怪：
![image](https://user-images.githubusercontent.com/6376638/60529356-fe2b1600-9d28-11e9-92ed-1e602d02d588.png)

**Comment by magicteddy** [comment]
> 试试在导言区添加
> 
> ```
> \AtBeginDocument{
>   \let\oldurl\url
>   \def\url{\newline\oldurl}
> }
> ```
> 
> 对于同时有超链接和 doi 的文献，这样会比较奇怪：
> ![image](https://user-images.githubusercontent.com/6376638/60529356-fe2b1600-9d28-11e9-92ed-1e602d02d588.png)

试了，确实有效，非常感谢！

**Comment by zepinglee** [comment]
> 有时会因为URL过长而拉伸文字不美观

这主要是 url 的断行问题，`xurl` 宏包处理得比较好，代码也很短：
```
\def\UrlBreaks{%
  \do\/%
  \do\a\do\b\do\c\do\d\do\e\do\f\do\g\do\h\do\i\do\j\do\k\do\l%
     \do\m\do\n\do\o\do\p\do\q\do\r\do\s\do\t\do\u\do\v\do\w\do\x\do\y\do\z%
  \do\A\do\B\do\C\do\D\do\E\do\F\do\G\do\H\do\I\do\J\do\K\do\L%
     \do\M\do\N\do\O\do\P\do\Q\do\R\do\S\do\T\do\U\do\V\do\W\do\X\do\Y\do\Z%
 \do\*\do\-\do\~\do\'\do\"\do\-%
 \do0\do1\do2\do3\do4\do5\do6\do7\do8\do9\do=\do/\do.\do:%
}
%
\def\UrlSpecials{%
  \do\ {\Url@space}%
  \do\%{\Url@percent}%
  \do\^^M{\Url@space}%
  \Url@force@Tilde
}

\Urlmuskip=0mu plus 1mu
```

@mohuangrui 其实已经包含在 https://github.com/CTeX-org/gbt7714-bibtex-style/blob/1b3ee5c529516c788a9d51538ab5f0a52f47abd4/gbt7714.sty#L116 里了。

**Comment by mohuangrui** [comment]
@muzimuzhi @zepinglee 谢谢两位的帮忙！
