### ISSUE TITLE
请教一个问题，想要参考文献中作者名字的显示格式是'Jin HH'而不是'Jin H H'

### ISSUE THREAD

**Issue by yllu** [mohuangrui/ucasthesis#180]
您好，真的非常感谢你们在这个模板上投入的精力，以及辛苦付出！

请教一个问题，作者中的第二个人Jin, Hoe Huh, 我们研究所的格式要求是生成Jin HH（两个H紧挨着）, 而不是Jin H H（两个H中间留有空间），请问该如何操作？
‘gbt7714-plain.bst‘中该修改哪个地方呢？

非常感谢！

ref.bib文件内容如下：
@article{Gehring2006DEMETER,
  title={DEMETER DNA Glycosylase Establishes MEDEA Polycomb Gene Self-Imprinting by Allele-Specific Demethylation},
  author={Gehring, Mary and **Jin, Hoe Huh** and Hsieh, Tzung Fu and Penterman, Jon and Choi, Yeonhee and Harada, John J. and Goldberg, Robert B. and Fischer, Robert L.},
  journal={Cell},
  volume={124},
  number={3},
  pages={495-506},
  year={2006},
}

**Comment by zepinglee** [comment]
https://github.com/mohuangrui/ucasthesis/blob/3b895a2cc87e14411756688662e531f1f05c8a2b/Biblio/gbt7714-plain.bst#L485

这一行改成
```
{ t #1 "{vv~}{ll}{~f}" format.name$
```

为啥你们每个所要求的格式还不一样啊？

**Comment by yllu** [comment]
非常感谢！

各个所的要求，有些细节上不一样，也不知道是不是国科大强制要求的。难道要每个所各自弄一个Latex模板才行？
我们所只给了个word的模板，请见附件。
关键是，这个模板给出的要求不全面，很多细节在这个模板上都没有统一要求。
例如，缩写词要不要写中文名称，要不要写成表格形式；


[4.学位论文撰写规范指导意见-植物所模版.docx](https://github.com/mohuangrui/ucasthesis/files/3363151/4.-.docx)
