### ISSUE TITLE
关于ubuntu18.04封面字体的问题

### ISSUE THREAD

**Issue by song-heng** [mohuangrui/ucasthesis#181]
学长，很感谢您的贡献，我用的是ubuntu18.04系统，TeX Live 2019以及TexStudio，利用您的latex模板生成的封面字体是黑体而不是宋体，其他字体貌似都是正常的，请问学长能给我提供个解决思路吗？
![image](https://user-images.githubusercontent.com/32189649/60750998-4163de00-9fe2-11e9-9a13-a77f23afc48c.png)
![image](https://user-images.githubusercontent.com/32189649/60751005-53458100-9fe2-11e9-9093-b84fb01bce66.png)

**Comment by mohuangrui** [comment]
你好，国科大封面既有黑体也有宋体。你所截图的编译结果是正确的。即“硕士学位论文”以及“标题”应为黑体，其他为宋体。具体请仔细参考国科大规范。
