### ISSUE TITLE
建议把这个模板放在overleaf里面

### ISSUE THREAD

**Issue by ck2019ML** [mohuangrui/ucasthesis#182]
建议把这个模板放在overleaf里面，这样使用起来更方便

**Comment by mohuangrui** [comment]
你好，谢谢建议，不过目前无法考虑这类个人使用方式的问题。若你可以，请自行操作。

**Comment by mohuangrui** [comment]
@ck2019ML 你好，Overleaf 已发布： [Overleaf](https://github.com/mohuangrui/ucasthesis/wiki/字体配置#linuxoverleaf-系统的字体配置)
