### ISSUE TITLE
如何修改章节标题为英文

### ISSUE THREAD

**Issue by vectorliu** [mohuangrui/ucasthesis#183]
现有的章节标题都是第*章，如何修改为Chapter *，论文为全英文的，除了摘要。

**Comment by mohuangrui** [comment]
Please follow the following simple steps: 

1. Open Thesis.tex, and find the line: 

```%- [plain]% thesis writing of international students ```

2. The above line says that you just need to add the option `plain` into the `\documentclass`:  
```
\documentclass[plain]{Style/ucasthesis}% 
```
3. Then you will be good to go.

**Comment by vectorliu** [comment]
> Please follow the following simple steps:
> 
> 1. Open Thesis.tex, and find the line:
> 
> `%- [plain]% thesis writing of international students `
> 
> 1. The above line says that you just need to add the option `plain` into the `\documentclass`:
> 
> ```
> \documentclass[plain]{Style/ucasthesis}% 
> ```
> 
> 1. Then you will be good to go.

问题解决，多谢。

**Comment by mohuangrui** [comment]
好的，那将关闭此issue了。

**Comment by mohuangrui** [comment]
注记：已修改英文模式下的 plain 选项为 scheme=plain 以消除对 Algorithm 样式的修改。
