### ISSUE TITLE
请问如何修改目录中的字体和字号？

### ISSUE THREAD

**Issue by water-can-carry-a-boat** [mohuangrui/ucasthesis#185]
您好，我想修改目录中的字体和字号，请问应该在哪里改呢

**Comment by muzimuzhi** [comment]
模板里预设的字体字号应该已经符合学校的相应要求，请问为何需要修改？

**Comment by muzimuzhi** [comment]
目前，模板中目录项的字体字号设置是
 - `\part` 和 `\chapter`：`\zihao{4}\sffamily`
 - 所有其他（包括 `\section`, `\subsection` 等）：`\zihao{-4}\sffamily`

相关源码是
`\part`
https://github.com/mohuangrui/ucasthesis/blob/ba430959717dee840d1e07045309d28dd8c414b6/Style/ucasthesis.cls#L672-L690
`\chapter`
https://github.com/mohuangrui/ucasthesis/blob/ba430959717dee840d1e07045309d28dd8c414b6/Style/ucasthesis.cls#L691-L709
其他
https://github.com/mohuangrui/ucasthesis/blob/ba430959717dee840d1e07045309d28dd8c414b6/Style/ucasthesis.cls#L655-L671

**Comment by water-can-carry-a-boat** [comment]
> 模板里预设的字体字号应该已经符合学校的相应要求，请问为何需要修改？

因为我想用模板写其他文章，十分感谢您的解答。
