### ISSUE TITLE
你好，模板里面封面下半部分的字体是黑体而不是宋体，跟要求不一样

### ISSUE THREAD

**Issue by chchzhao** [mohuangrui/ucasthesis#186]
老师给的模板里面，封面中题目下面的“作者姓名”等等都是宋体加粗，而模板编译出来是黑体加粗
我看了附带的“模板使用说明”，里面封面的设置是正确的，这是为什么？难道是我电脑编译环境的问题吗？我是windows系统+texlive2018+texstudio最新版
我把模板上传到overleaf，但是编译失败。求大佬解答一下~~

**Comment by mohuangrui** [comment]
1. 若要封面下半部分字体为宋体加粗，需要使用 xelatex 而不是 pdflatex。
2. 关于 overleaf，若没有具体的出错信息，很难解答。

**Comment by chchzhao** [comment]
xelatex无法编译，是我的设置有问题吗？
![图片](https://user-images.githubusercontent.com/54313826/63345595-ae121c80-c385-11e9-90b6-a7487014888d.png)

![图片](https://user-images.githubusercontent.com/54313826/63345568-9aff4c80-c385-11e9-98e6-f41381173bae.png)

**Comment by mohuangrui** [comment]
错误提示你的 texlive 缺乏 XITSMath 字体，你的texlive是安装的完整版吗？若是，可以更新下 fontspec 和 xits 宏包试试。或者用 Miktex 替代 texlive 也行

**Comment by chchzhao** [comment]
texlive2018无法更新宏包，重新下载安装了texlive2019之后就没问题了

**Comment by mohuangrui** [comment]
好的，祝写作顺利
