### ISSUE TITLE
不能生成pdf文件

### ISSUE THREAD

**Issue by Fancy0609** [mohuangrui/ucasthesis#187]
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/3528013/Thesis.log)

**Comment by mohuangrui** [comment]
建议仔细读读 https://github.com/mohuangrui/ucasthesis/wiki/%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97

1. 比如 “确保 LaTeX 软件的安装路径以及 LaTeX 模板的路径中不存在特殊字符，勿在路径中使用中文字符和空格”

2. 根据你的 log 文件，你的 miktex 宏包库很多都已经是古董了，比如
```
Document Class: ctexbook 2011/03/11 v1.02c ctexbook document class
```
更新下吧
