### ISSUE TITLE
图片尺寸设置过大就会占据整个页面，但页面上下仍然有空白

### ISSUE THREAD

**Issue by chchzhao** [mohuangrui/ucasthesis#188]
如题，如果把图片尺寸设置的超过0.7\textwidth，那么图片就会占据整个页面，就算图片上下还有空白也不会有文字，这个问题怎么解决？
学长有时间帮忙看一下，感谢！

**Comment by lihui077** [comment]
一般用\begin{figure}[!htbp]。我用的0.85没有出现您说的问题。也有可能是你图片本身的边缘空白比较大。



li07hui@163.com
 
发件人： chchzhao
发送时间： 2019-09-07 10:38
收件人： mohuangrui/ucasthesis
抄送： Subscribed
主题： [mohuangrui/ucasthesis] 图片尺寸设置过大就会占据整个页面，但页面上下仍然有空白 (#188)
如题，如果把图片尺寸设置的超过0.7\textwidth，那么图片就会占据整个页面，就算图片上下还有空白也不会有文字，这个问题怎么解决？
学长有时间帮忙看一下，感谢！

**Comment by chchzhao** [comment]
有时候调一调又好了，有点奇怪，后续如果遇到问题或者经验再来分享

**Comment by muzimuzhi** [comment]
1. 过大的浮动体会成为 float page，参考 https://latexref.xyz/Floats.html#Floats 中的相关内容。
2. `\begin{figure}[!...]` 里的感叹号会忽略对浮动体排版空间的限制，可以避免出现 float page

**Comment by chchzhao** [comment]
现在也解释不出来原因，多调试一下，比如移动图片的位置大小就能避免留白的情况吧

**Comment by mohuangrui** [comment]
@chchzhao 图文混排是一个比较复杂的优化问题，对于 LaTeX 也是如此，特别是当文本较少而图较多时。

就我个人经验，当在某一文档区域图较为集中而文本却较少时，较大的图往往会占据整个页面。由于文本较少，即使图所占页面留有空隙，文本也不会排入，因为从文档整体而言，LaTeX 的抉择仍可能是较优解。

可考虑的解决方法有两种：或是将图缩小一些；或是增加文本/调动图的位置以降低图的集中度。
