### ISSUE TITLE
图片大小不一致

### ISSUE THREAD

**Issue by lihui077** [mohuangrui/ucasthesis#189]
使用单个图的时候，图片在文档里面显示的比较大，用PS把两张单独（大小一样）和一起以后，重新引用，结果在文档里显示的效果比单张图的高度低很多。

**Comment by mohuangrui** [comment]
你好，关于 LaTeX 而非 ucasthesis 的问题，建议在相关论坛，如 tex exchange 或是 ctex forum （https://github.com/CTeX-org/forum）提问。

至于你的当前疑问，你用 ps 合并是横排合并吗？若是横排合并，得到的图的宽度就是原图的两倍以上，那么对合并的图你有使用两倍的 \texwidth 值吗？

**Comment by muzimuzhi** [comment]
@mohuangrui 
可以使用 Transfer issue 功能，把当前 issue 转移到 https://github.com/CTeX-org/forum

@lihui077 
建议提供带 ps 前后图片的完整例子

**Comment by mohuangrui** [comment]
@muzimuzhi 根据 Github “To transfer an open issue to another repository, you must have write permissions on the repository the issue is in and the repository you're transferring the issue to. ”


即使我 fork ctex forum，transfer 过去后会出现在 main branch 上吗？

**Comment by muzimuzhi** [comment]
- 原来需要在两个 repo 里都有写的权限。那现在 transfer 不了。
你有 ucasthesis 的权限，我有 forum 的权限。但是谁也不同时拥有两个项目的权限。
 - transfer 过去后，这个 issue 会在 ucasthesis 里消失

**Comment by lihui077** [comment]
多谢，已经解决了，单张图给的比例超过0.5了，导致两张图的高度显得比较低。
