### ISSUE TITLE
建议\institute{}和\advisors{}增加换行功能

### ISSUE THREAD

**Issue by Pantrick** [mohuangrui/ucasthesis#190]
由于中科院某些所的改名，现在有些所系的名字特别长，一行已经写不下了。
我现在的解决方案是自行在`ucasthesis.cls`中添加了`\advisorss`和`\institutes`命令，并改变了首页的部分结构，如果需要更多行数，可以继续添加诸如`\advisorsss`，但是破坏了模板的某些自洽性。
```tex
\def\ucas@value@ch@advisorss{}
\newcommand{\advisorss}[1]{\def\ucas@value@ch@advisorss{#1}}
\def\ucas@value@ch@institutes{}
\newcommand{\institutes}[1]{\def\ucas@value@ch@institutes{#1}}
```
<img width="416" alt="Snipaste_2019-09-30_11-42-08" src="https://user-images.githubusercontent.com/13287753/65848172-7381a380-e377-11e9-864b-46000db4930a.png">

希望作者可以想办法将`\institute{}`和`\advisors{}`增加换行功能，以兼容更长的所系名字。

（这是某些所作妖，与我们学生何关 ( : P））

**Comment by mohuangrui** [comment]
这个是官方要求的吗？感觉可能不太符合国科大的标准吧，根据国科大撰写规范：
“7. 培养单位
填写就读研究所或学院全称,如中国科学院 XX 研究所、中国科学院大学 XX 学院。”

虽然有很直接的实现方法，但因为表格环境限制较多，想要改的简洁明了，却也不太容易。所以，我再观望一阵吧

**Comment by Pantrick** [comment]
这是近几年新的要求，确实很麻烦，差点我就换word写了。
我贴一下我的完整解决方案，供其他同学参考。
在`ucasthesis.cls`的194行左右添加
```latex
\def\ucas@value@ch@advisorss{}
\newcommand{\advisorss}[1]{\def\ucas@value@ch@advisorss{#1}}
\def\ucas@value@ch@institutes{}
\newcommand{\institutes}[1]{\def\ucas@value@ch@institutes{#1}}
```
在`ucasthesis.cls`的293行左右修改
```latex
        \begin{tabular}{lc}
            \ucas@label@ch@author & \ulenhance[1.2pt]{\ulextend{\ucas@value@ch@author}}\\
            \ucas@label@ch@advisor & \ulenhance[1.2pt]{\ulextend{\ucas@value@ch@advisor}}\\
            & \ulenhance[1.2pt]{\ulextend{\ucas@value@ch@advisors}}\\
            & \ulenhance[1.2pt]{\ulextend{\ucas@value@ch@advisorss}}\\ %这行是新添加的
            \ucas@label@ch@degree & \ulenhance[1.2pt]{\ulextend{\ucas@value@ch@degreetype\ucas@value@ch@degree}}\\
            \ucas@label@ch@major & \ulenhance[1.2pt]{\ulextend{\ucas@value@ch@major}}\\
            \ucas@label@ch@institute & \ulenhance[1.2pt]{\ulextend{\ucas@value@ch@institute}}\\
            & \ulenhance[1.2pt]{\ulextend{\ucas@value@ch@institutes}}\\ %这行是新添加的
        \end{tabular}
```
最后在`Frontinfo.tex`中添加两行
```latex
\advisorss{\hspace{+0.0em}分子细胞科学卓越创新中心}
\institutes{\hspace{+0.0em}分子细胞科学卓越创新中心}
```
就可以让导师信息和培养单位分别多出一行，缺点是必须多出这两行，与原来的模板不兼容了。
最好就是希望`ucasthesis.cls`的`tabular`环境中可以有一些判别条件，可以根据`Frontinfo.tex`的信息自适应的改变格式。

**Comment by mohuangrui** [comment]
是的，需要自适应才行，我等有时间时改改看

**Comment by muzimuzhi** [comment]
我在提交 https://github.com/muzimuzhi/ucasthesis/commit/253b649f330588942e03938f8e8237a33989e30b 里做了一个实现，主要改动是
 - 允许 `\advisors` 和 `\institute` 接受多行的参数，新用法为 `\advisors{a\\b\\c}`
 - 新定义宏 `\ucas@titlepage@formatter`，生成 `\format{a} \\ & \format{b} \\ & \format{c}` 形式的输出

测试例子：
输入
```latex
\advisors{老师1\\老师2}
\institute{中国科学院力学研究所 \\ abc}
```
输出
![image](https://user-images.githubusercontent.com/6376638/66529976-34eaa680-eb38-11e9-9eda-727202cf130d.png)

------
PS：有了这个实现，感觉可以把 `\advisor` 和 `\advisors` 合并为一个。

**Comment by Pantrick** [comment]
用xelatex测试了一下，可以。

**Comment by mohuangrui** [comment]
@muzimuzhi 我在 Windows Miktex 

(This is XeTeX, Version 3.14159265-2.6-0.999991 (MiKTeX 2.9.7050 64-bit)
entering extended mode LaTeX2e <2018-12-01>) 

和 Ubuntu texlive 

(This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Debian) (preloaded format=xelatex) LaTeX2e <2017-04-15>)

上测试，出现错误：
```
The comma list \l_tmpb_clist contains the items (without outer braces):
>  {\ulenhance [1.2pt]{\ulextend {老师1}}}
>  {\ulenhance [1.2pt]{\ulextend {老师2}}}.
<recently read> }
                 
l.8 \MAKETITLE
              % 生成英文封面
```

可以解决吗？

**Comment by muzimuzhi** [comment]
这不是错误，是输出的调试信息。
把 `\clist_show:N\l_tmpb_clist` 这一行注释即可，参考提交 https://github.com/muzimuzhi/ucasthesis/commit/677a59acd4181c89e6a961453b56e5400ea2dbe5

**Comment by mohuangrui** [comment]
@Pantrick @muzimuzhi 模板已更新完毕，合并了 \advisor 和 \advisors。

同时细微调整了下 @muzimuzhi  的命令参数: https://github.com/mohuangrui/ucasthesis/blob/265914d05558b54a013f4ddb56b00b6c90dbd8b2/Style/ucasthesis.cls#L71

@muzimuzhi 再次感谢你的帮助～

**Comment by e71828** [comment]
@muzimuzhi 功能很强 我有个问题  `\ulextend{##1}` 的默认参数可以再次传入么？

**Comment by muzimuzhi** [comment]
> @muzimuzhi 功能很强 我有个问题 `\ulextend{##1}` 的默认参数可以再次传入么？

看起来是个单独的新问题，发新 issue？

**Comment by e71828** [comment]
@muzimuzhi  增加一个变量，套一个长度变量。其他人没有问题我也就不要求了。

**Comment by mohuangrui** [comment]
> @muzimuzhi 增加一个变量，套一个长度变量。其他人没有问题我也就不要求了。

现在的一些人是怎么了，请人帮忙回答/解决问题像是大爷在提要求？在开源社区，大家都是凭着热情自愿帮忙，每个人的时间都很珍贵。若不尊重他人的时间和付出，用大爷的口吻提不得其要的问题，请移步他处。
