### ISSUE TITLE
我想设计一个按照本学校的论文要求的latex模板

### ISSUE THREAD

**Issue by CaiNiaoLab** [mohuangrui/ucasthesis#191]
目前在学习使用你们的模板，可是有一个问题，在win下点击 artratex.abt后，提示我需要选择style文件没有，latex ：报出了一个Error，于是我根据理解找到artratex.sty，将artratex文件名输入，编译成功，但是在这个中间有很多的，错误，例如：Latex Error：File ‘ucas_logo' not found。我使用的是2019版本的，并且我测试过，一旦我默认选择artratex.sty后，我在重新clone后已经不提示需要需要选择style文件，所以我觉得是你们需要找一台没有使用过此项目的电脑测试，应该才能复现我的问题，这段时间我会努力找到这个原因，但是介于对latex和你们项目不熟悉，时间应该会挺久的，希望你们可以注意到我的反馈。谢谢！

**Comment by mohuangrui** [comment]
你好，谢谢你的反馈。建议你别着急，多看多学习，慢慢积累，以后你会发现很多问题并不是当初所理解的那样。
