### ISSUE TITLE
章节标题中笔画数较多的字显示不清晰

### ISSUE THREAD

**Issue by Fancy0609** [mohuangrui/ucasthesis#195]
![QQ截图20191011210416](https://user-images.githubusercontent.com/54384435/66653466-ba6e7380-ec6a-11e9-8647-a0e1fec16fd7.jpg)

**Comment by mohuangrui** [comment]
这个黑体加粗是按照撰写要求规定使用的，至于不清晰，那确实没有办法。。。

**Comment by Fancy0609** [comment]
好的，谢谢，

**Comment by mohuangrui** [comment]
发现使用 fontset=adobe，具体使用及安装见 https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE ，可以使放大的字体显示的好些，特别是 零 字。但不妨大的话，没有区别。

没办法，这个只能这样了。

**Comment by muzimuzhi** [comment]
是开启伪粗导致的。目前使用的是 `xecjk` 默认的伪粗粗细程度，为 4。可以试试较小的数值。

目前实现
https://github.com/mohuangrui/ucasthesis/blob/265914d05558b54a013f4ddb56b00b6c90dbd8b2/Style/artratex.sty#L396-L414

测试较小粗细程度
```latex
\documentclass{article}
\usepackage[hscale=0.9]{geometry}
\usepackage{xeCJK}
\usepackage{pgffor}
\setCJKsansfont{SimHei}

\begin{document}
\fontsize{72}{72}\selectfont
\bfseries\sffamily 

\foreach \i in {true, 3, 2.5, 2, 1, false} {
  \addCJKfontfeatures{AutoFakeBold=\i}
  \i: 氦稳零\par
}
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/66668078-fb748100-ec86-11e9-93ab-786ff4f5db6d.png)

对比 Word 里的效果
![image](https://user-images.githubusercontent.com/6376638/66668134-15ae5f00-ec87-11e9-97f2-96892d7382f5.png)

看起来 `AutoFakeBold=2.5` 比较接近 Word 里的伪粗效果。如果是全局设定，可以用 `xecjk` 的选项 `AutoFakeBold=2.5` 或 `EmboldenFactor=2.5`。

具体数值可在进一步比较后确定，这条评论只是为了指出，（比默认的 4）较小的粗细程度能更好地模拟 Word 里的伪粗效果，同时避免本 issue 里提到的问题。

**Comment by mohuangrui** [comment]
@muzimuzhi 厉害，没想到你对这么多宏包的用户文档都了解的如此细致，很是佩服!

**Comment by mohuangrui** [comment]
补充记录一下：今天发现 ubuntu 默认的 evince PDF 阅读器似乎对 AutoFakeBold 的 Windows/Adobe 字体有固定的粗度渲染，导致从视觉上无法判断调整 AutoFakeBold 数值的有效性，这曾经导致我以为 AutoFakeBold 的数值调整是无效的 Bug，因此再没考虑过这个途径。

但今天同时在 Linux 和 Windows 测试你的例子时发现原来问题是出在了 PDF 阅读器上，在此记录一下，以防以后再跳坑。
