### ISSUE TITLE
强烈建议，在 git commit message 里写具体信息

### ISSUE THREAD

**Issue by muzimuzhi** [mohuangrui/ucasthesis#196]
如我在 https://github.com/mohuangrui/ucasthesis/issues/154#issuecomment-485508234 的末尾提到的，
> git commit message 里应当提供关于本次提交的描述性信息（[参考指南](https://zhuanlan.zhihu.com/p/46916705)），而非千篇一律的「New Release」。这样有助于项目的维护。

强烈建议，不要继续用千篇一律的「New Release」作为 commit message 了。写任何和提交有关的内容就好。

**Comment by mohuangrui** [comment]
好的，谢谢 :)
