### ISSUE TITLE
请问如何设置整段缩进

### ISSUE THREAD

**Issue by liuzhaoming5954** [mohuangrui/ucasthesis#197]
请问如何设置整段缩进
从网上找了一些方法，都不成功，不知道怎么才能设置整段缩进
非常感谢您的帮助

**Comment by mohuangrui** [comment]
你好，与 latex 相关的问题请移步:

https://github.com/CTeX-org/forum

这样不仅你可以获得更有效的回答，而且也可以让你的问题帮助到更多的人。

谢谢！

**Comment by liuzhaoming5954** [comment]
收到，非常感谢

**Comment by mohuangrui** [comment]
好的，那我先关闭此 issue 了。
