### ISSUE TITLE
总结展望部分页眉显示不对

### ISSUE THREAD

**Issue by huiwenzhang** [mohuangrui/ucasthesis#198]
Hi,
有个小问题，正常文章最后一部分是总结和展望，不编号。为了实现这个效果使用命令：
\chapter*{总结和展望}，目的是不编号
\addcontentsline{toc}{chapter}{总结与展望}，目的是包含索引到目录
问题是这样做了之后，页眉会出现错误，还是会沿用上一章的页眉设置，如果解决？

**Comment by mohuangrui** [comment]
第一次听说总结展望不编号

至于你要的效果， 'Thesis.tex' 和 'Frontmatter.tex' 就有例子，即：

加入目录和书签：
```
\intotoc\chapter*{总结和展望}
```

不加入目录和但加入书签：
```
\intobmk\chapter*{总结和展望}
```

**Comment by huiwenzhang** [comment]
看以前师兄毕业论文都没有编号。你提供的方法基本实现了期望的效果，就是标签内容仍然是编号的。感谢及时回复！

**Comment by mohuangrui** [comment]
不明白你说的标签内容有编号是什么意思

**Comment by huiwenzhang** [comment]
是书签（即页眉内容）。正常页眉奇数页是本章标题，偶数页是论文题目。上面的方法得到的标题没有编号，但是页眉显示仍然有编号

**Comment by mohuangrui** [comment]
你好，已修复和更新，你可以：

1. 下载最新版然后用 `Style/artratex.sty` 替换你的当前的 `Style/artratex.sty`。
2. 使用方法不变：

加入目录和书签：
```
\intotoc\chapter*{总结和展望}
```

不加入目录和但加入书签：
```
\intobmk\chapter*{总结和展望}
```
感谢发现这个 bug !

**Comment by tengshangzhi** [comment]
你好，正文中的各章节页眉，我编译完显示的是：“chapter * + 章节名”，怎么改成：“第*章 + 章节名” 的样式。谢谢

**Comment by mohuangrui** [comment]
@tengshangzhi 见 https://github.com/mohuangrui/ucasthesis/issues/320
