### ISSUE TITLE
请问若要使用cleveref宏包，应该在哪里添加？

### ISSUE THREAD

**Issue by gaochenyi** [mohuangrui/ucasthesis#199]
cleveref需要最后加载

**Comment by mohuangrui** [comment]
自定义添加的建议放在 `artracom.sty` 内，首先其受版本更新的影响最小，然后其是最后加载的。

**Comment by gaochenyi** [comment]
> 自定义添加的建议放在 `artracom.sty` 内，首先其受版本更新的影响最小，然后其是最后加载的。

但是在`artratex.sty`中有如下代码。这似乎将`hyperref`推迟到最后一个加载了。是不是需要在如下代码之后中加载才能保证在`hyperref`之后加载？

```tex
\AtEndPreamble{%
    \RequirePackage{hyperref}% load at last
% ...
```

**Comment by mohuangrui** [comment]
鉴于package的层层堆叠，你永远不知道 hyperref 在何时就已经被加载了。

不管怎样，你可以在 `artracom.sty`内使用：
```
\AtEndPreamble{%
    \RequirePackage{cleveref}% load at last
}
```
这样就会加在最后。

**Comment by gaochenyi** [comment]
明白了，原来`\ AtEndPreamble`可以使用多个。这个方案好，不用改`artratex.sty`了。谢谢~

**Comment by mohuangrui** [comment]
@gaochenyi 谢谢建议，不过
1. 绝大多数时候，甚至是你的这个例子，直接加在 `artracom.sty`就可以，不会有那么多问题的。
2. 严格来讲你的问题不属于 ucasthesis 的范畴而是关于 LaTeX 的问题，而关于 LaTeX 的知识和技巧可以说是无穷尽的，很难说到底哪个应该放进去。
