### ISSUE TITLE
bib文件中的所有参考文献一下子都生成在pdf里了

### ISSUE THREAD

**Issue by jindongwang** [mohuangrui/ucasthesis#20]
bib文件中的参考文献一下子都生成在pdf里了，而一般写文章的时候是在正文里cite了哪个，哪个才会显示出来。请问如何设置？

**Comment by mohuangrui** [comment]
请在你的Tex源文件中删除如下引入所有文献的命令：

\nocite{*}% show all the bibliography entries

**Comment by nihaomiao** [comment]
你好，请问在现在发布的版本里，\nocite{*}% show all the bibliography entries这句话在哪？

**Comment by nihaomiao** [comment]
你好，非常感谢大佬的工作，请问在新发布的版本里，\nocite{*}% show all the bibliography entries这句话在哪？ @mohuangrui
