### ISSUE TITLE
Frontinfo.tex中的英文学位`\DEGREE{Master}`被注释掉编译时会出现报错。

### ISSUE THREAD

**Issue by Sandbem** [mohuangrui/ucasthesis#200]

**Comment by mohuangrui** [comment]
是的，报错信息就是告诉你需检查这一行，不要注释掉或拼写错误：
```
! Class ucasthesis Error: Invalid value of '\DEGREE'.

```

**Comment by Sandbem** [comment]
> 是的，报错信息就是告诉你需检查这一行，不要注释掉或拼写错误：
> 
> ```
> ! Class ucasthesis Error: Invalid value of '\DEGREE'.
> ```

您的这个模板排版什么的都比较好，我就想用来记录平时的材料整理，所以文档只需要从目录开始编译，不需要封面。但是我在注释掉`\input{Tex/Frontinfo}`这一句之后，发现存在上述报错，检查之后，只有`\DEGREE{Master}`这一句是必须存在的，其他都可以注释掉。所以就必须在导言区加上这个0.0可能是我有些强迫症，就提出了这个问题。

**Comment by mohuangrui** [comment]
这样的话，那你打开 Style/ucasthesis.cls，在 273 行附近注释掉如下一行就可以了：
```
        \ClassError{ucasthesis}{Invalid value of '\string\DEGREE'}{Please check the spelling}%
```

**Comment by Sandbem** [comment]
> 这样的话，那你打开 Style/ucasthesis.cls，在 273 行附近注释掉如下一行就可以了：
> 
> ```
>         \ClassError{ucasthesis}{Invalid value of '\string\DEGREE'}{Please check the spelling}%
> ```

好的，非常感谢！
