### ISSUE TITLE
关于图表标题格式

### ISSUE THREAD

**Issue by tuxify** [mohuangrui/ucasthesis#201]
<img width="472" alt="图表" src="https://user-images.githubusercontent.com/11568229/68729718-af11bd80-0605-11ea-8e30-dcf202e3a894.png">
按照如上格式规定，似乎存在以下问题待改进：

1. 图表序和图表名之间应空一个汉字符位，建议在调用 _caption_ 宏包时设置
`labelsep=quad`
或通过命令
`\DeclareCaptionLabelSeparator{ucas}{\hspace{\ccwd}} `
将间隔设置为一个汉字符位。

2. “表序和表注标题加粗，表注左缩进两个汉字符，续行悬挂缩进左对齐”：此处似乎是仅**表序**和**表注的标题**加粗，且仅表注左缩进两字符，续行悬挂缩进左对齐。按照这个理解，表格格式应该是下面的形式（图序及图注格式类似）
<img width="481" alt="表格" src="https://user-images.githubusercontent.com/11568229/68732142-534b3280-060d-11ea-9dc4-c28ed011bc87.png">

上述问题2有待讨论，因为规范中给出的例子图表标题是加粗的，但例子中图表序与图表名的间距也不是一个汉字符，前后不太一致。

**Comment by mohuangrui** [comment]
你好，规范与范例不一致，所以仍将按照范例来，而不是去过度解读不清晰的规范文字。

**Comment by tuxify** [comment]
可是范例中图表标题段前段后行间距均与规范文字不同，且图标题和表标题也不一致，相对而言，规范文字描述更统一。

此外，按范例和规范文字，图表标题应居中，悬挂缩进似乎应该是针对图注和表注的。

**Comment by mohuangrui** [comment]
当前样式曾经过学位办的老师审核，因此不会修改，如果你有个人需求，请自行修改即可

**Comment by tuxify** [comment]
嗯，可能确实各个单位要求不一样，目前的版本无法通过我所在的研究所的格式审核的。

**Comment by mohuangrui** [comment]
若是这样，你针对你所需要的进行修正，但对修改模板本身需十分谨慎。

**Comment by csxmli2016** [comment]
> <img alt="图表" width="472" src="https://user-images.githubusercontent.com/11568229/68729718-af11bd80-0605-11ea-8e30-dcf202e3a894.png">
> 
> 按照如上格式规定，似乎存在以下问题待改进：
> 1. 图表序和图表名之间应空一个汉字符位，建议在调用 _caption_ 宏包时设置
>    `labelsep=quad`
>    或通过命令
>    `\DeclareCaptionLabelSeparator{ucas}{\hspace{\ccwd}} `
>    将间隔设置为一个汉字符位。
> 2. “表序和表注标题加粗，表注左缩进两个汉字符，续行悬挂缩进左对齐”：此处似乎是仅**表序**和**表注的标题**加粗，且仅表注左缩进两字符，续行悬挂缩进左对齐。按照这个理解，表格格式应该是下面的形式（图序及图注格式类似）
> 
> <img alt="表格" width="481" src="https://user-images.githubusercontent.com/11568229/68732142-534b3280-060d-11ea-9dc4-c28ed011bc87.png">
> 
> 上述问题2有待讨论，因为规范中给出的例子图表标题是加粗的，但例子中图表序与图表名的间距也不是一个汉字符，前后不太一致。

你好，冒昧打扰下，这个表注是怎么加的，同时图注知道怎么加吗，非常感谢。
