### ISSUE TITLE
LaTeX Error: Command `\lvert' already defined. [...thopen}  {symbols}{106}{largesymbols}{12}]

### ISSUE THREAD

**Issue by WhiteDLee** [mohuangrui/ucasthesis#202]
LaTeX Error: Command `\lvert' already defined. [...thopen}  {symbols}{106}{largesymbols}{12}]

How to fix this problem

**Comment by mohuangrui** [comment]
no idea unless you know what you are doing and then can explain it!

**Comment by WhiteDLee** [comment]
Thanks for your reply. I have solved my trouble, by chance, through updating the "dvips" package.

Initially, for the first time when I compiled "Thesis.tex", one error occurred, that is, "[no file]:288: LaTeX Error: File `mathalfa.sty' not found. [\else]";
After I added this package, "mathalfa.sty", using MiKTeX tool, aforementioned errors came.

Finally, afterI uninstalled "mathalfa.sty" and updated the "dvips" package, the compilation worked.

Thank you again.
