### ISSUE TITLE
This erorr came again when I recompile 'thesis.tex' in another computer

### ISSUE THREAD

**Issue by WhiteDLee** [mohuangrui/ucasthesis#204]
Running 'thesis.tex' using TeXworks.

Some errors occurred

newtxmath.sty
783
LaTeX Error: Command `\lvert' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.783 ...thopen}  {symbols}{106}{largesymbols}{12}

newtxmath.sty
784
LaTeX Error: Command `\rvert' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.784 ...thclose} {symbols}{106}{largesymbols}{12}

newtxmath.sty
785
LaTeX Error: Command `\lVert' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.785 ...thopen}  {symbols}{107}{largesymbols}{13}

newtxmath.sty
786
LaTeX Error: Command `\rVert' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.786 ...thclose} {symbols}{107}{largesymbols}{13}

**Comment by mohuangrui** [comment]
1. Check https://github.com/mohuangrui/ucasthesis/wiki/%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97
    1. Do not modify uncasthesis before your compilation.
    2. Use xelatex rather than pdflatex
    3. Read guide carefully and provide your complete log file.

2. Reinstall your LaTeX compiler

3. Update your LaTeX packages.

**Comment by WhiteDLee** [comment]
Thank you. The problem has been solved by the aid of your advice, use xelatex rather than pdflatex.

**Comment by mohuangrui** [comment]
I have found the root of your problem. It's likely a bug in the latest `newtxmath` package, which defines `\lVert` command that conflicts with `amsmath` package.

If you insist on using pdflatex, the current solution of this is to revert the update of newtxmath rather than update...or you can remove the newtxmath package... 
 
Anyway,  the best solution is to use xelatex!
