### ISSUE TITLE
如何临时覆盖enumerate环境中的缩进设置wide=\parindent

### ISSUE THREAD

**Issue by happyTonakai** [mohuangrui/ucasthesis#205]
在最后列出成果列表的时候，希望按照类似参考文献的缩进格式列出发表的论文
```
\begin{enumerate}
    \item paper 1
    \item paper 2
    ...
\end{enumerate}
```

![TIM截图20191126163043](https://user-images.githubusercontent.com/21305646/69612516-c96a8300-106a-11ea-9117-75fc797c544f.png)

但是模板中的编号与后面item的内容进行了统一的缩进

![TIM截图20191126163829](https://user-images.githubusercontent.com/21305646/69612792-64fbf380-106b-11ea-8b41-40bc501762fc.png)

可以通过将`artratex.sty`中的这两行代码注释掉获得enumerate的默认缩进效果
```
\setlist[enumerate]{wide=\parindent}% only indent the first line
\setlist[itemize]{wide=\parindent}% only indent the first line
```

但是只缩进第一行应该是国科大的规定，

在注释掉这两行的情况下使用
```
\begin{enumerate}[wide=\parindent]
    \item ...
\end{enumerate}
```
可以实现符合规定的第一行缩进效果，但是这样的话未免过于麻烦

所以能否在backmatter中临时覆盖一下这个命令呢？

**Comment by happyTonakai** [comment]
解决了，直接使用list就可以了
```
\newcounter{mycounter}
\begin{list}{\arabic{mycounter}.}{\usecounter{mycounter}}
	\item Item one
	\item Item two
	\item Item three
\end{list}
```
Ref: [Making Your Own Lists in LaTeX and LyX](http://troubleshooters.com/linux/lyx/ownlists.htm)

**Comment by mohuangrui** [comment]
你也可用局部组环境来实现默认行为： 
```
{
\setlist[enumerate]{}% restore default behavior
\begin{enumerate}[nosep]
    \item paper 1
    \item paper 2
\end{enumerate}
}
```
