### ISSUE TITLE
没有副导师，删除副导师空白行

### ISSUE THREAD

**Issue by Sommet19** [mohuangrui/ucasthesis#206]
没有副导师，生成封面指导教师为两行，需要删除第二行空白行，这个要怎么处理。
尝试删除line 166-167
%\newcommand{\advisors}[1]{\def\ucas@value@ch@advisors{#1}}
%\def\ucas@value@ch@degree{}
并不能解决。

**Comment by mohuangrui** [comment]
**没有副导师，那一行就需空着。那一行是属于国科大论文格式规定的部分。**

至于删除方法，如果是最新版，只需在 Frontinfo.tex 中 https://github.com/mohuangrui/ucasthesis/blob/23ac7754d7e9f6ddb672afadbc605008ff22e803/Tex/Frontinfo.tex#L11 

去掉换行符。

如果不是最新版，需要在 ucasthesis.cls 中去掉：
```
            & \ulenhance[1.2pt]{\ulextend{\ucas@value@ch@advisors}}\\
```

**Comment by yangimp** [comment]
实测方法2有效，谢谢。
