### ISSUE TITLE
关于空白页

### ISSUE THREAD

**Issue by FunkyGod** [mohuangrui/ucasthesis#207]
为什么每章结束，会出现空白页啊？怎么去掉呢

**Comment by Sommet19** [comment]
因为规定每章开始必须在右侧页面，你上一章结束的时候也在右侧页面就会出现空白页。

**Comment by mohuangrui** [comment]
见：https://github.com/mohuangrui/ucasthesis/wiki/常见问题#为何会生成一些空白页

如果想要去掉，在 thesis.tex 中改 twoside 为 oneside
