### ISSUE TITLE
编译时英文封面出现的Overfull \hbox问题

### ISSUE THREAD

**Issue by qidaimu** [mohuangrui/ucasthesis#209]
[bathymetry.log](https://github.com/mohuangrui/ucasthesis/files/3892489/bathymetry.log)
![微信截图_20191126231228](https://user-images.githubusercontent.com/25176085/69646149-46651f00-10a2-11ea-8227-9436edb9779b.png)

附近代码：
%-
%-> 生成封面
%-
\maketitle% 生成中文封面
\MAKETITLE% 生成英文封面
%-
%-> 作者声明
%-
\makedeclaration% 生成声明页

**Comment by mohuangrui** [comment]
除非文本出现明显的溢出，否则这些warning都是不用理会的。如果你想把LaTeX编译的warning都移除，我能想到的最有效的建议应是你用LaTeX写0字文档。
