### ISSUE TITLE
图（表）题如何能同时显示中、英文？

### ISSUE THREAD

**Issue by weichanglong** [mohuangrui/ucasthesis#21]
晃锐，您好！
请教如何实现下面的这种中、英文图（表）题？目前模板中仅为单标题。谢谢！
Hi, Huangrui,
How to achieve the following Chinese and English figure/table title? The current template  only has a single title. Thanks!
![quality](https://user-images.githubusercontent.com/32944481/32977531-24751266-cc6a-11e7-8ebd-b6c6690b5d2f.jpeg)

![sites](https://user-images.githubusercontent.com/32944481/32977532-24aa9436-cc6a-11e7-9c88-606aa1951eab.jpeg)

**Comment by mohuangrui** [comment]
魏你好， LaTeX命令的自由度是很大的，你可以大胆的在命令中尝试你想要的格式。为实现你所需的双标题，例子如下：

\begin{figure}[!htbp]
  \centering
  \includegraphics[width=0.45\textwidth]{ITC_Q_Criteria}
  **\caption{Q判据等值面图\\Fig.~\ref{fig:ITC_Q_Criteria} Isocontour of Q criteria}**
  \label{fig:ITC_Q_Criteria}
\end{figure}

**Comment by weichanglong** [comment]
谢谢晃锐老师，已成功搞定！我思维定势了，以为交叉引用只在文字部分使用，网上也没有找到相关参考，给您添麻烦了！感谢！

魏

**Comment by mohuangrui** [comment]
哪有添麻烦，大家一起学习进步而已。很高兴你的当前问题得到了解决，以后再有问题，可以一起讨论研究。祝好！

**Comment by lijiansong** [comment]
@mohuangrui 
正文Latex写成如下：
```
begin{figure}[!htbp]
\centering
\includegraphics[width=0.45\textwidth]{ITC_Q_Criteria}
\caption{Q判据等值面图 \\ Fig.~\ref{fig:ITC_Q_Criteria} Isocontour of Q criteria}
\label{fig:ITC_Q_Criteria}
\end{figure}
```
但是扉页生成的图形列表里中英文都有，请问怎么让它只显示中文？

**Comment by mohuangrui** [comment]
@lijiansong，用 `[]`

```Tex
\caption[进入目录的部分]{标题部分}
```

不过这个 issue 的问题 ucasthesis 已经有了更好的解决， 见 

https://github.com/mohuangrui/ucasthesis/wiki/表注图注

**Comment by mohuangrui** [comment]
@lijiansong 仔细看下最新的模版的 pdf 文档

**Comment by lijiansong** [comment]
好的，多谢
