### ISSUE TITLE
关于多图编号位置及格式的问题

### ISSUE THREAD

**Issue by Sommet19** [mohuangrui/ucasthesis#210]
现在默认多图编号在图下侧，习惯于放置于图片左上角，这个能更改吗。
另外编号的格式在哪里修改，现在是（a）想改为 a 这样。

**Comment by mohuangrui** [comment]
你好，与 LaTeX 相关的问题请移步:

https://github.com/CTeX-org/forum

这样不仅你可以获得更有效的回答，而且也可以让你的问题帮助到更多的人。

谢谢！
