### ISSUE TITLE
XITS-Regular 找不到

### ISSUE THREAD

**Issue by ikey4u** [mohuangrui/ucasthesis#211]
在 MacOS 下使用的 TexLive  2018.

使用当前最新的  [commit 版本](https://github.com/mohuangrui/ucasthesis/commit/89e99d046f7cdb5b8f6e7df5901cdd6b23d9a78a), 下载后不作任何改动, 使用自带的 shell 脚本编译会提示如下错误

```
(/usr/local/texlive/2018/texmf-dist/tex/latex/amsfonts/amsfonts.sty))kpathsea:make_tex: Invalid filename `[XITS-Regular', contains '['
```

而字体 XITS-Regular 百分之一百在系统中安装了, 通过 fc-list 能获取到该字体.

参考文献中的俄语字体无法正确显示.

**Comment by mohuangrui** [comment]
在 Mactex 2018 和 2019 版中都测试过，没有出现你说的问题，应该是你的编译环境安装的问题。我能给出的建议是：

重新安装 Mactex，记得安装 Full 版本。

**Comment by mohuangrui** [comment]
你或者先整体更新一下 package 库试试

**Comment by ikey4u** [comment]
> 在 Mactex 2018 和 2019 版中都测试过，没有出现你说的问题，应该是你的编译环境安装的问题。我能给出的建议是：
> 
> 重新安装 Mactex，记得安装 Full 版本。

Mactex 2019 太大了, 而且 Mactex 2018 卸载太麻烦了.

今天又研究了一下, 发现了问题. xits 字体虽然在系统中安装了但是在 xelatex 中检测不到.

查了一下 xelatex 字体的加载方式, 成功安装 xits 让 xelatex 识别即可解决问题, 下面是解决方法,
以方便他人.

```
dxits=$(kpsewhich -var-value TEXMFHOME)/fonts/opentype/xits
mkdir -p $dxits
curl -LO https://github.com/alif-type/xits/releases/download/v1.301/XITS-1.301.zip
unzip XITS-1.301.zip
cp XITS-1.301/*.otf $dxits
rm -rf XITS-1.301
texhash
```

**Comment by mohuangrui** [comment]
好的，根据你的解决方法，应该就是你的 LaTeX 编译环境安装有缺失。正常情形下，xits本就会安装在tex目录下，而非系统里。

**Comment by muzimuzhi** [comment]
@ikey4u 
> 而字体 XITS-Regular 百分之一百在系统中安装了, 通过 fc-list 能获取到该字体.

> 今天又研究了一下, 发现了问题. xits 字体虽然在系统中安装了但是在 xelatex 中检测不到.

 - 在 macOS 下，xetex 通过系统 api 查找和调用系统字体，而不是通过 fontconfig。所以 fontconfig 提供的 fc-list 程序能找到的字体，xetex 不一定能调用
 - 在 macOS 下，xetex 调用系统字体，只能通过字体名（例如 `XITS Math`），不能通过字体文件名（例如 `XITS-Regular.otf`）。参考[这则回答](https://tex.stackexchange.com/a/133139)，这篇[知乎文章](https://zhuanlan.zhihu.com/p/59774395)从另一个角度提供了类似的信息。
 - 因为当前模板是通过字体名调用的，而你的发行版中不包含 XITS Math，所以会有「字体安装在系统了，但是指定字体文件名时 xetex 无法调用」的问题。
 - 用户端的解决方案，简单的是通过包管理器安装提供 xits 的字体包，见 https://ctan.org/pkg/xits 。你的解决方案，相当于手动安装了这个字体包。建立符号链接，或把模板中所有通过字体文件名调用 XITS 字体的地方都改成通过字体名，也可行的办法
 - 模板维护者的角度，也许可以增加提醒，强调「正常运行本模板需要安装 xits 字体包」

**Comment by ikey4u** [comment]
@muzimuzhi 你说的是使用 tlmgr 安装 xits 字体吗? 我第一次尝试的就是用 tlmgr 安装的 xits, 安装之之后确实在 latex 的字体目录下面发现了 xits 文件夹及其对应的字体, 然而 xelatex 并没有识别到, 最后手动安装的方式生效.

**Comment by mohuangrui** [comment]
@muzimuzhi 
```
模板维护者的角度，也许可以增加提醒，强调「正常运行本模板需要安装 xits 字体包」
```
从维护角度来看，绝大数用户很难处理和理解 「正常运行本模板需要安装 xits 字体包」，所以我强调的是 「安装 Texlive Full」。

事实上， @ikey4u 的情形应该是 fontspec 找到了 XITS-Regular.otf， 因为错误的出现意味着`IfFontExistsTF{XITS-Regular.otf}` 为 `True`，但不知为何 xetex 所调用的 `kpathsea` 找不到。至于 @ikey4u  提到的 tlmgr 和手动安装的背后细节与差异，不知道为何。

@ikey4u 
```
这个模板里面提供了字体检测的方法 IfFontExistsTF{XITS-Regular.otf} 如果 XITS 找不到就会去用另外一种默认字体代替之, 但是这种默认字体貌似不行, 无法编译通过, 所以应该强制安装 XITS 字体.
```
虽不知你进行了怎样的操作后给出了`这种默认字体貌似不行, 无法编译通过`的结论，我只好再次在 Ubuntu 和 macos 上两个版本的texlive进行了测试，结论是如果 ` IfFontExistsTF{XITS-Regular.otf}` 为 False，后备字体是完全可以用的。我给你的建议，仍然是确保你的编译环境的完备性。如果你坚持想要自行配置，那就在出现问题时，请针对问题进行配置，而非轻易下结论是模板错了，测试是很费时的 ：）

**Comment by ikey4u** [comment]
@mohuangrui 很抱歉给你造成了麻烦. 我的环境是完整的, 安装的是 MacTex 2018 Full 版本, 至于轻易下结论, 并没有轻易下结论, 我在解决这个问题上花费了不低于七个小时的全职时间, 提供的模版代码样式基本上都看了一遍了, 加入了调试信息最后才定位到 IfFontExistsITF 那里的. 另外我说的强制安装 xits 字体, 并没有说你的模版出了问题, 我的理解是这个依赖项可能是有必要的. 不过经过你的测试, 在你的测试环境中这个字体依赖项是可选的, 那它就是可选的吧, 感谢您辛苦的付出~

**Comment by muzimuzhi** [comment]
@ikey4u 
> 事实上， ikey4u 的情形应该是 fontspec 找到了 XITS-Regular.otf， 因为错误的出现意味着`IfFontExistsTF{XITS-Regular.otf}` 为 `True`，但不知为何 xetex 所调用的 `kpathsea` 找不到。

不一定。有可能报错就是出现在 `\IfFontExistsTF` 中，参考 https://github.com/CTeX-org/ctex-kit/pull/462#issuecomment-557966670

**Comment by muzimuzhi** [comment]
@ikey4u 
> 我第一次尝试的就是用 tlmgr 安装的 xits, 安装之之后确实在 latex 的字体目录下面发现了 xits 文件夹及其对应的字体, 然而 xelatex 并没有识别到, 最后手动安装的方式生效.

从解决具体问题的角度，你遇到的问题已经解决了。从刨根问题的角度，你说的这个新情况我没有遇到过，在自己电脑上也难以复现，寄希望于之后有「能复现问题的电脑」出现。



> 这个模板里面提供了字体检测的方法 [IfFontExistsTF{XITS-Regular.otf}](https://github.com/mohuangrui/ucasthesis/blob/89e99d046f7cdb5b8f6e7df5901cdd6b23d9a78a/Style/artratex.sty#L391) 如果 XITS 找不到就会去用另外一种默认字体代替之, 但是这种默认字体貌似不行, 无法编译通过, 所以应该强制安装 XITS 字体.

是的，是需要强制安装 XITS 字体的。

**Comment by mohuangrui** [comment]
> @mohuangrui 安装的是 MacTex 2018 Full 版本, 至于轻易下结论, 并没有轻易下结论, 我在解决这个问题上花费了不低于七个小时的全职时间, 提供的模版代码样式基本上都看了一遍了, 加入了调试信息最后才定位到 IfFontExistsITF 那里的. 另外我说的强制安装 xits 字体, 并没有说你的模版出了问题, 我的理解是这个依赖项可能是有必要的. 不过经过你的测试, 在你的测试环境中这个字体依赖项是可选的, 那它就是可选的吧

我也应向你说声抱歉，在这个问题上我也有些过早下结论了。经过更细致的测试：
```
1) XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Debian)
    ctexbook 2018/01/28 v2.4.12 Chinese adapter for class book

2) XeTeX, Version 3.14159265-2.6-0.99991 (TeX Live 2019/MacPorts 2019.50896)
    ctexbook 2019/04/07 v2.4.15 Chinese adapter for class book

3) XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX) 
    Document Class: ctexbook 2019/05/29 v2.4.16 Chinese adapter for class book
```
并将
```
    \IfFontExistsTF{XITS-Regalar.otf}{%
```
改为
```
    \IfFontExistsTF{XITS-Regar.otf}{%
```
以使 `\IfFontExistsTF` 肯定找不到字体。测试发现这个问题确实很纠缠：

在 1） 和 2）环境下，`\IfFontExistsTF` 会给出找不到`XITS-Relar`的提示但并不会报错，并且成功地为 False，使得模板调用 newtxmath 字体作为替代，编译成功。

在 3）环境下，`\IfFontExistsTF` 无找不到`XITS-Relar`的提示也不会报错，并且成功地为 False，使得模板调用 newtxmath 字体作为替代，但编译失败，出现错误：
```
LaTeX Error: Command `\lvert' already defined.
```
经过深入测试后发现是 ctex 2019/05/29 v2.4.16 宏包与 newtxmath 冲突了，想去建 issue 时，发现已经有人问了 ： https://github.com/CTeX-org/ctex-kit/issues/454

结论就是：`\IfFontExistsTF` 工作是正常的，但最新版 ctex 2019/05/29 v2.4.16，准确地说是最新版 ulem 宏包出了问题，详见   https://github.com/CTeX-org/ctex-kit/issues/454 ，这也就导致了可能你说的后备字体编译出错的问题。

**Comment by mohuangrui** [comment]
@muzimuzhi 

> 不一定。有可能报错就是出现在 \IfFontExistsTF 中

请见我上面对 @ikey4u 的回答，测试发现 `\IfFontExistsTF` 是没有问题的，而且即使你曾遇到过问题，但无论 \IfFontExistsTF 背后的实现细节是什么，从程序设计的语义出发，不应存在 \IfFontExistsTF 的使用不合理，而应总是强制安装某一字体。

> 从解决具体问题的角度，你遇到的问题已经解决了。从刨根问题的角度，你说的这个新情况我没有遇到过，在自己电脑上也难以复现，寄希望于之后有「能复现问题的电脑」出现。

其实纠结这么深入也许真没必要的，问题就是没有安装好字体，而这一信息在 log 文件里确实明确给出了。只是没有料到近期又出现了 https://github.com/CTeX-org/ctex-kit/issues/454 的问题。

不管怎样，非常感谢你每次的热心帮助～

**Comment by Triumphal** [comment]
在设置公式字体加粗的时候\mathbb 似乎是受到unicode的影响，字体变的比较奇怪，是否有什么办法使得公式显示原字体库的字体，虽然使用\setmathfont{TeXGyrePagellaMath-Regular}[range={\mathbb,\mathcal}]能够将其变成原来的显示。

**Comment by sikouhjw** [comment]
> 在设置公式字体加粗的时候\mathbb 似乎是受到unicode的影响，字体变的比较奇怪，是否有什么办法使得公式显示原字体库的字体，虽然使用\setmathfont{TeXGyrePagellaMath-Regular}[range={\mathbb,\mathcal}]能够将其变成原来的显示。

你所谓的『原字体库』是指 Latin Modern Math，也就是 latex 最常见的字体吧？

`\mathbb` 代表使用 `XITS Math` 的某种字形，这是属于 `XITS Math` 的一部分，接受它的形状。

当然你也可以选择替换一部分，就如你给的代码一样。

**Comment by sikouhjw** [comment]
> 在设置公式字体加粗的时候\mathbb 似乎是受到unicode的影响，字体变的比较奇怪，是否有什么办法使得公式显示原字体库的字体，虽然使用\setmathfont{TeXGyrePagellaMath-Regular}[range={\mathbb,\mathcal}]能够将其变成原来的显示。

请开一个新 issue 并详细提供信息
