### ISSUE TITLE
关于表注和图注

### ISSUE THREAD

**Issue by csxmli2016** [mohuangrui/ucasthesis#212]
![bicaption](https://user-images.githubusercontent.com/26357039/70443124-8aa8e400-1ad2-11ea-8d2a-922fad15e3bc.png)
请问一下关于在表格和图标题下面加图注和表注该怎么办，非常感谢！

**Comment by muzimuzhi** [comment]
参考入门手册 [`lshort-zh-cn`](https://github.com/CTeX-org/lshort-zh-cn/releases) 的 3.8.1 节。

**Comment by csxmli2016** [comment]
> 参考入门手册 [`lshort-zh-cn`](https://github.com/CTeX-org/lshort-zh-cn/releases) 的 3.8.1 节。

3.8.1讲的是mbox，还是不太明白这个mbox如何把bicaption里的标题后面都插入一个表注或者题注，如下图所示：
![示例1](https://user-images.githubusercontent.com/26357039/70451914-35280380-1ae1-11ea-9bd0-cb9ca4d89b6d.png)
非常期待以及感谢你的回复。

**Comment by muzimuzhi** [comment]
1. 是我写错了，应该是 3.9.1 节
1. 重新看了你的提问，我之前可能有些理解偏差；没有完全明白，你具体是要求中的哪一部分不会做。能否具体说明，「学校要求xxx，现在效果yyy，它们的差异在于zzz」

**Comment by muzimuzhi** [comment]
根据我自己目前的理解，尝试了一个比较手动的方案。如果仍有理解偏差，可以评论提出。

```tex
\documentclass[twoside]{Style/ucasthesis}
\usepackage[authoryear,list]{Style/artratex}
\usepackage{Style/artracom}
\input{Tex/Frontinfo}

\usepackage{lipsum}
\captionsetup[bi]{justification=centerfirst, textfont={md}}

\begin{document}
\frontmatter
\intobmk*{\cleardoublepage}{\listtablename}
\listoftables

\mainmatter
\begin{figure}
  \centering
  content
  \bicaption
    [text a]{\textbf{text a}\par\setlength\hangindent{2\ccwd} \lipsum[1]}
    [text b]{\textbf{text a}\par\setlength\hangindent{2\ccwd} \lipsum[2]}
\end{figure}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/70459266-ca7dc480-1aee-11ea-8d36-97af6ea34bf5.png)

注：根据模板目前的设置
https://github.com/mohuangrui/ucasthesis/blob/f8286050b55e99bac3d7c5f7449831c69043be59/Style/artratex.sty#L474
`\bicaption` 不会生成 `\listoftables` 和 `\listoffigures` 中的项目。如需要生成，可以自己改。

**Comment by mohuangrui** [comment]
@csxmli2016 

请参考 [图注表注](https://github.com/mohuangrui/ucasthesis/wiki/%E8%A1%A8%E6%B3%A8%E5%9B%BE%E6%B3%A8)

**Comment by csxmli2016** [comment]
@muzimuzhi @mohuangrui 问题已解决，非常感谢两位的帮忙，解决燃眉之急，感激之情无以言表。
