### ISSUE TITLE
在正文中引用多图中的子图时，能否改成带括弧的形式？

### ISSUE THREAD

**Issue by forallsunday** [mohuangrui/ucasthesis#213]
比如说子图的\label{fig:sth_a}
图\ref{fig:sth_a}
得到 图1.1a

而想得到 图1.1(a)

提个建议，希望能集成到模板内。

**Comment by mohuangrui** [comment]
可以用：
```Tex
\ref{fig:sth}(\subref{fig:sth_a})
```

**Comment by forallsunday** [comment]
> 可以用：
> 
> ```
> \ref{fig:sth}(\subref{fig:sth_a})
> ```

google了一下，找到了解决方法。
使用subcaption宏包
\usepackage{caption}
\usepackage{subcaption}
\captionsetup[subfigure]{labelformat=simple}
\renewcommand\thesubfigure{(\alph{subfigure})}
% def
\newcommand{\figref}[1]{ 图~\ref{#1}}
\newcommand{\tabref}[1]{ 表~\ref{#1}}

这样在一个figure环境中的caption中自己引用自己的子图，也是(a)的形式。
正文中引用 可以使用 \figref

可以考虑集成一下

closed

**Comment by mohuangrui** [comment]
可以自由选择方式，基于以下原因，不会集成你所陈述的那种：
1. 降低了 subcaption 的兼容性。
2. 降低了 \thesubfigure 的兼容性。
3.  减少了引用形式的多样性。
