### ISSUE TITLE
xelatex 下如何设置公式字体为 Computer Modern

### ISSUE THREAD

**Issue by happyTonakai** [mohuangrui/ucasthesis#215]
```
操作系统：Win 10 64 bit
ucasthesis版本 ：2019-06-15 手动更新至 2019-10-21
texlive版本：2019
```
按照 [字体配置](https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE) 中的设置，将

 ```\documentclass[twoside]{Style/ucasthesis}```

修改为 

```\documentclass[twoside,fontset=adobe]{Style/ucasthesis}```

之后使用 pdflatex 编译报错 

```Critical Package ctex: CTeX fontset 'adobe' is unavailable in current (ctex) mode.```

可是我的系统里面有adobe系列的这几个字体

![adobe](https://user-images.githubusercontent.com/21305646/70615663-ca450c80-1c47-11ea-83fd-94e3e0dfaa07.png)

然后我又重新安装了一次，并且选择了为所有用户安装

![adobe2](https://user-images.githubusercontent.com/21305646/70615758-f6f92400-1c47-11ea-9a4f-9915e8629805.png)

依然报错。

但是使用 xelatex 可以正常编译，且生成 pdf 文字可以正常复制，但是我之前按照 #131 的操作将公式字体改为 Computer Modern 的操作却失效了，又变回了 times new roman。（与`fontset`无关，修改之前使用 xelatex 公式的字体也不是 Computer Modern）

请问有什么办法可以让 pdflatex 正常编译吗？或者使用 xelatex 并且公式字体保持 Computer Modern 吗？

PS：修改 `fontset=adobe` 之前我出现的文字复制错误只有在复制英文时才会发生，中文是没问题的，并且公式环境下、`(sub)section` 标题环境下，以及 Figure、Table 等字样是可以正常复制的。

 [字体配置](https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE) 中说复制错误是 xelatex 的一个 bug，那我使用 pdflatex 出现的错误是否不是同一 bug？

**Comment by happyTonakai** [comment]
貌似 pdflatex 不支持 opentype 字体，Google 了一圈基本都是说使用 xelatex 就行了 [How do I use an OpenType font with my LaTeX document?](https://tex.stackexchange.com/questions/46/how-do-i-use-an-opentype-font-with-my-latex-document)

但是如果就是要用 pdflatex 的话好像也不是不可以 [How to use OTF fonts with pdflatex](https://nek0.eu/posts/2017-07-21-How-to-use-OTF-fonts-with-pdflatex.html)  但是好像很麻烦的样子……

好吧，所以有啥办法使用 xelatex 的情况下依然保持公式使用 Computer Modern 吗

**Comment by happyTonakai** [comment]
已解决  注释掉以下代码就可以了
https://github.com/mohuangrui/ucasthesis/blob/338d98c13d0cbdd0f499ba6b826bc62739b17150/Style/artratex.sty#L354-L389

**Comment by mohuangrui** [comment]
@happyTonakai 
1. 是的，opentype 字体最好就用 xelatex，pdflatex的问题不在于复制乱码，而是字体样式和字重无法满足需求。
2. 关于 cm 还是 tnm 字体，反正是众口难调，为了实现 tnm 需要费尽周折，要 cm 只需将 unicode math 相关的都注释掉就可以。
