### ISSUE TITLE
英文封面信息大小写问题

### ISSUE THREAD

**Issue by wqb-123** [mohuangrui/ucasthesis#216]
如截图，在英文封面中，dissertation submitted 首字母需要大写，但是在源码中找不到相应的修改位置。另外，in 怎么才能去掉呢？请多多指教。

**Comment by wqb-123** [comment]
截图上传失败。补充一下，是第二个 in （后接二级学科）

**Comment by mohuangrui** [comment]
https://github.com/mohuangrui/ucasthesis/blob/f8286050b55e99bac3d7c5f7449831c69043be59/Style/ucasthesis.cfg#L52

**Comment by wqb-123** [comment]
@mohuangrui  非常感谢您的提示和帮助 : )

**Comment by wqb-123** [comment]
还是在英文封面这一页，怎样操作可以把作者“by ... ”与上一段话“A Dissertation Submitted to ”互换位置？先谢谢啦

**Comment by mohuangrui** [comment]
https://github.com/mohuangrui/ucasthesis/blob/f8286050b55e99bac3d7c5f7449831c69043be59/Style/ucasthesis.cls#L422
