### ISSUE TITLE
中文封面更改类别后下划线的问题

### ISSUE THREAD

**Issue by Sommet19** [mohuangrui/ucasthesis#217]
![image](https://user-images.githubusercontent.com/51696729/70675685-d91dd480-1cc4-11ea-99f0-699d4ba371e0.png)
在把培养单位更改为学校/学院名称后，填充部分下划线自动缩进，导致后续文字也不再居中，这个要怎么解决。
非常感谢。

**Comment by Sommet19** [comment]
图片貌似挂了。
就是原来是 培养单位 4个字， 现在要改为学校/学院名称 字符增多，导致缩进问题。

**Comment by mohuangrui** [comment]
为什么要改？你想要怎样缩进？

**Comment by Sommet19** [comment]
> 为什么要改？你想要怎样缩进？

改是因为不是国科大的，由于是中科院共建高校，所以学校模板是按照国科大改的，改动的地方只有封面内容。

比如截图中，更改了学科专业和培养单位，变为一级学科和学校/学院名称。
由于学校/学院名称多出了字符，导致下划线缩进出现了问题，
![image](https://user-images.githubusercontent.com/51696729/70767840-af84ac00-1d9d-11ea-92be-f3b6e33e6150.png)

**Comment by mohuangrui** [comment]
将下面这一行

https://github.com/mohuangrui/ucasthesis/blob/f8286050b55e99bac3d7c5f7449831c69043be59/Style/ucasthesis.cls#L309

替换为
```Tex
        \end{tabular}
        \begin{tabular}{lc}
            \ucas@label@ch@institute & \ulenhance[1.2pt]{\ulextend[319pt]{\ucas@value@ch@institute}}\\
```
即可。

若想调整文本在下划线上位置，见

https://github.com/mohuangrui/ucasthesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BD%95%E5%B0%81%E9%9D%A2%E4%B8%8B%E5%88%92%E7%BA%BF%E4%B8%8A%E7%9A%84%E6%96%87%E6%9C%AC%E4%B8%8D%E5%B1%85%E4%B8%AD%E4%B8%8B%E5%88%92%E7%BA%BF

**Comment by Sommet19** [comment]
问题解决，非常感谢。
