### ISSUE TITLE
在英文封面页， by author ... 和 A dissertation submitted to ... 文字的位置互换问题？

### ISSUE THREAD

**Issue by wqb-123** [mohuangrui/ucasthesis#218]
如题。在英文封面这一页，怎样操作可以把作者“by ... ”与上一段话“A Dissertation Submitted to ”互换位置？

**Comment by mohuangrui** [comment]
https://github.com/mohuangrui/ucasthesis/blob/f8286050b55e99bac3d7c5f7449831c69043be59/Style/ucasthesis.cls#L422

建议多读读相关资料，请勿再开关于此类问题的 issue，谢谢
