### ISSUE TITLE
目录共2页，第1页的页眉如何去掉？

### ISSUE THREAD

**Issue by wqb-123** [mohuangrui/ucasthesis#219]
我的目录共2页，希望去掉第1页的页眉，保留第2页的页眉。

使用 Backmatter.tex 中的语句
\thispagestyle{noheaderstyle}% 如果需要移除当前页的页眉
我成功地去掉了各章首页的页眉，但是去不掉目录第1页的页眉。百度和谷歌上没有有效的解答，下面的尝试也失败了。求一个解决问题的办法，谢谢啦。

Thesis.tex 相关源码：
\intobmk*{\cleardoublepage}{\contentsname}% add link to bookmark
\tableofcontents% content catalog

我的尝试一：
\intobmk*{\cleardoublepage}{\contentsname}% add link to bookmark
\thispagestyle{noheaderstyle}% 如果需要移除当前页的页眉
\tableofcontents% content catalog
运行结果：目录第1页的页眉仍然存在。

我的尝试二：
\intobmk*{\cleardoublepage}{\contentsname}% add link to bookmark
\tableofcontents% content catalog
\thispagestyle{noheaderstyle}% 如果需要移除当前页的页眉
运行结果：目录第1页的页眉仍然存在，但第2页的页眉不见了.

**Comment by mohuangrui** [comment]
关于 LaTeX 的知识性问题，请前往 [CTeX Forum](https://github.com/CTeX-org/forum) 发问
