### ISSUE TITLE
三级标题

### ISSUE THREAD

**Issue by cseryp** [mohuangrui/ucasthesis#22]
添加\subsection{}后，目录中没有显示，请问如何修改？

**Comment by mohuangrui** [comment]
你好，此问题已在HowToUse.pdf的第11页第7条有解答：

将 subsection 显示到目录当中: 在 custom.sty 107 行附近, 将 1 改为 2 就可
以了
\setcounter{tocdepth}{1}% the depth for the Table of Contents.

祝好～
