### ISSUE TITLE
如何把参考文献和引用改为数字模式？

### ISSUE THREAD

**Issue by wqb-123** [mohuangrui/ucasthesis#222]
莫老师，您好。这个问题在 CTeX Forum 上提问题过，问题地址是 https://github.com/CTeX-org/forum/issues/87
根据建议，我在 https://en.wikibooks.org/wiki/LaTeX 上查找了，但是没有发现相关说明。因此，我在这儿向您再请教这个问题。不知道怎么改一下可以使用数字式的参考文献排序和引用？如果您那儿有这样的模板，烦请提供一下源码。

%--------------------------------------
附上在CTeX Forum 提的问题：
【检查】
 已在 issues 中进行搜索（包括已关闭的问题）
【编译环境 】
操作系统  Windows 7/8/10
TeX 发行版 MiKTeX

【描述问题】
1. 描述出现的情况
最新版 https://github.com/mohuangrui/ucasthesis 的参考文献和引用没继承旧版的数字模式。

新版的参考文献：LAMPORT L. Document preparation system [M]. Addison-Wesley Reading, MA, 1986.
新版参考文献的引用只有两种方式：Lamport (1986) 或者 (Lamport, 1986)

旧版的参考文献：[1] Thesis Template of the Universicty of Chinese Academy of Sciences, 2014.
旧版的参考文献引用方式： 如何继承旧版毕业论文模板 [1] 中的参考文献和引用模式？

2. 给出复现步骤
直接运行模板 https://github.com/mohuangrui/ucasthesis 即可复现参考文献和引用的模式。

3. 给出您解决问题所进行的尝试
在 artratex.sty 中，把原有 alpha 都改成了 abbrv，但是我没尝试成功。修改的部分代码如下（用%注释的代码为原有代码）
% \ifartx@alpha% enable alpha citation style
\ifartx@abbrv% enable abbrv citation style
\RequirePackage[square,comma,numbers]{natbib}% alpha citation mode
% \bibliographystyle{alpha}% alpha scheme
\bibliographystyle{abbrv}% alpha scheme
\fi

**Comment by mohuangrui** [comment]
[文献样式](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F)
