### ISSUE TITLE
请问运行的时候，artratex.sty 一直报错，显示找不到包

### ISSUE THREAD

**Issue by NineSH** [mohuangrui/ucasthesis#223]
在运行的时候，显示这个错误，而且Package caption Error: bi-first undefined. \captionsetup[bi-first]{bi-first}
![image](https://user-images.githubusercontent.com/42364410/71951499-33ec1280-3216-11ea-9cb1-b40681e08428.png)
怎么也无法解决，单独运行了.bat,发现掉包的时候的运行路径存在反斜杠问题("C:\Users\AppData\Local\Programs\MiKTeX 2.9\tex/latex/ctex\ctexbook.cls"
("C:\Users\AppData\Local\Programs\MiKTeX 2.9\tex/latex/l3kernel\expl3.sty"
请问这个要如何解决，麻烦您啦

**Comment by mohuangrui** [comment]
https://github.com/mohuangrui/ucasthesis/wiki/%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97

**Comment by NineSH** [comment]
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/4034122/Thesis.log)
其他的步骤都没有问题，但是就是失败了

**Comment by mohuangrui** [comment]
应该是 miktex 的问题，建议重装 或是安装 texlive。那个路径确实很异常。

**Comment by NineSH** [comment]
好哒，麻烦您啦，非常感谢

**Comment by mohuangrui** [comment]
不客气，安装 texlive 会比较保险，miktex容易出问题

**Comment by Architotle** [comment]
作者你好，今天刚安装了Texlive full最新版，编译模板时依然存在这个问题。
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/4039140/Thesis.log)

**Comment by NineSH** [comment]
我安装的texlive 2019版就没有问题了，你要不然不要安装最新版本

**Comment by mohuangrui** [comment]
@Architotle  @NineSH  可能是最新版的 bicaption 行为变了，对潜在的问题进行了修复，请测试最新版。即更新了 **artratex.sty** 文件

**Comment by Architotle** [comment]
测试通过，完美编译。谢谢！

**Comment by NineSH** [comment]
新版本的编译通过了，没有问题

**Comment by mohuangrui** [comment]
@NineSH @Architotle 好的，谢谢反馈！

**Comment by muzimuzhi** [comment]
这是由宏包 `caption` 2020/01/03 v3.4h 加入的改变，参考宏包维护者在 TeX.SX 的说明（https://tex.stackexchange.com/a/283984 ）

> Update (2020-01-03)
> 
> Starting with v3.4h of the `caption` package options cannot be used anymore prior to definition. Therefore `\captionsetup[bi-first]{bi-first}` and `\captionsetup[bi-second]{bi-second}` has to be done _after_ `\DeclareCaptionOption{bi-first}...`, otherwise the document will not compile anymore.

**Comment by hairuo** [comment]
> 这是由宏包 `caption` 2020/01/03 v3.4h 加入的改变，参考宏包维护者在 TeX.SX 的说明（https://tex.stackexchange.com/a/283984 ）
> 
> > Update (2020-01-03)
> > Starting with v3.4h of the `caption` package options cannot be used anymore prior to definition. Therefore `\captionsetup[bi-first]{bi-first}` and `\captionsetup[bi-second]{bi-second}` has to be done _after_ `\DeclareCaptionOption{bi-first}...`, otherwise the document will not compile anymore.

将
\captionsetup[bi-first]{bi-first}
\captionsetup[bi-second]{bi-second, list=off}
放在
\DeclareCaptionOption{bi-first}[]{%
  \def\tablename{表}%
  \def\figurename{图}}
\DeclareCaptionOption{bi-second}[]{%
  \def\tablename{Tab}%
  \def\figurename{Fig}}
之后果然问题解决了，非常感谢!
