### ISSUE TITLE
插入图片后编译时出现TeX capacity exceeded, sorry [input stack size=5000]的错误

### ISSUE THREAD

**Issue by Hugo166** [mohuangrui/ucasthesis#224]
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/4063801/Thesis.log)

![Snipaste_2020-01-15_16-36-09](https://user-images.githubusercontent.com/54338238/72418118-2eae3b00-37b5-11ea-8f98-aa358752fdab.png)
![Snipaste_2020-01-15_16-36-21](https://user-images.githubusercontent.com/54338238/72418121-2fdf6800-37b5-11ea-96e0-739d64cf1eb0.png)

这几行代码在一个单独的latex文件中是可以正常运行的，但一旦我把它放入mainmatter所链接的章节latex文件中，使用xelatex编译时便出现了以上问题，希望能得到解答，谢谢

**Comment by Hugo166** [comment]
![Snipaste_2020-01-15_16-36-09](https://user-images.githubusercontent.com/54338238/72418621-230f4400-37b6-11ea-8f93-cdeb4c5b338d.png)
![Snipaste_2020-01-15_16-36-21](https://user-images.githubusercontent.com/54338238/72418624-230f4400-37b6-11ea-8e6d-273b29fe2496.png)

**Comment by Hugo166** [comment]
已经解决了，不知道为啥只要把图标放在图上方就可以了，233333
\begin{figure}[h]
    \caption{L1}
    \centering
    \includegraphics[width=0.4\textwidth]{Img/L1.png}
  \end{figure}
有大佬知道原因的可以跟我交流一下😂

**Comment by muzimuzhi** [comment]
> 这几行代码在一个单独的latex文件中是可以正常运行的，但一旦我把它放入mainmatter所链接的章节latex文件中，使用xelatex编译时便出现了以上问题

请提供一个包含图片文件和完整可编译 tex 文件的例子

**Comment by mohuangrui** [comment]
建议你先查下bicaption的用法

On Jan 15, 2020, at 4:42 PM, Hugo166 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thesis.log<https://github.com/mohuangrui/ucasthesis/files/4063801/Thesis.log>

[Snipaste_2020-01-15_16-36-09]<https://user-images.githubusercontent.com/54338238/72418118-2eae3b00-37b5-11ea-8f98-aa358752fdab.png>
[Snipaste_2020-01-15_16-36-21]<https://user-images.githubusercontent.com/54338238/72418121-2fdf6800-37b5-11ea-96e0-739d64cf1eb0.png>

这几行代码在一个单独的latex文件中是可以正常运行的，但一旦我把它放入mainmatter所链接的章节latex文件中，使用xelatex编译时便出现了以上问题，希望能得到解答，谢谢
