### ISSUE TITLE
如何修改页眉处横线的格式？

### ISSUE THREAD

**Issue by SerendipitousAurorae** [mohuangrui/ucasthesis#225]
莫老师，您好！我是一名外校的学生，十分感谢您能开发出这个优秀的模板供大家使用。

我在使用时，由于我校规定：

`除封面及内封外，各页均应加页眉：在版芯上边线加粗、细双线（粗线在上，宽度1.5磅），双线上居中打印页眉，字号为5号宋体。`

对于在页眉处横线格式的问题，我应该在何处进行何种设置？期待您的解答，谢谢！

**Comment by mohuangrui** [comment]
你好，页眉的设定位于
https://github.com/mohuangrui/ucasthesis/blob/faad94b7fb60077e0371c7390743ade6516ef8bc/Style/artratex.sty#L611

其设定方法参见：  [fancyhdr](https://mirror.bjtu.edu.cn/ctan/macros/latex/contrib/fancyhdr/fancyhdr.pdf)

**Comment by SerendipitousAurorae** [comment]
老师好，抱歉再次打扰您，我记得之前的时候模板所有的附录都位于参考文献后面，这次的模板似乎修改了一下，把一部分附录提到了参考文献的前面，我应该怎么改回去呢？谢谢您！

**Comment by muzimuzhi** [comment]
@SerendipitousAurorae 
一个 issue 应仅用于讨论一个问题。新问题建议开新 issue，这样也能方便他人搜索和查看。
