### ISSUE TITLE
"XITSMath-Regular" cannot be found

### ISSUE THREAD

**Issue by lixinyu2016** [mohuangrui/ucasthesis#226]
看了之前值得一个issue，是类似的问题，但是不知道最后怎么解决的啊，没有看懂，希望能给一个详细的教程。@mohuangrui

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "XITSMath-Regular" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/4138572/Thesis.log)

**Comment by mohuangrui** [comment]
你好，#211 已经讨论过这个问题，问题是你的 texlive 中 xits 宏包缺失或安装异常，解决方法为：

1. 使用 texlive 宏包管理器安装 xits 宏包 （你的texlive 为 2018版本，可能不再支持单独更新宏包）
2. 卸载当前版本，安装最新版texlive完整版 （推荐）
3. 手动安装 xits 宏包 （见： https://github.com/mohuangrui/ucasthesis/issues/211#issuecomment-559714015）

**Comment by lixinyu2016** [comment]
> 你好，#211 已经讨论过这个问题，问题是你的 texlive 中 xits 宏包缺失或安装异常，解决方法为：
> 
> 1. 使用 texlive 宏包管理器安装 xits 宏包 （你的texlive 为 2018版本，可能不再支持单独更新宏包）
> 2. 卸载当前版本，安装最新版texlive完整版 （推荐）
> 3. 手动安装 xits 宏包 （见： [https://github.com/mohuangrui/ucasthesis/issues/211#issuecomment-559714015）](https://github.com/mohuangrui/ucasthesis/issues/211#issuecomment-559714015%EF%BC%89)

谢谢您！

**Comment by lixinyu2016** [comment]
> 你好，#211 已经讨论过这个问题，问题是你的 texlive 中 xits 宏包缺失或安装异常，解决方法为：
> 
> 1. 使用 texlive 宏包管理器安装 xits 宏包 （你的texlive 为 2018版本，可能不再支持单独更新宏包）
> 2. 卸载当前版本，安装最新版texlive完整版 （推荐）
> 3. 手动安装 xits 宏包 （见： [https://github.com/mohuangrui/ucasthesis/issues/211#issuecomment-559714015）](https://github.com/mohuangrui/ucasthesis/issues/211#issuecomment-559714015%EF%BC%89)

我在texlive manager中查询到了xits的宏包，是不是说明已经安装过了？目前还是没办法编译通过。

**Comment by lixinyu2016** [comment]
> 你好，#211 已经讨论过这个问题，问题是你的 texlive 中 xits 宏包缺失或安装异常，解决方法为：
> 
> 1. 使用 texlive 宏包管理器安装 xits 宏包 （你的texlive 为 2018版本，可能不再支持单独更新宏包）
> 2. 卸载当前版本，安装最新版texlive完整版 （推荐）
> 3. 手动安装 xits 宏包 （见： [https://github.com/mohuangrui/ucasthesis/issues/211#issuecomment-559714015）](https://github.com/mohuangrui/ucasthesis/issues/211#issuecomment-559714015%EF%BC%89)

我是在windows下面运行的，请问老师应该怎么手动安装xits宏包，谢谢您。

**Comment by mohuangrui** [comment]
这个很难具体界定问题本质出在哪里，建议是：

卸载当前版本，安装最新版texlive完整版

**Comment by mohuangrui** [comment]
如果你坚持想要手动安装字体，可以看看这个：

https://tex.stackexchange.com/questions/88423/manual-font-installation

**Comment by lixinyu2016** [comment]
> 如果你坚持想要手动安装字体，可以看看这个：
> 
> https://tex.stackexchange.com/questions/88423/manual-font-installation

按照您的方法问题已解决，谢谢您。

**Comment by Ricemeal** [comment]
> 
> 
> > 如果你坚持想要手动安装字体，可以看看这个：
> > https://tex.stackexchange.com/questions/88423/manual-font-installation
> 
> 按照您的方法问题已解决，谢谢您。

补充，方法可行。tex live2018, 与引用网页内容的第一步有区别，需将字体文件复制到.\texlive\2018\texmf-dist\fonts\opentype\public\xits
