### ISSUE TITLE
如何在公式换行时将编号放在最后一行右侧

### ISSUE THREAD

**Issue by Diananini** [mohuangrui/ucasthesis#227]
您好，我现在想在公式环境中进行换行，使用了\begin{split}环境，但是编号是在公式的中间的，
![image](https://user-images.githubusercontent.com/22095412/73544325-e6a93c80-4473-11ea-9750-6d22938b3991.png)
如果我使用align环境，可以把编号放在最后，但是\adddotsbeforeeqnnum%不起作用，公式编号前面没有...了
![image](https://user-images.githubusercontent.com/22095412/73544931-33414780-4475-11ea-8ea3-fe90dbb32303.png)
请问我该怎样在公式换行时将编号放在最后一行的右侧呢

**Comment by muzimuzhi** [comment]
1. 如果所有公式编号都需要 `... (1.1)` 的形式，直接在正文最开始使用一次 `\adddotsbeforeeqnnum` 即可。
1. 如果只有个别公式编号需要 `... (1.1)` 的形式，可以再定义一个 `\restoreDotBeforeEqnNum`，然后这么用
    ```tex
    \documentclass{article}
    \usepackage{amsmath}
    
    \makeatletter
    \newcommand{\adddotsbeforeeqnnum}{%
      \def\maketag@@@##1{\hbox{\m@th\normalfont\dots\ ##1}}}
    \newcommand{\restoreDotBeforeEqnNum}{%
      \def\maketag@@@##1{\hbox{\m@th\normalfont##1}}}
    \makeatother
    
    \begin{document}
    \adddotsbeforeeqnnum
    \begin{align}
      a \\ b
    \end{align}
    \restoreDotBeforeEqnNum
    
    \begin{align}
      a \\ b
    \end{align}
    \end{document}
    ```
    输出效果
    ![image](https://user-images.githubusercontent.com/6376638/73548546-f167cf80-447b-11ea-9322-91ebef33ded0.png)

**Comment by Diananini** [comment]
非常感谢，按照您的方法成功解决！
