### ISSUE TITLE
竖排合并单元格时出问题

### ISSUE THREAD

**Issue by Sommet19** [mohuangrui/ucasthesis#228]
使用竖排合并单元格命令

\multirow{3}{*}{Index ranges}
&\multicolumn{2}{c}{-16≤ h ≤ 16,}&-8 ≤ h ≤ 8,\\
&\multicolumn{2}{c}{-16 ≤ k ≤ 16,}&5 ≤ k ≤ 8,\\ 
&\multicolumn{2}{c}{-16 ≤ l ≤ 16,}&-7 ≤ l ≤ 8,\\

编译时报错：
! Undefined control sequence.
l.108 \multirow
               {3}{*}{Index ranges}
?

实际输出为：
![image](https://user-images.githubusercontent.com/51696729/73963698-c41f9380-494b-11ea-9da3-91270cb3c2a0.png)

问题是：出现3*，另外不上下居中。

**Comment by mohuangrui** [comment]
错误提示很明确，你需要启用支持 multirow 的宏包
