### ISSUE TITLE
宋体没有加粗、或加粗变黑体了

### ISSUE THREAD

**Issue by xujingchen** [mohuangrui/ucasthesis#23]
问题：
1. 下载解压后直接运行Compile得到的 `Tmp\Thesis.pdf` 中，首页里的标题、姓名…培养单位等文字都没有加粗(只有标题里的LaTeX加粗了)，跟`HowToUse.pdf`不一致。
2. 论文中用 `textbf{}` 加粗字体后，得到的是黑体，而不是加粗的宋体。  
不知是什么原因？

我在Win10和macOS high sierra (10.13.1)下都测试了，结果都是这样（macOS下在终端运行`./Compile.sh xa`, Win10下双击`Compile.bat`）。装的都是最新的`TeXLive-2017`。

**Comment by mohuangrui** [comment]
你好，
1. LaTeX中文的渲染有其特殊性，从而一般是不直接加粗宋体，加粗字体一般后台自动改为调用黑体。你所遇到的其它项目没有加粗不知是指怎样的加粗？ 建议你根据HowToUse.pdf中关于字体的部分下载安装相应的adobe中文字体。
2. 如1中所述，LaTeX中文渲染比较特殊，所以为了美观，一般调用黑体作为粗体。ucasthesis的中文字体选用直接依赖于ctex package完成，后者代表了中文LaTeX的标准。所以，并不建议理会这些细节。若是坚持在意这些，建议阅读xecjk package关于字体调用的设置。
希望上述回答对你有帮助，祝好。
莫

**Comment by xujingchen** [comment]
@mohuangrui 非常感谢你的回复！

我是想得到跟 HowToUse.pdf 首页（论文标题、作者姓名…等）一样的加粗宋体（相比正文里的宋体），是我们单位这么要求的。

有可能是没有安装对应的adobe中文字体吧，我没有去尝试——因为今天已用一种笨办法得到了想要的结果，即单独指定一种系统字体，粗体的宋体，用到首页的文字上。

下面两个截图，上图是 HowToUse.pdf 里的，下图是我在macOS或Win10下得到的结果 (我现在才发现能上传图片…)：

<img width="498" alt="b" src="https://user-images.githubusercontent.com/7146271/33769032-7c2e70c0-dc63-11e7-8fa9-a3ba6d4e4c06.png">

<img width="496" alt="a" src="https://user-images.githubusercontent.com/7146271/33769025-746d767e-dc63-11e7-8f05-aa34ef361a22.png">

**Comment by mohuangrui** [comment]
你的确实有些奇怪，很可能是系统字体的原因。加粗宋体是可以解决问题，但其缺点就是，当你将PDF放大到400%时你会发现其加粗是通过重叠文体实现的，从而有可能轻微地影响打印效果。但总的来说问题不大。

**Comment by xujingchen** [comment]
我用的是 Source Han Serif SC （思源宋体）的加粗宋体，好像不是通过重叠文体实现加粗的。
想请教下，如何知道具体缺了什么字体呢？通过安装相应缺失的字体来解决应该更好。

**Comment by mohuangrui** [comment]
你的Windows和Mac
OS都需要用开源字体吗？按道理Windows上应该不会出现缺乏中文字体的状况。若是如此，可能是ctex对你的系统字体的调用出现偏差。

不管怎样，最有效的解决方式就是请按照HowToUse.pdf第11页第9条的说明下载、安装、并调用Adobe中文字体。

祝好，
莫

**Comment by xujingchen** [comment]
Win上我后来没试（平常不用那个电脑工作）。
Mac上我设置了`fontset=adobe`，HowToUse.pdf第11页第9条提到的字体以前都装了，依然没有解决。
<img width="762" alt="screen shot 2017-12-16 at 08 42 04" src="https://user-images.githubusercontent.com/7146271/34065520-75ce8abe-e23d-11e7-84dc-de0ab7c5da42.png">

**Comment by weichanglong** [comment]
我在macOS High Sierra上编译存在同样的问题（中文封面字体不加粗），之前没有留意。

**Comment by mohuangrui** [comment]
不好意思，最近太忙，没来得及仔细检查问题出在哪儿了。我会在1月下旬时对模板进行修正。

**Comment by weichanglong** [comment]
谢谢，元旦快乐 @mohuangrui

**Comment by halois** [comment]
中英文标题中出现数学符号报错
环境: macos+texlive2016
问题: Frontpages.tex文件中若中英文标题中出现数学符号与中文如''平方和$x^2$", 则编译时出错, 去掉$$及其中内容则可以通过编译. 

好像也和字体有关

**Comment by halois** [comment]
按照了adobe字体仍然有错

信息为:
```
(./Tex/Frontpages.tex

LaTeX Font Warning: Font shape `TU/AdobeSongStd-Light(1)/bx/n' undefined
(Font)              using `TU/AdobeSongStd-Light(1)/m/n' instead on input line
36.


Package microtype Warning: One or more slots in the configuration are unknown.
(microtype)                Make sure that no text commands are used.
(microtype)                See the documentation for details (the note
(microtype)                on `xeCJK' in section 9: `Hints and caveats').

<use  "UCAS.pdf" >

LaTeX Font Warning: Font shape `TU/AdobeHeitiStd-Regular(0)/bx/n' undefined
(Font)              using `TU/AdobeHeitiStd-Regular(0)/m/n' instead on input li
ne 36.

! Undefined control sequence.
\UL@leaders ...L@skip \tw@ \UL@pixel \UL@leadtype
                                                  \LA@hskip \UL@skip \LA@hsk...
l.36 \makeenglishtitle
```

**Comment by mohuangrui** [comment]
@halois @weichanglong @xujingchen 大家新年好，针对国科大的一些规则变动，我已对模板进行了全局更新。关于你们的问题部分：
1） 标题使用数学公式的问题我已在更新后的模板中提供了示例，方法超级简单，就是加括号：{$x^2$}。
2） 我对封面字体加粗进行了修正。已在Linux和Windows上对模板测试完毕，一切正常。但由于Mac不在手头，所以还没测试。请问你们可以帮忙测试下吗？十分感谢。
祝一切顺利，
莫晃锐

**Comment by halois** [comment]
多谢作者@mohuangrui
我在mac上试了下, 现在封面的标题是粗体, 且可以使用数学符号. 然而标题下的部分仍不是粗体

![image](https://user-images.githubusercontent.com/3677698/35156960-7753833a-fd6d-11e7-8cc6-e9350cf43b0b.png)

**Comment by mohuangrui** [comment]
@halois @xujingchen @weichanglong 

你们好，问题终于找到了，是出在ctex的字体调用和2017 MacOS系统的默认字体库不匹配上了。读了ctex的宏文件才整出来，我已把这个问题反馈到了 [ctex Github](https://github.com/CTeX-org/ctex-kit/issues/335)。因为这是一个独立于ucathesis的问题，而且将来ctex应会解决掉，所以没有加入用户文档了。

在这里给出问题的解决办法：

在 artratex.sty （对应旧有的commons.sty） 的 \RequirePackage{fontspec}行下添加如下字体设置命令即可：

    \setCJKmainfont[BoldFont=Heiti SC,ItalicFont=Kaiti SC]{Songti SC}%
    \setCJKsansfont{Heiti SC}%
    \setCJKfamilyfont{zhsong}{Songti SC}%
    \setCJKfamilyfont{zhhei}{Heiti SC}%
    \setCJKfamilyfont{zhkai}{Kaiti SC}%

祝好！

**Comment by mohuangrui** [comment]
@halois @xujingchen @weichanglong

你们好，最后发现这个问题是因为我用错了字体切换命令。在最新的模板中已经进行了修正，并且不再需要额外的手动配置。

**Comment by zhanglinbo** [comment]
测试了最新的版本，你们讨论的标题下的字，Windows 10下为**黑体**，Linux下正常（和HowToUse.pdf显示一样）

**Comment by mohuangrui** [comment]
@zhanglinbo 你好，标题本就应是黑体的，姓名信息那部分是加粗宋体。如果你的不对，请看一下thesis.log，在里面搜索ctex.cls，看其版本是否过老。如果你的在Windows上显示不对，很可能是需要更新MikTeX的宏包库甚至是MikTex版本。

**Comment by zhanglinbo** [comment]
@mohuangrui 感谢回复，本人小白，Win 和Linux下都是最新版Texlive 2017。之前的版本，Linux下正常；win 10下显示为不加粗宋体，加了AutoFakeBold 打开全局的伪粗体功能后可正常显示加粗宋体! 下图为win10 下新版显示字体，貌似是黑体
![default](https://user-images.githubusercontent.com/33575669/36652011-0176d224-1ae7-11e8-8ce4-18867401a112.PNG)

**Comment by mohuangrui** [comment]
觉得那个就是宋体吧？你在编译得到文档后，将页面转到24页，也就是常见问题第7条，那里有各类字体的对比。你看看加粗宋体和黑体的对比。最新版我在一台英文windows8系统上编译都是可以正常显示加粗宋体而不会遭遇被黑体替换的情况，所以需你在确认下，谢谢。

**Comment by xujingchen** [comment]
我已经用不上这个模版了（ 毕业完毕 😄），仅提供一些反馈。

我刚下载了编译了一下（终端下 `./artratex.sh xa`），得到的结果如图（左边是我得到的封面、右边是 模板使用说明.pdf 里的封面）：
<img width="1159" alt="screen shot 2018-02-26 at 13 40 16" src="https://user-images.githubusercontent.com/7146271/36655100-aa47686e-1afb-11e8-8a59-cb5f7323f415.png">

可见差异仍然较多。

环境是： macOS High Sierra, version 10.13.3 (17D102); TeX Version 3.14159265 (TeX Live 2017).

**Comment by zhanglinbo** [comment]
@xujingchen 我在win10 下得到的和你左边图显示一样
@mohuangrui 下图左边黑体，右边宋体加粗，区别还是很明显的

![default](https://user-images.githubusercontent.com/33575669/36655707-4ed7407c-1aff-11e8-9e64-7e85cc91e52f.PNG)

**Comment by mohuangrui** [comment]
谢谢反馈，不同操作系统的宋体也是有区别的，请将将页面转到24页，也就是常见问题第7条，那里有各类字体的对比。请将其截图，以及你的编译的log文件过来给我，谢谢

**Comment by zhanglinbo** [comment]
![default](https://user-images.githubusercontent.com/33575669/36680578-19f34af2-1b51-11e8-88c5-569eee3f8117.PNG)
Thesis.log文件[Thesis.zip](https://github.com/mohuangrui/ucasthesis/files/1759305/Thesis.zip)

**Comment by mohuangrui** [comment]
这么晚还在工作，好努力！你看那个扈字，是不是不一样？觉得是windows所携带的宋体字样就是那个德行？如果你想在windows上要获得Linux那样的显示，觉得那才是标准，方法很简单，就是按第7条的调用自定义中文字体库的方法操作即可，即

**调用 ctex 预定义好的备用字库:在 Thesis.tex 中设置
\documentclass[doublesided,fontset=fandol]{Style/ucasthesis}%
便可方便地调用 fandol 这一字体库。**
MacOS既可以按照下面的调用SC字体，也可以调用fandol字体。

**Comment by zhanglinbo** [comment]
感谢！调用fandol字体正常

**Comment by mohuangrui** [comment]
是的，问题的核心就是Windows的中文字重不完备，比如宋体没有原生态的粗体，所以ctex做了一些后台的替换设定。还有就是Windows上调用的宋体库字体样式可能设计的不是那么好吧。fandol的字重是完备的，只是其不涵盖许多生僻字，不过这对我们无影响。MacOS上ctex为了照顾字库量而选择了ST类字，但ST类字也不带原生态的粗宋体，而MacOS内的SC类字是有完备的字重的。

**Comment by xujingchen** [comment]
确认：加上`fontset=fandol`后字体结果与`模版使用说明.pdf`一致。 @mohuangrui @zhanglinbo

**Comment by mohuangrui** [comment]
@xujingchen 哈哈，谢谢你的热心帮忙，还有幽默。很多时候，问题是由信息不对称所导致，开发者写出来的Manual和用户理解的问题往往总有那么一段距离，所以，大家相互理解有效沟通才行。
