### ISSUE TITLE
模板使用说明.pdf 文件中包含错别字

### ISSUE THREAD

**Issue by xiaokongkong** [mohuangrui/ucasthesis#230]
在 "2.2.5 Tex 文件夹" 下，出现错别字 “学文论文”，我觉得应该是 “学位论文”。
![image](https://user-images.githubusercontent.com/25687151/74121129-3ec50900-4c01-11ea-9b67-1699d65a2ff8.png)

望指教。

**Comment by xiaokongkong** [comment]
![image](https://user-images.githubusercontent.com/25687151/74121227-a7ac8100-4c01-11ea-8146-b2d2262292e9.png)

**Comment by mohuangrui** [comment]
好的，谢谢提醒！
