### ISSUE TITLE
模板使用说明.pdf 中有几处需添加空格

### ISSUE THREAD

**Issue by xiaokongkong** [mohuangrui/ucasthesis#231]
“2.3.4 图片插入” 中，有两处图片的引用。
`其效果如图2.1。`
`自动裁剪如图2.2。`
汉字和数字之间少了空格。

后台代码是：
```
其效果如图\ref{fig:c06h06}
自动裁剪如图\ref{fig:c06h06_trim}
```
应该添加 ~

望指教。

**Comment by mohuangrui** [comment]
好的，谢谢提醒！不过为了避免 repository 尺寸非正常增长，二进制类文件如 使用说明.pdf 将不再进行任何修改 ：）

**Comment by muzimuzhi** [comment]
仅从 git 使用的角度，可以重写所有历史 commit，从整个项目中删除 `使用说明.pdf` 文件，仅在 release 中提供 pdf 文件。
参考 https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

**Comment by mohuangrui** [comment]
@muzimuzhi  上次 commit 时我已经处理过了，把 git 从原本的600多M缩到了当前的4M左右，但为了避免这种操作，以后不再更新二进制文件。

**Comment by mohuangrui** [comment]
@xiaokongkong  更在源文件中修改你指出的几处 typos，谢谢
