### ISSUE TITLE
参考文献序列标号问题

### ISSUE THREAD

**Issue by tlok666** [mohuangrui/ucasthesis#232]
请问，模板的参考文献，如何才能调整成为1，2，3，4这样的序列？
如overlearf的模板中：https://www.overleaf.com/latex/templates/thesis-template-for-the-university-of-chinese-academy-of-sciences/fhbvbjrrgtwx
![image](https://user-images.githubusercontent.com/12291907/74399706-ab026100-4de9-11ea-804c-c1a387d043c0.png)

1、参考文献处（第15页）是直接列出来的，没有1，2，3，4这样的标号。
2、另外，使用\citepns{}进行参考文献引用后，文中的参考文献标号不是按照1，2，3，4顺序排列的，是乱序的。

请问应该如何使用呢？非常感谢！

**Comment by mohuangrui** [comment]
https://github.com/mohuangrui/ucasthesis/wiki/常见问题

https://github.com/mohuangrui/ucasthesis/wiki/文献样式
