### ISSUE TITLE
windows10+miktex 2.97100+texmaker 报错

### ISSUE THREAD

**Issue by jichilen** [mohuangrui/ucasthesis#234]
报错位置   miktex/tex/latex/chemgreek.sty
删除该包重装依旧报错，最新版的ucasproposal同样报这个错，用overleaf可以编译，但是overleaf太卡了，还是希望能够解决这个问题。报错信息如下：

> ! Undefined control sequence.
<argument> Chem\str_uppercase:f
{\tl_head:n {alpha}}\str_lowercase:f {\tl_ta...
l.584 \chemgreek_drop_symbols:
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/4214021/Thesis.log)

**Comment by muzimuzhi** [comment]
命令 `\str_uppercase:f` 是 l3kernel 在 2019-11-26 新加入的，参考最新版 [`texdoc interfac3`](http://mirrors.ctan.org/macros/latex/contrib/l3kernel/interface3.pdf), sec. VII.7

建议更新 l3kernel 包。

**Comment by jichilen** [comment]
谢谢大佬，完美解决问题。orz

**Comment by mohuangrui** [comment]
问题应该是源于上次更新加入的 chemfig 宏包，如果不是化学专业，也可以考虑注释掉 chemfig 和 mhchem 两个宏包：

\RequirePackage{chemfig}% draw 2D chemical structures
