### ISSUE TITLE
试图引用网页时出错

### ISSUE THREAD

**Issue by buxcon** [mohuangrui/ucasthesis#235]
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/4225074/Thesis.log)

我想将一个网页作为参考文献进行引用，我的做法是：

1. 在Thesis.tex中加上了\usepackage{hyperref}
2. 在ref.bib中使用@misc格式加入了该网页
3. 引用

![image](https://user-images.githubusercontent.com/8217175/74834872-3bdfbc00-5357-11ea-8b30-ed7caf28fcbe.png)
![image](https://user-images.githubusercontent.com/8217175/74834853-33878100-5357-11ea-982e-41e0cbcb650f.png)
![image](https://user-images.githubusercontent.com/8217175/74834901-4b5f0500-5357-11ea-90e9-2ea5c98de3c2.png)

然而，在最终生成出的文件中，引用之处显示为问号，且该参考文献没有出现在最后的参考文献列表之中。
![image](https://user-images.githubusercontent.com/8217175/74834179-e22ac200-5355-11ea-83c7-103ef69fd593.png)

随后我又试着将usepackage处改为url并将引用切换为对应格式、删掉添加的usepackage、在去掉引用之处的website，均没有解决问题。

**Comment by mohuangrui** [comment]
建议好好读读使用说明，特别是关于 全编译 xelatex + bibtex + xelatex

**Comment by buxcon** [comment]
是我的问题，谢谢
