### ISSUE TITLE
请问怎么添加参考文献样式

### ISSUE THREAD

**Issue by willstruggle** [mohuangrui/ucasthesis#236]
非常感谢分享这么好用的模板。我想请问下为什么添加参考文献样式会编译失败呢？
我是在Thesis.tex文件的参考文献前面用了一个标签\bibliographystyle。

\bibliographystyle{Biblio/gbt7714-plain}
\bibliography{Biblio/ref}% bibliography

**Comment by happyTonakai** [comment]
`artratex.sty` 中已经有相关定义，如需将 著者-出版年制（authoryear）改为 顺序编码制（numbers），只需将 `Thesis.tex` 中的：
```
\usepackage[authoryear,list]{Style/artratex}
```
改为
```
\usepackage[numbers,list]{Style/artratex}
```
详见 [文献样式](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F)
