### ISSUE TITLE
在linux 下将字体设置为 adobe 时，出现无法找到字体的错误（已安装指定的四个adobe字体）

### ISSUE THREAD

**Issue by Chao-zhi** [mohuangrui/ucasthesis#238]
操作系统：archlinux
编译环境：texlive 2019 全套安装
问题描述：
下载了AdobeSongStd-Light.otf，AdobeHeitiStd-Regular.otf，AdobeKaitiStd-Regular.otf，AdobeFangsongStd-Regular.otf 四个字体，并安装在/usr/share/fonts下，编译时提示没有找到这几个字体。查看问题时发现，模板./Stype/artratex.sty文件中

` \def\artx@fontdir{./Font/}% extra font location`

此处字体文件夹设置为.Font目录，将他改为正确的字体目录后，可以正常编译了。

此处字体设置方法和wiki中的不一样，应当需要更正。

**Comment by mohuangrui** [comment]
建议仔细理解： https://github.com/mohuangrui/ucasthesis/wiki/字体配置 ，特别是Linux下的两种字体配置方法。

至于安装字体后为何找不到字体，那应该是没有正确安装字体为系统字体，建议查阅关于 Linux 下如何正确安装外部字体为系统字体。

**Comment by Chao-zhi** [comment]
> 建议仔细理解： [https://github.com/mohuangrui/ucasthesis/wiki/字体配置](https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE) ，特别是Linux下的两种字体配置方法。
> 
> 至于安装字体后为何找不到字体，那应该是没有正确安装字体为系统字体，建议查阅关于 Linux 下如何正确安装外部字体为系统字体。

我确认我已经正确安装这四个字体，我的WPS或其他文字编辑软件都可以选择这四个字体了，我不论将字体安装在 `/usr/share/fonts` 下还是个人目录 `~/.local/share/fonts` 下都无法被该模板识别。而其他文字编辑软件都可以识别。

**但是只需要将`artratex.sty`文件 第 283 行的字体路径改为正确的路径就可以识别了。**

**Comment by mohuangrui** [comment]
1. 安装系统字体：问题肯定为没有安装好系统字体，这涉及到一系列的命令与设定，如字体配置、文件权限与属性设定、字体cache等，除非承认问题并仔细排查，否则应无进一步讨论的必要。

2. 局部字体方案：再次建议仔细理解： https://github.com/mohuangrui/ucasthesis/wiki/字体配置 。你通过修改 \artx@fondir 链接到放字体文件的位置然后编译成功，认为找到了事情的真相。然而真相是，作为一个模版，不会考虑让用户去修改一个 \artx@fondir命令，而是告诉用户在 ucasthesis 下建立一个 Font 文件夹，然后把字体丢进去就可以。
