### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by alex0516** [mohuangrui/ucasthesis#241]
Hi there,

The codes were compiled in Texlive2013 on Windows7 platform. 
There was an error saying '**600 undefined control sequence 1.600 \ctexset**'.
The whole procedure is as follows:

1. run artratex.bat, but no reactions.
2. open Thesis.tex with Texworks, compile that with xelatex, then error was reported.

So could you address the issue and give some suggestion or improvement? 

Regards,
Alex

**Comment by happyTonakai** [comment]
See [编译指南
](https://github.com/mohuangrui/ucasthesis/wiki/%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97). Update your Texlive to 2017 or later.

**Comment by mohuangrui** [comment]
Two options:
1. update your LaTeX to Texlive2017 or newer.
2. use Overleaf: https://www.overleaf.com/latex/templates/thesis-template-for-the-university-of-chinese-academy-of-sciences/fhbvbjrrgtwx
