### ISSUE TITLE
macOS下中文逗号的编译问题

### ISSUE THREAD

**Issue by Junyangz** [mohuangrui/ucasthesis#242]
首先非常感谢你们提供的这个模版，让我们不用为论文格式烦恼。
我在使用的过程中遇到个小问题反馈一下：
```
OS: macOS Catalina 10.15.3
Editor: VSCode
Tex: macTex
System lang: en
```

Thesis: font默认配置，不管是VSCode里编译还是通过脚本`artratex.sh`编译都会出现如下全角中文逗号的问题。`font=mac` 逗号问题解决了但样式变化了很多（例如首页作者信息加粗无效，下载Adobe字体并配置后，也是同样的样式问题。)
现在默认的配置下样式是没问题，唯一的问题就是逗号这一块。难道是字体库的问题？

---
![](https://img.junyangz.com/p/ucas-thesis-feedback.png)

**Comment by muzimuzhi** [comment]
> 不管是VSCode里编译还是通过脚本artratex.sh编译都会出现如下全角中文逗号的问题

具体是什么问题？

**Comment by Junyangz** [comment]
> > 不管是VSCode里编译还是通过脚本artratex.sh编译都会出现如下全角中文逗号的问题
> 
> 具体是什么问题？

上面的那张图篇可能看的不太明显，我重新弄了个对比图。

---
![WechatIMG25.jpeg](https://i.loli.net/2020/03/05/Ws1CqigIPJ7bXkx.jpg)
上面是正常的逗号（同学在windows下编译的），下面是我编译出来的逗号，可以看出两种逗号不太相同，在文章里显得会有点不太协调。

**Comment by muzimuzhi** [comment]
不同系统下编译，使用的是（系统自带的）不同的中文字体。不同字体里的逗号看起来有差异。

**Comment by mohuangrui** [comment]
不同字体库自然存在差异，如果你觉得mac上的不符合你的审美，你最后到Windows上编译一遍就是。

至于你说的 fontset=mac 和 adobe 时封面无法加粗是很奇怪的，或者说是不应该的。当然，我不知道 Catalina 对 mac 做了怎样的字体库修改，但即使这样，Adobe也不会出问题。建议你把问题确认清楚

**Comment by Junyangz** [comment]
> 不同系统下编译，使用的是（系统自带的）不同的中文字体。不同字体里的逗号看起来有差异。

目前看应该就是字体的原因了，稍后测试下Docker下编译；

> 不同字体库自然存在差异，如果你觉得mac上的不符合你的审美，你最后到Windows上编译一遍就是。
> 
> 至于你说的 fontset=mac 和 adobe 时封面无法加粗是很奇怪的，或者说是不应该的。当然，我不知道 Catalina 对 mac 做了怎样的字体库修改，但即使这样，Adobe也不会出问题。建议你把问题确认清楚

`fontset=mac/adobe`设定下经过仔细对比，格式是没问题。加粗的样式和Windows下的看起来差别有点大，我试试换环境编译，谢谢。

**Comment by mohuangrui** [comment]
@Junangz 没必要把Windows当成标准，即使你最后想要Windows上的效果，最后交稿时放windows编译一下即可。

**Comment by ChangXiaoning** [comment]
> > 不同系统下编译，使用的是（系统自带的）不同的中文字体。不同字体里的逗号看起来有差异。
> 
> 目前看应该就是字体的原因了，稍后测试下Docker下编译；
> 
> > 不同字体库自然存在差异，如果你觉得mac上的不符合你的审美，你最后到Windows上编译一遍就是。
> > 至于你说的 fontset=mac 和 adobe 时封面无法加粗是很奇怪的，或者说是不应该的。当然，我不知道 Catalina 对 mac 做了怎样的字体库修改，但即使这样，Adobe也不会出问题。建议你把问题确认清楚
> 
> `fontset=mac/adobe`设定下经过仔细对比，格式是没问题。加粗的样式和Windows下的看起来差别有点大，我试试换环境编译，谢谢。

@Junyangz 想请问你一下，你是怎么解决的呢，我遇到了和你一模一样的问题。谢谢啦

**Comment by sikouhjw** [comment]
> @Junyangz 想请问你一下，你是怎么解决的呢，我遇到了和你一模一样的问题。谢谢啦

前面的回答说的很清楚：
- 没必要把Windows当成标准
- 即使你最后想要Windows上的效果，最后交稿时放windows编译一下即可

**Comment by Junyangz** [comment]
> > > 不同系统下编译，使用的是（系统自带的）不同的中文字体。不同字体里的逗号看起来有差异。
> > 
> > 
> > 目前看应该就是字体的原因了，稍后测试下Docker下编译；
> > > 不同字体库自然存在差异，如果你觉得mac上的不符合你的审美，你最后到Windows上编译一遍就是。
> > > 至于你说的 fontset=mac 和 adobe 时封面无法加粗是很奇怪的，或者说是不应该的。当然，我不知道 Catalina 对 mac 做了怎样的字体库修改，但即使这样，Adobe也不会出问题。建议你把问题确认清楚
> > 
> > 
> > `fontset=mac/adobe`设定下经过仔细对比，格式是没问题。加粗的样式和Windows下的看起来差别有点大，我试试换环境编译，谢谢。
> 
> @Junyangz 想请问你一下，你是怎么解决的呢，我遇到了和你一模一样的问题。谢谢啦

@ChangXiaoning 换个 Windows 环境编译下就行
