### ISSUE TITLE
参考文献编号问题

### ISSUE THREAD

**Issue by ifeelok92** [mohuangrui/ucasthesis#243]
模板里的参考文献显示出来没有编号，但是我看往届博士论文，参考文献是[1] [2][3]这种格式排下去的，请问我该如何修改模板，使得参考文献能编号显示？多谢~

**Comment by happyTonakai** [comment]
[文献样式](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F)
