### ISSUE TITLE
引用网站

### ISSUE THREAD

**Issue by Sommet19** [mohuangrui/ucasthesis#244]
需要引用一个网站，请问这种如何添加。
非常感谢。

**Comment by happyTonakai** [comment]
建议 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 加一条遇到问题请先百度。

![TIM截图20200306231231](https://user-images.githubusercontent.com/21305646/76095868-00541b80-6000-11ea-8741-4c5a1e7e2818.png)
