### ISSUE TITLE
解决本地部署ShareLaTex编译标题不是Times字体问题

### ISSUE THREAD

**Issue by wangyifantech** [mohuangrui/ucasthesis#246]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Linux (本地ShareLaTex系统)

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2017
  - [ ] MiKTeX 
  - [ ] CTeX #

## 描述问题 / Problem Description

由于实验室经常会多人协同写论文及文档，Overleaf访问速度比较慢，所以我们在实验室服务器上搭建了一个本地的ShareLeTex系统；在最近使用本模板时，发现文章标题中的数字和英文不是Times New Roman字体，而是保持了Sans Font (有点像是黑体)，影响的部分为abstract标题，正文的chapter/section/subsection标题，以及目录/图目录/表目录中的标题。

参考 [issue #159](https://github.com/mohuangrui/ucasthesis/issues/159) 发现应该是服务器中没有安装XITS-Regular.otf字体，导致使用XeLaTex编译时，标题仍然保留了Sans Font字体。

## 解决方案 / Solutions
**方案1**：在`artratex.sty`中`\IfFontExistsTF{XITS-Regular.otf}`找不到该字体后进入false语句 (409行)，则比较粗暴的方式就是在false语句中添加Times New Roman字体设置，即如下所示：
```
\setmainfont[NFSSFamily=entextrm]{Times New Roman}
\setsansfont[NFSSFamily=entextsf]{Times New Roman}
%\RequirePackage{newtxtext}
%\RequirePackage[cmintegrals]{newtxmath}%
\RequirePackage{mathrsfs}
\RequirePackage[cal=cm]{mathalfa}
```
好像前面的2个`\RequirePackage`不注释也行，不过这样其实没有解决字体XITS-Regular.otf缺失的问题；

**方案2**：首先下载[XITS](https://github.com/alif-type/xits)字体，本地的ShareLeTex一般使用docker进行安装，其实就是进入sharelatex的docker安装字体，和普通的Linux字体安装类似，具体可以参考这篇帖子：[ArchLinux 部署ShareLaTex并且配置中文支持](https://blog.csdn.net/hello_percy/article/details/72147414)；

不过这个方法我没有成功，`\IfFontExistsTF{XITS-Regular.otf}`依然是进入false语句，不知道是否需要重启sharelatex的docker，因为其他同学也在用，所以暂时没有重启docker进行实验；

**方案3**：`\IfFontExistsTF{XITS-Regular.otf}`也会检查本地路径，所以将XITS的6个字体直接放到和Thesis.tex平级的目录即可编译通过；如果觉得项目路径不够美观，则可以仿照使用Adobe字体一样，新建一个Font文件夹，将XITS字体放入Font，然后将`\IfFontExistsTF{XITS-Regular.otf}`修改为`\IfFontExistsTF{\artx@fontdir XITS-Regular.otf}`，然后下面的9个\setxxxx语句中都添加一句`Path= \artx@fontdir,`，示例如下：
```
\setmainfont[NFSSFamily=entextrm]{XITS}[
      Path           = \artx@fontdir,
      Extension      = .otf,
      UprightFont    = *-Regular,
      BoldFont       = *-Bold,
      ItalicFont     = *-Italic,
      BoldItalicFont = *-BoldItalic,
      Ligatures=TeX,
    ]
```
这个方法应该没什么问题，因为是直接添加字体到了项目中，缺点是每个用户都要这样配置一遍。方案2应该是一劳永逸的解决办法，但是目前还有其他同学再用，所以没有尝试重启docker或者更新TeX Live (目前是2017，我看Overleaf目前用的是2019)。

本地配置Latex比较麻烦，换个电脑就要重新来一遍，并且没法协同工作，所以目前我写论文和文档都转移到组内的ShareLaTex中了，不知道有多少同学也在用自己部署的ShareLaTex服务，把这个问题发上来，希望能对大家有帮助。

**Comment by mohuangrui** [comment]
谢谢总结，稍做补充如下：

* 方案1：
    * 前提是已经为Linux系统安装了Times New Roman 字体；
    * 难以实现让数学字体也保持为Times类字体
* 方案2:
    * 可能是需要重启的
* 方案3
    * 如果不想每个文档都把字体拷贝一遍，可以把 \artx@fontdir 定义到系统的一个固定目录，然后把字体放到那个固定目录下，这样所有文档都可以到固定目录调用字体。
    * 当然还是全局安装字体到系统 / 更新Texlive到2019 or 2020 更加理想一点。

“本地配置Latex比较麻烦，换个电脑就要重新来一遍，并且没法协同工作，所以目前我写论文和文档都转移到组内的ShareLaTex中了”

或者可以考虑本地用 virtualbox 安装一个Windows虚拟机，先不管服务器上的配置导致样式如何，先把文稿写完，最后如果需要修正特定的样式细节，可以用虚拟机上的Windows编译一遍即可。至于换电脑，直接把虚拟机拷贝走就可以了。

**Comment by wangyifantech** [comment]
@mohuangrui 感谢回复，昨天写作过程中突然发现的这个格式问题，我查看了Overleaf上的编译结果和之前师兄师姐的毕业论文，确定了是本地ShareLeTex的编译问题，然后在强迫症的驱使下就想把这个问题解决；

我对Latex的格式不是很熟，通常都是直接用模板，平时也就是改改细节的格式问题，后续等不忙了会尝试更新服务器上的Texlive到比较新的版本；

主要是平时的写作常常涉及到多人协同，而且不想再配置环境了（因为懒），如果Overleaf能解决国内访问的稳定性还是一个不错的选择；

@mohuangrui 可以根据你那边的规则close issue，我这边没有问题了，感谢。

**Comment by mohuangrui** [comment]
@wangyifantech 更新 texlive 应是目前较优的选项。好的，那关闭了。
