### ISSUE TITLE
更新 cls 和 sty 等文件中的版本信息（日期和版本号）

### ISSUE THREAD

**Issue by muzimuzhi** [mohuangrui/ucasthesis#252]
https://github.com/mohuangrui/ucasthesis/blob/282c773266a8702c1da479db1b23cc691473ec75/Style/ucasthesis.cls#L15

https://github.com/mohuangrui/ucasthesis/blob/282c773266a8702c1da479db1b23cc691473ec75/Style/artracom.sty#L15

https://github.com/mohuangrui/ucasthesis/blob/282c773266a8702c1da479db1b23cc691473ec75/Style/artratex.sty#L15

https://github.com/mohuangrui/ucasthesis/blob/282c773266a8702c1da479db1b23cc691473ec75/Style/ucasthesis.cfg#L14

**Comment by mohuangrui** [comment]
这个意义不大？

**Comment by muzimuzhi** [comment]
有意义。
 - 对普通用户而言，源码和文档中的软件版本号和发布日期是了解「版本信息」的唯一渠道。
 - 对进阶用户至维护者而言，能从用户的 log 中知道模板版本，也能提前梳理错误原因。

而且，维护它们的成本也不大。

**Comment by mohuangrui** [comment]
那以后主要更新时改下
