### ISSUE TITLE
能不能提供一份IEEE引用格式的版本，老师非让用IEEE的参考文献格式且我的论文有大量公式，移植到word的难度太大了。

### ISSUE THREAD

**Issue by MelO-BeE** [mohuangrui/ucasthesis#253]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by MelO-BeE** [comment]
谢谢了！

**Comment by happyTonakai** [comment]
texlive 里自带，善用百度

**Comment by MelO-BeE** [comment]
> texlive 里自带，善用百度

查了好久，也没整太明白，还毁了好几个文档，幸好有备份（T——T）

**Comment by happyTonakai** [comment]
1. 复制 `texlive\2019\texmf-dist\bibtex\bst\IEEEtran\IEEEtran.bst` 到 `ucasthesis\Biblio` 下
2. 将 `ucasthesis\Style\artatex.sty` 中 `\bibliographystyle{Biblio/gbt7714-unsrt}` 或 `\bibliographystyle{Biblio/gbt7714-plain}` 修改为 `\bibliographystyle{Biblio/IEEEtran}`

**Comment by MelO-BeE** [comment]
> 1. 复制 `texlive\2019\texmf-dist\bibtex\bst\IEEEtran\IEEEtran.bst` 到 `ucasthesis\Biblio` 下
> 2. 将 `ucasthesis\Style\artatex.sty` 中 `\bibliographystyle{Biblio/gbt7714-unsrt}` 或 `\bibliographystyle{Biblio/gbt7714-plain}` 修改为 `\bibliographystyle{Biblio/IEEEtran}`

大佬，并不管用。。。

**Comment by happyTonakai** [comment]
我这里是有效的，你有按照 `xelatex -> bibtex -> xelatex -> xelatex` 的顺序编译吗

**Comment by hushidong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    把         \bibliographystyle{Biblio/IEEEtran}改为 \bibliographystyle{IEEEtran}

**Comment by MelO-BeE** [comment]
> 我这里是有效的，你有按照 `xelatex -> bibtex -> xelatex -> xelatex` 的顺序编译吗

Package natbib Error: Bibliography not compatible with author-year citations. ...and\NAT@force@numbers{}\NAT@force@numbers

**Comment by MelO-BeE** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 把         \bibliographystyle{Biblio/IEEEtran}改为 \bibliographystyle{IEEEtran}

大佬，上面的代码插哪里？

**Comment by MelO-BeE** [comment]
难道是因为用的texstudio的锅（T——T）

**Comment by hushidong** [comment]
Thesis.tex 中设置\usepackage[bibtex,numbers,list]{Style/artratex}

artratex.sty中设置

%-
%-> Bibliography processor and package
%-
%- Bibtex processor + natbib package
\ifartx@bibtex%
    % Set punctuation and mode of citation style
    \newcommand{\bibstyle@super}{\bibpunct{[}{]}{,}{s}{,}{\textsuperscript{,}}}%
    \newcommand{\bibstyle@numbers}{\bibpunct{[}{]}{,}{n}{,}{,}}%
    \newcommand{\bibstyle@authoryear}{\bibpunct{(}{)}{;}{a}{,}{,}}%
    \newcommand{\bibstyle@alpha}{\bibpunct{[}{]}{,}{n}{,}{,}}%
    \ifartx@numbers% enable numbered citation style
        \RequirePackage[sort&compress]{natbib}% numbered citation mode
        \ifartx@super% enable superscripted citation style
            \citestyle{super}%
        \else
            \citestyle{numbers}%
        \fi
        \bibliographystyle{IEEEtran}% numbered scheme
    \fi
    \ifartx@authoryear% enable author year citation style
        \RequirePackage{natbib}% author year citation mode
        \citestyle{authoryear}%
        \bibliographystyle{Biblio/gbt7714-plain}% author year scheme
    \fi
    \ifartx@alpha% enable alpha citation style
        \RequirePackage[square,comma,numbers]{natbib}% alpha citation mode
        \bibliographystyle{alpha}% alpha scheme
    \fi
    \providecommand*{\citetns}[2][]{% text embedded \citet in superscripted mode
        \begingroup\citestyle{numbers}\citet[#1]{#2}\endgroup%
    }
    \providecommand*{\citepns}[2][]{% text embedded \citep in superscripted mode
        \begingroup\citestyle{numbers}\citep[#1]{#2}\endgroup%
    }
\fi

**Comment by MelO-BeE** [comment]
> Thesis.tex 中设置\usepackage[bibtex,numbers,list]{Style/artratex}
> 
> artratex.sty中设置
> 
> %-
> %-> Bibliography processor and package
> %-
> %- Bibtex processor + natbib package
> \ifartx@bibtex%
> % Set punctuation and mode of citation style
> \newcommand{\bibstyle@super}{\bibpunct{[}{]}{,}{s}{,}{\textsuperscript{,}}}%
> \newcommand{\bibstyle@numbers}{\bibpunct{[}{]}{,}{n}{,}{,}}%
> \newcommand{\bibstyle@authoryear}{\bibpunct{(}{)}{;}{a}{,}{,}}%
> \newcommand{\bibstyle@alpha}{\bibpunct{[}{]}{,}{n}{,}{,}}%
> \ifartx@numbers% enable numbered citation style
> \RequirePackage[sort&compress]{natbib}% numbered citation mode
> \ifartx@super% enable superscripted citation style
> \citestyle{super}%
> \else
> \citestyle{numbers}%
> \fi
> \bibliographystyle{IEEEtran}% numbered scheme
> \fi
> \ifartx@authoryear% enable author year citation style
> \RequirePackage{natbib}% author year citation mode
> \citestyle{authoryear}%
> \bibliographystyle{Biblio/gbt7714-plain}% author year scheme
> \fi
> \ifartx@alpha% enable alpha citation style
> \RequirePackage[square,comma,numbers]{natbib}% alpha citation mode
> \bibliographystyle{alpha}% alpha scheme
> \fi
> \providecommand*{\citetns}[2][]{% text embedded \citet in superscripted mode
> \begingroup\citestyle{numbers}\citet[#1]{#2}\endgroup%
> }
> \providecommand*{\citepns}[2][]{% text embedded \citep in superscripted mode
> \begingroup\citestyle{numbers}\citep[#1]{#2}\endgroup%
> }
> \fi

大佬稳！！！

**Comment by hushidong** [comment]
ok了？

**Comment by MelO-BeE** [comment]
> ok了？

对的！谢谢大佬！

> 我这里是有效的，你有按照 `xelatex -> bibtex -> xelatex -> xelatex` 的顺序编译吗

大佬，你的方法也可以！谢谢大佬！
