### ISSUE TITLE
模板remark环境没有编号以及证明后面由.改为：

### ISSUE THREAD

**Issue by ifeelok92** [mohuangrui/ucasthesis#255]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
1. \begin{remark} \end{remark}不编号，我尝试在preamble处加\newtheorem{remark}{Remark}等处理也不行
2. 证明后面怎么由.改为：
3. 证明 显示的字体 如何 统一改变？

**Comment by muzimuzhi** [comment]
本条回复只针对「在 latex 里如何实现」，我不了解「你的需求是否符合院校规定」。

前两点
```tex
\documentclass[twoside]{Style/ucasthesis}
\usepackage[authoryear,list]{Style/artratex}
\usepackage{Style/artracom}
\input{Tex/Frontinfo}

% 重定义 remark 环境，从不编号改为编号
\makeatletter
\let\remark\@undefined
\theoremstyle{remark}
\newtheorem{remark}{注}
\makeatother

% 把 proof 环境头的西文点号改为直立的西文冒号
\usepackage{xpatch}
\xpatchcmd\proof{.}{\textup{:}}{}{\fail}

\begin{document}
\frontmatter
\mainmatter

\begin{remark}
  content
\end{remark}

\begin{proof}
  content
\end{proof}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/77802371-a8b44780-70b5-11ea-8293-e3dd02250a73.png)

第三点没看懂，也许可以使用
```tex
\xpatchcmd\proof{\itshape}{<字体命令，影响 proof 环境的所有内容>}{}{\fail}
```

**Comment by mohuangrui** [comment]
对于这类特别细节同时很局部的样式修改，不一定要去修改已有命令，建议自定义相应命令用于实现所需样式即可，省事省时省力
