### ISSUE TITLE
数学公式中省略号居下

### ISSUE THREAD

**Issue by changraku** [mohuangrui/ucasthesis#256]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
怎么把数学公式里面的\ldots居下，而不是居中。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

比如这里的省略号想居下，但是不知道怎么修改。
![image](https://user-images.githubusercontent.com/50002323/77837746-42a3ef00-719f-11ea-84c4-ad05a0447dbd.png)

## 最小工作示例(MWE) / Minimal Working Example 

只有把artratex.sty文件中\setmathfont{XITSMath-Regular}注释掉就可以，但是数学字体完全变了。

**Comment by happyTonakai** [comment]
与字体无关，你是不是把 `\ldots` 打成 `\cdots` 了

![dots](https://user-images.githubusercontent.com/21305646/77838100-243ff280-71a3-11ea-84bb-523841311662.png)

**Comment by changraku** [comment]
> 与字体无关，你是不是把 `\ldots` 打成 `\cdots` 了
> 
> ![dots](https://user-images.githubusercontent.com/21305646/77838100-243ff280-71a3-11ea-84bb-523841311662.png)

不是，可能我加别的包导致的这个问题。我再找找吧，感觉我好二。

**Comment by changraku** [comment]
> 与字体无关，你是不是把 `\ldots` 打成 `\cdots` 了
> 
> ![dots](https://user-images.githubusercontent.com/21305646/77838100-243ff280-71a3-11ea-84bb-523841311662.png)

终于找到了，是我加了xecjkmath的原因。谢谢您了。
\xeCJKsetup{CJKmath=true,PunctStyle=kaiming}%
