### ISSUE TITLE
关于硕博士论文的引用

### ISSUE THREAD

**Issue by huskier** [mohuangrui/ucasthesis#257]
您好，

《中国科学院大学研究生学位论文撰写规范指导意见》中给出了学位论文的引用格式：
林钰婷.台产攀蜥属之细胞遗传研究[D].台湾.台湾师范大学生命科学研究所，2006.

但在ref.bib中好像没有专门的关于学位论文的例子，我也查了wiki和issues，没找到相关的讨论。

主要是论文题目后面的[D]，如果是采用book的式样的话，会是[M].

Thanks.

## 检查 / Check

- [X] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [X] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [X] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by happyTonakai** [comment]
@phdthesis

**Comment by huskier** [comment]
Thanks. @happyTonakai
