### ISSUE TITLE
miktex，运行artratex.bat提示pdfdraftmode not found.

### ISSUE THREAD

**Issue by hbliu80** [mohuangrui/ucasthesis#258]
## 检查 / Check

- [x ] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [x] MiKTeX 2.9.7364
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：运行artratex.bat，出错并提示pdfdraftmode not found。但是，我安装了tex studio，加载thesis.tex编译成功！觉得还是运行bat更方便，因此想消除此错误。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/4400664/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![image](https://user-images.githubusercontent.com/52145821/77873084-7c4a2800-727b-11ea-9bd0-a57a205ab22f.png)

## 最小工作示例(MWE) / Minimal Working Example 

就是下载的原版Thesis，没做任何改动

**Comment by mohuangrui** [comment]
这个可能和你的运行权限有关，bat只是给新手提供测试用的快捷途径，不建议一直用bat，不安全同时慢。
