### ISSUE TITLE
单个长图片跨页问题

### ISSUE THREAD

**Issue by zzddsg** [mohuangrui/ucasthesis#259]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
我将多张图片放在一张图片中，图注比较长，图加图注超过了一页，wiki里面有多图的解决方案，因为图片比例问题，我必须放在一张图里。请问如何将图注跨页？

谢谢！

**Comment by muzimuzhi** [comment]
必须放在一张图里，是指一个图片文件，还是指一个 figure 浮动体环境？

**Comment by zzddsg** [comment]
> 必须放在一张图里，是指一个图片文件，还是指一个 figure 浮动体环境？
你好，效果是像这样的，图片本身不是很大，但是图注比较长，谢谢。 
```
\begin{figure}[!htbp]
	\centering
	\includegraphics[trim = 0mm 0mm 0mm 0mm, clip, width=1\textwidth]{c06h06}
	\captionsetup[bi]{justification=centerfirst}% adjust local caption justification
	\bicaption%
	[中文标题]{中文标题。\mdseries\par\setlength\hangindent{2\ccwd}中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。中文标题非常长。}%
	[English caption ]{English caption. \mdseries\par\setlength\hangindent{2\ccwd}Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.Very long English caption.}%

    \label{fig:c06h06}
	
\end{figure}
```
![捕获](https://user-images.githubusercontent.com/12294679/78207402-245a2e00-74d4-11ea-9900-ad958e4cda3e.PNG)

**Comment by muzimuzhi** [comment]
试试调整写法，把部分图注挪到正文中？

**Comment by zzddsg** [comment]
图注没有办法跨页吗？ 860101959 Email:860101959@qq.com Signature is customized by Netease Mail Master 在2020年04月02日 17:23，muzimuzhi 写道： 试试调整写法，把部分图注挪到正文中？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by muzimuzhi** [comment]
> 图注没有办法跨页吗？

就 `caption` 宏包目前的实现方式，不能。可以尝试手动，参考 https://tex.stackexchange.com/q/487728

**Comment by zzddsg** [comment]
> > 图注没有办法跨页吗？
> 
> 就 `caption` 宏包目前的实现方式，不能。可以尝试手动，参考 https://tex.stackexchange.com/q/487728

好的，谢谢。
