### ISSUE TITLE
Sublime Text + Latextools 参考文献自动填写问题

### ISSUE THREAD

**Issue by CarnoZhao** [mohuangrui/ucasthesis#260]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [x] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

使用Sublime Text 3配合Latextools 插件写论文，可以对`\citep{}`和`\citet{}`完成弹窗式文献自动补全，但是在目前的文件夹结构下不能成功找到另一个文件夹下的`bib`文件，报错“No bib files found”。

根据[https://github.com/sjtug/SJTUThesis/issues/192#issue-229588351](https://github.com/sjtug/SJTUThesis/issues/192#issue-229588351)和[https://github.com/SublimeText/LaTeXTools/issues/228#issue-16573285](https://github.com/SublimeText/LaTeXTools/issues/228#issue-16573285)，可以在每个需要用cite的子tex文件第一行添加：
`% !TEX root = ..\thesis.tex`

目前我个人的测试没有对其他功能产生影响。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by sheldonxxd** [comment]
如果短时间没人理你，建议使用VScode编辑器加上LaTeX插件，还可以使用JabRef管理Bib文件，目前我已经用这套工具组合完成了论文撰写，祝顺利！
![image](https://user-images.githubusercontent.com/42539486/78541642-86929600-7828-11ea-932e-2e5d47378876.png)

**Comment by CarnoZhao** [comment]
> 如果短时间没人理你，建议使用VScode编辑器加上LaTeX插件，还可以使用JabRef管理Bib文件，目前我已经用这套工具组合完成了论文撰写，祝顺利！
> ![image](https://user-images.githubusercontent.com/42539486/78541642-86929600-7828-11ea-932e-2e5d47378876.png)

谢谢你的建议！
但是我试了一下vscode的Latex插件，没有自动补全文献的功能（可能是我没找到……）
sublime可以实现如下：
![test](https://user-images.githubusercontent.com/43026195/78543694-9d86b780-782b-11ea-88ee-850773078bf9.gif)
输入citep后输入大括号会自动弹出窗口，里面包括bib文件中的所有文献，并且支持搜索筛选，就可以不用手动输入每个文献的bib名字了。

如果vscode的插件也有这个功能或者类似的还希望同学能指点一下！

**Comment by sheldonxxd** [comment]
我看了下，vscode中也能自动弹出窗口，不过并不支持在弹出窗口中进行搜索筛选，只能下拉查找，不过它能根据你的key快速定位到附近，所以效率上应该影响不大。
![image](https://user-images.githubusercontent.com/42539486/78549955-cf9d1700-7835-11ea-9d28-4761f8b5593e.png)

**Comment by sheldonxxd** [comment]
插件名称是，LaTeX Workshop
![image](https://user-images.githubusercontent.com/42539486/78550340-7d102a80-7836-11ea-97cd-6444250a79f8.png)

**Comment by CarnoZhao** [comment]
谢谢啦，我再看看吧

**Comment by lipcaty** [comment]
想修改参考文献的格式怎么修改？
模板中的参考文献格式为不带序号不显示marker而是大写作者姓名，这十分不正规。我想用回原始的\bibliographystyle{alpha}该如何修改？

**Comment by devon-ge** [comment]
建议使用jabref + texstudio。前者可以集成所有的bib格式为一个文件，或者管理多个。jabref有一个按钮，点击可以直接在texstudio当前的光标位置插入\citep{}等引用。非纯文字编辑，不太建议使用编辑器，texstudio这类IDE功能很全，尤其是交叉引用
