### ISSUE TITLE
关于希腊字母的字体问题

### ISSUE THREAD

**Issue by Zoujinqi** [mohuangrui/ucasthesis#261]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2019 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
请问一下这种字体属于什么类型？这跟现在模板中的字体不太一样。我想把模板数学公式中的希腊字母字体换成图中的这种，应该怎么操作？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![b777cb6623f967a19396b1b88fcad06](https://user-images.githubusercontent.com/63116322/78549228-9ca65380-7834-11ea-804a-4881bced855a.png)

**Comment by muzimuzhi** [comment]
在导言区
```tex
\documentclass[twoside]{Style/ucasthesis}
\usepackage[authoryear,list]{Style/artratex}
\usepackage{Style/artracom}
```
之后，添加
```tex
\setmathfont{Latin Modern Math}
```

**Comment by Zoujinqi** [comment]
谢谢！问题解决了。（抱歉没注意到这里不能缩放图片==）
