### ISSUE TITLE
大的花括号、方括号显示不出

### ISSUE THREAD

**Issue by ppppbamzy** [mohuangrui/ucasthesis#263]
很抱歉打扰您，我遇到的问题是现在大的方括号和花括号都显示不出来，不管是分cases还是画矩阵，只有试过把sty文件里关于font的部分全注释掉才能出现。在Mac和Ubuntu下都是这样，用的xelatex编译。查看log没有关于那一章的warning或error。

## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ ] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [x] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
<img width="505" alt="截屏2020-04-13下午8 49 43" src="https://user-images.githubusercontent.com/10197323/79121646-5880f900-7dc8-11ea-9f41-b85c59dfeeac.png">

**Comment by muzimuzhi** [comment]
信息不足，请提供 MWE 和编译生成的 log 文件、pdf 文件。

有没有试过，使用不同的 pdf 阅读器？

**Comment by ppppbamzy** [comment]
> 信息不足，请提供 MWE 和编译生成的 log 文件、pdf 文件。
> 
> 有没有试过，使用不同的 pdf 阅读器？

不同的pdf阅读器都是那样。以下是mwe
[mwe.zip](https://github.com/mohuangrui/ucasthesis/files/4473298/mwe.zip)

**Comment by ppppbamzy** [comment]
我在artratex.sty里加了这样一段，凑合着解决了
```tex
\DeclareFontFamily{U}{matha}{\hyphenchar\font45}
\DeclareFontShape{U}{matha}{m}{n}{
    <5> <6> <7> <8> <9> <10> gen * matha
    <10.95> matha10 <12> <14.4> <17.28> <20.74> <24.88> matha12
}{}
\DeclareSymbolFont{matha}{U}{matha}{m}{n}
\DeclareFontSubstitution{U}{matha}{m}{n}
\DeclareFontFamily{U}{mathx}{\hyphenchar\font45}
\DeclareFontShape{U}{mathx}{m}{n}{
    <5> <6> <7> <8> <9> <10>
    <10.95> <12> <14.4> <17.28> <20.74> <24.88>
    mathx10
}{}
\DeclareSymbolFont{mathx}{U}{mathx}{m}{n}
\DeclareFontSubstitution{U}{mathx}{m}{n}
\DeclareMathDelimiter{(}              {matha}{"70}{mathx}{"00}
\DeclareMathDelimiter{)}              {matha}{"71}{mathx}{"08}
\DeclareMathDelimiter{[}              {matha}{"72}{mathx}{"10}
\DeclareMathDelimiter{]}              {matha}{"73}{mathx}{"18}
\DeclareMathDelimiter{\lbrace}     {4}{matha}{"74}{mathx}{"20}
\ifx\@latexbug\undefined
\mathabx@aliases\lbrace\{
\else% suggested by Patrick Cousot
\DeclareRobustCommand{\{}{\ifmmode\lbrace\else\textbraceleft\fi}
\fi
\DeclareMathDelimiter{\rbrace}     {5}{matha}{"75}{mathx}{"28}
\ifx\@latexbug\undefined
\mathabx@aliases\rbrace\}
\else
\DeclareRobustCommand{\}}{\ifmmode\rbrace\else\textbraceright\fi}
\fi
```
<img width="384" alt="截屏2020-04-14下午1 24 45" src="https://user-images.githubusercontent.com/10197323/79189360-2026fc80-7e54-11ea-9177-85ccde9b609a.png">
参考了[这里](https://tex.stackexchange.com/questions/14386/importing-a-single-symbol-from-a-different-font)

**Comment by ppppbamzy** [comment]
多谢各位

**Comment by muzimuzhi** [comment]
你的问题是 
```tex
./Style/artratex.sty:819:\RequirePackage[italic,noendash]{mathastext}
```
导致的。模板的最新版已经去掉了这个包，建议试试新版的模板。

**Comment by ppppbamzy** [comment]
> 你的问题是
> 
> ```
> ./Style/artratex.sty:819:\RequirePackage[italic,noendash]{mathastext}
> ```
> 
> 导致的。这个宏包是你在上传的例子中的提交 7bbe6c64ea1f38a4c0b20d8595ec9e82c718efb1 里加上的，模板自身没有载入过这个包。
> 
> 当时加载它是为了什么，是否必须使用这个包？
> 
> PS：为了控制例子的文件体积，制作 zip 压缩包时，不用把 `.git` 目录打进来。

嗯，我也考虑过是加了某些包之后冲突了。多谢了！！！🙏🙏🙏
那个包跟\bm的问题有关，根据#264 这个包和bm都是不需要的。
隐藏的`.git`目录忘记了，下次注意😂
