### ISSUE TITLE
bm粗体在win下编译不出，在mac下可以，win下是texlive2020，mac下是texlive2018

### ISSUE THREAD

**Issue by ifeelok92** [mohuangrui/ucasthesis#264]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
用了包\usepackage{bm}, 我的论文在mac下编译正常，今天移植到win7下，凡是有\bm命令的地方报错 extended mathchar used as mathchar。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/4469741/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![B2C8482DD590F48D021C904B16E23F58](https://user-images.githubusercontent.com/19997093/79125219-6175c880-7dd0-11ea-9fd6-620ef2c15d98.jpg)

**Comment by ppppbamzy** [comment]
加个mathastext包试试

**Comment by muzimuzhi** [comment]
模板已经调用了 `unicode-math` 宏包，可以直接使用 `\symbfit{a}` 得到加粗倾斜的 `a`。

**Comment by ifeelok92** [comment]
> 模板已经调用了 `unicode-math` 宏包，可以直接使用 `\symbfit{a}` 得到加粗倾斜的 `a`。

好的，我recommand了\bm为\symbfit，win7下编译成功了。但是为啥Mac下不用这个操作？

**Comment by muzimuzhi** [comment]
@ifeelok92 
猜测和字体有关，具体原因可能需要提供可复现的例子。我目前接触不到 Win 7 系统，所以没法详细测试。

如果问题已解决，可以关闭当前 issue。
