### ISSUE TITLE
连续引用参考论文出现问号

### ISSUE THREAD

**Issue by loklio** [mohuangrui/ucasthesis#265]
如图
![问题](https://user-images.githubusercontent.com/25979365/79182886-899e0f80-7e42-11ea-9da6-499aef6bafa0.png)
没找到问题出在哪，麻烦您啦

**Comment by muzimuzhi** [comment]
请展示你是如何输入的。最好能提供一个可编译的完整例子，编译结果能复现你的问题。

**Comment by mohuangrui** [comment]
检查标点符号、label、bib条目、编译方式
