### ISSUE TITLE
如何将图目录和表目录合并为图表目录？

### ISSUE THREAD

**Issue by 282338169** [mohuangrui/ucasthesis#267]
您好，我主要是有两个问题。1.如何可以将图标目录合并呢？就是统一为图表目录，图排列完后空两行进行表排列，而不是图目录和表目录都是开始于新的一页。2.图目录和表目录中，不同章节的标题间行距有些大，可以把整个图表目录设置为统一行距吗？谢谢您啦！

**Comment by muzimuzhi** [comment]
> 1.如何可以将图标目录合并呢？就是统一为图表目录，图排列完后空两行进行表排列，而不是图目录和表目录都是开始于新的一页。

提醒：注意关注是否符合院系对论文的格式要求。

```tex
{% content list region
\linespread{1.2}% local line space
\intobmk*{\cleardoublepage}{\contentsname}% add link to bookmark
\tableofcontents% content catalog
\intobmk*{\cleardoublepage}{\listfigurename}% add link to bookmark
\listoffigures% figure catalog

%% 调整 chapter/break=...
\makeatletter
\ctexset{
  chapter/break=\addpenalty{\@secpenalty}\par\vspace{2\baselineskip}
}
\makeatother
%% 删除 \cleardoublepage
\intobmk*{}{\listtablename}% add link to bookmark
\listoftables% table catalog
}
```

> 2.图目录和表目录中，不同章节的标题间行距有些大，可以把整个图表目录设置为统一行距吗？

在 `\begin{document}` 之前添加
```tex
\ctexset{
  % 默认值都是是 `10pt`
  chapter/lofskip=0pt,
  chapter/lotskip=0pt
}
```
详见 https://github.com/TheNetAdmin/zjuthesis/issues/56#issuecomment-612043229

**Comment by 282338169** [comment]
您好，首先谢谢您！第二个问题已经解决了。第一个问题，采用您的办法是可以将图和表排在一起，但是前面没有'图'和‘表’字（用了您之前在提问中讲到的，然而行间距太大），无法区分。我现在做了如下处理，生成了如下图，请问有什么办法将下一页的表接着上一页图的下方空白处继续显示吗？我没有使用\您上面提到的listfigurename=图表目录，而是继续采用\listoffigures和\listoftables，将ucasthesis.cfg中“表格列表”删掉了。

![image](https://user-images.githubusercontent.com/63667852/79312140-09a2a300-7f31-11ea-9692-9378260c3ec4.png)
![image](https://user-images.githubusercontent.com/63667852/79312268-3a82d800-7f31-11ea-81f9-272cba034a98.png)

**Comment by muzimuzhi** [comment]
试试我评论的最初版本
![image](https://user-images.githubusercontent.com/6376638/79409014-618fe700-7fcf-11ea-850d-d84a8a42b06a.png)

**Comment by 282338169** [comment]
太棒了，谢谢您，解决了！我觉得模板本身自带的生成目录就很好，研究生部老师非要让这么改，也是很无奈！感谢您啦

**Comment by jqbk** [comment]
> > 1.如何可以将图标目录合并呢？就是统一为图表目录，图排列完后空两行进行表排列，而不是图目录和表目录都是开始于新的一页。
> 
> 提醒：注意关注是否符合院系对论文的格式要求。
> 
> ```
> %% 放在 \begin{document} 之前
> \ctexset{
>   listfigurename=图表目录
> }
> ```
> 
> ```
> {% content list region
> \linespread{1.2}% local line space
> \intobmk*{\cleardoublepage}{\contentsname}% add link to bookmark
> \tableofcontents% content catalog
> \intobmk*{\cleardoublepage}{\listfigurename}% add link to bookmark
> \listoffigures% figure catalog
> 
> %% 以下为有变化的部分
> \vspace{2\baselineskip}
> \makeatletter
> \@starttoc{lot}
> \makeatother
> }
> ```
> 
> > 2.图目录和表目录中，不同章节的标题间行距有些大，可以把整个图表目录设置为统一行距吗？
> 
> 在 `\begin{document}` 之前添加
> 
> ```
> \ctexset{
>   % 默认值都是是 `10pt`
>   chapter/lofskip=0pt,
>   chapter/lotskip=0pt
> }
> ```
> 
> 详见 [TheNetAdmin/zjuthesis#56 (comment)](https://github.com/TheNetAdmin/zjuthesis/issues/56#issuecomment-612043229)

您好，按照您的修改，图目录和表目录确实是同一行距了，但是`图目录`和下面的间距变小了，请问您知道怎么调整么？

加“图”和“表”后，对于长标题的图标，文字无法对齐，请问如何调整？
![微信截图_20210127223600](https://user-images.githubusercontent.com/23696676/106006845-9e594480-60f0-11eb-8a4d-54a0fd8a1439.png)
![微信图片_20210127223659](https://user-images.githubusercontent.com/23696676/106006853-a0bb9e80-60f0-11eb-9f72-35d08806bb08.png)

**Comment by muzimuzhi** [comment]
请给完整的例子，例如 fork 当前仓库，把能复现问题的例子 push 到一个新分支，然后把分支链接贴过来。
