### ISSUE TITLE
按要求设置后字体仍然有警告

### ISSUE THREAD

**Issue by tiantianwahaha** [mohuangrui/ucasthesis#268]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：使用了最新版 ucasthesis + Texlive (2019) + Windows 10 + TeXstudio最新版。
1. PDF中内容可以正确拷贝不产生乱码，但是字体还是有5条警告如图。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![warning](https://user-images.githubusercontent.com/20633103/79542494-5798e180-80be-11ea-9d5f-cbba89794485.PNG)

**Comment by muzimuzhi** [comment]
正常信息，无需担心。

**Comment by tiantianwahaha** [comment]
> 正常信息，无需担心。

好滴，非常感谢~
