### ISSUE TITLE
能否帮助修改正文前面的页脚样式？

### ISSUE THREAD

**Issue by ColdCodeCool** [mohuangrui/ucasthesis#27]
如图
<img width="1365" alt="2018-02-03 11 55 44" src="https://user-images.githubusercontent.com/14211604/35762815-588b56a4-08d9-11e8-94b0-d32b444fad27.png">

**Comment by mohuangrui** [comment]
请问你使用的是最新版吗？最新版标题应该出现在页眉，不应该出现在页脚啊。这个改起来很简单，但是最新版的ucasthesis与国科大发布的模版是完全一致的，不知你为何要弄成这样的？

**Comment by ColdCodeCool** [comment]
我是想在页脚加入单位名称，并且正文前面部分需要也按doubleside那种奇偶页码排列样式

**Comment by ColdCodeCool** [comment]
仔细看了一下您写的artratex.sty，现在会写了，谢谢！
