### ISSUE TITLE
增加延迟公开的样式选择

### ISSUE THREAD

**Issue by sunyz** [mohuangrui/ucasthesis#271]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 10

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
增加延迟公开的样式，与“密级”类似又不完全相同
“（三）延迟公开学位论文应在论文印刷本封面和电子版首页右上角使用黑体三号字明确标注，标注方法如下：
延迟公开★　　  年（空白处必须填写延迟公开年限，一般不超过2年）。”

**Comment by mohuangrui** [comment]
国科大撰写指南中目前并没有这一选项，如果需要，可以在cfg文件中将 密级 改为 延迟公开★
