### ISSUE TITLE
如何在图表目录中移除参考文献引用

### ISSUE THREAD

**Issue by FangShancheng** [mohuangrui/ucasthesis#273]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

图表标题caption中的参考文献引用，会直接带到目表目录中，然鹅只希望正文中有参考文献引用，而不希望目录中有参考文献引用。

## 问题截图 / Screenshots

![1588004045541](https://user-images.githubusercontent.com/18243865/80395359-a546f280-88e5-11ea-97d6-e79e258940fd.jpg)

**Comment by happyTonakai** [comment]
A good option is to avoid cites in titles, and to specify optional caption text without cites:
```\caption [Picture of a bird.]{Picture of a bird \cite{audobon}.}```

如果你的问题是图表目录出现在正文之前，会导致引用顺序混乱，试试 notoccite 宏包

**Comment by FangShancheng** [comment]
> A good option is to avoid cites in titles, and to specify optional caption text without cites:
> `\caption [Picture of a bird.]{Picture of a bird \cite{audobon}.}`
> 
> 如果你的问题是图表目录出现在正文之前，会导致引用顺序混乱，试试 notoccite 宏包

亲测有效：
1. \caption[目录标题]{正文标题+引用}不会出现目录中引用
2. notoccite不会导致引用混乱

非常感谢！
