### ISSUE TITLE
如何将附录位置放在参考文献的后面

### ISSUE THREAD

**Issue by SerendipitousAurorae** [mohuangrui/ucasthesis#274]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

您好，我记得曾经的附录是放在参考文献的后面，如今更新宏包后发现附录的位置在参考文献的前面了，请问如何修改。

**Comment by happyTonakai** [comment]
你记错了，这个模板从第一个release开始附录就在参考文献前面的。

**Comment by happyTonakai** [comment]
如果你一定要修改，在 Theis.tex 里调换 `\input{Tex/Appendix}` 和 `\bibliography{Biblio/ref}` 的位置就好了，注意他们各自上下的环境初始化命令和 `\cleardoublepage`

**Comment by mohuangrui** [comment]
仔细阅读 LaTeX 知识小站？

https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何调整附录设置
