### ISSUE TITLE
修改图片、表格、公式编号的格式

### ISSUE THREAD

**Issue by SerendipitousAurorae** [mohuangrui/ucasthesis#275]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

您好，请问如何将模板中图片、表格、公式编号由 `图1.1`、`表1.1`、`(1.1)`，改为`图1-1`、`表1-1`、`(1-1)`的形式。

**Comment by muzimuzhi** [comment]
```tex
\patchcmd\thefigure   {.}{-} {}{\fail}
\patchcmd\thetable    {.}{-} {}{\fail}
\patchcmd\theequation {.}{-} {}{\fail}
```
