### ISSUE TITLE
如何移除参考文献后边出现的文献页码？

### ISSUE THREAD

**Issue by JieLi1994** [mohuangrui/ucasthesis#276]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
参考文献后边会出现引用这篇文献的页码，如何把这个页码去掉

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![WechatIMG2](https://user-images.githubusercontent.com/31659916/80798205-690ddd80-8bd6-11ea-8add-b3db19319ad1.jpeg)

**Comment by muzimuzhi** [comment]
一种手动的办法，手动修改 bib 文件，注释页码部分。

**Comment by mohuangrui** [comment]
你自己启用了backref？
见：
https://github.com/mohuangrui/ucasthesis/wiki/文献样式#超链接参考文献到文档引用页不建议启用

**Comment by JieLi1994** [comment]
确实是，多谢，解决了发自我的华为手机-------- 原始邮件 --------主题：Re: [mohuangrui/ucasthesis] 如何移除参考文献后边出现的文献页码？ (#276)发件人：mohuangrui 收件人：mohuangrui/ucasthesis 抄送：JieLi1994 ,Author 

你自己启用了backref？

见：

https://github.com/mohuangrui/ucasthesis/wiki/文献样式#超链接参考文献到文档引用页不建议启用
