### ISSUE TITLE
biber/biblatex 支持

### ISSUE THREAD

**Issue by Memcys** [mohuangrui/ucasthesis#277]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
\usepackage[biber]{Style/artratex}
提示
`\bibliography{Biblio/ref}` `Can be used only in preamble`.

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
https://paste.ubuntu.com/p/JHHtsQSP9d/

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

## 最小工作示例(MWE) / Minimal Working Example 

`ucasthesis/Thesis.tex' 文件：
https://paste.ubuntu.com/p/WWxf3WZNhb/

在 ucasthesis 主文件夹下编译
```
latexmk -xelatex
```
提示
`\bibliography{Biblio/ref}` 出错，`Can be used only in preamble`.

```
latexmk -C
ls Thesis.*
```
确保清除了 Thesis 所有生成文件。删除 `Thesis.tex` 中 biber 选项，重新编译：
```
latexmk -xelatex
```
正常结束。得到 log 文件 https://paste.ubuntu.com/p/tjVPqTKqJn/

## 问题定位
`biblatex` 通过 `\addbibresource{filename.bib}` 添加 bib 文件，并通过 `\printbibliography` 打印文献, 但它们只能出现在 preamble 中。`\backmatter` 初始化了环境，为了开启 biber 选项，暂且注释掉。`Thesis.tex` 部分修改如下：
```
\documentclass[twoside]{Style/ucasthesis}
\usepackage[biber]{Style/artratex}% document settings
\usepackage{Style/artracom}% user defined commands
\addbibresource{Biblio/ref.bib}
\begin{document}
\cite{wikibook2014latex}
\printbibliography
\end{document}
```
清理辅助文件后重新编译，成功得到了 PDF 文件。那么问题在于
- [ ] \backmatter 与 biblatex 冲突。

但是还没有完全成功。编译提示
```
biber Thesis: Could not find bib file for 'Thesis'
```
所以又有一个问题：
- [ ] bib 文件定位出错。

对所有文件搜索 `biber`, 发现文件 `./Style/artratex.sty` 中
```
488 \ifartx@biber%
...
502 \addbibresource{ref.bib}%
```
也就是直接假定参考文献为 `ucasthesis/ref.bib`. 这显然与其他地方默认 `ucasthesis/Biblio/ref.bib` 不一致。

注释上述 `artratex.sty` 中的 `\ifartx@biber` 下的 `\addbibresource{ref.bib}`. 清理辅助文件，重新编译，得到带有参考文献的 PDF.

## 尝试解决方案小结
- [x] 注释 `\backmatter` 和 `bibliography{}`.
- [x] 注释 `./Style/artratex.sty` 中的 `\ifartx@biber` 下的 `\addbibresource{ref.bib}`. 并在 preamble 中合适位置添加 `\addbibresource{}`.

但这也**破坏**了 `\backmatter` 的设计。请问 @HuangruiMo 有什么更好的解决方案？

**Comment by hushidong** [comment]
参考一下这个

https://github.com/mohuangrui/ucasthesis/issues/247

**Comment by mohuangrui** [comment]
鉴于大多数期刊仍只支持 `bibtex`，`ucasthesis` 对 `biblatex` 的初始支持只是基本的。如果你要使用 `biblatex`，至少需要在 `Thesis.tex` 中作如下设定：

1. 启用 `biber` 选项来调用 `biblatex`：
```Tex
\usepackage[biber,authoryear,list]{Style/artratex}% document settings
```
2. 启用 `biblatex` 所需的文献输出命令：
```Tex
%\bibliography{Biblio/ref}% bibliography
\printbibliography% bibliography
```
3. 使用 `biblatex` 支持的 `\cite` 系列命令，而不是模版默认的 `\citet` 和 `\citep`等。

更多细节修正可见 [hushidong, issue 247](https://github.com/mohuangrui/ucasthesis/issues/247)

**Comment by Memcys** [comment]
> 参考一下这个
> 
> #247

谢谢 @hushidong 的 gb7714-2015 样式。很强大也很管用。

不过，关于 @hushidong 在 https://github.com/mohuangrui/ucasthesis/issues/247#issuecomment-598128152 中的修改建议，我认为 `\addbibresource{Biblio/ref.bib}%` 这一行灵活度有限。

用户固然可以在 preamble 其他位置添加自己的 bib 文件：
```
% anywhere in preamble
\addbibresource{custom.bib}
```
但如果 `Biblio/ref.bib` 文件不存在，则参考文献失效：
```
biber Thesis: Could not find bib file for 'Thesis'
```
即使 `custom.bib` 存在。

也许大家默认会保证 `Biblio/ref.bib` 存在。但作为提醒，我特此说明。

**Comment by hushidong** [comment]
bib文件的位置的确没必要在cls中指定，可以去掉。

使用biblatex-gb7714-2015的话，citet和citep命令，一样用法。文档不用做修改。

@mohuangrui 有时间的话可以完善一下biblatex支持，或者我写个pr？

**Comment by hushidong** [comment]
bib文件可以在选项中给出。比如fdu的设置

 bib-backend = bibtex,
    % 参考文献支持方式
    % 允许选项：
    %   bib-backend = bibtex|biblatex
    %
    % bib-style = numerical,
    % 参考文献样式
    % 允许选项：
    %   bib-style = author-year|numerical|<其他样式>
    % 说明：
    %   author-year  著者—出版年制
    %   numerical    顺序编码制
    %   <其他样式>   使用其他 .bst（bibtex）或 .bbx（biblatex）格式文件
    %
    % cite-style = {},
    % 引用样式
    % 默认为空，即与参考文献样式保持一致
    % 仅适用于 biblatex；如要填写，需保证相应的 .cbx 格式文件能被调用
    %
    bib-resource = {fduthesis-template.bib},
    % 参考文献数据源
    % 可以是单个文件，也可以是用英文逗号 “,” 隔开的一组文件
    % 如果使用 biblatex，则必须明确给出 .bi

**Comment by mohuangrui** [comment]
@hushidong 谢谢建议，biblatex的支持我再观察一下～

**Comment by hushidong** [comment]
👌ok
