### ISSUE TITLE
如何在“原创性声明”和“授权使用声明”页中插入电子签名和日期？

### ISSUE THREAD

**Issue by 282338169** [mohuangrui/ucasthesis#278]

**Comment by mohuangrui** [comment]
可用 Adobe -〉sign -〉Insert image

**Comment by 282338169** [comment]
嗯嗯，这个确实可以完成。我是想问可以在LaTeX中完成这项操作吗？我看到声明页是在.cfg文件中，不是.tex文件。

**Comment by mohuangrui** [comment]
如果愿意折腾，LaTeX 当然可以，比如用 Tikz。

**Comment by happyTonakai** [comment]
在cfg或者cls文件中使用wrapfigure似乎可以实现，我试了试排版还是有点麻烦

**Comment by mohuangrui** [comment]
@happyTonakai 当然是这样的，更别提不同电子签名的图片尺寸也是有差异的。

再者，要注意签名还需导师的，使用插入功能就会需要保存并操作导师的电子签名的图片，若无授权则有法律风险，即使有授权，也是存在程序问题的。
