### ISSUE TITLE
中文粗体有点细，英文粗体正常

### ISSUE THREAD

**Issue by Sundrops** [mohuangrui/ucasthesis#282]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
中文粗体有点细，英文粗体正常

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/4672848/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
左边为模板使用说明的pdf显示，右边为我编译后的pdf显示
![WX20200524-095753](https://user-images.githubusercontent.com/14829222/82744036-deb83400-9da5-11ea-81ce-dd4e15aa50f4.png)
![WX20200524-095830](https://user-images.githubusercontent.com/14829222/82744029-d3650880-9da5-11ea-8315-5adfbccbd536.png)
![WX20200524-095817](https://user-images.githubusercontent.com/14829222/82744031-d9f38000-9da5-11ea-8c4d-fffcf73821c5.png)

**Comment by mohuangrui** [comment]
1 macOS 与 windows 的系统中文字体是有差异的
2 没有谁知道多粗才是正确的，或者就没有所谓的正确
3 不同的PDF阅读器有时对字体的渲染也是会出现差异的

如果需要，你可以最后放到windows上编译一下，或者去调试 artratex.sty 中的 AutoFakeBold 值

**Comment by mathfinder** [comment]
好像有同学win编译下来还是比较细

**Comment by mohuangrui** [comment]
Windows编译也取决于调用的字体，比如Adobe，系统字体等。总之，如果需要，可以去调试 artratex.sty 中的 AutoFakeBold 值

**Comment by Sundrops** [comment]
@mohuangrui 改完AutoFakeBold之后，没啥变化，全部把2.5换成5或者25都没用，跪求怎么操作

**Comment by mohuangrui** [comment]
@Sundrops mac上不启用autofakebold，autofakebold是字体库不全时需要，mac上是全的，没必要使用。如果一定要用，可以考虑在下面这行：
https://github.com/mohuangrui/ucasthesis/blob/85edd386a52ccbd59b33d0fe8212b9311c9476d2/Style/artratex.sty#L410
下面加：
```Tex
AutoFakeBold=2.5,
```

**Comment by Sundrops** [comment]
@mohuangrui 好的 太感谢了

**Comment by lsvih** [comment]
经测试 fontset 使用 `none`，下好 Adobe 字体之后在 artratex.sty 中 autofakebold 改成 4 可以得到与其他人相似的粗体效果

```
\setCJKmainfont{AdobeSongStd-Light}[%
            Path=\artx@fontdir,
            Extension=.otf,
            AutoFakeBold=4,
            ItalicFont=AdobeKaitiStd-Regular,
        ]
        \setCJKsansfont{AdobeHeitiStd-Regular}[%
            Path=\artx@fontdir,
            Extension=.otf,
            AutoFakeBold=4,
        ]%
        \setCJKmonofont{AdobeFangsongStd-Regular}[%
            Path=\artx@fontdir,
            Extension=.otf,
            AutoFakeBold=4,
        ]
```

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/5164225/117243834-89681c00-ae6a-11eb-8ed0-8bb7fac726f7.png">
