### ISSUE TITLE
eps图片格式问题

### ISSUE THREAD

**Issue by lixinyu2016** [mohuangrui/ucasthesis#283]
说明文档中声明支持的图片格式并不包括eps，试了一下也确实显示有有问题，但目前有大量eps的格式图片，请问有办法插入eps的图片吗

**Comment by mohuangrui** [comment]
eps 转 pdf 或 png 即可，若会linux，直接批量转即可

**Comment by lixinyu2016** [comment]
谢谢，已解决。

**Comment by lixinyu2016** [comment]
``

**Comment by bronzeMe** [comment]
@mohuangrui 请教一下，如果想支持eps编译，大概要做哪些改动呢，目前使用Ps2pdf转换后，PDF有大量的白边，不是很好

**Comment by bronzeMe** [comment]
@mohuangrui  已解决，使用ps2pdf命令时加'-dEPSCrop'，ps2pdf -dEPSCrop xx.eps xx.pdf
