### ISSUE TITLE
请问gbt7714-plain.bst样式可实现参考文献双语言对照吗？

### ISSUE THREAD

**Issue by zhihengszu** [mohuangrui/ucasthesis#284]
## 检查 / Check

-[x] -->已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
-[x] --> 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
-[x] --> 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
-[x] -->已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] --> Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] --> TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：我想在@Article中的note = {xxx}输入另外一种语言，但样式编译后note中的xxx不显示。另外我也不知道有没有更直接的办法

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/4673852/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![498f14fa4aa34bf8e68057578a9fcd9](https://user-images.githubusercontent.com/50646133/82758455-393ea800-9e19-11ea-8397-87c20ef4e055.png)

**Comment by hushidong** [comment]
你给的是biblatex-gb7714-2015的示例，注意其实现原理。见

https://github.com/hushidong/biblatex-gb7714-2015/blob/master/egfigure/egdoublelan.tex

如果使用bibtex，请教一下lee zeping看是怎么实现的？

**Comment by zhihengszu** [comment]
> 你给的是biblatex-gb7714-2015的示例，注意其实现原理。见
> 
> https://github.com/hushidong/biblatex-gb7714-2015/blob/master/egfigure/egdoublelan.tex
> 
> 在bib中把中英文分开，是为了后面方便使用，想使用哪种语言都行，只在需要时使用双语言对照。
> 
> 双语用的还是少的，从我16年写这个功能到现在，你好像是第一个明确希望使用的。
> 
> 如果使用bibtex，请教一下lee zeping看是怎么实现的？

嗯嗯，非常感谢，请教过了，gbt7714-2015.bst样式没有定义其他输出域，比如定义一个translation域。目前一个折衷的办法就是在最后一个域加内容，比如这样pages = {1--10.\\另一种语言内容}。这种只适合临时用一次，既然双语用得不多，biblatex又能实现，这个问题也不那么重要了。

**Comment by hushidong** [comment]
好的。
