### ISSUE TITLE
移除 \citet 引用方式：作者名字与年份前括号之间的空格

### ISSUE THREAD

**Issue by lsuniue** [mohuangrui/ucasthesis#285]
感谢各位老师同学为国科大模板的辛苦付出！
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live  2020
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

实现的功能：老师要求把引用参考文献中的的括号改成中文格式的括号，我通过 \bibpunct 实现了。此时使用 \citet 后编译的PDF中作者名字与年份前的括号之间多了一个空格，是否有办法可以移除 \citet 引用方式：作者名字与年份前括号之间的空格，即将 xiang 等 （2016）更改为 xiang 等（2016）

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

括号更改后间距略大
![111](https://user-images.githubusercontent.com/26479010/83259098-08c88680-a1ea-11ea-82dd-329192495bbf.png)

**Comment by mohuangrui** [comment]
你好，见 https://github.com/mohuangrui/ucasthesis/issues/192#issuecomment-540559066

“因为文献列表中统一采用的都是英文标点，因此 gbtxxx.bst 文件也都是基于英文标点写的，从而部分字段显示加了空格符号，而将 cite 样式中改用中文标点后，那些在 bst 中的空格符号就会产生额外的空格”

如果一定要改，可以考虑在 （）前后手动缩减间距，即用 `\hspace{-0.5em}（` 代替 `（`

**Comment by Youguang** [comment]
@mohuangrui 
请问`\hspace{-0.5em}（ ` 是在哪里改？

论文撰写规范指导意见中确实要求的是中文逗号、括号，如果要用这个模版有没有更好的解决办法？

<img width="606" alt="Screen Shot 2021-01-26 at 00 08 52" src="https://user-images.githubusercontent.com/7878120/105731870-d6cf1600-5f6a-11eb-8cc8-7d7e861e7cbd.png">

**Comment by mohuangrui** [comment]
"能去除\citet括号前的空格，但是会使\citep括号前的空间变得很小；另外\citep引用逗号后面有的后面有空格，有的没有。"

试试：
1. 将 
 https://github.com/mohuangrui/ucasthesis/blob/5ea69e8debd01294b7f14be3a443b72026d83b2b/Style/artratex.sty#L470
改为
```Tex
\newcommand{\bibstyle@authoryear}{\bibpunct{\hspace{-0.25em}（}{）}{；}{a}{，\hspace{-0.25em}}{，\hspace{-0.25em}}}%
```
2. 不使用 著者-出版年制（authoryear），而使用 顺序编码制（numbers），规避这个中英文标点问题。见 https://github.com/mohuangrui/ucasthesis/wiki/文献样式
3. 就使用英文标点

**Comment by Youguang** [comment]
> 
> 1. 将
>    https://github.com/mohuangrui/ucasthesis/blob/5ea69e8debd01294b7f14be3a443b72026d83b2b/Style/artratex.sty#L470
>    
>    改为
> 
> ```
> \newcommand{\bibstyle@authoryear}{\bibpunct{\hspace{-0.25em}（}{）}{；}{a}{，\hspace{-0.25em}}{，\hspace{-0.25em}}}%
> ```

使用 biber 编译的话要怎么改呢？
