### ISSUE TITLE
关于模版使用和个性化的问题

### ISSUE THREAD

**Issue by dearealeo** [mohuangrui/ucasthesis#286]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

辛苦各位学长学姐了！我想问下能否允许外校学生的使用？如果可以的话，能否告知下具体的个性化的方法吗？例如如何修改封面一类的（不是修改封面上的字 就是换 由我自己来作封面 还有如何将列表改成缩进？感谢！

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/4705432/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by mohuangrui** [comment]
ucasthesis 是开源的，你想怎么改即可怎么改。

至于如何实现你要的，建议多读关于 LaTeX的资料

**Comment by dearealeo** [comment]
谢谢您！

**Comment by dearealeo** [comment]
> ucasthesis 是开源的，你想怎么改即可怎么改。
> 
> 至于如何实现你要的，建议多读关于 LaTeX的资料

谢谢您！
