### ISSUE TITLE
参考文献责任者中的 Collaboration 项

### ISSUE THREAD

**Issue by flycicitsh** [mohuangrui/ucasthesis#287]
一些文献的责任者标记使用「第一作者（集体责任者）」的形式，例如：[物理评论D 98 030001](https://journals.aps.org/prd/abstract/10.1103/PhysRevD.98.030001) 中为
> M. Tanabashi et al. (Particle Data Group)

尝试在 bst 文件中的 ENTRY 中添加 collaboration 项，并按 REVTeX 的 bst 对应修改 format.authors 函数
```
FUNCTION {format.authors}
{ author "author" format.names
  duplicate$ empty$ 'skip$
    { collaboration "collaboration" bibinfo.check
      duplicate$ empty$ 'skip$
        { " (" swap$ * ")" * }
      if$
      *
    }
  if$
  "author" 'bibfield :=
}
```

但是不成功。

其实还是不是太理解 bst 的写法，请高人指教。

PS 当然这个可以用魔改 bib 的方法 hack 就是了...
```
author = {M. Tanabashi and {et al} and {(Particle Data Group)}}
```

**Comment by mohuangrui** [comment]
学位论文要求符合国标，不应采用这种形式。至于若是投稿需要这样的样式，你直接用相应期刊的bst即可

**Comment by flycicitsh** [comment]
> 学位论文要求符合国标

国标中也有主要责任者是机构、团体时的情形吧？

参见 **GB/T 7714-2015** 中
- 3.2 主要责任者的定义
- 4.3.2 三个著录例的责任者都为机构

具体的需求应该是在 format.authors 后检查 bibtex 中是否有 collaboration 项。如有则在主要责任者后加上。但是不太理解 bst 的语法。

**Comment by mohuangrui** [comment]
@flycicitsh 这样的话，需请教一下 gbt bst的开发者 @zepinglee 

建议将问题转至： https://github.com/CTeX-org/gbt7714-bibtex-style

**Comment by zepinglee** [comment]
GB/T 7714-2015 都是要求“主要责任者”，没有“第一作者（集体责任者）”的格式。所以要么个人著者，要么是机关团体
