### ISSUE TITLE
参考文献列表中，如何在只有两个或三个作者的时候，如何在倒数第2个和倒数第1个作者之间加上“and”？

### ISSUE THREAD

**Issue by zzddsg** [mohuangrui/ucasthesis#288]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
参考文献列表中，如何在只有两个或三个作者的时候，如何在倒数第2个和倒数第1个作者之间加上“and”？

## 最小工作示例(MWE) / Minimal Working Example 

![image](https://user-images.githubusercontent.com/12294679/83574399-00f94100-a560-11ea-8eb5-83941c4cac33.png)
请问如何将两个作者之间的连接词由“,”改成“and”？在有三个作者的时候，如何在第二个作者和第
三个作者之间的连接词由“,”改成“and”？

**Comment by mohuangrui** [comment]
样式设定以国标为准，如果想问一般情形如何这样改，请前往ctex form 发问

**Comment by Shuang0420** [comment]
朋友，我遇到了同样的问题，请问还记得解决方案吗
