### ISSUE TITLE
附录格式调整

### ISSUE THREAD

**Issue by zzddsg** [mohuangrui/ucasthesis#289]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
我想改附录的三个格式： 
1. 将附录页眉处由“附录A”改成“附  录”，中间的空格为一个汉字符位
2. 将附录的标题由“附录A”改成“附录”，我只需要一个附录即可
3. 附录下面表的编号由“表A.x”改成“附表x”

## 最小工作示例(MWE) / Minimal Working Example 

原版：

![Annotation 2020-06-03 065622](https://user-images.githubusercontent.com/12294679/83577702-7ddbe900-a567-11ea-8688-1520e51634ce.png)

改成这种格式：
![image](https://user-images.githubusercontent.com/12294679/83577746-9d731180-a567-11ea-959f-cb3be523921c.png)

谢谢！

**Comment by mohuangrui** [comment]
1. 将

https://github.com/mohuangrui/ucasthesis/blob/85edd386a52ccbd59b33d0fe8212b9311c9476d2/Style/ucasthesis.cls#L654

改为
```Tex
        number = ,
```

2. 在

https://github.com/mohuangrui/ucasthesis/blob/85edd386a52ccbd59b33d0fe8212b9311c9476d2/Thesis.tex#L80

下面添加：

``` Tex
\renewcommand{\theequation}{\arabic{equation}}% configure the label style
\renewcommand{\thefigure}{\arabic{figure}}% configure the label style
\renewcommand{\thetable}{\arabic{table}}% configure the label style
\renewcommand{\figurename}{附图}
\renewcommand{\tablename}{附表}
```

至于你的第一点，这个没法在不影响其他地方的条件下去改，除非你自己去修改 ctex 的内部命令。

**Comment by muzimuzhi** [comment]
> 至于你的第一点，这个没法在不影响其他地方的条件下去改，除非你自己去修改 ctex 的内部命令。

是可以改的。第 1、2 两点需求综合起来，在导言区增加：
```tex
\ctexset{
  appendixname={附\hspace{\ccwd}录},
  appendix/name={\appendixname},
  appendix/number={}
}
```
![image](https://user-images.githubusercontent.com/6376638/83980234-9b81c780-a946-11ea-8e70-6286c5e04d2b.png)

**Comment by mohuangrui** [comment]
@muzimuzhi 貌似需要的是页眉中附录加空格，章标题中附录不加空格

**Comment by muzimuzhi** [comment]
> @muzimuzhi 貌似需要的是页眉中附录加空格，章标题中附录不加空格

是的，我之前看错了。

> https://github.com/mohuangrui/ucasthesis/issues/289#issue-629568194
> 1. 将附录页眉处由“附录A”改成“附  录”，中间的空格为一个汉字符位
> 1. 将附录的标题由“附录A”改成“附录”，我只需要一个附录即可


```tex
% 导言区
\ctexset{
  appendix/name={\appendixname},
  appendix/number={}
}

% Appendix.tex
\chapter{中国科学院大学学位论文撰写要求}
\markboth{\MakeUppercase{附\hspace{\ccwd}录\quad 中国科学院大学学位论文撰写要求}}{}
```
![image](https://user-images.githubusercontent.com/6376638/84001165-aa916580-a998-11ea-9a71-a7d4868a7c7a.png)

PS：这样的需求，破坏了一致性。

**Comment by mohuangrui** [comment]
@muzimuzhi 是的，破坏了一致性，没有什么意义。

你这个实现很取巧了，只是这样以来目录中的“附录”是否还是会带空格？

**Comment by muzimuzhi** [comment]
> 只是这样以来目录中的“附录”是否还是会带空格？

不会。`\markboth` 只影响 `\leftmark` 和 `\rightmark`。
