### ISSUE TITLE
关于编译的小白问题

### ISSUE THREAD

**Issue by Xiaoye-A** [mohuangrui/ucasthesis#290]
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/4724403/Thesis.log)
您好！
我在编译的时候按照“模板使用说明”安装软件，安装了一圈的软件都没法正确运行，我把pdf推荐的软件全都试了一遍也跑不通，所以我还是安装回了ctex。我运行简单的可以顺利通过，但是运行这个模板的时候还是报错，具体见附件的log文件！谢谢您！

**Comment by mohuangrui** [comment]
如果不会装软件，可用 overleaf： https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE#linuxoverleaf-%E7%B3%BB%E7%BB%9F%E7%9A%84%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE
