### ISSUE TITLE
\sf命令不识别

### ISSUE THREAD

**Issue by lixinyu2016** [mohuangrui/ucasthesis#293]
老师您好，我在论文中使用\sf命令后，显示的结果和不使用时是一样的，是不是不支持这个字体？

**Comment by muzimuzhi** [comment]
具体是怎么用的？请给一个完整的例子，从 `\documentclass` 开始，到 `\end{document}` 结束。

**Comment by lixinyu2016** [comment]
举一个比较简单的例子，输出的两个verify的字体格式完全一样。
\documentclass[twoside]{Style/ucasthesis}
\usepackage[numbers,list]{Style/artratex}% document settings
\usepackage{graphicx}
\usepackage{epstopdf}
\usepackage{amssymb,amsmath,amsfonts,amsthm}
\usepackage{verbatim}
\usepackage{setspace}
\usepackage{tabularx}
\usepackage{threeparttable}
\usepackage{multirow}
\usepackage[referable]{threeparttablex}
\begin{document}
我们想做一个测试 {\sf verify} 和 verify。
\end {document}

**Comment by muzimuzhi** [comment]
使用 xelatex 编译时，目前模板会把西文 serif, sans serif 和 mono 都设成 XITS 衬线字体，导致 `\sffamily` 和 `\ttfamily` 等字族切换命令看起来没有效果。
https://github.com/mohuangrui/ucasthesis/blob/8238e31470b32115aad5a4bf85369af3ac1d7801/Style/artratex.sty#L338-L361

这一修改是 https://github.com/mohuangrui/ucasthesis/commit/05fdcb86ebff3c95802f9301cb84a8b6461ccf28 引入的，修改理由需要等待维护者的回应。

临时方案时，（在导言区）重设 sans serif 西文字体，例如 `\setsansfont{Latin Modern Sans}`。

**Comment by mohuangrui** [comment]
国科大的要求就是这样的，英文都用times类字体

**Comment by lixinyu2016** [comment]
谢谢您，我继续按照模板的要求使用
