### ISSUE TITLE
如何将参考文献的格式显示去掉

### ISSUE THREAD

**Issue by lixinyu2016** [mohuangrui/ucasthesis#294]
请问可以将参考文献显示的格式去掉吗，比如[C],[M][J]等。

**Comment by mohuangrui** [comment]
这是国标所要求的，不建议去掉。如果坚持去掉，见：

https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E4%BF%AE%E6%94%B9%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%88%97%E8%A1%A8%E7%9A%84%E9%BB%98%E8%AE%A4%E6%8E%92%E7%89%88%E8%A1%8C%E4%B8%BA-%E7%94%B1-zepinglee-%E5%BC%80%E5%8F%91%E6%8F%90%E4%BE%9B
