### ISSUE TITLE
参考文献

### ISSUE THREAD

**Issue by lixinyu2016** [mohuangrui/ucasthesis#295]
请问在公开网站上的论文怎么应用，比如arxiv，我用@electronic和@misc都无法显示出“Cryptology ePrint Archive, Report 2005/237”

@electronic{gilbert2005active,
title={An active attack against HB\^{}+-A provable secure lightweight protocol},
  author={Gilbert, Henri  and  Robshaw, Matthew and Sibert, Hervé},
  note = {Cryptology ePrint Archive, Report 2005/237},
    year = {2005},
    url = {https://eprint.iacr.org/2005/237}
}

@misc{gilbert2005active,
      author={Gilbert, Henri  and  Robshaw, Matthew and Sibert, Hervé},
   title={An active attack against HB\^{}+-A provable secure lightweight protocol},
    howpublished = {Cryptology ePrint Archive, Report 2005/237},
    year = {2005},
    note = {\url{https://eprint.iacr.org/2005/237}}
}

**Comment by mohuangrui** [comment]
启用 shownote

https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E4%BF%AE%E6%94%B9%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%88%97%E8%A1%A8%E7%9A%84%E9%BB%98%E8%AE%A4%E6%8E%92%E7%89%88%E8%A1%8C%E4%B8%BA-%E7%94%B1-zepinglee-%E5%BC%80%E5%8F%91%E6%8F%90%E4%BE%9B

**Comment by lixinyu2016** [comment]
谢谢，不过howpublished 怎么显示呢

**Comment by mohuangrui** [comment]
这个不知是否支持，你可以前往 https://github.com/CTeX-org/gbt7714-bibtex-style 进行咨询
