### ISSUE TITLE
参考文献顺序编码问题

### ISSUE THREAD

**Issue by Tony1886** [mohuangrui/ucasthesis#299]
## 检查 / Check

- [x]  已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
-  [x]  确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
-  [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
-  [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  -  [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

最新的参考文献使用顺序编码，参考文献显示是按照字母排序的，不知道哪里出了问题。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![image](https://user-images.githubusercontent.com/38371437/88607062-d8e61400-d0b0-11ea-8774-528414a7e1c8.png)

**Comment by mohuangrui** [comment]
你好，问题源于 gbt-7714 的 bst 文件，已更新修复。
