### ISSUE TITLE
bibtex 引用@masterthesis entry在参考文献中不显示“Master's Thesis”字样

### ISSUE THREAD

**Issue by desenzhou** [mohuangrui/ucasthesis#300]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [x] CTeX

## 描述问题 / Problem Description

问题描述：

想在thesis里引用其他人的硕士论文，但是在bibtex中加了@mastersthesis结果在Reference中仅仅显示引用文章的名字、作者、学校及年份，而不显示Master's Thesis，如何解决呢？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by hushidong** [comment]
这是国标的要求，你的单位的参考文献格式有不同要求么？
要实现也不困难，
是用bibtex的话去请教leezeping
用biber的话参考biblatex-gb7714-2015说明文档。

**Comment by desenzhou** [comment]
谢谢，是我没注意国标要求，已解决。
