### ISSUE TITLE
拷贝文件到新目录，编译未有pdf输出 

### ISSUE THREAD

**Issue by cnforChina** [mohuangrui/ucasthesis#301]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：为了便于使用sublime 进行编辑和文档编译，新建了一个临时目录，将 tex文档和style目录下的.sty, .cls 等文件以及 Img, Biblio目录拷贝到 该临时目录下。
使用 sublime text 编译时，没有error，只有一个warning: 
**(Log parsing issues. Disregard unless something else is wrong.)**

然后该目录下也没有输出pdf文件。请教一下如何解决这个问题。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/5085326/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
编译出现的warning
![2020_08_18_000607](https://user-images.githubusercontent.com/24601147/90417773-c9be1900-e0e6-11ea-9ff5-cf7e80552fb9.png)

当前目录没有产生 pdf文件
![2020_08_18_000647](https://user-images.githubusercontent.com/24601147/90417843-df334300-e0e6-11ea-8050-e662e0ed97d7.png)

**Comment by mohuangrui** [comment]
正常来说，你应该去修改sublime让其支持多级文件结构

如果你坚持要改，看 

https://github.com/mohuangrui/ucasthesis/wiki/%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97#%E7%A7%BB%E9%99%A4%E5%A4%9A%E7%BA%A7%E6%96%87%E4%BB%B6%E7%BB%93%E6%9E%84

**Comment by cnforChina** [comment]
谢谢师兄。 pdf能正常出来了。 不过仍然会有 下面的warning.
(Log parsing issues. Disregard unless something else is wrong.)
是哪里还有什么问题吗？

> 正常来说，你应该去修改sublime让其支持多级文件结构
> 
> 如果你坚持要改，看
> 
> https://github.com/mohuangrui/ucasthesis/wiki/%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97#%E7%A7%BB%E9%99%A4%E5%A4%9A%E7%BA%A7%E6%96%87%E4%BB%B6%E7%BB%93%E6%9E%84

**Comment by mohuangrui** [comment]
warning 和 sublime 的处理方式有关，LaTeX 一般都会有些warning，基本不用管

**Comment by cnforChina** [comment]
了解了。 Thanks.
