### ISSUE TITLE
参考文献显示为？

### ISSUE THREAD

**Issue by lhprojects** [mohuangrui/ucasthesis#302]
## 检查 / Check

- [ x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ x] TeX Live 2019 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

引用文献显示为？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/5219563/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![image](https://user-images.githubusercontent.com/4395807/93108122-0466a180-f6e5-11ea-814b-9a5fa59e5ca9.png)

## 最小工作示例(MWE) / Minimal Working Example 

我编译的是Thesis.tex，我自己的tex也有相同的问题。

**Comment by mohuangrui** [comment]
仔细读读使用说明和知识小站，比如：

https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E7%BC%96%E8%AF%91%E5%90%8E%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%BC%95%E7%94%A8%E5%A4%84%E4%B8%BA%E9%97%AE%E5%8F%B7%E5%90%8C%E6%97%B6%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%88%97%E8%A1%A8%E4%B8%8D%E6%98%BE%E7%A4%BA

**Comment by lhprojects** [comment]
> 仔细读读使用说明和知识小站，比如：
> 
> https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E7%BC%96%E8%AF%91%E5%90%8E%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%BC%95%E7%94%A8%E5%A4%84%E4%B8%BA%E9%97%AE%E5%8F%B7%E5%90%8C%E6%97%B6%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%88%97%E8%A1%A8%E4%B8%8D%E6%98%BE%E7%A4%BA


问题解决了，谢谢，我个人的不仔细耽误您宝贵的时间

**Comment by mohuangrui** [comment]
不客气
