### ISSUE TITLE
字体设置问题：安装`xits`字体包后，`\texttt`用于英文无效，不使用打印机字体

### ISSUE THREAD

**Issue by gaochenyi** [mohuangrui/ucasthesis#303]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - macOS
 
- `TeX 发行版 / Tex Distribution`
  - TeX Live 2020

## 描述问题 / Problem Description

问题描述：

安装`xits`字体包后，`\texttt`用于英文无效，不显示打印机字体效果。
若卸载`xits`字体包，则`texttt`用于英文有效，显示为打印机字体效果。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[ucasthesis-bug.log](https://github.com/mohuangrui/ucasthesis/files/5444041/ucasthesis-bug.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![Screen Shot 2020-10-27 at 16 53 17](https://user-images.githubusercontent.com/32761974/97278605-f162f780-1874-11eb-87fe-040222afc3f5.png)
![Screen Shot 2020-10-27 at 16 57 11](https://user-images.githubusercontent.com/32761974/97279084-7bab5b80-1875-11eb-9f5a-0196fa042050.png)

## 最小工作示例(MWE) / Minimal Working Example 

```latex
\documentclass{ctexbook}
\usepackage{artratex}
\begin{document}

测试

\texttt{测试}

test

\texttt{test}

\end{document}
```

**Comment by Wenchuan5000** [comment]
👍

**Comment by mohuangrui** [comment]
你好，国科大模板默认英文皆为 times 字体，因此模板将 等宽字体 \texttt 也设定为了 times。你所描述的问题为既定效果。

**Comment by gaochenyi** [comment]
> 你好，国科大模板默认英文皆为 times 字体，因此模板将 等宽字体 \texttt 也设定为了 times。你所描述的问题为既定效果。

感谢回复。不过撰写指南对于正文中各种情形下字体的说明其实很少吧，以下非杠哈，只是表达一下观点。撰写指南里只说了中文宋体，英文Times，然后部分地方指明了黑体。但如果按照英文默认均为Times来理解的话，那也要把中文非指定黑体的部分全转换成宋体吧？这样逻辑上才一致对吧。再一个，如果论文里贴代码，如果也用衬线体的话，跟通行的学术规范也不一致呢。

不过我也没问过学位办的老师，所以仅提个意见哈，我自己是打算先改回来，如果审批不通过再调整——主要有些场景下，因为衬线体是非等宽的，显示效果很不理想。

**Comment by mohuangrui** [comment]
这个很难协调，每个人都有不同的看法，你按照自己的偏好设定即可。
