### ISSUE TITLE
必须将`sty`文件移至根目录，否则`artra*`的宏包选项无法使用。

### ISSUE THREAD

**Issue by gaochenyi** [mohuangrui/ucasthesis#304]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - macOS

- `TeX 发行版 / Tex Distribution`
  - TeX Live 2020

## 描述问题 / Problem Description

问题描述：
默认状态无法编译。
检查发现，利用宏包选项自动加载的宏包没有被加载。
将sty文件移至根目录，并移除相应的`Style/`，则编译成功。

搜了一下，貌似是文件放在子目录导致的问题。

> quoted from [here](https://tex.stackexchange.com/questions/138745/138751#comment312855_138745)
>
> It is a syntax error to put a file path in the name argument. Like many TeX errors it is possible to do it anyway and get some sort of result. but it is still an error. – David Carlisle

参见如下讨论：

1. [How can I properly resolve relative paths in `\usepackage`?](https://tex.stackexchange.com/a/124013/51870)
2. [Can I `\usepackage` with a full path?](https://tex.stackexchange.com/questions/138745)
3. [Specify path to sister directory in a style file](https://tex.stackexchange.com/questions/185684/specify-path-to-sister-directory-in-a-style-file#comment429334_185691)

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/5464943/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by mohuangrui** [comment]
你好，请见 #305

**Comment by gaochenyi** [comment]
OK

**Comment by mohuangrui** [comment]
问题已修复： https://github.com/latex3/latex2e/issues/422#issuecomment-719949626
