### ISSUE TITLE
自 LaTeX2e 2020-10-01，通过 \usepackage[...]{Style/...} 加载的宏包，宏包选项永不执行

### ISSUE THREAD

**Issue by muzimuzhi** [mohuangrui/ucasthesis#305]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ ] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [x] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

简化后的例子见 https://github.com/latex3/latex2e/issues/422 ，但因为这种用法本就不推荐，不确定会得到修复。

基于 `ucasthesis` 的间接的测试方式可以是
 - 使用任意的未定义宏包选项，预期得到警告，实际得不到。例如 `\usepackage[xxxxxx]{artratex}`
 - 修改宏包选项定义，插入任意会导致报错的代码，实际无报错。

实际可以加载 `unravel` 宏包，然后在 `*.sty` 里使用 `\unravel{\ProcessOptions\relax}`，最后在命令行编译、查看实际展开。可以在第 10 步看到预期为 true 的 test 实际得到的是 false 
```
[===== Step 10 =====] \ifcsname opt@Style/artratex.sty\endcsname =false => skip to \else
||
|| \edef \@curroptions {
|> \@ifundefin@d@ii \fi {opt@\@currname .\@currext }\@empty {\csname
|> opt@\@currname .\@currext \endcsname }}\@ifstar \@xprocess@ptions
|> \@process@ptions \relax
```

### 绕过问题

不论 latex2e 方面是否修复，都可以用
```tex
\makeatletter
\def\input@path{{./Style}}
\makeatother
\documentclass[twoside]{ucasthesis}
\usepackage[authoryear,list]{artratex}
\usepackage{artracom}
```
绕过问题。

**Comment by mohuangrui** [comment]
谢谢解答，下次更新时改用这个方案试试，不知 `\def\input@path{{./Style}}` 是否会影响 .sty 内的相对路径搜索？我在 .sty 内还相对调用 biblio 内的 bst，然后 .cls 内调用了 .cfg。

当然最省事的就是都丢到主文件目录下，不过总觉得有些乱

**Comment by muzimuzhi** [comment]
> 不知 `\def\input@path{{./Style}}` 是否会影响 .sty 内的相对路径搜索？我在 .sty 内还相对调用 biblio 内的 bst，然后 .cls 内调用了 .cfg。

会。类似 `\graphicspath{<directory-list>}`，可以写多个路径。根据 https://github.com/latex3/latex2e/issues/422#issuecomment-719949626 ，latex2e 方面会修复。

**Comment by mohuangrui** [comment]
我在 artratex.sh 中是通过修改环境变量：
```
export TEXINPUTS=".//:$TEXINPUTS" # paths to locate .tex 
export BIBINPUTS=".//:$BIBINPUTS" # paths to locate .bib
export BSTINPUTS=".//:$BSTINPUTS" # paths to locate .bst
```
来实现搜索的

对于 `\input@path` 我刚测试了一下 [tex.se](https://tex.stackexchange.com/questions/79058/can-a-default-path-be-set-globally-for-input-akin-to-graphicspath/79060) 中给出的 `edef` 方案，发现 `\input@path` 对 `Tex/`，`Style` 等 latex 路径有效，但是 `bibtex` 无效。不知 bibtex 是否有类似的内建变量？

**Comment by mohuangrui** [comment]
bibtex 的问题在于它是直接读取 .aux 文件内的信息，而 .aux 是 latex 写入的，感觉很难一并解决好

**Comment by mohuangrui** [comment]
问题已修复： https://github.com/latex3/latex2e/issues/422#issuecomment-719949626
