### ISSUE TITLE
如何修改参考文献作者数量

### ISSUE THREAD

**Issue by MingChaoXu** [mohuangrui/ucasthesis#306]
如题所示，参考文献的作者数量默认显示3个，超过会用et al.代替，请问如何修改参考文献的作者数量

**Comment by zhanglinbo** [comment]
指导意见里就是这样规定的，什么原因需要修改呢？

**Comment by mohuangrui** [comment]
见
https://github.com/mohuangrui/ucasthesis/wiki/文献样式#修改参考文献列表的默认排版行为
```
max.num.authors
```
