### ISSUE TITLE
多处引用同一著者的同一文献的问题

### ISSUE THREAD

**Issue by zhanglinbo** [mohuangrui/ucasthesis#307]
学位论文撰写规范指导意见中：使用著者-出版年制标注参考文献时，多处引用同一著者的同一文献时，在“（）”外以角标的形式著录引文页码。例如：（张永 等，2005）8；（张永 等，2005）12-15。

请问这个这么实现？谢谢

**Comment by hushidong** [comment]
如果用biblatex/biber的话，
```
\usepackage[biber,authoryear,list]{Style/artratex}% document settings
```
我试了下使用citet和citep命令都不是你要的效果，
那么使用cite命令，比如：

```
如此，即完成了文献的索引\cite[30]{lamport1986document}，请查看下本文档的参考文献一章，看看是不是就是这么简单呢？是的，就是这么简单\cite[80-90]{lamport1986document}！
```

结果为：
![图片](https://user-images.githubusercontent.com/20421795/100764090-ee899280-3430-11eb-9c9b-fa59efe059a8.png)

**Comment by zhanglinbo** [comment]
非常感谢，页码能不能自动生成了，而不是手动添加？

**Comment by hushidong** [comment]
单处引用是可以的，用pagescite命令可以自动生成。

比如：
```
如此\pagescite{chen2005zhulu}，即完成了文献的索引\cite[30]{lamport1986document}，请查看下本文档的参考文献一章，看看是不是就是这么简单呢？是的，就是这么简单\cite[80-90]{lamport1986document}！
```

结果为
![图片](https://user-images.githubusercontent.com/20421795/100812112-3206ef80-3477-11eb-82a7-f90a67d1ed07.png)


而多处引用的话，理论上需要在bib文件中提供不同处引用的页码，同时后端要能解析出来，这样才有可能取到这个数据。但还有一个问题是，cite命令是不知道在引用时取哪个页码的，所以这是无解的。

当然如果把不同页码的文献做不同的文献条目处理，那么使用pagescite是可以的，但因为文献的作者相同，为了区分文献，会在年份后面添加a，b，c等，这样就失去了原来的意义。

所以最后的方式还是自己手动标记。

**Comment by zhanglinbo** [comment]
感谢！

**Comment by zhanglinbo** [comment]
pagescite命令用不了，! Undefined control sequence.

**Comment by hushidong** [comment]
不会吧，我昨天新下的模板，然后用texlive2020编译的没有问题呀，
下面这句设置你设置了没？
```
\usepackage[biber,authoryear,list]{Style/artratex}% document settings
```

**Comment by zhanglinbo** [comment]
\usepackage[authoryear,list]{Style/artratex} 我设置的这样的

**Comment by hushidong** [comment]
这样自然是不行的，加上biber选项才使用biblatex，同时编译文献的命令也从bibtex换成biber，具体看一下模板的wiki

**Comment by zhanglinbo** [comment]
明白了，非常感谢
