### ISSUE TITLE
如何修改参考文献作者数量

### ISSUE THREAD

**Issue by MingChaoXu** [mohuangrui/ucasthesis#309]
您好，我之前问过这个问题没来得及回复，如题所示，参考文献的作者数量默认显示3个，超过会用et al.代替，请问如何修改参考文献的作者数量
修改原因:论文评审意见要求我显示全部作者
请问可以修改吗，谢谢

**Comment by mohuangrui** [comment]
已经回答过了，见

https://github.com/mohuangrui/ucasthesis/issues/306

**Comment by MingChaoXu** [comment]
您好，我按照#306的方法修改了参数，可是依然报错，我的方式如下：
mac系统
修改了gbt7714-author-year.bst 和 gbt7714-numerical.bst 中同样位置的配置函数如下：
添加了参数：#9 'max.num.authors :=

![image](https://user-images.githubusercontent.com/8822286/101244502-e20f7d80-3741-11eb-8d87-7939ad4af4a3.png)

bibtex编译时报错信息如下：
Process started

This is BibTeX, Version 0.99d (TeX Live 2020) The top-level auxiliary file: Thesis.aux The style file: Biblio/gbt7714-numerical.bst max.num.authors is an unknown function---line 55 of file Biblio/gbt7714-numerical.bst Database file #1: Biblio/ref.bib You can't pop an empty literal stack while executing---line 2253 of file Biblio/gbt7714-numerical.bst 3 is an integer literal, not a function, while executing---line 2253 of file Biblio/gbt7714-numerical.bst Warning--empty booktitle in mishra2012scene (There were 3 error messages)

Process exited with error(s)

**Comment by mohuangrui** [comment]
你好，忘记更新 wiki 了，见更新的 wiki:

https://github.com/mohuangrui/ucasthesis/wiki/文献样式#修改参考文献列表的默认排版行为
