### ISSUE TITLE
关于编译

### ISSUE THREAD

**Issue by brightlee-china** [mohuangrui/ucasthesis#31]
弄了一晚上，安装了各种字体，就是编译不过，下载了master分支，发现还是出现adobe字体找不到。用了relase版本也是一样。

错误：

Could not resolve font "AdobeFangsongStd-Regular/BI" (it probably doesn't
. exist).
.................................................
.................................................
. fontspec info: "no-font-shape"
. 
. Could not resolve font "AdobeFangsongStd-Regular/B" (it probably doesn't
. exist).
.................................................
.................................................
. fontspec info: "no-font-shape"
. 
. Could not resolve font "AdobeFangsongStd-Regular/I" (it probably doesn't
. exist).

另外，原来的版本
已经不能用\project\Ctex@spacechar了
\newcommand\UCASspace{\qquad}

环境：新安装的Miktex，2.9版本最新版，编译不通过。

就是各种坑，latex对原来兼容性是真的差，已经不止一次碰到这样的问题了

**Comment by mohuangrui** [comment]
这位同学，遇到问题时请先冷静。ucasthesis的主页 https://github.com/mohuangrui/ucasthesis 上明确说了下载请点击页面右上角的download zip，release里面明确标明了那是2013年版的历史记录，不是2018年版。

若你下载了当前最新版，请花几分钟阅读下使用说明文档，这样远比你暗自折腾一晚上更有效率。最新版中，根本没有调用adobe字体，也就是说你一开始就不会遇到任何问题。

最后，你的问题很明确的是你的当前版本调用了adobe字体，而你的系统没有adobe字体，你安装再多的其他字体自是无用。LaTeX远比你认为的要好，前提是你知道你在做什么。

若仍有问题，欢迎反馈，祝好。

**Comment by brightlee-china** [comment]
非常抱歉，昨晚是冲动了。

目前用了最新版本，然后安装了最新的MikTex。还是编译不通过。

[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/1788211/Thesis.log)

**Comment by brightlee-china** [comment]
直接在winedit里面编译通过了。另外，第一封面那个，“硕士学位论文”下面不用加粗线

**Comment by brightlee-china** [comment]
![image](https://user-images.githubusercontent.com/14074537/37089719-80301970-223c-11e8-8f5d-24f688cf2a17.png)

为啥下划线宽度不一致，看了代码是一致的。。。

**Comment by zhixy** [comment]
求编译经验，折腾了大半天，ubuntu， win10都没能编译成功:(

**Comment by mohuangrui** [comment]
@brightlee-china 你的Thesis.log文件中并没有错误，Miktex在安装后的头几次编译容易出现问题，而且编译很慢，多试几次后一般就可以了，所以一般不推荐Miktex。
@zhixy 最有价值的编译经验就是请耐心地读模板使用说明文档。

**Comment by zhixy** [comment]
@mohuangrui 嗯，又折腾了一下，最终还是编译通过了，但是是用pdflatex编译才行，xalatex还是不行，奇怪

**Comment by mohuangrui** [comment]
那确实是奇怪，可以肯定的是当前模版没有编译缺陷。最可能的就是你的LaTeX安装有问题，建议你按照说明文档中给出的问题排解步骤进行操作。
