### ISSUE TITLE
无法编译l.475 \captionsetup[bi-first]{bi-first}                                        % ? 无法消除。

### ISSUE THREAD

**Issue by pacmacX** [mohuangrui/ucasthesis#310]
## 检查 / Check

- [x ] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x ] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ This is XeTeX, Version 3.14159265-2.6-0.999992 (MiKTeX 20.11)] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
我下载到模板后，直接对thesis.tex进行编译，出现
! Package caption Error: bi-first undefined.

See the caption package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.475 \captionsetup[bi-first]{bi-first}
                                       %
? 
的报错。觉得是参数没有定义，但是找不到原因，尝试过重装miktex最新版本，更新宏包，仍没有解决。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Uploading Thesis.log…]()

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![$C0@%C6GI`AIQ}VIJG%46H](https://user-images.githubusercontent.com/39003023/101158397-9c31b700-3666-11eb-8173-4239cadf8c14.png)

**Comment by mohuangrui** [comment]
确定你是从 Github 下载的最新版？这个问题很早之前就已经更新解决了。根据

475 \captionsetup[bi-first]{bi-first}

你使用的很可能不是最新版
