### ISSUE TITLE
默认选择著作-年格式，但是编译了之后参考文献是编号方式，不是著作者-年的格式

### ISSUE THREAD

**Issue by yan-yantest** [mohuangrui/ucasthesis#311]
## 检查 / Check

- [x ] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX
  - [*] Texmaker 5.0.4
## 描述问题 / Problem Description

问题描述：

在win10 上，下载了UCASThesis 的模板，编译了之后参考文献是编号方式，不是著作者-年的格式

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/5651398/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![微信图片_20201207162748](https://user-images.githubusercontent.com/75607495/101327147-413bd200-38a9-11eb-804b-eda98d936bdd.png)

## 最小工作示例(MWE) / Minimal Working Example 

我希望的结果
![微信图片_20201207162755](https://user-images.githubusercontent.com/75607495/101327222-5b75b000-38a9-11eb-96fa-32e1abe167b7.png)

**Comment by mohuangrui** [comment]
如果你没有修改 Thesis.tex，即仍保持了：
```Tex
\usepackage[authoryear,list]{Style/artratex}% document settings
```
那么很可能就是和如下的问题类似：
https://github.com/latex3/latex2e/issues/422#issuecomment-719949626

解决办法为 1. 使用一个较低版本的 LaTeX 编译器，比如 2019 版本。 或者 2. 进一步更新 LaTeX 编译器至最新版 （最新版对问题进行了修复）。

**Comment by yan-yantest** [comment]
更换到了latex live 2019 问题得到了解决。多谢！
