### ISSUE TITLE
请教下公式与正文和页脚的间距过大的问题

### ISSUE THREAD

**Issue by stormalpha** [mohuangrui/ucasthesis#314]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live2020 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
新人求教，请教大佬们
1, 公式与正文间距太大，如图1,2 我看之前学长们用Word的间距没这么大，请问如何调整？
2，如果公式在某一页的末尾，如图3，会和页码之间有非常大的距离。请问该怎样调整？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/5714236/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![image](https://user-images.githubusercontent.com/33691440/102586388-078a8700-4145-11eb-9d8b-4c68b760ae81.png)
![image](https://user-images.githubusercontent.com/33691440/102586443-2557ec00-4145-11eb-8420-95d3f518c68b.png)

## 最小工作示例(MWE) / Minimal Working Example 

其公式为
%--------------------------------DeltaVBE---------------------------------------------------%
	\begin{align}
		\Delta V_{BE}   		&= V_{BE1}  - V_{BE2}  \nonumber \\ 
								&= V_T In\frac{{NI_0 }}{{I_{S1} }} - _T In\frac{{I_0 }}{{I_{S2} }} \nonumber \\ 
		\label{eq:DeltaVBE}		&= V_T InN  
	\end{align}
带隙基准的输出电压的一般公式如下所示
%------------------------------------------------------------------------------------------%
%------------------------------Vref1------------------------------------------------------%
	\begin{align}
		V_{{\rm{ref}}}  		&= \alpha V_{BE}  + \beta \left( {\Delta V_{BE} } \right) \nonumber \\ 
		\label{eq:Vref1}		&= \alpha V_{BE}  + \beta \left( {V_T InN} \right)  
	\end{align}
%------------------------------------------------------------------------------------------%

其中，V$_{BOD}$为掉电检测电路的翻转阈值，C$_{N13}$是$N_{13}$的栅电容值，C$_D$是D点的寄生电容值。V$_{th\_P7}$是晶体管P$_7$的阈值电压。
%------------------------------POR公式2----------------------------------------------------------%
\begin{equation}\label{eq:POR2}
	%\adddotsbeforeeqnnum%
	V_{BOD}  = \frac{{C_{N13} }}{{C_D  + C_{N13} }} \cdot V_{MAX}  - \left| {V_{th\_P7} } \right| 
\end{equation}

将公式\eqref{eq:Iavg}带入公式\eqref{eq:energy conservation}可得
%-------------------------------------energy conservation2--------------------------------------------------
\begin{equation}\label{eq:energy conservation2}
	\frac{1}{2} \times \left( {D_1  + D_2 } \right) \times \left( {\frac{{V_i }}{L}D_1 T_s } \right) \times V_{i}  = \frac{{V_{_o }^2 }}{{R_L }}
\end{equation}
%-------------------------------------------------------------------------------------------------
公式\eqref{eq:伏秒平衡输出}与公式\eqref{eq:energy conservation2}联立化简可得
%----------------------------------------energy conservation3---------------------------------------------
\begin{equation}\label{eq:energy conservation3}
	\frac{{V_o^2 }}{{V_i^2 }} - \frac{{V_o }}{{V_i }} - \frac{{D_1^2 T_s R_L }}{{2L}} = 0
\end{equation}
%-------------------------------------------------------------------------------------------------

**Comment by stormalpha** [comment]
![image](https://user-images.githubusercontent.com/33691440/102587225-74eae780-4146-11eb-8bf9-82dd36cc5468.png)
补上图3

**Comment by mohuangrui** [comment]
LaTeX 的排版一般为诸多约束下的最优结果，一般不建议手动调整。至于与 Word 的对比，意义不大。毕竟 LaTeX 才是专业级排版，而不是 Word 。
