### ISSUE TITLE
不显示目录和! LaTeX Error: Environment algorithm undefined.

### ISSUE THREAD

**Issue by zyamss** [mohuangrui/ucasthesis#315]
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/5745893/Thesis.log)
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [x] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by zzllc3** [comment]
相同问题+1

**Comment by mohuangrui** [comment]
具体情形不是特别清楚，不过根据你的 log 文件，至少有如下问题：

1. 建议用 xelatex，你用的 pdflatex

This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.12) (preloaded format=pdflatex 2020.12.28)  28 DEC 2020 12:20

2. 你的miktex安装路径乱码
C:\Users\å¼ æ¨\AppData\Roaming\MiKTeX\tex/latex/ctex\ctexbook.cls

3. 你很可能把 Thesis.tex 中的 list 选项移除了
\usepackage[authoryear,list]{Style/artratex}% document settings

**Comment by ChangITP** [comment]
我用的xelatex同样遇到LaTeX Error: Environment algorithm undefined的问题，目前通过在Thesis.tex中添加`\usepackage{algorithm,algpseudocode}`
解决了。

**Comment by mohuangrui** [comment]
同样的问题： https://github.com/mohuangrui/ucasthesis/issues/316

**Comment by mohuangrui** [comment]
确认为 LaTeX 的问题 （https://github.com/mohuangrui/ucasthesis/issues/305），目前简单的解决方案见 ：https://github.com/mohuangrui/ucasthesis/issues/316
