### ISSUE TITLE
Backmatter.tex 文件 行 21: Undefined control sequence. \setlist 

### ISSUE THREAD

**Issue by ChangITP** [mohuangrui/ucasthesis#316]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：TeXLive2020，所有宏包都更新到最新。编译模板出错，提示 Backmatter.tex 文件 
行 21 `Undefined control sequence. \setlist`
行 23 `Something's wrong--perhaps a missing \item. \item u`
行 24 `Something's wrong--perhaps a missing \item. \end{enumerate}`

## 日志文件 / .log file

[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/5758586/Thesis.log)

## 问题截图 / Screenshots

![屏幕截图 2021-01-01 104053](https://user-images.githubusercontent.com/33488875/103432665-df5b5780-4c1d-11eb-82f9-9d0e0803d97a.png)

![屏幕截图 2021-01-01 105726](https://user-images.githubusercontent.com/33488875/103432760-39f5b300-4c20-11eb-97c3-e0271f9219d6.png)

**Comment by mohuangrui** [comment]
问题很可能还是和下面的 issue 有关：

https://github.com/mohuangrui/ucasthesis/issues/305

最简单的解决方案可试试在 artratex.sty 中把如下部分的 if 条件去掉：
```Tex
%\ifartx@list% enable enhanced list and verbatim structures
    \RequirePackage{verbatim}% improve verbatim environment
    \RequirePackage{enumitem}% configure the enumerate environment
    \setlist[enumerate]{wide=\parindent}% only indent the first line
    \setlist[itemize]{wide=\parindent}% only indent the first line
    \setlist{nosep}% default text spacing
    \RequirePackage{listings}% source code
    \RequirePackage{algpseudocode,algorithm,algorithmicx}% algorithm
    \providecommand{\algname}{Algorithm}%
    \def\ALG@name{\algname}% rename label
%\fi
```
比较可靠的方案为，将texlive改为2019

**Comment by mohuangrui** [comment]
同样的问题: https://github.com/mohuangrui/ucasthesis/issues/315

**Comment by ChangITP** [comment]
> 问题很可能还是和下面的 issue 有关：
> 
> #305
> 
> 最简单的解决方案可试试在 artratex.sty 中把如下部分的 if 条件去掉：
> 
> ```
> %\ifartx@list% enable enhanced list and verbatim structures
>     \RequirePackage{verbatim}% improve verbatim environment
>     \RequirePackage{enumitem}% configure the enumerate environment
>     \setlist[enumerate]{wide=\parindent}% only indent the first line
>     \setlist[itemize]{wide=\parindent}% only indent the first line
>     \setlist{nosep}% default text spacing
>     \RequirePackage{listings}% source code
>     \RequirePackage{algpseudocode,algorithm,algorithmicx}% algorithm
>     \providecommand{\algname}{Algorithm}%
>     \def\ALG@name{\algname}% rename label
> %\fi
> ```


多谢！目前暂时采用这个方法，不再报错。

**Comment by mohuangrui** [comment]
好的，那就是 LaTeX 的问题无疑了，等新的 LaTeX 发布即可自行解决。
