### ISSUE TITLE
Overleaf模板编译效果和"模板使用说明.pdf"不一样

### ISSUE THREAD

**Issue by LynnHo** [mohuangrui/ucasthesis#317]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description
问题描述：Overleaf模板编译效果和"模板使用说明.pdf"不一样，比如以下两图中"日期"的"日"字。我们应该以哪种为准，还是两种都是符合要求的？感谢回答！（另外，正如wiki里面所说，我在linux下用tex live 2020不改任何设置编译的结果和overleaf上的一模一样，那"模板使用说明.pdf"是用什么环境编译出来的？）

## 问题截图 / Screenshots
该项目提供的Overleaf模板直接编译，不做任何修改，效果如下

![image](https://user-images.githubusercontent.com/16457298/103480685-96b7c000-4e10-11eb-8c1e-2a768b81069b.png)

该项目里的文件"模板使用说明.pdf"的显示效果如下

![image](https://user-images.githubusercontent.com/16457298/103480668-856eb380-4e10-11eb-939f-e3809fa574c0.png)

**Comment by muzimuzhi** [comment]
> 那"模板使用说明.pdf"是用什么环境编译出来的？

从 pdf 内嵌字体的名称来看，很可能是在 WIndows 下编译出来的。「日」字的不同，是因为使用的字体不同。Windows 下使用的是系统自带的商业字体，Linux 下使用的是免费字体。

**Comment by LynnHo** [comment]
那么这两种均符合国科大要求？所以我们任选一种就好？

**Comment by mohuangrui** [comment]
@LynnHo 见 https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE
