### ISSUE TITLE
公式中数字和字母的字体非 times 字体

### ISSUE THREAD

**Issue by huangjihongchina** [mohuangrui/ucasthesis#318]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2017 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
公式中数字和字母的字体并不是所设置的 Times 字体，\mathrm 操作仍保留 Latin Modern Math 的字体，而 \text 操作则可以改为 Times。但是对于数字，如果不用 \text 进行修饰，直接当作数学公式，仍是 Modern Math 的字体。详情可见下图。

请问有什么办法可以使得他们都默认为 Times 的字体？我认为我应该不缺少字体，那时什么原因？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/5864227/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![屏幕快照 2021-01-25 12 14 58](https://user-images.githubusercontent.com/52959546/105662575-03ebdc00-5f0b-11eb-937e-c2a3e5724281.png)

这一部分的代码如下：
`\begin{equation}
g_{\mu\nu}=g^{\mu\nu}=\begin{pmatrix}
\text{1} & 0 & 0 & 0\\
0 & \text{-1} & 0 & 0\\
0 & 0 & -1 & 0\\
0 & 0 & 0 & -1\\
\end{pmatrix}.
\end{equation}
`
对于前两个对角元数字1和-1，我利用 \text 进行修饰，变为 Times 的字体；后两个-1，没有修饰，就是 modern math。

![屏幕快照 2021-01-25 12 15 11](https://user-images.githubusercontent.com/52959546/105662591-10703480-5f0b-11eb-84fe-cb7bf01f4e22.png)

这是使用说明中的，直接编译后的结果。可见 \mathrm 并不好用，连带着字母、数字都为 Latin Modern Math。

**Comment by mohuangrui** [comment]
由于网络原因我这无法看到图片，检查 Thesis.log 你的系统内无法找到 xits 字体，说明问题很可能出在这里。解决方案：

1. 更新 mac 上的 texlive
或
2. 使用window系统编译

**Comment by huangjihongchina** [comment]
感谢，更新成了 texlive 2020，成功了。
