### ISSUE TITLE
如何实现参考文献在每一章后面而不是整个论文统一一个参考文献章节

### ISSUE THREAD

**Issue by twn1993** [mohuangrui/ucasthesis#32]
完全的新手，看师哥师姐写的毕业论文都是参考文献每章一个，不知道如何设置，希望赐教！

**Comment by twn1993** [comment]
你好，按照您给的链接我看了一下，不过主目录里还是会出现参考文献的字样，而且当我后面按照wiki的说法加了之后原来可以引用的参考文献都变成了“？”，对于我这个纯新手来说确实不知道该如何做了，而且每章节后面单独的参考文献似乎是很多人写文献的标准格式，希望作者更新下照顾一下我们纯新手，在此谢谢了！

**Comment by mohuangrui** [comment]
你好，建议你先别整分章的了，2018官方要求里明确写明了参考文献只集中于文末一处，即使你最后被要求（尽管不会），你也可以再去弄分章的，LaTeX不会让你做任何额外的调整，你只需按照Wikibook的指导调用package即可。至于其他的，实在不好意思，我也有我自己的人生和问题。
