### ISSUE TITLE
在“图形列表”和“表格列表”的编号前加“图”和“表”之后目录的行距自动变成文章的默认行距，这个问题可以解决么

### ISSUE THREAD

**Issue by jqbk** [mohuangrui/ucasthesis#321]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live <2020>
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
如问题标题所述，在`artracom.sty`中添加了

```
\RequirePackage[titles]{tocloft}
\newlength{\mylen}
\renewcommand{\cftfigpresnum}{\figurename\enspace}
\renewcommand{\cftfigaftersnum}{}
\settowidth{\mylen}{\cftfigpresnum\cftfigaftersnum}
\addtolength{\cftfignumwidth}{\mylen}
\renewcommand{\cfttabpresnum}{\tablename\enspace}
\renewcommand{\cfttabaftersnum}{}
\settowidth{\mylen}{\cfttabpresnum\cfttabaftersnum}
\addtolength{\cfttabnumwidth}{\mylen}
\renewcommand{\cftchapfont}{\zihao{4}\sffamily}
\renewcommand{\cftsecfont}{\zihao{-4}\sffamily}
\renewcommand{\cftsubsecfont}{\zihao{-4}\sffamily}
\renewcommand{\cftsubsubsecfont}{\zihao{-4}\sffamily}
\renewcommand{\cftfigfont}{\zihao{-4}\sffamily}
\renewcommand{\cfttabfont}{\zihao{-4}\sffamily}
\renewcommand{\cftchapleader}{\cftdotfill{\cftdotsep}}
\renewcommand{\cftdotsep}{1.5}
```
目录的行距自动变成文章的默认行距

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by mohuangrui** [comment]
目前我也不知问题具体出在哪里，实在没有时间去追究这些非关键问题

**Comment by jqbk** [comment]
> 目前我也不知问题具体出在哪里，实在没有时间去追究这些非关键问题

你好，我这边提供一种方法，仅供有需要的同学参考：
将`Thesis.tex`中的
```
\intobmk*{\cleardoublepage}{\listfigurename}% add link to bookmark
\listoffigures% figure catalog
\intobmk*{\cleardoublepage}{\listtablename}% add link to bookmark
\listoftables% table catalog
```
修改为：
```
{%
\let\oldnumberline\numberline%
\renewcommand{\numberline}{\figurename~\oldnumberline}%
\intobmk*{\cleardoublepage}{\listfigurename}
\listoffigures%
}
{%
\let\oldnumberline\numberline%
\renewcommand{\numberline}{\tablename~\oldnumberline}%
\intobmk*{\cleardoublepage}{\listtablename}
\listoftables%
}
```
即可

但是对于很长的标题缩进会有些小问题
![微信截图_20210127205245](https://user-images.githubusercontent.com/23696676/105993670-a362c780-60e1-11eb-800c-545231a29167.png)
正在查找解决的办法，谢谢

**Comment by opee007** [comment]
你好，请问需要添加在artracom.sty的什么位置，我遇到了这种错误“! Package inputenc Error: Unicode character 图 (U+56FE)”

**Comment by wyxliyiyi** [comment]
> 你好，请问需要添加在artracom.sty的什么位置，我遇到了这种错误“! Package inputenc Error: Unicode character 图 (U+56FE)”

你好，我也遇到了这个问题，你解决了吗

**Comment by yymygod** [comment]
> > 目前我也不知问题具体出在哪里，实在没有时间去追究这些非关键问题
> 
> 你好，我这边提供一种方法，仅供有需要的同学参考： 将`Thesis.tex`中的
> 
> ```
> \intobmk*{\cleardoublepage}{\listfigurename}% add link to bookmark
> \listoffigures% figure catalog
> \intobmk*{\cleardoublepage}{\listtablename}% add link to bookmark
> \listoftables% table catalog
> ```
> 
> 修改为：
> 
> ```
> {%
> \let\oldnumberline\numberline%
> \renewcommand{\numberline}{\figurename~\oldnumberline}%
> \intobmk*{\cleardoublepage}{\listfigurename}
> \listoffigures%
> }
> {%
> \let\oldnumberline\numberline%
> \renewcommand{\numberline}{\tablename~\oldnumberline}%
> \intobmk*{\cleardoublepage}{\listtablename}
> \listoftables%
> }
> ```
> 
> 即可
> 
> 但是对于很长的标题缩进会有些小问题 ![微信截图_20210127205245](https://user-images.githubusercontent.com/23696676/105993670-a362c780-60e1-11eb-800c-545231a29167.png) 正在查找解决的办法，谢谢
请问这种长标题缩进有办法解决吗？
