### ISSUE TITLE
使用minted包在附录中插入代码

### ISSUE THREAD

**Issue by Youguang** [mohuangrui/ucasthesis#323]
## 描述问题

因为`minted`包对代码的识别要比模版自带的`listings`好，我想用`minted`包在附录中插入代码，我实现的方式是
- 在`Thesis.tex`中调用`\usepackage[outputdir=Tmp]{minted}`
- 附录插入代码文件`\inputminted[fontsize=\scriptsize, frame=single, linenos, stepnumber=5]{tcsh}{Code/test.sh}`
- 将`artratex.sh`中`$TexCompiler`替换为`$TexCompiler -shell-escape`进行编译

问题：编译出的pdf附录包含代码部分，但是被识别成了普通文字，空格合并、格式打乱、行间距变大。字体也没有单独编译的好看。如何保留`minted`代码格式插入附录？

## 问题截图
从单独文件使用`minted`插入代码：
<img width="672" alt="Screen Shot 2021-01-30 at 14 14 21" src="https://user-images.githubusercontent.com/7878120/106349018-7db60800-6305-11eb-9ce2-2fbd469bc303.png">

在`ucasthesis`模版附录部分使用`minted`插入代码，空格合并、格式打乱、行间距变大，字体变大、不好看：
<img width="672" alt="Screen Shot 2021-01-30 at 14 15 05" src="https://user-images.githubusercontent.com/7878120/106349046-a5a56b80-6305-11eb-9bc7-a0bb384701e1.png">

在`ucasthesis`模版附录部分使用`listings`插入代码，代码特殊字符识别不准，字符、行间距大，不好看：
<img width="672" alt="Screen Shot 2021-01-30 at 14 15 24" src="https://user-images.githubusercontent.com/7878120/106349072-d4234680-6305-11eb-8ab9-ae38e44b00f2.png">

## 最小工作示例(MWE)

要插入的代码（路径命名`Code/test.sh`）：
```
#!/bin/tcsh

set subjs = "$argv[2-]"

# process all subjs
foreach subj ( $subjs )
    # create a run.afni_proc script in this directory
    cat > run.afni_proc.$subj.stdsurf.noblur.${argv[1]} << EOF
    afni_proc.py -subj_id $subj.stdsurf.noblur.${argv[1]}                   \
        -blocks tshift align volreg surf scale regress                      \
        -copy_anat $subj_outdir/anat/T1w.nii.gz                             \
        -dsets $subj_indir/func/r0?.nii.gz                                  \
        -surf_anat $subj_surfdir/${subj}_SurfVol.nii                        \
        -surf_spec $subj_surfdir/std.141.${subj}_?h.spec                    \
        -tcat_remove_first_trs 2
EOF
# EOF denotes the end of the run.afni_proc command

    # now run the analysis (generate proc and execute)
    tcsh run.afni_proc.$subj.stdsurf.noblur.${argv[1]}
    
# end loop over subjs
end
```

从单独文件使用`minted`插入代码（编译：`pdflatex -shell-escape -output-directory=Tmp Tex/test.tex`）：
```
\documentclass{article}
\usepackage[outputdir=Tmp]{minted}

\begin{document}
\inputminted[fontsize=\scriptsize, frame=single, linenos, stepnumber=5]{tcsh}{Code/test.sh}
\end{document}
```
附录：
```
\chapter{Test} 
\lstinputlisting[language=csh, caption={}]{Code/test.sh}

\inputminted[fontsize=\scriptsize, frame=single, linenos, stepnumber=5]{tcsh}{Code/test.sh}
```

**Comment by muzimuzhi** [comment]
`ucasthesis` 把 `\texttt{...}/\ttfamily` 也定义成 times 字体了，可以用 `text \texttt{text} text {\ttfamily text}` 复现问题。
https://github.com/mohuangrui/ucasthesis/blob/5ea69e8debd01294b7f14be3a443b72026d83b2b/Style/artratex.sty#L357-L364

根据 https://github.com/mohuangrui/ucasthesis/issues/303#issuecomment-717225727 ，维护者的意见是维持不变。你可以自己定义一个等宽字族并在抄录环境里设置它。例如，使用 Latin Modern Mono，
```tex
% 建议放在 preamble
\newfontfamily\verbtt{Latin Modern Mono}[NFSSFamily=verbtt]

\fvset{codes*={\linespread{1}\selectfont}} % 恢复单倍行距
\setminted{fontfamily=verbtt} % 使用等宽字族
```

**Comment by Youguang** [comment]
@muzimuzhi 

谢谢回复

> % 建议放在 preamble

preamble是哪里呢？我试着放在`artratex.sty`，编译时报`! Package fontspec Error: The font "Latin Modern Mono" cannot be found.` 查了一下好像跟系统有关，编译环境是Mac Big Sur。自己不会解决，能再详细说一下吗？

**Comment by muzimuzhi** [comment]
> 我不太明白`preamble`指的是哪里

https://www.overleaf.com/learn/latex/Creating_a_document_in_LaTeX#The_preamble_of_a_document

> [...] 编译时报`! Package fontspec Error: The font "Latin Modern Mono" cannot be found.` 查了一下好像跟系统有关，编译环境是Mac OS。

[《[LaTeX 引擎] XeLaTeX + macOS，通过字体名调用发行版字体》](https://zhuanlan.zhihu.com/p/59774395)

> 但是边框不知道为啥不是一个完整的方框了，求解。

提供一个能复现问题的完整例子。不想手动粘贴了。

**Comment by Youguang** [comment]
> 提供一个能复现问题的完整例子。不想手动粘贴了。

```
\documentclass{article}
\usepackage[outputdir=Tmp]{minted}
\usepackage{fancyvrb}
\fvset{codes*={\linespread{1}\selectfont}} %single line space
\setminted{
    fontsize=\scriptsize, 
    linenos, 
    stepnumber=5,
    breaklines,
    frame=single
}

\begin{document}
\inputminted{tcsh}{Code/test.sh}
\end{document}
```

<img width="696" alt="Screen Shot 2021-02-02 at 13 00 46" src="https://user-images.githubusercontent.com/7878120/106554693-dd572200-6556-11eb-9e76-04d7b7bfa756.png">

跟设置字体无关，跟设置单倍行距有关，不设置单倍行距没有这个问题。

**Comment by muzimuzhi** [comment]
我之前给的通过 `\fvset{codes*={...}}` 调整行距的方式不对，这个 hook 被使用的时间太晚了。这里用 `minted` 的选项 `baselinestretch=1` 就好。

简化后的例子
```tex
\documentclass{article}
\RequirePackage{minted}
\fvset{codes*={\linespread{1}\selectfont}}
\setminted{frame=single}

\begin{document}
\begin{minted}{text}
text
text
\end{minted}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/106646699-ff898800-65c8-11eb-92d0-081f73563be8.png)

用 `baselinestretch=1` 的例子
```tex
\documentclass{article}
\usepackage{minted}
\usepackage{lipsum}

\setminted{
    baselinestretch=1,
    frame=single
}
\linespread{1.2}

\begin{document}
\lipsum[2]
\begin{minted}{tex}
text
text
\end{minted}
\lipsum[2]
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/106647479-f3ea9100-65c9-11eb-9dfd-b25c0e3d3aeb.png)


------
> 好像是[`fancyvrb `](https://github.com/gpoore/minted/issues/242#issuecomment-532480799)的问题。

是两个问题。

**Comment by Youguang** [comment]
@muzimuzhi 

能解释一下这里为什么选择用`baselinestretch=1`不用`fontsize=\linespread{1}\scriptsize`吗？

**Comment by muzimuzhi** [comment]
> 能解释一下这里为什么选择用 `baselinestretch=1` 不用 `fontsize=\linespread{1}\scriptsize` 吗？

@Youguang 从 `fancyvrb.sty` 的实现看，在最终效果上没差别。只是 `baselinestretch` 这个 key 的名字更贴合「调整行距」。把所有的字体设置都写在 `fontsize=<code>` 里也是可以的，甚至看起来更简单：
```tex
\newfontfamily\verbtt{Latin Modern Mono}
\setminted{
    fontsize=\verbtt\linespread{1}\scriptsize,
    frame=single
}
```
