### ISSUE TITLE
TexLive2020编译书脊模板成功，编译ucasthesis出现undefined control sequence \begin{document}错误

### ISSUE THREAD

**Issue by LorrainsBox** [mohuangrui/ucasthesis#325]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
最开始是用Tex Live 2018编译时出现缺少XITS字体的问题，于是干脆更新到2020，用TexLive2020编译书脊模板成功，编译ucasthesis出现undefined control sequence \begin{document}错误，tlmgr也更新过了，网上搜索后也没找到有效的方法

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/5952482/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![SharedScreenshot](https://user-images.githubusercontent.com/6948338/107390041-40861d00-6b32-11eb-97b3-8bd2d82b361d.jpg)

**Comment by muzimuzhi** [comment]
是 `hyperref` v7.00h 更新导致的，具体原因还不清楚。

临时方案：执行 `tlmgr restore hyperref 57623` 回退到前一个版本的 `hyperref`。

------
附：从 `Thesis.log` 抽取的具体报错信息
```tex
! Undefined control sequence.
\ucas@value@ch@title ...学学位论文\LaTeX {}模板 {$~^{\pi 
                                                  }\pi ^{\pi }$}
l.55 \begin{document}
                     
? 
```
在 texstudio 里点 "Log File" 也能定位到具体报错信息。
![image](https://user-images.githubusercontent.com/6376638/107442833-a98d8500-6b72-11eb-83cb-89ab8a060bd5.png)

**Comment by LorrainsBox** [comment]
![hyerref restore](https://user-images.githubusercontent.com/6948338/107926293-7ef75e00-6fb0-11eb-908b-0ad081ea2f5e.jpg)

似乎无法回滚，不过我看到hyperref更新到v7.00j了，更新之后编译成功啦~感谢 ♡
