### ISSUE TITLE
在使用pandoc将Thesis.tex文件转docx时遇到报错

### ISSUE THREAD

**Issue by jiangyoufeng** [mohuangrui/ucasthesis#326]
## 描述问题 / Problem Description

问题描述: 在使用pandoc将Thesis.tex文件转docx时在“documentclass[twoside]{Style/ucasthesis}”中遇到报错。

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![image](https://user-images.githubusercontent.com/75768465/107872670-cf09ee00-6ee6-11eb-8704-16cdaff3a5f9.png)

**Comment by mohuangrui** [comment]
pandoc可能无法处理多层结构的tex文档，即使最终可以，也很难处理好带数学公式和图文混排的tex对word的转换。

建议走将tex生成的pdf转成word的途径。但无论哪一条途径，都没有完美的方案。
