### ISSUE TITLE
页眉设置

### ISSUE THREAD

**Issue by L-rookie** [mohuangrui/ucasthesis#328]
奇数页页眉显示为章节标题，偶数页页眉显示为论文标题。请问如何解决？

**Comment by muzimuzhi** [comment]
如果我没看错的话，模板现在就是这样的。

**Comment by L-rookie** [comment]
好的，谢谢您！我之前看错了。发自我的华为手机-------- 原始邮件 --------发件人： muzimuzhi <notifications@github.com>日期： 2021年2月18日周四 19:15收件人： mohuangrui/ucasthesis <ucasthesis@noreply.github.com>抄送： rookieveteran <zhangyingjie@iie.ac.cn>, Author <author@noreply.github.com>主    题： Re: [mohuangrui/ucasthesis] 页眉设置 (#328)

如果我没看错的话，模板现在就是这样的。
