### ISSUE TITLE
在Frontinfo.tex中的\title中加入$$公式报错

### ISSUE THREAD

**Issue by cnforChina** [mohuangrui/ucasthesis#329]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ ] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x ] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ 2020] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
在Frontinfo.tex中的\title中加入$$公式报错，比如$a$,报错信息 为  ：

Frontmatter.tex:8: Undefined control sequence. [\MAKETITLE]
Frontmatter.tex:8: Extra }, or forgotten \endgroup. [\MAKETITLE]

删掉 $a$ 之后即可编译正常。 
奇怪的是，在另外一台电脑上(同样是win10, texlive 2020)尝试却没有报错.
请问这可能是什么导致的呢？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/6009158/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![2021-02-19_180618](https://user-images.githubusercontent.com/24601147/108490782-1674ed80-72de-11eb-85b4-875d816b9e8a.png)

## 最小工作示例(MWE) / Minimal Working Example 

Frontinfo.tex中 将title设置如下:
\title{$a$}

**Comment by muzimuzhi** [comment]
> 奇怪的是，在另外一台电脑上(同样是win10, texlive 2020)尝试却没有报错.

在 `\begin{document}` 前加入 `\listfiles`，在 `\title` 中不包含 `$a$` 时编译，把 `.log` 末尾的版本信息复制粘贴过来。在两台电脑上分别这样做，就能看到版本差异。

**Comment by cnforChina** [comment]
你好，得到的两个版本的log文件如下所示。

在\title加$a$能编译成功的电脑上，\begin{document} 前加入 \listfiles，\title 中不包含 $a$ 时编译 得到的log文件:
[Add_listfiles_on_PC_Succeed$a.log](https://github.com/mohuangrui/ucasthesis/files/6014117/Add_listfiles_on_PC_Succeed.a.log)
\title加$a$编译失败的电脑上得到的log文件:
[Add_listfiles_on_PC_failed$a.log](https://github.com/mohuangrui/ucasthesis/files/6014119/Add_listfiles_on_PC_failed.a.log)

**Comment by cnforChina** [comment]
不知道是不是由于failed掉的那台电脑上texlive部分包 未更新到最新所导致的。
正在尝试更换成国内源，升级一下。看看后面是否还有这个问题。

**Comment by mohuangrui** [comment]
@cnforChina 仔细看看模板样例是怎么给的？
```
\title{中国科学院大学学位论文\LaTeX{}模板 {$~^{\pi}\pi^{\pi}$}}% 论文中文题目
```

**Comment by cnforChina** [comment]
需要单独加{} ?  thanks,我试试看
不过为什么在另一台电脑上就可以呢？

**Comment by mohuangrui** [comment]
具体原因很难得知，重点是使用 `{$ math $}` 形式解决问题即可。

**Comment by cnforChina** [comment]
后来尝试更新完所有的宏包后，没有加{}, 问题解决了。
