### ISSUE TITLE
具体格式

### ISSUE THREAD

**Issue by brightlee-china** [mohuangrui/ucasthesis#33]
@mohuangrui。你的这个最新版本好像和今年的有些不一样，包括标题下划线，英文字体，行间距等。能不能改个完整的版本。细节调整真的是非常麻烦。

**Comment by mohuangrui** [comment]
我现在手头上就有3个版本的官方要求，标题下划线有的有有的没有，行间距有的1.5有的1.2。你要是真嫌麻烦，你倒是提供下所谓的官方要求是什么啊？

对于英文字体，拜托你能读一下模板使用说明文档么？在你问的一个编译的iissues里，我已经说了多少次请读下说明文档了？

**Comment by mohuangrui** [comment]
我再次对模板进行了更新，行距采用1.2，段前后距离改回原来的更为正确的设定，如果你需要1.5倍行距，请阅读使用说明，修改很简单，而且我已调试过了，不会影响到不该改变的地方。若再有其他建议，请在反馈时能将修改要求直接描述清楚，这样大家都省时间，多谢。
