### ISSUE TITLE
公式太长需要换行

### ISSUE THREAD

**Issue by lovecp3** [mohuangrui/ucasthesis#333]
你好呀，感谢提供的LaTeX模板。由于我有的公式太长，需要换行写，用了split环境，但编号出现了问题，没有三个小数点了。如图
![捕获](https://user-images.githubusercontent.com/40683684/110762112-6ca8d100-828b-11eb-820d-f8d34f83e0a0.PNG)

**Comment by lovecp3** [comment]
@mohuangrui

**Comment by muzimuzhi** [comment]
提功能复现问题的完整例子。

**Comment by lovecp3** [comment]
\begin{equation}
\adddotsbeforeeqnnum
Tr_k=\rho_0-1+I^0+D_0-\frac{1}{\bar{\rho}}-(\frac{\bar{\rho}\bar{I}}{\bar{D}}+\eta)k^2
\label{trk}
\end{equation}
上面这段是刚刚截图的3.24式子

\begin{align}
\Delta_k = &\frac{1}{\bar{\rho}}(1-\rho_0)-I^0-D_0-k^2(-\frac{\eta}{\bar{\rho}}+\eta I^0+\eta D_0+\frac{\rho_0\bar{\rho}\bar{I}}{\bar{D}}+\frac{\bar{\rho}\bar{I}}{\bar{D}}+\frac{I^0\bar{\rho}^2}{\bar{D}}\notag\\
&+\frac{D_0\bar{\rho}^2}{\bar{D}})+\frac{\eta\bar{\rho}\bar{I}}{\bar{D}}k^4.\label{deltak}
\end{align}
这段是用align环境换行的，效果就是截图的3.25式子

\begin{equation}
\begin{split}
\Delta_k = &\frac{1}{\bar{\rho}}(1-\rho_0)-I^0-D_0-k^2(-\frac{\eta}{\bar{\rho}}+\eta I^0+\eta D_0+\frac{\rho_0\bar{\rho}\bar{I}}{\bar{D}}+\frac{\bar{\rho}\bar{I}}{\bar{D}}+\frac{I^0\bar{\rho}^2}{\bar{D}}\notag\\
&+\frac{D_0\bar{\rho}^2}{\bar{D}})+\frac{\eta\bar{\rho}\bar{I}}{\bar{D}}k^4.\label{deltak}
\end{split}
\end{equation}
这段是用split环境换行的，效果就是没有编号

**Comment by daliang16** [comment]
\begin{equation}
\adddotsbeforeeqnnum
\begin{split}
\Delta_k = &\frac{1}{\bar{\rho}}(1-\rho_0)-I^0-D_0-k^2(-\frac{\eta}{\bar{\rho}}+\eta I^0+\eta D_0+\frac{\rho_0\bar{\rho}\bar{I}}{\bar{D}}+\frac{\bar{\rho}\bar{I}}{\bar{D}}+\frac{I^0\bar{\rho}^2}{\bar{D}}\notag\
&+\frac{D_0\bar{\rho}^2}{\bar{D}})+\frac{\eta\bar{\rho}\bar{I}}{\bar{D}}k^4.\label{deltak}
\end{split}
\end{equation}

**Comment by lovecp3** [comment]
\begin{equation}
\adddotsbeforeeqnnum
\begin{split}
\Delta_k = &\frac{1}{\bar{\rho}}(1-\rho_0)-I^0-D_0-k^2(-\frac{\eta}{\bar{\rho}}+\eta I^0+\eta D_0+\frac{\rho_0\bar{\rho}\bar{I}}{\bar{D}}+\frac{\bar{\rho}\bar{I}}{\bar{D}}+\frac{I^0\bar{\rho}^2}{\bar{D}}\notag\\
&+\frac{D_0\bar{\rho}^2}{\bar{D}})+\frac{\eta\bar{\rho}\bar{I}}{\bar{D}}k^4.\label{deltak}
\end{split}
\end{equation}
采用这段代码，虽然加了\adddotsbeforeeqnnum，但没编号。如图
![捕获](https://user-images.githubusercontent.com/40683684/110766021-b693b600-828f-11eb-9ee1-6740369f1801.PNG)

**Comment by lovecp3** [comment]
谢谢，已解决。需要把\notag去掉=.=，这样编号就在两行的中间了
![捕获](https://user-images.githubusercontent.com/40683684/110766697-679a5080-8290-11eb-8c2a-adabb9fa6943.PNG)

**Comment by muzimuzhi** [comment]
1. 建议发完整的例子，带 `\documentclass` 和 `document` 环境
2. 建议把代码标记为 code，见 https://guides.github.com/features/mastering-markdown
3. 试试用 `\begin{aligned}[b]` 代替 `\begin{split}`

**Comment by lovecp3** [comment]
好的，谢谢~已解决
