### ISSUE TITLE
模板无法输入 摄氏度符号 即： ℃   只显示一个小方框。

### ISSUE THREAD

**Issue by bujianbusan** [mohuangrui/ucasthesis#334]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

Missing character: There is no ℃ in font [XITS-Regular.otf]/OT:script=latn;lang
uage=dflt;mapping=tex-text;!

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![image](https://user-images.githubusercontent.com/19358640/111245342-72ae0180-863f-11eb-81c3-c08858fe08f9.png)

**Comment by muzimuzhi** [comment]
像是字体缺字。在 log 文件里搜 `missing character` 应该看到具体的错误信息。

可以用 `36 \textcelsius` 输入 "36 摄氏度"。如果特别关注量和单位之间的空距，可以使用 siunitx 宏包的 `\SI{36}{\celsius}`。

**Comment by zhanglinbo** [comment]
我这样写的，36~$^{\circ}$C.
正常显示！

**Comment by bujianbusan** [comment]
log文件里确实显示是字体缺字，不是textcomp宏包的问题，但\textcelsius依然显示小方框，会有更好的办法么？

**Comment by muzimuzhi** [comment]
> 不是textcomp宏包的问题，但\textcelsius依然显示小方框，会有更好的办法么？

提供完整例子

**Comment by mohuangrui** [comment]
> log文件里确实显示是字体缺字，不是textcomp宏包的问题，但\textcelsius依然显示小方框，会有更好的办法么？

@bujianbusan  建议采用 @zhanglinbo  的输入方式，就我的经验，我都是使用$^{\circ}$，没有任何问题。
