### ISSUE TITLE
中文参考文献，没有按照作者首字母排序

### ISSUE THREAD

**Issue by LKN321** [mohuangrui/ucasthesis#336]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [x] CTeX

## 描述问题 / Problem Description

问题描述：
中文参考文献，没有按照作者首字母排序

感谢您的解答！！！
## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![参考文献](https://user-images.githubusercontent.com/50196585/111407090-50cf8000-870e-11eb-9614-802600eea716.jpg)
![参考文献2](https://user-images.githubusercontent.com/50196585/111407213-7b213d80-870e-11eb-9ac3-02f4713efd33.jpg)

**Comment by mohuangrui** [comment]
https://github.com/mohuangrui/ucasthesis/wiki/文献样式#著者-出版年制authoryear模式下中文参考文献排序

重复问题   https://github.com/mohuangrui/ucasthesis/issues/247

**Comment by LKN321** [comment]
感谢回信！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mohuangrui/ucasthesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 晚上8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mohuangrui/ucasthesis] 中文参考文献，没有按照作者首字母排序 (#336)





 
https://github.com/mohuangrui/ucasthesis/wiki/文献样式#著者-出版年制authoryear模式下中文参考文献排序
 
重复问题   #247
