### ISSUE TITLE
！TeX capacity exceeded, sorry [input stack size=5000].

### ISSUE THREAD

**Issue by Young398** [mohuangrui/ucasthesis#339]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live <2020>
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
插入参考文献后，总是显示：
！TeX capacity exceeded, sorry [input stack size=5000].
\hyper@normalise ->\begingroup \catcode `\^^M
                                             \active \def ^^M{ }\catcode `\%...
l.215 ...-3-642-37006-9{\textunderscore}, \doi{}5}
通过更改texmf.cnf容量，结果无效。
在起初插入几个参考文献试验的时候，全编译后是正常的，也可以通过。后来插入的参考文献多了以后，出现了上述问题。
我怀疑是导入到ref.bib的名称里有特殊字符，更改后依然无效。
！TeX capacity exceeded, sorry [input stack size=5000].下放的描述我看不懂，第一次用LaTex。麻烦可以解答一下。
谢谢

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/6160612/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![image](https://user-images.githubusercontent.com/80864669/111558424-b0d72c80-87c9-11eb-8a81-0e03dad8e2ea.png)

## 最小工作示例(MWE) / Minimal Working Example 

例如：海水营养盐为河口、沿海和大洋等水体生态系统提供了重要的支撑，是海洋水文和生物地球化学等海洋学研究的基础\citet{ITTEKKOT.2000, Ma.2016}。
这一句在插入参考文献试验的时候是可以的，一切显示正常。但是后来参考文献插入多了以后，一直出现这样的问题。一直显示eX capacity exceeded, sorry [input stack size=5000].

**Comment by muzimuzhi** [comment]
提供的信息不足。提供能复现问题的完整例子，或检查 bib 文件内容，关注有没有未 escape 的特殊符号。

**Comment by Young398** [comment]
> 提供的信息不足。提供能复现问题的完整例子，或检查 bib 文件内容，关注有没有未 escape 的特殊符号。


谢谢回复。通过我的调试，发现问题是在一个书的章节的引用中，也就是incollection的引用中。
去掉该引用即可顺利编译通过，加上就会出现上述问题。
该incollection引用如下：
@incollection{Cleary.2013,
 author = {Cleary, J. and Maher, D. and Diamond, D.},
 title = {Development and Deployment of a Microfluidic Platform for Water Quality Monitoring},
 pages = {125--148},
 volume = {4},
 publisher = {{Springer Berlin Heidelberg}},
 isbn = {978-3-642-37005-2},
 series = {Smart Sensors, Measurement and Instrumentation},
 editor = {Mukhopadhyay, Subhas C. and Mason, Alex},
 booktitle = {Smart Sensors for Real-Time Water Quality Monitoring},
 year = {2013},
 address = {Berlin, Heidelberg},
 doi = {10.1007/978-3-642-37006-9{\textunderscore }6}
}

通过与chap_guide中的如下的incollection对比，发现内容无缺少：
@incollection{chen1980zhongguo,
    author       = {陈晋镳 and 张惠民 and 朱士兴 and 赵震 and
        王振刚},
    key          = {Chen Jing Ao Zhang Hui Ming Zhu Shi Xing Zhao Zhen Wang Zhen Gang},
    title        = {蓟县震旦亚界研究},
    editor       = {中国地质科学院天津地质矿产研究所},
    booktitle    = {中国震旦亚界},
    address      = {天津},
    publisher    = {天津科学技术出版社},
    year         = {1980},
    pages        = {56--114},
}
请问你能看出我引文中该incollection的问题吗？
麻烦你了。

**Comment by Young398** [comment]
> 提供的信息不足。提供能复现问题的完整例子，或检查 bib 文件内容，关注有没有未 escape 的特殊符号。

是doi的格式问题，doi中出现了{\textunderscore }这个表达。我把doi删了就可以了。

**Comment by mohuangrui** [comment]
@Young398 既然开始没问题，后来插入文献多了出现了问题，那就很可能是文献的问题。

根据你刚提供的信息，建议：

1. 移除 doi = {10.1007/978-3-642-37006-9{\textunderscore }6}，特别是 \textunderscore会是个大问题。
2. 移除 Cleary.2013 中的 点号，这些用来引用的 label 尽量不要弄特殊字符。
3. publisher = {{Springer Berlin Heidelberg}}, 我不知道这种双括号意义在哪，有何影响。
4. 是isbn很可能多余，且可能无法识别。isbn = {978-3-642-37005-2},

**Comment by muzimuzhi** [comment]
> 2\. 移除 Cleary.2013 中的 点号，这些用来引用的 label 尽量不要弄特殊字符。

无关。label name 是置于 `\csname ... \endcsname` 中的，可以接受大部分字符。



> 3\. publisher = {{Springer Berlin Heidelberg}}, 我不知道这种双括号意义在哪，有何影响。

猜是为了保留大小写不被修改
