### ISSUE TITLE
conference 类型的论文在参考文献列表中的引用格式有问题

### ISSUE THREAD

**Issue by jdhao** [mohuangrui/ucasthesis#34]
# 问题描述
对于 conference 类型的论文，生成的参考文献，题目与会议名称之间不是 dot，变成了两个 back slash，怀疑是使用的 `gt7714-unsrt.bst` 的原因。具体生成的错误参考文献见[这里](https://ibb.co/eJHi7n).

# 复现步骤
在 `ref.bib` 文件中加入一个会议论文的 bib 引用，如下面的条目
```
@inproceedings{Philbin2007ObjectRW,
  title={Object retrieval with large vocabularies and fast spatial matching},
  author={James Philbin and Ondrej Chum and Michael Isard and Josef Sivic and Andrew Zisserman},
  booktitle={2007 IEEE Conference on Computer Vision and Pattern Recognition},
  year={2007},
  pages={1--8}
}
```

然后在 tex 文件中引用该论文，如在 `Chap_Guide.tex` 文件中引用该论文，然后重新运行 `artratex.bat` 生成 pdf，即可看到这个错误。

**Comment by Youguang** [comment]
@mohuangrui  @jdhao 

我也遇到了这个问题，没有会议名称是两个反斜杠，请问怎么解决？

```
@inproceedings{Irfanoglu2017,
   author = {Irfanoglu, Mustafa Okan and Nayak, Amritha and Jenkins, Jeffrey and Pierpaoli, Carlo},
   title = {{TORTOISE} v3: Improvements and new features of the {NIH} diffusion {MRI} processing pipeline},
   journal = {{ISMRM} Annual Meeting. Hawaii, {USA}},
   pages = {3540},
   year = {2017},
   type = {Conference Proceedings}
}
```




<img width="767" alt="ref" src="https://user-images.githubusercontent.com/7878120/105146030-72f7b800-5b3a-11eb-9935-987a98ae769c.png">

**Comment by jdhao** [comment]
sorry， 我忘了当时怎么解决的了。 我猜应该是修改引用风格的某个 separator 的风格，对于这个例子，应该是文章类型 (`[C]`) 和年份 (`2017`) 之间的分隔符的样式。

**Comment by Youguang** [comment]
@jdhao  感谢🙏

改了`gbt7714-author-year.bst` 中：`FUNCTION {bbl.slash} { ". \allowbreak " }`之后的效果：

<img width="767" alt="ref2" src="https://user-images.githubusercontent.com/7878120/105152633-65dec700-5b42-11eb-914d-eae5634b3a8f.png">

另外，这里显示的页码实际是摘要的编号，这样可以吗？
