### ISSUE TITLE
国科大2021年学位模板的一些改变

### ISSUE THREAD

**Issue by Jasonhz** [mohuangrui/ucasthesis#341]
国科大在2021年上线了一个学位论文格式自动检测系统（目前仅支持word版本论文的检测），同时也提供了一个论文格式的指导意见文件，见附件。
[中国科学院大学研究生学位论文撰写规范指导意见.docx](https://github.com/mohuangrui/ucasthesis/files/6195703/default.docx)

经对照，似乎发现当前模板和这个指导意见有所不同：
1、纸张大小：模板设定146.6mm×246.2mm，文件要求210mm×297mm
2、正文行间距：模板设定1.6，文件要求1.5
3、页眉页脚距页边界：模板设定10.4mm，文件要求1.5cm
4、左、右：模板设定6.3mm，文件要求3.17cm
5、章节标题：段前：模板设定7pt，文件要求24磅
6、一级节标题：段前：模板设定12pt，文件要求24磅

供作者参考，谢谢！经询问学位办，采用latex编译的论文，可通过线下审核，无需转为word版本。

**Comment by mohuangrui** [comment]
@Jasonhz  LaTeX 不是 Word，两者参数并非一一对应，LaTeX参数的设定和计算也并非你看到的那么简单。
如果想测试当前的参数设定，你可以把模板打出来，并和word打出来的对比，或者花时间真正弄懂那些参数意味着什么，最终转换后得到的是什么。

**Comment by benkwoook** [comment]
> 
> 
> 国科大在2021年上线了一个学位论文格式自动检测系统（目前仅支持word版本论文的检测），同时也提供了一个论文格式的指导意见文件，见附件。
> [中国科学院大学研究生学位论文撰写规范指导意见.docx](https://github.com/mohuangrui/ucasthesis/files/6195703/default.docx)
> 
> 经对照，似乎发现当前模板和这个指导意见有所不同：
> 1、纸张大小：模板设定146.6mm×246.2mm，文件要求210mm×297mm
> 2、正文行间距：模板设定1.6，文件要求1.5
> 3、页眉页脚距页边界：模板设定10.4mm，文件要求1.5cm
> 4、左、右：模板设定6.3mm，文件要求3.17cm
> 5、章节标题：段前：模板设定7pt，文件要求24磅
> 6、一级节标题：段前：模板设定12pt，文件要求24磅
> 
> 供作者参考，谢谢！经询问学位办，采用latex编译的论文，可通过线下审核，无需转为word版本。

师兄你好，请问你说的线下审核是指所有研究所都可以交给国科大线下审核吗

**Comment by Jasonhz** [comment]
> > 国科大在2021年上线了一个学位论文格式自动检测系统（目前仅支持word版本论文的检测），同时也提供了一个论文格式的指导意见文件，见附件。
> > [中国科学院大学研究生学位论文撰写规范指导意见.docx](https://github.com/mohuangrui/ucasthesis/files/6195703/default.docx)
> > 经对照，似乎发现当前模板和这个指导意见有所不同：
> > 1、纸张大小：模板设定146.6mm×246.2mm，文件要求210mm×297mm
> > 2、正文行间距：模板设定1.6，文件要求1.5
> > 3、页眉页脚距页边界：模板设定10.4mm，文件要求1.5cm
> > 4、左、右：模板设定6.3mm，文件要求3.17cm
> > 5、章节标题：段前：模板设定7pt，文件要求24磅
> > 6、一级节标题：段前：模板设定12pt，文件要求24磅
> > 供作者参考，谢谢！经询问学位办，采用latex编译的论文，可通过线下审核，无需转为word版本。
> 
> 师兄你好，请问你说的线下审核是指所有研究所都可以交给国科大线下审核吗

其它研究所的情况我不了解。不过去年毕业用latex写论文的学生最后在答辩时仍被要求修改格式的。个人感觉学校这一关没有问题，但不同学院可能要求程度有所差异。

**Comment by benkwoook** [comment]
师兄你是本部的吗？请问在京研究所的学生怎么线下审核论文格式呢？谢谢

发自我的iPhone

**Comment by Jasonhz** [comment]
> 师兄你是本部的吗？请问在京研究所的学生怎么线下审核论文格式呢？谢谢 发自我的iPhone
> […](#)
> 在 2021年9月24日，上午12:06，Jasonhz ***@***.***> 写道： ﻿ 国科大在2021年上线了一个学位论文格式自动检测系统（目前仅支持word版本论文的检测），同时也提供了一个论文格式的指导意见文件，见附件。 中国科学院大学研究生学位论文撰写规范指导意见.docx 经对照，似乎发现当前模板和这个指导意见有所不同： 1、纸张大小：模板设定146.6mm×246.2mm，文件要求210mm×297mm 2、正文行间距：模板设定1.6，文件要求1.5 3、页眉页脚距页边界：模板设定10.4mm，文件要求1.5cm 4、左、右：模板设定6.3mm，文件要求3.17cm 5、章节标题：段前：模板设定7pt，文件要求24磅 6、一级节标题：段前：模板设定12pt，文件要求24磅 供作者参考，谢谢！经询问学位办，采用latex编译的论文，可通过线下审核，无需转为word版本。 师兄你好，请问你说的线下审核是指所有研究所都可以交给国科大线下审核吗 其它研究所的情况我不了解。不过去年毕业用latex写论文的学生最后在答辩时仍被要求修改格式的。个人感觉学校这一关没有问题，但不同学院可能要求程度有所差异。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我是本部。研究所的情况不太了解，不好意思。请咨询研究所相关老师。
