### ISSUE TITLE
图表标题中文献引用问题

### ISSUE THREAD

**Issue by cnforChina** [mohuangrui/ucasthesis#342]
## 检查 / Check

- [x ] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x ] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
在wiki中有下列表述
----
图表标题中的文献编号总排在前列
使用顺序编码制（numbers）或上标顺序编码制（super）时，若在图表标题中引用文献，因为表格列表和图形列表位于文档的最前列，从而标题中的文献编号也会排在前列。如想改变此行为，可使用

\caption[出现在列表中的标题]{标题 \citep{xxx}}
\bicaption[出现在列表中的标题]{中文标题 \citep{xxx}}{英文标题\citep{xxx}}
-----
想问一下如果标题中不同位置存在多个引用的话，如何设置呢？ 
能否给个简单的示例？ 谢谢

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by muzimuzhi** [comment]
正常写就好，`\caption[出现在列表中的标题]{标题 \citep{xxx} 文字 \citep{yyy}}`

**Comment by cnforChina** [comment]
谢谢。
试了好几次，终于明白了。 []里面放的是出现在目录里列表的标题，后面{}放的是正文中列表的标题。
wiki里表述可以再清晰一些。

**Comment by muzimuzhi** [comment]
这是通用的 latex 使用的知识，模板文档很难全部覆盖。否则模板文档的篇幅会膨胀到相当于 完整的latex入门教程 + 特定模板的教程。

**Comment by freemanxzx** [comment]
加了引用后，标题不居中了，有遇到这种情况的吗
