### ISSUE TITLE
同一页插入多张矢量图，除第一张图以外，其它图的字体均变粗了

### ISSUE THREAD

**Issue by cnforChina** [mohuangrui/ucasthesis#344]
## 检查 / Check

- [ ] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ ] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x ] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
遇到了跟 https://www.zhihu.com/question/265042553/answer/376489964
差不多的问题，即同一页面除第一张图外，其它的字体都变粗了，有些图例直接就糊掉了，很奇怪。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by cnforChina** [comment]
求助一下这个该如何解决呢？

**Comment by mohuangrui** [comment]
见 [图中文本渲染错误出现异常加粗](https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE#%E5%9B%BE%E4%B8%AD%E6%96%87%E6%9C%AC%E6%B8%B2%E6%9F%93%E9%94%99%E8%AF%AF%E5%87%BA%E7%8E%B0%E5%BC%82%E5%B8%B8%E5%8A%A0%E7%B2%97)

**Comment by cnforChina** [comment]
谢谢，我试试看
