### ISSUE TITLE
符号列表中的缩写如何添加一列中文解释？

### ISSUE THREAD

**Issue by jqbk** [mohuangrui/ucasthesis#346]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
符号列表中的缩写如何添加一列中文解释？试着按照字符来输入，但是最后一列是右对齐的，将`artratex.sty`中的
```
\providecommand{\nomenclatureitem}[3][ ]{%
    \noindent\makebox[0.15\textwidth][l]{#2}{{#3}\hfill{#1}}\par
}
```
修改为
```
\providecommand{\nomenclatureitem}[3][ ]{%
    \noindent\makebox[0.15\textwidth][l]{#2}\makebox[0.6\textwidth][l]{#3}{#1}\par
}
```
可以实现左对齐，但是对于较长的字符，仍需要使用如下方法对原条目进行拆解
```
\section*{缩写}
\nomenclatureitem[单传输载流子光电探]{UTC-PD}{Uni-Travelling Carrier Photo-Detector}
\nomenclatureitem[测器]{}{}
```
实现效果如下图所示，请问一下有没有更好的实现方法

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![微信截图_20210408154307](https://user-images.githubusercontent.com/23696676/113987650-3c038980-9881-11eb-9652-663244008374.png)

**Comment by mohuangrui** [comment]
见 [符号列表中，术语过长换行时文字缩进不对齐](https://github.com/mohuangrui/ucasthesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E7%AC%A6%E5%8F%B7%E5%88%97%E8%A1%A8%E4%B8%AD%E6%9C%AF%E8%AF%AD%E8%BF%87%E9%95%BF%E6%8D%A2%E8%A1%8C%E6%97%B6%E6%96%87%E5%AD%97%E7%BC%A9%E8%BF%9B%E4%B8%8D%E5%AF%B9%E9%BD%90-1)
以及 https://github.com/mohuangrui/ucasthesis/issues/146
