### ISSUE TITLE
论文长标题添加强制换行，页眉会跟随换行

### ISSUE THREAD

**Issue by jaredyam** [mohuangrui/ucasthesis#347]
## 问题描述
论文标题稍长，刚好在第二行多处几个字，所以我想通过添加强制换行换取封面页的美观，但页眉的标题内容也会随之改变。在这种情况下，我可能并不需要页眉按照同样形式进行换行，保持其原来的单行形式即可。

按照目前的页眉设置单行可以包含46个中文字符，封面页单行最长可以包含27个中文字符，所以在标题长度介于28到35之间会出现封面页标题两行内容长度明显不均的情况，而这种长度的标题大概率存在中间断点，可以进行强制换行。

## 截图示例
包含30个中文字符的标题，会在第二行稍微多出几个字：
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/50312506/114124765-bbe42f00-9927-11eb-9a9a-19398e14ff13.png">
其对应的页眉
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/50312506/114124808-d4ece000-9927-11eb-96a7-3d7db6abab9f.png">
这时标题中可能存在某种合适的断点
<img width="759" alt="image" src="https://user-images.githubusercontent.com/50312506/114124996-25fcd400-9928-11eb-80b7-98f92248cd50.png">
页眉也会按照同样形式变化
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/50312506/114125063-4b89dd80-9928-11eb-9e7a-ce87d6ac1251.png">

**Comment by mohuangrui** [comment]
```Tex
\title[给定出现在页眉中的标题内容]{默认标题内容}% 论文中文题目
```
