### ISSUE TITLE
中文标题页横线上的文字左右间距不一致

### ISSUE THREAD

**Issue by jqbk** [mohuangrui/ucasthesis#348]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live <2020>
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
中文标题页横线上的文字左右间距不一致，请问应该如何修改使文字在横线上居中呢？
注意到了 https://github.com/mohuangrui/ucasthesis/wiki/常见问题#为何封面下划线上的文本不居中下划线
想问下只能通过手动添加空格的方式进行调整么，**能否让文字右边测下划线短一些呢，如果可以的话，具体如何实现呢，谢谢！**

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![image](https://user-images.githubusercontent.com/23696676/115551434-a4b92000-a2dd-11eb-8688-ab5d97162bb3.png)

**Comment by mohuangrui** [comment]
下划线长度是和指导文件长度一致的，如果想自行调整，读 ucasthesis.cls 文件
