### ISSUE TITLE
标点符号出现在行首应该如何避免

### ISSUE THREAD

**Issue by jqbk** [mohuangrui/ucasthesis#350]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live <2020>
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
标点符号会出现在行首，请问这个如何才能避免呢

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![image](https://user-images.githubusercontent.com/23696676/118463040-e3ea5d80-b731-11eb-8368-16cfe07eb2cd.png)

**Comment by muzimuzhi** [comment]
需要一个具体例子。可以试试删掉 nm 和顿号之间的空格。

**Comment by jqbk** [comment]
> 需要一个具体例子。可以试试删掉 nm 和顿号之间的空格。

您好，我这边找到原因了，主要是使用了`siunitx`宏包并在`artracom.sty`中使用了`\newcommand{\nm}{\si{\nano\metre} }`，所以在正文中通过如下方法使用单位时会出现问题：`1310~{\nm}、`，现在把标点符号出现在行首的地方改成`1310~nm、`就可以了，不知道是否还有更好的办法，谢谢您！

**Comment by muzimuzhi** [comment]
> `\newcommand{\nm}{\si{\nano\metre} }`

问题出在这里的空格。我能理解为什么需要这个空格，但这里是它导致了在顿号前断行。不确定 `xspace` 宏包的 `\xspace` 在这里是否管用。缺乏具体的（完整的）例子，懒得测试。

另外，获得 "1310 nm" 的输出，可以使用 `siunitx` 提供的 `\SI` 命令，输入 `\SI{1310}{\nano\metre}` 或 `\SI{1310}{nm}` 均可。

**Comment by jqbk** [comment]
> > `\newcommand{\nm}{\si{\nano\metre} }`
> 
> 问题出在这里的空格。我能理解为什么需要这个空格，但这里是它导致了在顿号前断行。不确定 `xspace` 宏包的 `\xspace` 在这里是否管用。缺乏具体的（完整的）例子，懒得测试。
> 
> 另外，获得 "1310 nm" 的输出，可以使用 `siunitx` 提供的 `\SI` 命令，输入 `\SI{1310}{\nano\metre}` 或 `\SI{1310}{nm}` 均可。

谢谢您，加空格主要是想让单位前后的间距一致，问题也确实是出在了这个空格，但是由于`nm`这个单位以及其他单位如`GHz`使用得比较多，采用`\SI{1310}{\nano\metre}`或者`\SI{1310}{nm}`会显得比较繁琐，现在只在出现问题的地方使用`\SI{1310}{\nano\metre}`或者`\SI{1310}{nm}`即可解决问题。

**Comment by muzimuzhi** [comment]
> 但是由于`nm`这个单位以及其他单位如`GHz`使用得比较多，采用`\SI{1310}{\nano\metre}`或者`\SI{1310}{nm}`会显得比较繁琐

可以用 `\DeclareSIUnit` 定义新的（复合）单位，也可以先直接写 `1310 nm`，然后用正则替换。

**Comment by jqbk** [comment]
> 可以用 `\DeclareSIUnit` 定义新的（复合）单位，也可以先直接写 `1310 nm`，然后用正则替换。

好的，谢谢您~
