### ISSUE TITLE
提示 File `ctexbook.cls' not found. \@ifclasslater

### ISSUE THREAD

**Issue by HankerSia** [mohuangrui/ucasthesis#354]
## 检查 / Check

- [x ] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ ] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x ] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
File `ctexbook.cls' not found. \@ifclasslater

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/6974007/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![微信图片_20210812164539](https://user-images.githubusercontent.com/32951817/129167313-041c074b-4c0f-4ab5-84f8-63257800d302.png)

**Comment by sikouhjw** [comment]
```
kpsewhich ctexbook.cls
```
返回什么？

**Comment by HankerSia** [comment]
你好，问下我其他模版正常，这个编译不通过，试过更改编译器，查阅模版使用说明，均未发现此问题的解决方法，遂提问，谢谢！

**Comment by HankerSia** [comment]
> ```
> kpsewhich ctexbook.cls
> ```
> 
> 返回什么？

![image](https://user-images.githubusercontent.com/32951817/129168034-14dbb212-e8db-4603-8e34-3459d99bf6a3.png)

**Comment by sikouhjw** [comment]
> 
> 
> > ```
> > kpsewhich ctexbook.cls
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 返回什么？
> 
> ![image](https://user-images.githubusercontent.com/32951817/129168034-14dbb212-e8db-4603-8e34-3459d99bf6a3.png)

```tex
\documentclass{ctexbook}
\begin{document}
  test
\end{document}
```
编译试试？

**Comment by HankerSia** [comment]
@sikouhjw 你好，提示unfortunately the package ctex could not be installed.

**Comment by HankerSia** [comment]
@sikouhjw Hi! 一样的，提示没有那个文件
![image](https://user-images.githubusercontent.com/32951817/129170980-b11b65bf-693b-4d59-95ab-4cbfe0450266.png)
你有那个文件的话可以长传给我下 应该就可以

**Comment by sikouhjw** [comment]
> @sikouhjw Hi! 一样的，提示没有那个文件
> ![image](https://user-images.githubusercontent.com/32951817/129170980-b11b65bf-693b-4d59-95ab-4cbfe0450266.png)
> 你有那个文件的话可以长传给我下 应该就可以

请自行安装。miktex 如何安装宏包，请自行检索。


> 你好，问下我其他模版正常，这个编译不通过，试过更改编译器，查阅模版使用说明，均未发现此问题的解决方法，遂提问，谢谢！

现在看来，你所谓的「其他模板正常」是不包括 `ctex` 系列的。

**Comment by sikouhjw** [comment]
> @muzimuzhi 应该是上面兄台说的没装ctex。。我寻思这使用教程也没说要装什么前置包啊。。。

默认大家都是 texlive+完全安装，这是潜规则。

**Comment by HankerSia** [comment]
也可能我萌新没处理好texstudio 跟其他的包的路径问题 反正环境总感觉怪怪的

**Comment by muzimuzhi** [comment]
> 2021-08-12 16:50:50,429+0800 FATAL kpsewhich - The remote package repository is not registered. You have to choose another repository.
> 2021-08-12 16:50:50,429+0800 FATAL kpsewhich - Info: ="url="http://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/""

miktex 有自动安装包的功能，但是你遇到了无法安装的问题。查了，tuna 在 miktex package repositories 列表中 https://miktex.org/pkg/repositories 。打开 miktex console 重新选一下/选一个国内的其他镜像呢？

**Comment by mohuangrui** [comment]
mixtex一般可以自动安装缺失的宏包，初始使用时可能会弹出对话框，记得选择允许自动下载安装，别否决了。

如果不会安装编译环境，也可以使用overleaf，详见：

https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE#linuxoverleaf-%E7%B3%BB%E7%BB%9F%E7%9A%84%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE

问题很明确是的编译环境安装问题，因此关闭问题了。
