### ISSUE TITLE
英文摘要第二页页眉是中文

### ISSUE THREAD

**Issue by HankerSia** [mohuangrui/ucasthesis#355]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x ] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live <2021>
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
英文摘要部分如果超过一页，第二页页眉错误显示中文标题，应该要显示英文标题，请问怎么修改

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![image](https://user-images.githubusercontent.com/32951817/129823915-3a45b4a1-fb79-4788-8012-ea2f3bccb1f4.png)

**Comment by mohuangrui** [comment]
没听说过英文摘要页的页眉要换成英文标题。

如果你想，
1. 在https://github.com/mohuangrui/ucasthesis/blob/09ccc45827daf7831c60cf07fc32d5320db3ff87/Style/artratex.sty#L695
下面插入如下代码：
```Tex
    \fancypagestyle{enfrontmatterstyle}{% style for frontmatter
        \fancyhf{}% clear fields
        \fancyhead[C]{\footnotesize \ifnumodd{\value{page}}{\leftmark}{\ucas@value@en@title}}% structure elements
        \fancyfoot[C]{\footnotesize \thepage}% page number
        \renewcommand{\headrulewidth}{0.8pt}% header rule
        \renewcommand{\footrulewidth}{0pt}% footer rule
    }

```
2. 在
https://github.com/mohuangrui/ucasthesis/blob/09ccc45827daf7831c60cf07fc32d5320db3ff87/Tex/Frontmatter.tex#L26
下面插入代码：
```Tex
\pagestyle{enfrontmatterstyle}%
```
3. 在
https://github.com/mohuangrui/ucasthesis/blob/09ccc45827daf7831c60cf07fc32d5320db3ff87/Tex/Frontmatter.tex#L30
下面插入代码：
```Tex
\cleardoublepage\pagestyle{frontmatterstyle}%
```

**Comment by HankerSia** [comment]
@mohuangrui，非常感谢，上述方案已经测试成功。
P.S. 查了几个师兄、师姐的论文，确实是英文摘要页用英文标题。
