### ISSUE TITLE
如何改变bst文件，使得文中显示参考文献的所有作者为：A，B和C

### ISSUE THREAD

**Issue by Cindy2022** [mohuangrui/ucasthesis#357]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：请教一下，使用\citet*{} 想显示所有作者，但是不希望显示为A，B and C，而是希望显示为A，B和C。

已善用搜索，搜到类似的问题如下：
https://github.com/mohuangrui/ucasthesis/issues/44

但是其中的回复：
“那个 and 要改的话只能你自己手动去修改 Biblio 里的 bst 文件了，或者可以考虑求助 zepinglee <https://github.com/zepinglee>/gbt7714-bibtex-style <https://github.com/zepinglee/gbt7714-bibtex-style> 。 至于authoryear的样式，规范就是不加序号的，因为用authoryear必须是通过author来索引而不是序号，这也是authoryear的目的。
”
上面的两个链接无法打开，导致不知道该如何修改 Biblio 里的 bst 文件，所以只好请教一下，感谢！

补充一下，调用的是super的样式
\usepackage[super,list]{Style/artratex}

**Comment by sikouhjw** [comment]
`gbt7714` 转到了 CTeX-org 这里：https://github.com/CTeX-org/gbt7714-bibtex-style

**Comment by mohuangrui** [comment]
关于 gbt7714 文献和引用样式的问题，请前往：https://github.com/CTeX-org/gbt7714-bibtex-style 需求帮助，我不熟悉bst的规则，难以帮上忙

**Comment by Cindy2022** [comment]
> `gbt7714` 转到了 CTeX-org 这里：https://github.com/CTeX-org/gbt7714-bibtex-style

好的，感谢告知！

**Comment by Cindy2022** [comment]
> 关于 gbt7714 文献和引用样式的问题，请前往：https://github.com/CTeX-org/gbt7714-bibtex-style 需求帮助，我不熟悉bst的规则，难以帮上忙

谢谢大神百忙之中给予解答！

**Comment by mohuangrui** [comment]
忘记biblatex确实可以很轻松的实现你的要求。具体操作见：

https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#biblatex-%E5%90%AF%E7%94%A8

记得采用正确的编译方式：biber而非bibtex。然后记得修改默认的最大作者显示数目。

**Comment by mohuangrui** [comment]
对了，使用biblatex时，无需使用 \citet*{}，而是直接用 \citet{}
