### ISSUE TITLE
参考文献不是按顺序编号，求帮助

### ISSUE THREAD

**Issue by uoyevoli** [mohuangrui/ucasthesis#358]
我使用了这个命令编译，
\usepackage[super, list]{Style/artratex}

但
编译出的文件参考文献的顺序并不是从1开始，我的是从11，12这样乱序编号的，比如我想实现第一个被 引用的文献序号是1，这样怎么解决呢？例如unsrt这样的顺序，wiki中没有提及这个问题，求帮助

**Comment by mohuangrui** [comment]
https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E5%9B%BE%E8%A1%A8%E6%A0%87%E9%A2%98%E4%B8%AD%E7%9A%84%E6%96%87%E7%8C%AE%E7%BC%96%E5%8F%B7%E6%80%BB%E6%8E%92%E5%9C%A8%E5%89%8D%E5%88%97

**Comment by uoyevoli** [comment]
已经解决了，谢谢
我用VScode编译的，只要把编译生成的中间文件全删掉，重新编译之后顺序就对了
