### ISSUE TITLE
研究单位名称过长导致封面空间不足的问题

### ISSUE THREAD

**Issue by KaifengC** [mohuangrui/ucasthesis#36]
![image](https://user-images.githubusercontent.com/13186802/37264295-7ea81a18-25e7-11e8-9c37-646bf5e7cf52.png)

如图所示，在更新后的模板上，当研究单位名称较长的时候，指导教师一栏的居中将出现问题。
请问有何解决方案？

**Comment by mohuangrui** [comment]
请阅读使用说明常见问题第8条：如需要调整文本在下划线上的位置,可用 \hspace{+/- n.0em} 命令来插入
或删除 n 个空格,进行手动调整。
比如 \advisor{\hspace{+/- 3.0em}黄。。。}

**Comment by Ricemeal** [comment]
> 
> 
> 请阅读使用说明常见问题第8条：如需要调整文本在下划线上的位置,可用 \hspace{+/- n.0em} 命令来插入
> 或删除 n 个空格,进行手动调整。
> 比如 \advisor{\hspace{+3.0em}黄。。。}

你好，版主，建议在第8条里增加：可以调整ucasthesis.cls文件中152行中“\newcommand{\ulextend}[2][250pt]{% extend underline length”中的250pt，更改下划线长度。
