### ISSUE TITLE
UCAS-Logo更新

### ISSUE THREAD

**Issue by hotchilipowder** [mohuangrui/ucasthesis#360]
[上一个版本的logo](https://github.com/mohuangrui/ucasthesis/blob/a098ea3eb367e2535f0abe55b870ee25ff543e2c/Img/ucas_logo.pdf)的“圆不圆”。

查找了一圈，官网给出了Ai的文件。 可以直接从官网下载原版Ai的图，然后用Ai导出就可以了。

https://www.ucas.edu.cn/site/11?zu=64925

[ucas-logo.pdf](https://github.com/mohuangrui/ucasthesis/files/7385619/ucas-logo.pdf)
看看如果我传的这个版本OK的话，请更新一下～

**Comment by hotchilipowder** [comment]
区别点

<img width="1404" alt="区别" src="https://user-images.githubusercontent.com/11959047/138208393-28203c7e-d7ec-4880-b1dc-9b329ea185f6.png">

**Comment by mohuangrui** [comment]
好的，谢谢，等有必要时，将更新
