### ISSUE TITLE
如何设置参考文献带编号(引用也带编号)+按字母排序？

### ISSUE THREAD

**Issue by XYYYLRRH** [mohuangrui/ucasthesis#361]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [x] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
参考文献，学校要求要有编号（引用时也是带编号），但是要按照字母排序，如下图所示。
请问如何设置？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![1](https://user-images.githubusercontent.com/25168873/138717716-9d72ee62-3685-427b-a10e-65d53cb1802f.jpg)
![2](https://user-images.githubusercontent.com/25168873/138717972-f4025090-9e44-4b73-9142-59b9fe89b726.jpg)

**Comment by mohuangrui** [comment]
你可以看看如下信息，对于这种特殊格式，我所能帮的就这么多了

https://tex.stackexchange.com/questions/161097/sorting-references-in-both-number-and-alphabetic-manner

https://tex.stackexchange.com/questions/373569/bibliography-first-name-sorting
