### ISSUE TITLE
关于盲审设置的打开

### ISSUE THREAD

**Issue by song-heng** [mohuangrui/ucasthesis#362]
作者，您好，我已经用您的模板把论文排版好，在答辩申请的时候，需要提交盲审格式（隐去论文封面中的学生姓名、导师姓名，发表文章目录、论文致谢部分 PDF格式），我搜索了下，当时2017年4月的时候Style/ucasthesis.cls 有个UCAS@mangshentrue可以设置盲审模式，但是现在新版本没有了， 我想问下如何开启盲审模式，谢谢作者啦

**Comment by mohuangrui** [comment]
建议手动删除需要去除的信息，这样更能满足不同人的需求。
