### ISSUE TITLE
`\ulextend` 的默认参数可以再次传入么？

### ISSUE THREAD

**Issue by muzimuzhi** [mohuangrui/ucasthesis#363]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

@e71828 在
 - https://github.com/mohuangrui/ucasthesis/issues/190#issuecomment-974813905

提问

> 我有个问题 `\ulextend{##1}` 的默认参数可以再次传入么？

因为问题和原 issue 无关，我代为开一个新 issue。

**Comment by muzimuzhi** [comment]
我没理解「默认参数可以再次传入么」的意思。现在 `\ulextend` 的定义是
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L158-L160
支持的用法为
```tex
\ulextend{要添加下划线的内容}  % 相当于 \ulextend[350pt]{要添加下划线的内容}
\ulextend[200pt]{要添加下划线的内容}
```

想修改的是哪个默认参数？

**Comment by e71828** [comment]
我说的是`350pt`

我是看这个[问题](https://tex.stackexchange.com/a/42464)想到的

**Comment by muzimuzhi** [comment]
通过可选参数 `\ulextend[...]{...}` 可以指定想要的值（和 350pt 相同或不同均可），重定义 `\ulextend` 才可以修改使用 `\ulextend{...}` 时的默认行为。以上都和 `##1` 这种用法无关，因为都不涉及 "nested macro definitions"。

你提到的「再次传入」，我猜是指修改 `\ulextend{...}` 的默认行为。不能靠「传入」修改，必须重定义 `\ulextend`。

**Comment by e71828** [comment]
是的，说了这么多，才终于达成了一致的理解。 致上遗憾与抱歉，请关闭这个 issue 吧。
