### ISSUE TITLE
如何添加生僻字

### ISSUE THREAD

**Issue by akonnerr** [mohuangrui/ucasthesis#365]
我导师的名字有棡字，但是无法显示，这个有什么好的解决办法吗，对latex不太熟悉，麻烦作者解答一下，感激万分！

**Comment by sikouhjw** [comment]
```tex
\documentclass[fontset=fandol]{ctexart}
\begin{document}
  棡
\end{document}
```
fandol 确实没有这个字，请你查看 [字体配置](https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE) 自行设置字体。

**Comment by mohuangrui** [comment]
@akonnerr Windows/Mac系统应该不会有问题，如果使用的 Linux，需[配置字体](https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE#linuxoverleaf-%E7%B3%BB%E7%BB%9F%E7%9A%84%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE)
