### ISSUE TITLE
如何取消已“正式接受论文”列表前面的缩进

### ISSUE THREAD

**Issue by masterLZ** [mohuangrui/ucasthesis#366]
- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`]
## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 10

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 2020

## 描述问题 / Problem Description
问题描述：在当前模板下如果添加自己发表的论文，会自动加入一个缩进如图所示
![image](https://user-images.githubusercontent.com/9996628/153537396-5ec1ebac-4db8-4f07-bb6b-e7d87f16fe24.png)

但是学校模板要求不能有缩进，类似于下图所示
![image](https://user-images.githubusercontent.com/9996628/153537543-2c14b7b8-c9ad-4cd3-91f7-04f5d8116d9b.png)

我尝试使用\noindent指令进行取消缩进，但是没有效果，请问该如何处理这个问题？

**Comment by sikouhjw** [comment]
在 group 内加上
```tex
\setlist[enumerate]{wide=0pt}
```

**Comment by masterLZ** [comment]
> 

谢谢，如果仅仅设置`wide=0pt`,会取消悬挂缩进，最后在group内加上了
`\setlist[enumerate]{wide=0pt,leftmargin=1.6em}`
后解决了
