### ISSUE TITLE
macOS下如何把CJK字体替换为仿宋？

### ISSUE THREAD

**Issue by zhongwei-yao** [mohuangrui/ucasthesis#368]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live  2020
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

如实实现正文中文字体为仿宋，切标题仿宋加粗，生成的PDF可复制加粗字体。修改[ucasthesis.cls](https://github.com/mohuangrui/ucasthesis/blob/ba430959717dee840d1e07045309d28dd8c414b6/Style/ucasthesis.cls#L672-L690)文件中的字体后，标题无法加粗。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
<img width="681" alt="image" src="https://user-images.githubusercontent.com/42103822/154832617-2b338878-26ab-4580-acbc-8723c185d7fb.png">

**Comment by sikouhjw** [comment]
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L430-L437
加个伪粗
```tex
\setCJKmainfont{STFangsong}[AutoFakeBold]
```

**Comment by zhongwei-yao** [comment]
> https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L430-L437
> 
> 
> 加个伪粗
> ```
> \setCJKmainfont{STFangsong}[AutoFakeBold]
> ```

这个针对正文文本加粗了，但是标题好像还是没能加粗。

**Comment by sikouhjw** [comment]
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L607-L619
你需要的是全文仿宋还是正文 + `\chapter` 仿宋？

1. 全文就把 CJK 全部设成仿宋
2. `\chapter` 就加上
    ```
    \ctexset { 
      chapter = { 
          format = \linespread{1.0}\zihao{4}\bfseries\centering, 
          nameformat = {}, 
          titleformat = {}, 
          number = \arabic{chapter}, 
          numberformat = \rmfamily, 
          aftername = \quad, 
          beforeskip = {7pt}, 
          afterskip = {18pt}, 
          pagestyle = plain, 
      } 
    }
    ```

**Comment by zhongwei-yao** [comment]
> https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L607-L619
> 
> 
> 你需要的是全文仿宋还是正文 + `\chapter` 仿宋？
> 1. 全文就把 CJK 全部设成仿宋
> 2. `\chapter` 就加上
>    ```
>    \ctexset { 
>      chapter = { 
>          format = \linespread{1.0}\zihao{4}\bfseries\centering, 
>          nameformat = {}, 
>          titleformat = {}, 
>          number = \arabic{chapter}, 
>          numberformat = \rmfamily, 
>          aftername = \quad, 
>          beforeskip = {7pt}, 
>          afterskip = {18pt}, 
>          pagestyle = plain, 
>      } 
>    }
>    ```

谢谢你的解决方案！是正文 + \chapter 仿宋，已经实现了。
