### ISSUE TITLE
自定义模板—如何将标题"第1章  绪论"更改"1  绪论"并左对齐

### ISSUE THREAD

**Issue by zhongwei-yao** [mohuangrui/ucasthesis#369]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
- 1. 如何将标题"第1章  绪论"更改"1  绪论"
- 2. 如何将Mainmatter中的chapter设置成左对齐而不是居中？但是Frontmatter中的"目录"和"摘要"等标题仍然居中。我尝试将`ucathesis.cls`中的`\ctexset{chapter={format=...\centering,...}}`修改成`\ctexset{chapter={format=...\raggedright,...}}`但是Frontmatter中的"目录"和"摘要"等标题也会变成左对齐。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by muzimuzhi** [comment]
> 1. 如何将标题"第1章  绪论"更改"1  绪论"

`\ctexset{chapter/name={}}`

> * 2. 如何将Mainmatter中的chapter设置成左对齐而不是居中？但是Frontmatter中的"目录"和"摘要"等标题仍然居中。我尝试将`ucathesis.cls`中的`\ctexset{chapter={format=...\centering,...}}`修改成`\ctexset{chapter={format=...\raggedright,...}}`但是Frontmatter中的"目录"和"摘要"等标题也会变成左对齐。

在 `\mainmatter` 之后，添加 `\ctexset{chapter/format={...\raggedright...}}`。如果能确保所有不编号的章名都左对齐，还可以用 `\ctexset{chapter={format=...\CTEXifname{\centering}{\raggedright}}}`。

PS：如果需求来自同一学校不同学院的规定，可以提供具体规定原文，然后模板进行适配，以便利其他使用者。

**Comment by zhongwei-yao** [comment]
谢谢您提供的方法和建议@muzimuzhi ，我是外校的学生，但很喜欢这个项目^_^
