### ISSUE TITLE
itemsize自然段起始缩进

### ISSUE THREAD

**Issue by Jong-Won** [mohuangrui/ucasthesis#37]
你好，请问itemsize中每个item中的自然段如何设置缩进呢？

谢谢

**Comment by Jong-Won** [comment]
找到问题答案

https://tex.stackexchange.com/questions/240278/how-to-indent-a-new-paragraph-within-items

使用
\begin{enumerate}[listparindent=\parindent]

**Comment by mohuangrui** [comment]
你好，根据国科大本科部陆晴老师和学位办老师的核对沟通后，item的缩进规定为只有第一行缩进，所以你的设定似乎将不符合规定。请查看更新后的ucasthesis的当前设定。

**Comment by Jong-Won** [comment]
谢谢，我已经update了。格式很好！
