### ISSUE TITLE
参考文献中的//是否必要，包括会议的[C]//  专著的 [M]//

### ISSUE THREAD

**Issue by Loneseven** [mohuangrui/ucasthesis#370]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
参考文献中的//，包括会议的[C]//  专著的 [M]//，这些//默认出现在本模板的生成结果中，但一位国科大老师在讲行文规范时提到，多年前的论文中从未见到有该//。经查阅GB7714—87参考文献著录规则，未见//的示例？所以该//是否必要？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by mohuangrui** [comment]
文献样式基于 [GB/T 7714—2015](http://www.cessp.org.cn/uploads/1/file/public/201607/20160708142456_8mqgu0dpgk.pdf) 

如要修改参考文献列表的默认排版行为，如去掉 [M] 见： https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E4%BF%AE%E6%94%B9%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%88%97%E8%A1%A8%E7%9A%84%E9%BB%98%E8%AE%A4%E6%8E%92%E7%89%88%E8%A1%8C%E4%B8%BA 

更多个性化设定可自行配置bst文件，见 ：
https://github.com/zepinglee/gbt7714-bibtex-style

**Comment by nizhenliang** [comment]
想去掉会议论文参考文献中的//，该怎么设置

**Comment by mohuangrui** [comment]
如要修改参考文献列表的默认排版行为，如去掉 [M] 见： https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E4%BF%AE%E6%94%B9%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%88%97%E8%A1%A8%E7%9A%84%E9%BB%98%E8%AE%A4%E6%8E%92%E7%89%88%E8%A1%8C%E4%B8%BA 

可以测试一下相关选项，即将一些选项前的 `#1` 改为 `#0`
