### ISSUE TITLE
图形列表和表格列表行距问题

### ISSUE THREAD

**Issue by tuyanglin** [mohuangrui/ucasthesis#371]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
图形列表和表格列表的行距问题，每一章的图表行距一样，但是章与章之间突然宽了很多，能否全部一致呢

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
<img width="323" alt="3070adbee13a76948e2738446512318" src="https://user-images.githubusercontent.com/40054702/155507629-34cae5f5-ba36-4f88-b70a-085cdfa3a1b5.png">

<img width="329" alt="e1b3ca819039bc9bda04e74ebb919c0" src="https://user-images.githubusercontent.com/40054702/155507617-2fa23aa8-8cf3-4f57-8a6f-8045e50020fb.png">

**Comment by tuyanglin** [comment]
今天又仔细找了下原来的提问，找到了以前的解决方法，方法如下
在 \begin{document} 之前添加

> \ctexset{
  % 默认值都是是 `10pt`
  chapter/lofskip=0pt,
  chapter/lotskip=0pt
}

**Comment by tshu-w** [comment]
ctexset 不太行
如果不想 `\renewcommand*{\addvspace}[1]{}` 可以
```latex
\captionsetup{figurewithin=none,tablewithin=none}
```
