### ISSUE TITLE
参考文献引用问题，把和、等改为and、et al.后不显示逗号

### ISSUE THREAD

**Issue by tuyanglin** [mohuangrui/ucasthesis#372]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
overleaf操作，xelatex 2020/2021都试过，启用了biber
我根据wiki的操作，把ucasthesis.cfg的“和”、“等” 改为 "and"、"et al."后，et al和年份之间没有逗号，没改之前会出现逗号，只修改了cfg后就不出现。 不过只有两个以内的作者会显示逗号。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![image](https://user-images.githubusercontent.com/40054702/155650910-69452546-7030-4084-8f72-dc07d3a5db62.png)

**Comment by hushidong** [comment]
```
\def\ucas@label@ch@bibetal{et al.\isdot}
\def\ucas@label@en@bibetal{et al.\isdot}
\def\ucas@label@ch@biband{ and }
\def\ucas@label@en@biband{ and }
```
注意其中添加的\isdot

**Comment by tuyanglin** [comment]
> 
已经解决了，非常感谢。

**Comment by tuyanglin** [comment]
> ```
> \def\ucas@label@ch@bibetal{et al.\isdot}
> \def\ucas@label@en@bibetal{et al.\isdot}
> \def\ucas@label@ch@biband{ and }
> \def\ucas@label@en@biband{ and }
> ```
> 
> 注意其中添加的\isdot



> ```
> \def\ucas@label@ch@bibetal{et al.\isdot}
> \def\ucas@label@en@bibetal{et al.\isdot}
> \def\ucas@label@ch@biband{ and }
> \def\ucas@label@en@biband{ and }
> ```
> 
> 注意其中添加的\isdot

你好，刚刚发现有个问题，这样操作的话，在最后的参考文献中也会有这个逗号。
![1645780577(1)](https://user-images.githubusercontent.com/40054702/155688651-21281ed0-d9f6-43ca-ab3b-5e7abfb96d4c.jpg)

**Comment by tuyanglin** [comment]
补充下，在启用biblatex 出现该问题，用bibtex 正常

**Comment by hushidong** [comment]
biblatex修改这里：

```
    \DefineBibliographyStrings{english}{%
        andincite         = {\biband},
        andothersincite   = {\bibetal{}},
        andincitecn       = {\biband},
        andothersincitecn = {\bibetal\isdot},
    }
```



因为这样的定义
```
\def\bibetal{\ucas@label@ch@bibetal}
\def\biband{\ucas@label@ch@biband}
```
但这个\bibetal实际是用在著录表中的信息的，所以对于biblatex来说，若需要修改修改引用标注中的，那么需要修改
```
    \DefineBibliographyStrings{english}{%
        andincite         = {\biband},
        andothersincite   = {\bibetal{}},
        andincitecn       = {\biband},
        andothersincitecn = {\bibetal\isdot},
    }
```
为避免修改著录表，那么直接修改这里。
biblatex因为高度的可定义性，所以不写死，有各种修改的方式和可能。

可以参考：https://github.com/hushidong/biblatex-gb7714-2015/blob/master/egthesis/thesis-ucas-m.tex
