### ISSUE TITLE
摘要之后的目录内容和图形列表内容的加黑效果能去掉吗，谢谢

### ISSUE THREAD

**Issue by ghost** [mohuangrui/ucasthesis#373]
## 检查 / Check

- [x ] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x ] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x ] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX
2020
## 描述问题 / Problem Description

问题描述：
摘要之后的目录内容和图形列表内容的加黑效果能去掉吗，谢谢

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by mohuangrui** [comment]
加黑效果是指“加粗”还是“黑体”？

摘要之后的目录内容和图形列表内容并没有“加粗”，但使用的是“黑体”。如需修改，见：

https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L683

https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L703

https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L721

其中 `\sffamily` 代表调用了黑体。

**Comment by ghost** [comment]
> 加黑效果是指“加粗”还是“黑体”？
> 
> 摘要之后的目录内容和图形列表内容并没有“加粗”，但使用的是“黑体”。如需修改，见：
> 
> https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L683
> 
> https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L703
> 
> https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L721
> 
> 其中 `\sffamily` 代表调用了黑体。

按照您的意见已成功修改，谢谢您

**Comment by mohuangrui** [comment]
不客气
