### ISSUE TITLE
复杂编译windows bib->xe报错： ERROR - Cannot find 'Thesis.bcf'!

### ISSUE THREAD

**Issue by guangminglftg** [mohuangrui/ucasthesis#374]
win10
按照视频https://www.bilibili.com/video/BV19v411j71N?spm_id_from=333.337.search-card.all.click安装

## 描述问题 / Problem Description
复杂编译windows bib->xe报错：
ERROR - Cannot find 'Thesis.bcf'!

但是使用简单编译不会报错且生成了pdf

**Comment by mohuangrui** [comment]
抱歉无法提供与个人相关的debug服务
