### ISSUE TITLE
如何实现Bib正文为author-year文末为numbered排列

### ISSUE THREAD

**Issue by zhongwei-yao** [mohuangrui/ucasthesis#375]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

如何在文本中使用author-year形式的citation: Jones (1995); 括号: (Jones, 1995)。

同时，文末的参考文献前有序号:

[1] Jones, 1995. 
[2] Paul, ...

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by hushidong** [comment]
biblatex这边，目前使用如下方法最方便(虽然使用标注样式和著录样式分开设置也可以)：
```

\documentclass[twoside]{article}
\usepackage{ctex}
\usepackage{xcolor}
\usepackage[colorlinks=true,citecolor=blue!75!black]{hyperref}
\usepackage[backend=biber,style=gb7714-2015ay,gbalign=gb7714-2015]{biblatex}



\begin{filecontents}{\jobname.bib}

@Article{Walls2013-399-418,
  Title                    = {drought, deluge and declines: the impact of precipition extremes on amphibians in a changing climate},
  Author                   = {Walls, S C and barichivich, W. J. and BROWN, m. e.},
  Journal                  = {Biology},
  Number                   = {1},
  Pages                    = {399-418},
  Volume                   = {2},
  Url                      = {http://www.mdpi.com},
  Urldate                  = {2013-11-04},
  Year                     = {2013},
  doi                      = {10.3390/biology2010399}
}

@Article{Zhang2007-500-503,
  Title                    = {The design and experimental investigations of supersonic length shorted nozzle},
  Author                   = {Zhang, Min Li and Yi, Shi He and Zhao, Yu Xin},
  Journal                  = {ACTA AERODYNAMICA SINICA},
  Number                   = {4},
  Pages                    = {500-503},
  Volume                   = {25},
  Year                     = {2007},
  nameformat={quanpin},
}

@Book{Yi2013--,
  Title                    = {Supersonic and hypersonic nozzle design},
  Address                  = {Beijing},
  Author                   = {Yi, Shi He and Zhao, Yu Xin and He, Lin and Zhang, Min Li},
  Publisher                = {National Defense Industry Press},
  Year                     = {2013},
  nameformat={quanpin},
}

@Archive{中国第一历史档案馆2001--,
  author    = {中国第一历史档案馆 and 辽宁省档案馆},
  title     = {中国明朝档案总汇},
  year      = {2001},
  address   = {桂林},
  publisher = {广西师范大学出版社},
}

@Www{萧钰2001--,
  Title                    = {出版业信息化迈入快车道},
  Author                   = {萧钰},
  Url                      = {http://www.creader.com/news/20011219/200112190019.html},
  Urldate                  = {2002-04-15},
  Date                     = {2001-12-19}
}




\end{filecontents}

\addbibresource{\jobname.bib}
%\addbibresource{example.bib}

\begin{document}


文献\citet{Walls2013-399-418,Zhang2007-500-503,Yi2013--,中国第一历史档案馆2001--,萧钰2001--}

文献\citep{Walls2013-399-418,Zhang2007-500-503,Yi2013--,中国第一历史档案馆2001--,萧钰2001--}

\printbibliography


\end{document} 
```

结果为：
![图片](https://user-images.githubusercontent.com/20421795/156472732-e591530f-2b35-4d65-a8e2-0143c0ca5c47.png)

**Comment by zhongwei-yao** [comment]
按照@[hushidong](https://github.com/hushidong)的方法，我在artratex.sty这个文件做了如下修改：

<img width="1634" alt="image" src="https://user-images.githubusercontent.com/42103822/156483872-97002dee-4bd8-4ccc-b43e-b2510e0bfbae.png">

并在正文中启用了`\usepackage[biber,authoryear,list]{Style/artratex}`，但是文末参考文献还是没能实现number
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/42103822/156484187-b240d6ff-c0ed-42fe-ad9c-4b0cfb535f0e.png">

能帮忙看看是哪里出了问题嘛？

**Comment by hushidong** [comment]
gbalign选择直接写选项名。
gbalign 选项 ：right， left， center， gb7714-2015， gb7714-2015ay.

**Comment by zhongwei-yao** [comment]
请问是这样吗？`\RequirePackage[backend=biber,style=\artxbiberauy,gbalign=gb7714-2015,mincitenames=1,maxcitenames=2]{biblatex}`
好像参考文献还是没有标号。

**Comment by hushidong** [comment]
更新一下biblatex-gb7714-2015

换其它选也行的，比如：gbalign=right

**Comment by zhongwei-yao** [comment]
非常感谢，更新了之后实现了！
