### ISSUE TITLE
生成的pdf论文怎么查重

### ISSUE THREAD

**Issue by freemanxzx** [mohuangrui/ucasthesis#376]
现在pdf版本的论文查重很麻烦，会检测出很多乱码，无法有效查重，转化成word文件也很多乱码，再重新排版一次word代价太大了，有谁有啥好办法么？

**Comment by reizercraft** [comment]
我也在思考相同的问题，除此以外还有一个**论文格式审查系统**，这个系统只接受word版上传。如果转换的话，也许可以试一试[pandoc](https://www.pandoc.org/)？

将tex转docx：

```bash
pandoc mythesis.tex -o mythesis.docx
```

可以指定使用的word模板：

```bash
pandoc mythesis.tex --reference-doc=ucas_template.docx mythesis.docx
```

转换的结果还算差强人意，标题、正文和公式没问题。小毛病挺多，包括但不限于所有编号和引用都没了，用tabular画的表格报错（注释掉后能转换了），algorithm不支持（不报错，转换出来是平铺的文本）。编号和引用的问题好像是有解决方案的，可以试试[这个](https://www.jianshu.com/p/dc62b915920e)。

不知道这样能否被系统接受，如果有测试结果望告知。

**Comment by freemanxzx** [comment]
Error at "Thesis.tex" (line 14, column 15):
unexpected [
\documentclass[twoside]{Style/ucasthesis}%

转换不成功，提示上述错误

**Comment by freemanxzx** [comment]
> 我也在思考相同的问题，除此以外还有一个**论文格式审查系统**，这个系统只接受word版上传。如果转换的话，也许可以试一试[pandoc](https://www.pandoc.org/)？
> 
> 将tex转docx：
> 
> ```shell
> pandoc mythesis.tex -o mythesis.docx
> ```
> 
> 可以指定使用的word模板：
> 
> ```shell
> pandoc mythesis.tex --reference-doc=ucas_template.docx mythesis.docx
> ```
> 
> 转换的结果还算差强人意，标题、正文和公式没问题。小毛病挺多，包括但不限于所有编号和引用都没了，用tabular画的表格报错（注释掉后能转换了），algorithm不支持（不报错，转换出来是平铺的文本）。编号和引用的问题好像是有解决方案的，可以试试[这个](https://www.jianshu.com/p/dc62b915920e)。
> 
> 不知道这样能否被系统接受，如果有测试结果望告知。

Error at "Thesis.tex" (line 14, column 15):
unexpected [
\documentclass[twoside]{Style/ucasthesis}%

转换不成功，提示上述错误

**Comment by reizercraft** [comment]
> > 我也在思考相同的问题，除此以外还有一个**论文格式审查系统**，这个系统只接受word版上传。如果转换的话，也许可以试一试[pandoc](https://www.pandoc.org/)？
> > 将tex转docx：
> > ```shell
> > pandoc mythesis.tex -o mythesis.docx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以指定使用的word模板：
> > ```shell
> > pandoc mythesis.tex --reference-doc=ucas_template.docx mythesis.docx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 转换的结果还算差强人意，标题、正文和公式没问题。小毛病挺多，包括但不限于所有编号和引用都没了，用tabular画的表格报错（注释掉后能转换了），algorithm不支持（不报错，转换出来是平铺的文本）。编号和引用的问题好像是有解决方案的，可以试试[这个](https://www.jianshu.com/p/dc62b915920e)。
> > 不知道这样能否被系统接受，如果有测试结果望告知。
> 
> Error at "Thesis.tex" (line 14, column 15): unexpected [ \documentclass[twoside]{Style/ucasthesis}%
> 
> 转换不成功，提示上述错误

复现了，找不到解决方法。我是拿IEEE模板做的转换测试，没有遇到这个问题。

**Comment by freemanxzx** [comment]
> > > 我也在思考相同的问题，除此以外还有一个**论文格式审查系统**，这个系统只接受word版上传。如果转换的话，也许可以试一试[pandoc](https://www.pandoc.org/)？
> > > 将tex转docx：
> > > ```shell
> > > pandoc mythesis.tex -o mythesis.docx
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 可以指定使用的word模板：
> > > ```shell
> > > pandoc mythesis.tex --reference-doc=ucas_template.docx mythesis.docx
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 转换的结果还算差强人意，标题、正文和公式没问题。小毛病挺多，包括但不限于所有编号和引用都没了，用tabular画的表格报错（注释掉后能转换了），algorithm不支持（不报错，转换出来是平铺的文本）。编号和引用的问题好像是有解决方案的，可以试试[这个](https://www.jianshu.com/p/dc62b915920e)。
> > > 不知道这样能否被系统接受，如果有测试结果望告知。
> > 
> > 
> > Error at "Thesis.tex" (line 14, column 15): unexpected [ \documentclass[twoside]{Style/ucasthesis}%
> > 转换不成功，提示上述错误
> 
> 复现了，找不到解决方法。我是拿IEEE模板做的转换测试，没有遇到这个问题。

不过格式检查似乎不是必须的，选择性的

**Comment by lengluodefanhua** [comment]
> > > > 我也在思考相同的问题，除此以外还有一个**论文格式审查系统**，这个系统只接受word版上传。如果转换的话，也许可以试一试[pandoc](https://www.pandoc.org/)？
> > > > 将tex转docx：
> > > > ```shell
> > > > pandoc mythesis.tex -o mythesis.docx
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 可以指定使用的word模板：
> > > > ```shell
> > > > pandoc mythesis.tex --reference-doc=ucas_template.docx mythesis.docx
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 转换的结果还算差强人意，标题、正文和公式没问题。小毛病挺多，包括但不限于所有编号和引用都没了，用tabular画的表格报错（注释掉后能转换了），algorithm不支持（不报错，转换出来是平铺的文本）。编号和引用的问题好像是有解决方案的，可以试试[这个](https://www.jianshu.com/p/dc62b915920e)。
> > > > 不知道这样能否被系统接受，如果有测试结果望告知。
> > > 
> > > 
> > > Error at "Thesis.tex" (line 14, column 15): unexpected [ \documentclass[twoside]{Style/ucasthesis}%
> > > 转换不成功，提示上述错误
> > 
> > 
> > 复现了，找不到解决方法。我是拿IEEE模板做的转换测试，没有遇到这个问题。
> 
> 不过格式检查似乎不是必须的，选择性的

如果格式审查不通过 没办法提交到导师那里。。。

**Comment by mohuangrui** [comment]
1. 关于PDF字体乱码的问题，请看： [Windows 系统编译得到的 PDF 无法拷贝文本](https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE#windows-%E7%B3%BB%E7%BB%9F%E7%BC%96%E8%AF%91%E5%BE%97%E5%88%B0%E7%9A%84-pdf-%E6%97%A0%E6%B3%95%E6%8B%B7%E8%B4%9D%E6%96%87%E6%9C%AC)，也就是说，乱码的问题是可以不存在的，前提是采取了正确的措施。
2. 至于格式审查只能用word，这点我不清楚，还需更多了解详情及解决办法的人帮忙解答。LaTeX 转 Word 本身非一件容易的事情，pandoc可以处理好文本的问题，但对图、表、复杂公式等往往存在困难。最好的解决知道，应是保证能使用 PDF。

**Comment by Sundrops** [comment]
@freemanxzx @mpraiser @lengluodefanhua 求问下各位大佬如何解决：论文格式审查系统需要word的问题？我用ilovepdf转的word乱码比较严重

**Comment by reizercraft** [comment]
@Sundrops 我们是latex写的线下格式审查，可以咨询一下相关负责的老师

**Comment by Sundrops** [comment]
> @Sundrops

@mohuangrui 好的 谢谢
