### ISSUE TITLE
关于学位论文模板的3个问题

### ISSUE THREAD

**Issue by ghost** [mohuangrui/ucasthesis#377]
## 检查 / Check

- [ x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x ] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ x2020] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
1. 想将页码调整到页脚中间；
2. 想让“证明”两字与“定理”两字的字体一致， 同时将“证明”两字在段首空两个；
3. 中文参考文献在正文中用“和”， “等”这样的术语， 英文参考文献在正文中用“and”， “et.al ”这样的术语.

尝试多次不能解决，麻烦您可以帮帮我吗， 非常感谢您的帮助哈.

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by mohuangrui** [comment]
1. 见 #367 
2. 在 [ctex 文档](https://mirrors.bfsu.edu.cn/CTAN/language/chinese/ctex/ctex.pdf) 中搜索 “证明” 两字，可查到到设定命令
3. 见 [wiki: 将英文引用中的 “和”、“等” 改为 "and"、"et al."](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E5%B0%86%E8%8B%B1%E6%96%87%E5%BC%95%E7%94%A8%E4%B8%AD%E7%9A%84-%E5%92%8C%E7%AD%89-%E6%94%B9%E4%B8%BA-andet-al)
