### ISSUE TITLE
如何调整目录页码的字体和大小？

### ISSUE THREAD

**Issue by SAMTRONG** [mohuangrui/ucasthesis#379]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
师兄你好，国科大发的“研究生学位论文撰写规范指导意见”里面目录里面的条目确实大小不一样，但是页码的大小是保持一致的。求问这个需要怎么改呢？

## 问题截图 / Screenshots
![Inked页码_LI](https://user-images.githubusercontent.com/64763714/162747671-b994f0e4-8808-4efe-aa21-b99c57e0de5d.jpg)

![页码](https://user-images.githubusercontent.com/64763714/162747617-720b9a1e-029f-4039-b382-bd3ad2c8e8ab.png)

**Comment by mohuangrui** [comment]
你好，目录的设定位于：
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L658

你仔细读下说明，找到 page number 对应的位置，然后在其位置前面加上
```
\zihao{4}
```
即可
