### ISSUE TITLE
\ctexset error

### ISSUE THREAD

**Issue by yoookoo** [mohuangrui/ucasthesis#38]
ctex版本2.9，在编译Thesis.tex会出现 undefined control sequence，报错显示在
\ctexset {
    chapter = {
        format = \linespread{1.0}\zihao{4}\bfseries\sffamily\centering,
        number = \arabic{chapter},
        aftername = \quad,
        beforeskip = {0pt},
        afterskip = {18pt},
        pagestyle = plain,
    }
}

**Comment by mohuangrui** [comment]
请先认真阅读使用说明文档，谢谢

**Comment by AIRicky** [comment]
hi~解决了\ctexset undefined control sequence的问题么？求分享经验。谢谢~

===========================
> ctex版本2.9，在编译Thesis.tex会出现 undefined control sequence，报错显示在
> \ctexset {
> chapter = {
> format = \linespread{1.0}\zihao{4}\bfseries\sffamily\centering,
> number = \arabic{chapter},
> aftername = \quad,
> beforeskip = {0pt},
> afterskip = {18pt},
> pagestyle = plain,
> }
> }

**Comment by AIRicky** [comment]
> ctex版本2.9，在编译Thesis.tex会出现 undefined control sequence，报错显示在
> \ctexset {
> chapter = {
> format = \linespread{1.0}\zihao{4}\bfseries\sffamily\centering,
> number = \arabic{chapter},
> aftername = \quad,
> beforeskip = {0pt},
> afterskip = {18pt},
> pagestyle = plain,
> }
> }

hi~ 最终是如何解决\ctexset Undefined control sequence的问题的？求拨冗分享经验。非常感谢~

**Comment by mohuangrui** [comment]
请见“https://github.com/mohuangrui/ucasthesis/wiki/编译指南”：

LaTeX 宏包过时：编译生成的 .log 文件给出 undefined control sequence 类的错误，是由于当前所使用的 LaTeX 编译系统版本过旧或其宏包库没有更新，请或是更新 LaTeX 宏包库或是安装最新 LaTeX 编译器。这一问题常发生于 CTEX 套装的使用者，注意 CTEX 套装已停止维护，需改用其他编译器如 Texlive 或是 Miktex。更多编译器的信息，可见“模版使用说明.pdf”的“系统要求”一节。
