### ISSUE TITLE
不能识别部分unicode字符

### ISSUE THREAD

**Issue by iMountTai** [mohuangrui/ucasthesis#381]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live2021 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

不能识别部分unicode字符

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/8477654/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![image](https://user-images.githubusercontent.com/35353688/163085082-56a530fc-4dea-443c-a919-9f5277bd5e0e.png)

![image](https://user-images.githubusercontent.com/35353688/163085635-2d1cff5a-33bf-4ae5-8a67-781999edca95.png)
pdf中显示为
![image](https://user-images.githubusercontent.com/35353688/163085743-d7152865-42b4-4b97-9717-d4600295033c.png)

## 最小工作示例(MWE) / Minimal Working Example 

⠼

**Comment by sikouhjw** [comment]
问题在于你输入的是盲文，而这一般的字体都没有。

你需要设置额外的字体作为输出的盲文的字体，比如 FandolBraille
```
\newfontfamily\mangwen{FandolBraille-Regular.otf}
```
然后在使用时用 `{}` 包起来
```tex
{\mangwen ^^^^2831}
```

**Comment by iMountTai** [comment]
可以在thesis中加入`\newcommand{\braille}{\fontspec{DejaVuSerif}}`，然后使用的时候使用\braille{⠚⠦}即可，前提是要先下载支持盲文的字体
