### ISSUE TITLE
定理的的排版设计

### ISSUE THREAD

**Issue by ghost** [mohuangrui/ucasthesis#383]
## 检查 / Check

- [ x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ 2018] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
问题1
![image](https://user-images.githubusercontent.com/50438483/166649586-e1c61209-a505-4185-b89e-7bbb18ea0c10.png)
想让图中1的定义位置空2个汉字位置，位置2的条目（i）和上一行的定义对齐，也就是空2个汉字，但是条目（i）到了第二行（位置3）就不空了，和左边界对齐。麻烦请问如何调整。

问题2
全部的定理，定义，推论，引理都空两个汉字， 同时删除末尾的点号。例如，需要将 “定理4.1.”修改为“定理4.1”

问题3
遇到中文文献的时候多人用“等”，遇到英语文献的时候多人用“et. al”, 但是目前的模板固定了只能全部使用“等”或者“et. al”, 请问如何调整。

问题4
将最后一章的总结不编号， 例如，需要将“第七章 总结”修改为“总结”

麻烦您可以帮我看看如何修改吗，非常感谢您，祝您在五一的小尾巴节日快乐哈。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by ghost** [comment]
“证明.”后面的点号也不要哈，谢谢您

**Comment by syvshc** [comment]
1, 2. 将 `Style/artratex.sty` 中的 https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L273-L295 替换为如下代码

```latex
% 重定义 plain definition remark 的样式
\newtheoremstyle{myplain}%⟨name⟩
    {3pt}%⟨Space above⟩1
    {3pt}%⟨Space below⟩1
    {\itshape}%⟨Body font⟩
    {2\ccwd}%⟨Indent amount⟩2
    {\bfseries}% ⟨Theorem head font⟩
    {}%⟨Punctuation after theorem head⟩
    {.5em}%⟨Space after theorem head⟩3
    {}%⟨Theorem head spec (can be left empty, meaning ‘normal’)⟩
\newtheoremstyle{mydefinition}%⟨name⟩
    {3pt}%⟨Space above⟩1
    {3pt}%⟨Space below⟩1
    {\normalfont}%⟨Body font⟩
    {2\ccwd}%⟨Indent amount⟩2
    {\bfseries}% ⟨Theorem head font⟩
    {}%⟨Punctuation after theorem head⟩
    {.5em}%⟨Space after theorem head⟩3
    {}%⟨Theorem head spec (can be left empty, meaning ‘normal’)⟩
\newtheoremstyle{myremark}%⟨name⟩
    {}%⟨Space above⟩1
    {}%⟨Space below⟩1
    {\normalfont}%⟨Body font⟩
    {2\ccwd}%⟨Indent amount⟩2
    {\bfseries}% ⟨Theorem head font⟩
    {}%⟨Punctuation after theorem head⟩
    {.5em}%⟨Space after theorem head⟩3
    {}%⟨Theorem head spec (can be left empty, meaning ‘normal’)⟩
\theoremstyle{myplain}% for theorems, lemmas, propositions, etc
\providecommand{\theoremname}{Theorem}%
\newtheorem{theorem}{\theoremname}[\artxmaincnt]
\providecommand{\axiomname}{Axiom}%
\newtheorem{axiom}[theorem]{\axiomname}
\providecommand{\lemmaname}{Lemma}%
\newtheorem{lemma}[theorem]{\lemmaname}
\providecommand{\corollaryname}{Corollary}%
\newtheorem{corollary}[theorem]{\corollaryname}
\providecommand{\assertionname}{Assertion}%
\newtheorem{assertion}[theorem]{\assertionname}
\providecommand{\propositionname}{Proposition}%
\newtheorem{proposition}[theorem]{\propositionname}
\providecommand{\conjecturename}{Conjecture}%
\newtheorem{conjecture}[theorem]{\conjecturename}
\theoremstyle{mydefinition}% for definitions and examples
\providecommand{\definitionname}{Definition}%
\newtheorem{definition}{\definitionname}[\artxmaincnt]
\providecommand{\examplename}{Example}%
\newtheorem{example}{\examplename}[\artxmaincnt]
\theoremstyle{myremark}% for remarks and notes
\providecommand{\remarkname}{Remark}%
\newtheorem*{remark}{\remarkname}
% 重定义 proof
\renewenvironment{proof}[1][\proofname]{\par
  \pushQED{\qed}%
  \normalfont \topsep6\p@\@plus6\p@\relax
  \trivlist
  \item\relax
  {\hspace*{2\ccwd}\itshape
  #1}\hspace\labelsep\ignorespaces
  }{%
  \popQED\endtrivlist\@endpefalse
  }
```

然后列表环境的缩进: 在 `\begin{document}` 前加上 

```latex
\setlist[enumerate,1]{label=(\roman*), labelindent=\parindent, leftmargin=0pt, widest=iii, itemindent=*}
```

这是一段测试用代码:

```latex
\begin{definition}
    设 $ X, Y $ 是两个随机变量
    \begin{enumerate}
        \item 若对于任意的 $ t \in \mathbb{R} $, 都有 $ \bar{F}_{X}(t) \le \bar{F}_{Y}(t) $, 则称 $ X $ 在普通随机序下小于 $ Y $, 记作 $ X \le Y $;
        \item 若对于任意的 $ t \in \mathbb{R} $, 都有 $ h_{X}(t) \ge h_{Y}(t) $, 则称 $ X $ 在失效率序下小于 $ Y $, 记作 $ X \le_{ht} Y $ 
    \end{enumerate}
\end{definition}
```

![image](https://user-images.githubusercontent.com/38098591/166921814-c619d15c-58b7-4648-91b0-0717d5aad3cc.png)


3. 我不会

4. 可以使用 `\chapter*{总结}` 来取消编号, 如果还想让它出现在目录里, 需要使用

```latex
\chapter*{总结)
\addcontentsline{toc}{chapter}{总结}
```

**Comment by ghost** [comment]
> ```
> \setlist[enumerate,1]{label=(\roman*), labelindent=\parindent, leftmargin=0pt, widest=iii, itemindent=*}
> ```

非常感谢您的耐心解答，通过操作以后发现有下图的报错麻烦您能帮我看看吗，非常感谢

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/50438483/166950702-e019df00-0067-4f56-873c-ac97fccf3583.png)

**Comment by syvshc** [comment]
把 `enumerate` 宏包去掉, 模板调用了 `enumitem` 宏包, 二者冲突.

**Comment by ghost** [comment]
> enumerate

我试了好像还是不行

**Comment by syvshc** [comment]
emm, 那你新建一个 `.tex` 文件, 用 pdflatex 编译以下代码:

```latex
\documentclass{article}
\usepackage{enumitem}
\setlist[enumerate,1]{label=(\roman*), labelindent=\parindent, leftmargin=0pt, widest=iii, itemindent=*}
\begin{document}
  \begin{enumerate}
    \item Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut purus elit,
    vestibulum ut, placerat ac, adipiscing vitae, felis. Curabitur dictum gravida
    mauris. Nam arcu libero, nonummy eget, consectetuer id, vulputate a, magna.
  \end{enumerate}
\end{document}
```

查看是否有报错？

**Comment by mohuangrui** [comment]
3. 见 [将英文引用中的 “和”、“等” 改为 "and"、"et al."](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E5%B0%86%E8%8B%B1%E6%96%87%E5%BC%95%E7%94%A8%E4%B8%AD%E7%9A%84-%E5%92%8C%E7%AD%89-%E6%94%B9%E4%B8%BA-andet-al)
