### ISSUE TITLE
请问如何导出排版良好的word版本，涉及到国科大Sep系统的格式检测。

### ISSUE THREAD

**Issue by Jantzyy** [mohuangrui/ucasthesis#384]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ ] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by mohuangrui** [comment]
#376 已有相关讨论，对于只能用word才能进行特定的步骤的设定，个人建议有需求的同学能够一起向学校反馈一下，毕竟兼容pdf应该是非常基本的需求

**Comment by Jantzyy** [comment]
目前我用的ilovepdf转换成word，然后重新排版，还好参考文献可以导入Endnote。技多不压身啊~同时学习了word和Latex~

**Comment by mohuangrui** [comment]
近期有较多同学遭遇了这个要求word的问题，其中 Sundrops 提示所可以找相关负责老师进行线下格式审查：
> @Sundrops 我们是latex写的线下格式审查，可以咨询一下相关负责的老师

同时，对于只能用word才能进行特定的步骤的设定，个人建议有需求的同学能够一起向学校反馈一下，毕竟兼容pdf应该是非常基本的需求。

**Comment by singledoggy** [comment]
目前有老师给出过反馈吗，以及存在咨询途径吗

**Comment by Jantzyy** [comment]
没有呢，我重新用word排版了～



----- Original Message -----

**Comment by singledoggy** [comment]
谢谢回复.

**Comment by labdog** [comment]
![批注 2022-06-27 200452](https://user-images.githubusercontent.com/48740808/175937091-f468d446-e2f9-4415-aa53-4b47e93ff97e.png)
图题如果增加（a）(b)(c)......，就不居中了。请问怎么解决呢？

**Comment by JamesWZM** [comment]
我本人是微生物所的，目前正在格式审查
为了方便老板批注以及sep的格式审查，最终我放弃了使用latex，转而找人要来了word的模板，然后陷入了长时间的痛苦的格式修改中，不过这不是重点

我想说的是，格式审查系统那个不是必需的，只是给使用word的人准备的自动检查工具，原因正是国科大官方没有给出相应的模板，整个审查流程是走先自动检查再人工初审格式的流程，无论如何，人工初审格式那一步只需要PDF和纸质版，所以用这个模板是没问题的，如果每年都紧追最新要求的话

如果哪个所的规定跟微生物所不同，只使用那个系统做格式审查而没有初审的过程，那就没办法了

**Comment by JamesWZM** [comment]
好消息，据说今年年底会增加latex版本的格式检测，以后就可以快乐地用这个模板了（但这跟我们这些已经写好论文的家伙有什么关系呢QAQ）

**Comment by Ricemeal** [comment]
今天所里推送了新版论文格式要求，除了word版，也有Latex的附件包，特来打卡

**Comment by JamesWZM** [comment]
哪个所啊这么好，微生物所这边根本没信儿呢QAQ
________________________________
发件人: Ricemeal ***@***.***>
发送时间: 2022年10月14日 17:01
收件人: mohuangrui/ucasthesis ***@***.***>
抄送: James Wang ***@***.***>; Comment ***@***.***>
主题: Re: [mohuangrui/ucasthesis] 请问如何导出排版良好的word版本，涉及到国科大Sep系统的格式检测。 (Issue #384)


今天所里推送了新版论文格式要求，除了word版，也有Latex的附件包，特来打卡

―

**Comment by atongsa** [comment]
> 今天所里推送了新版论文格式要求，除了word版，也有Latex的附件包，特来打卡

同学您好，请问现在可以在 sep 直接 上传  latex 文件，不需要 word 对吗

**Comment by JamesWZM** [comment]
已毕业人士，没有这方面情报
________________________________
发件人: atongsa ***@***.***>
发送时间: 2024年2月19日 18:08
收件人: mohuangrui/ucasthesis ***@***.***>
抄送: James Wang ***@***.***>; Comment ***@***.***>
主题: Re: [mohuangrui/ucasthesis] 请问如何导出排版良好的word版本，涉及到国科大Sep系统的格式检测。 (Issue #384)


今天所里推送了新版论文格式要求，除了word版，也有Latex的附件包，特来打卡

同学您好，请问现在可以在 sep 直接 上传 latex 文件，不需要 word 对吗

―

**Comment by singledoggy** [comment]
不可以，需要上传pdf，跳过格式检查步骤做后面的审查签字。

---- 回复的原邮件 ----
| 发件人 | James ***@***.***> |
| 发送日期 | 2024年02月22日 13:21 |
| 收件人 | mohuangrui/ucasthesis ***@***.***> |
| 抄送人 | Han ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [mohuangrui/ucasthesis] 请问如何导出排版良好的word版本，涉及到国科大Sep系统的格式检测。 (Issue #384) |

已毕业人士，没有这方面情报
________________________________
发件人: atongsa ***@***.***>
发送时间: 2024年2月19日 18:08
收件人: mohuangrui/ucasthesis ***@***.***>
抄送: James Wang ***@***.***>; Comment ***@***.***>
主题: Re: [mohuangrui/ucasthesis] 请问如何导出排版良好的word版本，涉及到国科大Sep系统的格式检测。 (Issue #384)


今天所里推送了新版论文格式要求，除了word版，也有Latex的附件包，特来打卡

同学您好，请问现在可以在 sep 直接 上传 latex 文件，不需要 word 对吗

―

**Comment by lllvcs** [comment]
> > 今天所里推送了新版论文格式要求，除了word版，也有Latex的附件包，特来打卡
> 
> 同学您好，请问现在可以在 sep 直接 上传 latex 文件，不需要 word 对吗

我们这边不允许，Latex必须要人工查格式，还需要填格式检测审核表。

![WeChat截图_20240313234603](https://github.com/mohuangrui/ucasthesis/assets/22395524/62da4af1-e2c9-47ac-b6d6-9339d5f82eea)
