### ISSUE TITLE
当论文名字和章节名字比较长时会出现重叠

### ISSUE THREAD

**Issue by reinforcementwonder** [mohuangrui/ucasthesis#386]
## 检查 / Check

- [ x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux
  - [x] overleaf
- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [x] CTeX

## 描述问题 / Problem Description

问题描述：当论文名字和chapter名字比较长时会出现重叠。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
not applicable

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
该样例中，我选择论文题目为：`通过测试名字长度看看会不会出问题哦哦`,章节名字为`研究背景及其意义`
![image](https://user-images.githubusercontent.com/104648446/167180614-bb29356a-f161-4ca6-822f-582fd1223a5f.png)

## 最小工作示例(MWE) / Minimal Working Example 

as above

**Comment by mohuangrui** [comment]
为何章节标题和论文题目会出现在同一个header里？若自行修改过代码，则很可能需要检查一下你的修改

**Comment by reinforcementwonder** [comment]
明白了。谢谢！
