### ISSUE TITLE
如何修改声明

### ISSUE THREAD

**Issue by pppiao666** [mohuangrui/ucasthesis#387]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [x] CTeX

## 描述问题 / Problem Description

问题描述：
我想要修改声明页内容，但是不知道在哪里以及如何修改。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![image](https://user-images.githubusercontent.com/60561874/168946678-48558140-54f4-4a2b-a8f2-62ad4cec0546.png)
修改这一页的内容

**Comment by mohuangrui** [comment]
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cfg#L109

**Comment by pppiao666** [comment]
了解了，太感谢了！
