### ISSUE TITLE
参考文献排序问题

### ISSUE THREAD

**Issue by pppiao666** [mohuangrui/ucasthesis#388]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
想让参考文献的标号按引用顺序排列，看了相关问题的解答还是不知道如何操作，也下了新的 gbt7714 相关的文件，还是不行。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

## 最小工作示例(MWE) / Minimal Working Example 

以上图为例，希望参考文献的标号为 [19], [20] 而不是 [19], [101]

**Comment by pppiao666** [comment]
![问题](https://user-images.githubusercontent.com/60561874/174439723-de2a3338-c649-4f55-b631-f155b8786d7a.png)
抱歉刚刚图片上传失败，这是现在编译的结果，希望参考文献的标号为 [19], [20] 而不是 [19], [101]

**Comment by mohuangrui** [comment]
见 [图表标题中的文献编号总排在前列](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E5%9B%BE%E8%A1%A8%E6%A0%87%E9%A2%98%E4%B8%AD%E7%9A%84%E6%96%87%E7%8C%AE%E7%BC%96%E5%8F%B7%E6%80%BB%E6%8E%92%E5%9C%A8%E5%89%8D%E5%88%97)
