### ISSUE TITLE
./Style/artratex.sty.sty:314: file "algpseudocode.sty" not found，I donot know why?

### ISSUE THREAD

**Issue by weitaod** [mohuangrui/ucasthesis#39]
我在linux下使用xelatex main.tex编译了一下，结果出现了./Style/artratex.sty.sty:314: file "algpseudocode.sty" not found

**Comment by tangjie1992** [comment]
你自己伪代码宏包不存在呀

**Comment by mohuangrui** [comment]
你在linux安装的LaTeX缺乏algpseudocode.sty宏包，1）要么你安装Texlive Full，2）要么手动安装此宏包，3）要么在Thesis.tex中去掉list选项不去调用此宏包也不用算法环境。

顺便，我也想问你一个问题，很奇怪为什么问问题之前都不愿读下使用说明，难道那文档有那么晦涩难看吗？
