### ISSUE TITLE
过长的图片标题强制居中

### ISSUE THREAD

**Issue by JamesWZM** [mohuangrui/ucasthesis#391]
如图，写作中我注意到使用此模板，若图标题名过长以至于需要换行会导致自动居左对齐，对足够短的标题则是居中
![image](https://user-images.githubusercontent.com/48663928/185043689-8d3fcee9-c7c1-4bb3-b0c4-4fdf28e1a4a0.png)
![image](https://user-images.githubusercontent.com/48663928/185043743-a22638ca-93c7-41b5-a8a9-c65c33593425.png)

在此提出解决方案，参考自https://blog.csdn.net/weixin_43958105/article/details/115541531
![image](https://user-images.githubusercontent.com/48663928/185043836-0c7af688-9196-4b60-865b-0a66a89d84e3.png)
如图添加以下包即可
\usepackage[justification=centering]{caption}

**Comment by JamesWZM** [comment]
补充，效果如下：
![image](https://user-images.githubusercontent.com/48663928/185043944-a80a1bd7-051a-43b8-809f-075305682248.png)

**Comment by mohuangrui** [comment]
原来的设定是默认的需求。如果需要改变，可以按需调整即可。

**Comment by JamesWZM** [comment]
我有比较研究生部给出的要求和师兄之前写的论文，我认为应该是需要全部居中的。原文：

置于图的下方，宋体五号居中（英文用Times New Roman体），1.5倍行距，段前6磅，段后12磅，图序与图名文字之间空一个汉字符位，图序加粗。图注位于图名下方，标题加粗，左缩进两个汉字符，续行悬挂缩进左对齐

另，非常感谢莫师兄的工作，我是研一的时候被刘洋老师带入坑的，之后一直苦于国内少有支持TeX格式，不过至少我在写的时候可以爽爽。事实上sep需要用word格式审查的问题挺普遍的，我已经做好先写完再调格式的心理准备了
________________________________
发件人: Huangrui Mo ***@***.***>
发送时间: 2022年8月17日 14:02
收件人: mohuangrui/ucasthesis ***@***.***>
抄送: James Wang ***@***.***>; Author ***@***.***>
主题: Re: [mohuangrui/ucasthesis] 过长的图片标题强制居中 (Issue #391)


原来的设定是默认的需求。如果需要改变，可以按需调整即可。

―
