### ISSUE TITLE
国科大今年改了行间距等内容，也许这个模板需要更多维护？

### ISSUE THREAD

**Issue by JamesWZM** [mohuangrui/ucasthesis#392]
![image](https://user-images.githubusercontent.com/48663928/191191663-abb59e51-5a9b-4053-a88c-5c312d446465.png)

**Comment by mohuangrui** [comment]
请问可以给出官方文件的出处吗？

**Comment by JamesWZM** [comment]
这个，大概是因为今年改了要求，结果大家都不太适应，今年我看见至少四个版本的要求，这两个分别是微生物所研究生部提供的版本以及国科大论文格式检测系统给出的版本，我认为后者是国科大的要求，前者应该是微生物所单独加了些字数之类的要求
________________________________
发件人: Huangrui Mo ***@***.***>
发送时间: 2022年9月20日 17:20
收件人: mohuangrui/ucasthesis ***@***.***>
抄送: James Wang ***@***.***>; Author ***@***.***>
主题: Re: [mohuangrui/ucasthesis] 国科大今年改了行间距等内容，也许这个模板需要更多维护？ (Issue #392)


请问可以给出官方文件的出处吗？

―

**Comment by mohuangrui** [comment]
为了保持稳定和满足大多数人的需求，样式不会根据个别所或临时政策而调整，谢谢反馈。
