### ISSUE TITLE
修改正文行距

### ISSUE THREAD

**Issue by tryhere** [mohuangrui/ucasthesis#393]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/38278343/194273763-68e272de-7068-4bfa-95b5-86fb7b6a1f5b.png">
<img width="509" alt="image" src="https://user-images.githubusercontent.com/38278343/194273897-0d41fd40-4366-4ae6-9963-b5d49d85a28f.png">
如图所示，2023年冬季批次的要求已经更新，主要是行间距的改动。请问如何修改设置呢？

**Comment by mohuangrui** [comment]
你好，原模板的设定与你所发布的要求是一致的，唯一的区别是正文行距。

如果要修改正文行距为 1.25倍，只需修改如下一行即可：

https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L133

对于宋体小四，1.25倍行距对应的数值应该是
```Tex
\linespread{1.035}% line space setting 
```
因为LaTeX控制行距的机制与Word不同，如果要很好地对应Word的1.25倍行距，建议你对这个数字进行一些微调，并与Word的文字进行一下对比。

总得来说，精确的数值没有太大意义，应该差不多就行，对于排版美观合理更重要，而不是精确的数值。

**Comment by tryhere** [comment]
> 你好，原模板的设定与你所发布的要求是一致的，唯一的区别是正文行距。
> 
> 如果要修改正文行距为 1.25倍，只需修改如下一行即可：
> 
> https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L133
> 
> 对于宋体小四，1.25倍行距对应的数值应该是
> 
> ```
> \linespread{1.035}% line space setting 
> ```
> 
> 因为LaTeX控制行距的机制与Word不同，如果要很好地对应Word的1.25倍行距，建议你对这个数字进行一些微调，并与Word的文字进行一下对比。
> 
> 总得来说，精确的数值没有太大意义，应该差不多就行，对于排版美观合理更重要，而不是精确的数值。

好的，感谢您的帮助！

**Comment by clouddea** [comment]
我设置成了1.035, 但还是显得很挤，跟word宋体小四 1.25差距挺大。

**Comment by clouddea** [comment]
我设置成了1.035, 但还是显得很挤，跟word宋体小四 1.25差距挺大。

**Comment by qisongshi** [comment]
> 我设置成了1.035, 但还是显得很挤，跟word宋体小四 1.25差距挺大。

linespread设置为1.354貌似是比较正确的换算值，虽然你应该已经毕业了但我在这里回复一下，以防有人搜issue找到该问题。
查看一些前人的毕业论文，发现行距大概比word的模板大一点点，大概是linespread=1.4的感觉。应该是差不多就行，不用特别精确。
