### ISSUE TITLE
学校发布了LaTeX的模板，但直接编译会报错

### ISSUE THREAD

**Issue by Hermiterexakm** [mohuangrui/ucasthesis#394]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10//Win11
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live <2021>
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description
<学校发布了LaTeX的模板，但直接编译会报错>
首先感谢大佬的持续更新。
问题描述：学校发布了LaTeX的模板，但直接编译会在使用$^\citepns[]{XXX}$时报错。
按照顺序编码法，需要将参考文献上标，并且在旁附带参考文献的页码（也要上标），因此学校给的模板是$^\citepns[]{XXX}$。但此时会直接报错。在将$^\citepns$改为\citep时不会报错，但页码会和正文字体大小一致；此时如果再将\citep改为$^\citepns$便又能够正常编译了，但[]内的参考文献序号字体稍大。
另外，源文件如果用overleaf编译就不会出bug，其他本地软件都出了bug。
以及，是否能够实现参考文献直接放在脚注处？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/9923413/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![屏幕截图(57)](https://user-images.githubusercontent.com/117310774/199579658-44779afb-6a7e-465c-969a-8c883d9d58d5.png)
![屏幕截图(58)](https://user-images.githubusercontent.com/117310774/199580727-e635b944-91a1-413e-aed2-c982fb770778.png)

![屏幕截图(59)](https://user-images.githubusercontent.com/117310774/199580747-de6d1ab2-e7cc-48a0-8158-c1c1583a8089.png)

**Comment by sikouhjw** [comment]
> 源文件如果用overleaf编译就不会出bug，其他本地软件都出了bug。

那就用 texlive 2022

**Comment by Hermiterexakm** [comment]
> > 源文件如果用overleaf编译就不会出bug，其他本地软件都出了bug。
> 
> 那就用 texlive 2022

然而亲测2022也会报错

**Comment by sikouhjw** [comment]
1. 你问的是学校提供的模板，那应该去问学校，最不济也应该提供下载链接；
2. 编译本项目的模板是没有这个问题的；
3. 根据你的描述，你需要的是 `\usepackage[super,list,biber]{Style/artratex}` 及 `\cite[]{}`；
4. 然后用 `biber`/`latexmk -xelatex Thesis` 编译即可。

**Comment by Hermiterexakm** [comment]
> 1. 你问的是学校提供的模板，那应该去问学校，最不济也应该提供下载链接；
> 2. 编译本项目的模板是没有这个问题的；
> 3. 根据你的描述，你需要的是 `\usepackage[super,list,biber]{Style/artratex}` 及 `\cite[]{}`；
> 4. 然后用 `biber`/`latexmk -xelatex Thesis` 编译即可。

1、抱歉，原本准备上传的，现在才发现没有上传。
[附件4 中国科学院大学学位论文LaTeX模板.zip_20221006.zip](https://github.com/mohuangrui/ucasthesis/files/9925928/4.LaTeX.zip_20221006.zip)

2、编译本项目模板中的开题报告模板时也会出现这个情况
3、用该种编译方法得到的效果如图
![屏幕截图(60)](https://user-images.githubusercontent.com/117310774/199656083-1b921618-265f-4854-8ba2-35c34d4dbb94.png)
究其原因是$^\citepns[]{XXX}$的问题。
使用biber就变成了
![屏幕截图(61)](https://user-images.githubusercontent.com/117310774/199656337-de0c8f29-7ec8-4234-adee-788d2ebaa63d.png)

**Comment by mohuangrui** [comment]
_1. 源文件如果用overleaf编译就不会出bug，其他本地软件都出了bug。_

是指因为\citepns还是指直接在github下载本模板，本地编译出错？

_2. 按照顺序编码法，需要将参考文献上标，并且在旁附带参考文献的页码（也要上标），因此学校给的模板是$^\citepns[]{XXX}$。但此时会直接报错。在将$^\citepns$改为\citep时不会报错，但页码会和正文字体大小一致；此时如果再将\citep改为$^\citepns$便又能够正常编译了，但[]内的参考文献序号字体稍大。_

这是因为用错了！\citepns的存在为了：若在上标顺序编码制（super）模式下，希望在特定位置将上标 改为嵌入式标。你本就是需要用上标，直接用\citep{}和\citet{}即可！

至于在下载模板后，如何将引用从著者-出版年制（authoryear）改为上标顺序编码制（super），见[引用样式](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E5%BC%95%E7%94%A8%E6%A0%B7%E5%BC%8F)
![image](https://user-images.githubusercontent.com/7518165/199662349-269c6188-8851-4aab-9092-7a4611dc3fce.png)

再至于如何加上页码，通常这并不需要你去改文献引用命令，在著者-出版年制（authoryear）或顺序编码制（numbers）模式下，直接用 '\citep[页码]{}' 即可。

但是，在上标顺序编码制（super）模式下加年份是个比较奇特的操作，尽管如此，也无需修改命令，只需打开一点思路即可：

```Tex
看！上标引用带页码\citet{lamport1986document}\textsuperscript{\tiny 250}; 

看！上标引用带页码\citep{lamport1986document}\textsuperscript{\tiny 250}。

```
![image](https://user-images.githubusercontent.com/7518165/199662824-8fa03e46-fb46-4b49-afdc-2fc8fe4b3c00.png)

**Comment by Hermiterexakm** [comment]
> _1. 源文件如果用overleaf编译就不会出bug，其他本地软件都出了bug。_
> 
> 是指因为\citepns还是指直接在github下载本模板，本地编译出错？
> 
> _2. 按照顺序编码法，需要将参考文献上标，并且在旁附带参考文献的页码（也要上标），因此学校给的模板是$^\citepns[]{XXX}$。但此时会直接报错。在将$^\citepns$改为\citep时不会报错，但页码会和正文字体大小一致；此时如果再将\citep改为$^\citepns$便又能够正常编译了，但[]内的参考文献序号字体稍大。_
> 
> 这是因为用错了！\citepns的存在为了：若在上标顺序编码制（super）模式下，希望在特定位置将上标 改为嵌入式标。你本就是需要用上标，直接用\citep{}和\citet{}即可！
> 
> 至于在下载模板后，如何将引用从著者-出版年制（authoryear）改为上标顺序编码制（super），见[引用样式](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E5%BC%95%E7%94%A8%E6%A0%B7%E5%BC%8F) ![image](https://user-images.githubusercontent.com/7518165/199662349-269c6188-8851-4aab-9092-7a4611dc3fce.png)
> 
> 再至于如何加上页码，通常这并不需要你去改文献引用命令，在著者-出版年制（authoryear）或顺序编码制（numbers）模式下，直接用 '\citep[页码]{}' 即可。
> 
> 但是，在上标顺序编码制（super）模式下加年份是个比较奇特的操作，尽管如此，也无需修改命令，只需打开一点思路即可：
> 
> ```
> 看！上标引用带页码\citet{lamport1986document}\textsuperscript{\tiny 250}; 
> 
> 看！上标引用带页码\citep{lamport1986document}\textsuperscript{\tiny 250}。
> ```
> 
> ![image](https://user-images.githubusercontent.com/7518165/199662824-8fa03e46-fb46-4b49-afdc-2fc8fe4b3c00.png)

1、学校的模板是直接借用这个模板的。但是在super情况下，学校模板中给出的是$^\citepns$这一形式，因此出现报错。我测试了学校的模板和github的本模板，在使用$^\citepns$情况下都会在本地的编译软件中报错，在overleaf就没问题（很奇怪）
2、学校模板制作者估计是想着在需要加页码的地方把\citep变成嵌入式，再打包页码，并加上公式环境，一起放在上标，所以有了$^\citepns{lamport1986document}33$这一形式。
3、这个思路是个很好的解决办法，感谢大佬。不过现在新版本的论文都要求页码置于方括号旁边，并上标。如果使用\citep[33]{lamport1986document}并不能形成上标页码的方式，只能是和文本字体大小一样。
再次感谢，暂时先用您第三点提出的思路。

**Comment by mohuangrui** [comment]
_3. 是否能够实现参考文献直接放在脚注处？_

可以，你需要在`Thesis.tex`中启用 [biber] 并使用 biblatex 而不是 bibtex 编译文献
```Tex
\usepackage[biber,super,list]{Style/artratex}% document settings
```
然后使用
```Tex
看！脚注上标引用带页码\footfullcite{lamport1986document}\textsuperscript{\tiny 250}; 

看！脚注上标引用带页码\footfullcite{lamport1986document}\textsuperscript{\tiny 250}。

```
效果如下：
![image](https://user-images.githubusercontent.com/7518165/199667475-ffeb6af9-3fb5-49c6-a3e5-e6ceeaceec40.png)

脚注如下：
![image](https://user-images.githubusercontent.com/7518165/199667595-76d27e3f-9d7a-4c68-8f26-ffce1c4d865e.png)

至于如果想将footnote中的数字加上 []，这个我确实不太清楚如何实现。

**Comment by mohuangrui** [comment]
_在使用$^\citepns$情况下都会在本地的编译软件中报错，在overleaf就没问题（很奇怪）
学校模板制作者估计是想着在需要加页码的地方把\citep变成嵌入式，再打包页码，并加上公式环境，一起放在上标，所以有了$^\citepns{lamport1986document}33$这一形式。_

将cite命令放入数学环境中为异常操作，出错不意外。

`$^\citepns{lamport1986document}33$`

这是将简单问题复杂化了（更别论你展现的这个命令存在多处错误）！即使要用数学环境实现页码上标，也应该用如下用法：
```Tex
看！数学环境实现上标引用带页码\citep{lamport1986document}${}^{33}$
```

**Comment by sikouhjw** [comment]
> 2、编译本项目模板中的开题报告模板时也会出现这个情况 3、用该种编译方法得到的效果如图 ![屏幕截图(60)](https://user-images.githubusercontent.com/117310774/199656083-1b921618-265f-4854-8ba2-35c34d4dbb94.png) 究其原因是$^\citepns[]{XXX}$的问题。 使用biber就变成了 ![屏幕截图(61)](https://user-images.githubusercontent.com/117310774/199656337-de0c8f29-7ec8-4234-adee-788d2ebaa63d.png)

说明你没有用 `biber` 编译。

**Comment by Hermiterexakm** [comment]
> 



> > 2、编译本项目模板中的开题报告模板时也会出现这个情况 3、用该种编译方法得到的效果如图 ![屏幕截图(60)](https://user-images.githubusercontent.com/117310774/199656083-1b921618-265f-4854-8ba2-35c34d4dbb94.png) 究其原因是$^\citepns[]{XXX}$的问题。 使用biber就变成了 ![屏幕截图(61)](https://user-images.githubusercontent.com/117310774/199656337-de0c8f29-7ec8-4234-adee-788d2ebaa63d.png)
> 
> 说明你没有用 `biber` 编译。

谢谢指出。不过还有个小问题，我一直没法调用biber，出现报错内容是:
INFO - This is Biber 2.17
INFO - Logfile is 'ref.blg'
ERROR - Cannot find 'ref.bcf'!
INFO - ERRORS: 1

不知道是什么问题
