### ISSUE TITLE
还是不明白如何将参考文献编号

### ISSUE THREAD

**Issue by HWWH123** [mohuangrui/ucasthesis#395]
## 检查 / Check

- [x ] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
还是不明白如何在参考文献前加编号，以及将现在的形式变为在正文中只有编号[1]类似于图二

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![image](https://user-images.githubusercontent.com/67941031/199799361-49c35a2e-2d6b-49c9-bf48-b02f13aaf2cc.png)
![image](https://user-images.githubusercontent.com/67941031/199799472-3633d89a-a6b6-443d-858e-976426a9ce35.png)

## 最小工作示例(MWE) / Minimal Working Example 

已经在Thesis中使用
\usepackage[biber,authoryear,list]{Style/artratex}
并在artratex文件中修改
\RequirePackage[backend=biber,style=\artxbiberauy,gbalign=gb7714-2015,mincitenames=1,maxcitenames=2]{biblatex}
并更新Biblio中的文件

**Comment by mohuangrui** [comment]
[引用样式](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E5%BC%95%E7%94%A8%E6%A0%B7%E5%BC%8F)

![image](https://user-images.githubusercontent.com/7518165/199873880-8bc0cd71-a207-4ad0-b295-be7fd3e362b1.png)

**Comment by HWWH123** [comment]
在Thesis中使用了\usepackage[numbers,list]{Style/artratex}，在正文中引用使用\citet还是没用

**Comment by HWWH123** [comment]
已经解决，谢谢

**Comment by zyc53** [comment]
想问一下如何解决的呀？

**Comment by sikouhjw** [comment]
> 想问一下如何解决的呀？

那张图你看不懂吗？

**Comment by zyc53** [comment]
> 

嗯嗯，解决了，只需要改一下Thesis.tex.

将里面的 
\usepackage[biber,authoryear,list]{Style/artratex}
改为
\usepackage[numbers,list]{Style/artratex}% 文本: Jones [1]; 括号: [1]
