### ISSUE TITLE
只保留本模板内容，使用xeletex编译报错

### ISSUE THREAD

**Issue by ChangXiaoning** [mohuangrui/ucasthesis#396]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2021 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
注释掉自己撰写的部分，只保留本项目提供的Tex/Chap_Intro和Tex/Chap_Guide。使用xelatex编译，报错Recipe terminated with error，但是vscode左下角的叉没有报错。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/10092270/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/32586762/203969123-d7a55ee8-3ef2-4e0e-bdca-ef21c0659ee5.png">

**Comment by mohuangrui** [comment]
你的问题应该产生于你自己的修改
