### ISSUE TITLE
使用学校发的模板，但公式序号根据section不同而重新编号，请问如何更改

### ISSUE THREAD

**Issue by cbx812** [mohuangrui/ucasthesis#398]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

使用国科大LaTeX模板[4.LaTeX.zip_20221006.zip](https://github.com/mohuangrui/ucasthesis/files/10329893/4.LaTeX.zip_20221006.zip)，编辑公式时序号根据section不同而重新编号，如下图，而不是再同一chapter下连续编号，如第二个公式应为4.2，请问应该如何修改？
![image.png](https://pic7.58cdn.com.cn/nowater/webim/big/n_v23c084f24c117422899e59cad01424948.png)

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by sikouhjw** [comment]
问题在于
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L674-L676
你发的模板将这段代码取消注释了，导致 equation 随着 section 增加而归零。

解决方案：
1. 将这段代码注释，但不能确保其它地方没错；
2. 使用 github 上的模板（建议）。

**Comment by cbx812** [comment]
> 问题在于
> 
> https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L674-L676
> 
> 
> 你发的模板将这段代码取消注释了，导致 equation 随着 section 增加而归零。
> 解决方案：
> 
> 1. 将这段代码注释，但不能确保其它地方没错；
> 2. 使用 github 上的模板（建议）。

明白了，非常感谢！
