### ISSUE TITLE
新模板的附录section显式不全

### ISSUE THREAD

**Issue by Bingrong-Yu** [mohuangrui/ucasthesis#399]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：在2022年9月新发行的国科大毕业论文latex模板中，附录部分如果要用\section分节的话，节标题序号会显示不完全。例如，附录A的第一节 \section{第一节}，其显示为".1 第一节"，而不是完整的"A.1 第一节"。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[Thesis_Yu.log](https://github.com/mohuangrui/ucasthesis/files/10393062/Thesis_Yu.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![question](https://user-images.githubusercontent.com/122458688/211825622-a66124c1-cd2d-4382-bb39-94f1150d22f2.jpg)

## 最小工作示例(MWE) / Minimal Working Example 
\chapter{附录A\quad 记号约定}

\section{自然单位制}
$c=\hbar=k_{{\rm B}}^{}=1$

\section{闵氏度规}
$\eta_{\mu\nu}^{}=\eta^{\mu\nu}={\rm Diag}\left(+1,-1,-1,-1\right)$

\section{其它}
\begin{itemize}
\item  三维Levi-Civita符号$\epsilon_{ijk}^{}$：约定$\epsilon_{123}^{}=1$
\end{itemize}

**Comment by sikouhjw** [comment]
請注意，在本模板的附錄輸入中，不需要手動編號 `\chapter{附录A\quad 记号约定}`，因此一定是你修改了模板的格式設置，是你的問題
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Tex/Appendix.tex#L1-L5

**Comment by mohuangrui** [comment]
"在2022年9月新发行的国科大毕业论文latex模板中" 

那个是他人基于我的模板修改部分参数后发布的，我不清楚其修改意图，也无法维护其发布。

建议使用当前Github的版本。
