### ISSUE TITLE
大神，怎样把摘要加入目录中？

### ISSUE THREAD

**Issue by taopanpan** [mohuangrui/ucasthesis#40]

**Comment by mohuangrui** [comment]
官方规则明确写了摘要不加入目录。如果你想加，在Frontpage.tex中移除
\chapter*{摘要}
等中的*号即可。

其他的比如列表，列图等等，请Thesis.tex启用：

\intotoc{\listfigurename}% add link to contents table and bookmark
\listoffigures% figures catalog
\intotoc{\listtablename}% add link to contents table and bookmark
\listoftables% tables catalog

**Comment by zhanglinbo** [comment]
怎么把目录从目录中干掉？谢谢

**Comment by mohuangrui** [comment]
请查看最新版。
