### ISSUE TITLE
overleaf平台上能否使用biblatex编译参考文献？该平台没有类似“xelatex + biblatex + xelatex + xelatex”的编译选项

### ISSUE THREAD

**Issue by minghuisvn** [mohuangrui/ucasthesis#400]
## 检查 / Check

- [x ] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment
overleaf

- `TeX 发行版 / Tex Distribution`
  - [ x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：overleaf平台使用ucas的模板，启用了biber但是文中引用参考文献乱码，文后参考文献正常。另一个问题是，引用样式为<super>时，该平台上使用\citep{}和\citepns{}没有区别。不知道原因是不是编译命令不同，改模板是否适合在overleaf上使用？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by sikouhjw** [comment]
> 启用了biber但是文中引用参考文献乱码，文后参考文献正常。

给截图+log 或者 Overleaf 链接。

> 另一个问题是，引用样式为时，该平台上使用\citep{}和\citepns{}没有区别。

引用样式为什么？根据[^1]，在上标顺序编码制（super）模式下，这两种命令会有区别。

> 不知道原因是不是编译命令不同，改模板是否适合在overleaf上使用？

适合[^2]。

[^2]: https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE#linuxoverleaf-%E7%B3%BB%E7%BB%9F%E7%9A%84%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE

[^1]: https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E5%BC%95%E7%94%A8%E6%A0%B7%E5%BC%8F

**Comment by minghuisvn** [comment]
引用格式为上标顺序编码制`<super>`，\citep和\citepns没有区别。share link: https://latex.ihep.ac.cn/6725737451bqkyvckfhnnm

开启biber文中引用处乱码，如下图：
![overleaf_citeproblem](https://user-images.githubusercontent.com/68952982/216802878-348e9bfb-90cd-4005-bce3-32e8b1a76675.jpg)

**Comment by sikouhjw** [comment]
> share link: https://latex.ihep.ac.cn/6725737451bqkyvckfhnnm

1. 这不是 Overleaf
2. 尽量不要使用非公认可靠的平台

> 开启biber文中引用处乱码，如下图： ![overleaf_citeproblem](https://user-images.githubusercontent.com/68952982/216802878-348e9bfb-90cd-4005-bce3-32e8b1a76675.jpg)

1. 你用的模板是旧版本，最新版本的文本与截图不同
2. 使用[^1]提供的模板[^2]，在修改参数为 `\usepackage[biber,super,list]{Style/artratex}` 后，结果为
    ![图片](https://user-images.githubusercontent.com/49770925/216835696-21cc90b9-21ba-4a89-899c-4e40f8540222.png)
3. 只需要修改参数再编译即可，Overleaf 会自动调用 `latexmk` 来执行整个编译链


[^1]: https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE#linuxoverleaf-%E7%B3%BB%E7%BB%9F%E7%9A%84%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE
[^2]: https://www.overleaf.com/latex/templates/thesis-template-for-the-university-of-chinese-academy-of-sciences/fhbvbjrrgtwx

**Comment by minghuisvn** [comment]
已解决，谢谢~
