### ISSUE TITLE
在“章节”之上新增“部分”

### ISSUE THREAD

**Issue by SabriQ** [mohuangrui/ucasthesis#401]
整体用起来问题不大。但是有两个可能属于latex比较高阶的使用，个人不是很会，在已有的配置文件中修改起来也比较麻烦。
问题一： 在“章节”之上新增“部分”，希望标题“第一部分 xxxx”直接在标题“第1章 xxx”之上，但是不是很清楚该怎么设置，中间总会出现newpage
问题二： 图注过长的时候，超过该页的部分不会显示，不知道该怎么设置比较好

**Comment by sikouhjw** [comment]
> 问题一： 在“章节”之上新增“部分”，希望标题“第一部分 xxxx”直接在标题“第1章 xxx”之上，但是不是很清楚该怎么设置，中间总会出现newpage

1. 本模板基於 `ctexbook`，並用 `\ctexset` 設置章節格式
2. 如果你想讓 `\part` 與 `\chapter` 之間不分頁，你需要設置兩個地方
   2.1 設置 `\chapter` 的 `break` 選項
   2.2 設置 `\part` 後的分頁
   也就是在導言區加上
    ```
    \ctexset{
      chapter = {
        break = {},
      }
    }
    \makeatletter
    \def\@endpart{%
      \CTEX@setheadingskip \CTEX@part@afterskip
      \ifodd \CTEX@part@fixskip \CTEX@fixheadingskip \fi
      \vskip \CTEX@headingskip
      \if@twoside
        \if@openright
          \null
          \thispagestyle{empty}%
        \fi
      \fi
      \if@tempswa
        \twocolumn
      \fi}
    \makeatother
    ```
   注意，這會導致 `\chapter` 之間不會分頁，如果『既要又要』，請自行在後續的 `\chapter` 前回調 `chapter/break`

> 问题二： 图注过长的时候，超过该页的部分不会显示，不知道该怎么设置比较好

什麽叫『过该页的部分』？

**Comment by SabriQ** [comment]
感谢你的回复。我算是新手，刚刚能看懂一些设置，还不能灵活地运用。
问题一: 确实是“既要又要”.依据你的设置后确实达到了效果，并且也出现了\chapter 不分页地问题，“回调`chapter/break`”怎么设置比较好？
问题二：“超过该页”的意思是，图注内容很多，一页装不下，那么多出来的部分不会跨页显示出来，二是就这么消失了。

**Comment by sikouhjw** [comment]
> “回调`chapter/break`”怎么设置比较好？

在第二個（即需要開始分頁的）`\chapter` 前添加
```tex
\makeatletter
\ctexset{
  chapter = {
    break = {\if@openright\cleardoublepage\else\clearpage\fi},
  }
}
\makeatother
```

> 问题二：“超过该页”的意思是，图注内容很多，一页装不下，那么多出来的部分不会跨页显示出来，二是就这么消失了。

需要可復現的代碼和示例截圖，如果你的意思是 `\caption` 内容太多導致内容溢出，這是不現實的。
- 浮動體會自動尋找位置存放
- 正常情況不會出現 `\caption` 的文字能占據一整頁
- 如果 `\caption` 的文字多到溢出了，可能會出現
   ```tex
   Dimension too large.
   \caption@slc ...ke {#1}{#2}}\ifdim \wd \@tempboxa 
   ```
   的報錯

請你檢查你是否使用了 `float` 宏包的 `H` 選項，以及 `\caption` 的内容是否多的不合理。

**Comment by SabriQ** [comment]
问题一： 已解决。非常感谢。
问题二：确实不是出现在`caption`或者`bicaption`中，准确来讲是在 ”图注“中，如下图。
![image](https://user-images.githubusercontent.com/12730409/217255287-aa6630fd-7679-4d8a-89f0-5a334fe45c6c.png)

**Comment by sikouhjw** [comment]
>  问题二：确实不是出现在`caption`或者`bicaption`中，准确来讲是在 ”图注“中

你的問題在於『子圖的説明文本』超過了頁面的限制，《中国科学院大学研究生学位论文撰写规范指导意见》[^1]沒有規定『子圖的説明文本』的格式規範，但是根據學術界的習慣，一般是用子圖宏包或者在 `\caption` 處書寫『子圖的説明文本』。

本模板給出了示例，應當遵循示例的指示不在子圖処輸出子圖的説明文本，而是在縂圖標題処輸出子圖的説明文本
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Tex/Chap_Guide.tex#L185-L213

那麽你的問題是不成立的，因爲子圖的説明文本應當寫在 `\caption` 内。

[^1]: http://www.las.cas.cn/yjsjy/pyyxw/xwglhj/201902/t20190201_5238746.html

**Comment by mohuangrui** [comment]
过长的图注没有意义，也过于极端，建议修改图注为合适长度，而不是追求实现极端功能，很简单：如果图注超过一页纸的容量，自然应该出错。
