### ISSUE TITLE
修改字体配置时编译出错

### ISSUE THREAD

**Issue by spwpun** [mohuangrui/ucasthesis#402]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux
  - [x] overleaf平台

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
修改字体配置时编译出错！
以下载Adobe字体。
修改的代码为Thesis.tex:14, `\documentclass[twoside,fontset=none]{Style/ucasthesis}%`
后续将`fontset` 改为 `Fontset` 能成功编译了！但这是为什么呢？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![image](https://user-images.githubusercontent.com/32606457/217262922-fd4b3610-4bd8-4600-a697-5449cb35ffb0.png)

**Comment by sikouhjw** [comment]
請提供可復現的代碼或 Overleaf 鏈接，按你的截圖去添加、修改字體，不會出現你説的問題

**Comment by spwpun** [comment]
> 請提供可復現的代碼或 Overleaf 鏈接，按你的截圖去添加、修改字體，不會出現你説的問題

https://www.overleaf.com/9592641589cxytyshkvbjk

**Comment by sikouhjw** [comment]
> https://www.overleaf.com/9592641589cxytyshkvbjk

手動修改字體名和路徑后仍然找不到字體，猜測是你修改了什麽地方。建議重新開一個模板再修改字體，其實不修改也無所謂。

建議 @mohuangrui 配置一下 Overleaf 自帶的思源字體 `Noto Serif CJK SC`[^1]，就不需要依賴外部字體了，改起來也挺麻煩。

[^1]: https://www.overleaf.com/learn/latex/Questions/Which_OTF_or_TTF_fonts_are_supported_via_fontspec%3F#Chinese

**Comment by spwpun** [comment]
> > https://www.overleaf.com/9592641589cxytyshkvbjk
> 
> 手動修改字體名和路徑后仍然找不到字體，猜測是你修改了什麽地方。建議重新開一個模板再修改字體，其實不修改也無所謂。
> 
> 建議 @mohuangrui 配置一下 Overleaf 自帶的思源字體 `Noto Serif CJK SC`[1](#user-content-fn-1-c707aa468fe738468b7b78a2e4ebbfe7)，就不需要依賴外部字體了，改起來也挺麻煩。
> 
> ## Footnotes
> 1. https://www.overleaf.com/learn/latex/Questions/Which_OTF_or_TTF_fonts_are_supported_via_fontspec%3F#Chinese [↩](#user-content-fnref-1-c707aa468fe738468b7b78a2e4ebbfe7)

重新试了下，是我字体下载错误了，导致找不到正确的字体。改为Fontset设置应该也只是参数被忽略而过了编译吧！
