### ISSUE TITLE
由于生僻字因素，将字体替换为Adobe,但是学位论文页生成样式与Fandol的不一致？

### ISSUE THREAD

**Issue by elfisworking** [mohuangrui/ucasthesis#403]
## 检查 / Check

- [X] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [X] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [X] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [X] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)
## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [X] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
平台为overleaf
由于生僻字因素，将字体替换为Adobe,但是学位论文页生成样式与Fandol的不一致。
修改方式，参照已经提供的文档，Adobe字体下载来源为文档中的github地址

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
Fandol
<img width="448" alt="截屏2023-02-09 下午3 28 18" src="https://user-images.githubusercontent.com/37609214/217747000-927e5eb7-347f-4723-8529-41425b1fab1c.png">
Adobe
<img width="467" alt="截屏2023-02-09 下午3 29 27" src="https://user-images.githubusercontent.com/37609214/217747222-7257aace-38d3-4a12-9290-6fa16dc4c17f.png">

**Comment by sikouhjw** [comment]
你想説的可能是『Adobe Song 的粗體』不如『Fandol Song 的粗體』那麽粗，這是因爲 Fandol 有真的粗體，而 Adobe 是用偽粗實現的。

如果你這麽糾結效果不同，你應該考慮使用 win 下的字體配置，而不是用 Adobe。所以，不要糾結。

**Comment by elfisworking** [comment]
thanks
