### ISSUE TITLE
文末参考文献列表的序号排版的左对齐/右对齐问题

### ISSUE THREAD

**Issue by ALONMARK** [mohuangrui/ucasthesis#404]
## 检查 / Check

- [ X] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ X] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ X] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ X] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ X] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ X] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
 国科大word模板中给出参考文献的著录列表中的序号例如（[1]-[10]）是按照左对齐排版的，但是latex模板编译出来是按照序号[10]的右对齐排版的，请问有没有哪里有命令可以修改这个对齐方式。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
word版本著录格式：
![word著录格式](https://user-images.githubusercontent.com/46768827/218483948-20cfdd9a-a6a3-4af5-9bc7-c206a92762cf.png)

latex编译出来著录格式：
![latex著录格式](https://user-images.githubusercontent.com/46768827/218483373-590a8f0b-67ab-4d5b-9fcf-8433a581f3a6.png)

**Comment by sikouhjw** [comment]
使用 `bibtex` 时，可以在导言区加以下代码[^1]：
```tex
\makeatletter
\renewcommand{\@biblabel}[1]{[#1]\hfill}
\makeatother

```

[^1]: https://tex.stackexchange.com/a/21309

**Comment by ALONMARK** [comment]
在mainmatter.tex里加了
\makeatletter
\renewcommand{\@biblabel}[1]{[#1]\hfill}
\makeatother
真的有用！感谢大佬！
