### ISSUE TITLE
中文标题过长在标题页不会换行

### ISSUE THREAD

**Issue by Tianluo-Qi** [mohuangrui/ucasthesis#405]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live <2021>
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：当中文标题过长时论文标题页面的中文标题不会自动换行而会直接超出整个页面。与之相对的，英文标题并不会出现这个问题。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/10791612/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
[中文标题太长.pdf](https://github.com/mohuangrui/ucasthesis/files/10791621/default.pdf)

**Comment by mohuangrui** [comment]
使用换行符 `\\`在需要的位置换行即可，英文的使用了换行符。

**Comment by sikouhjw** [comment]
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L152-L157
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L303-L307
把 `\uline` 换成可换行的也行，比如 `xeCJKfntef` 的 `\CJKunderline`。

即
```tex
\usepackage{xeCJKfntef}
```
再
```tex
\renewcommand{\ulunify}[1]{\CJKunderline{#1}}
```

**Comment by Tianluo-Qi** [comment]
“使用可换行版本的uline”这个解决方案更合适，因为如果手动添加换行符的话在页眉处也会变成两行，而原本因为页眉处的字体较小标题是可以不换行的。
