### ISSUE TITLE
数学公式的字体问题

### ISSUE THREAD

**Issue by Triumphal** [mohuangrui/ucasthesis#406]
发现问题是在使用数学公式的时候，在使用黑板粗体\mathbb{R}指令表示实数集的时候，字体比较奇怪（见下图），可能是由于使用了XITS 字体库的原因

|||
|--|--|
|![](https://user-images.githubusercontent.com/33827648/220520754-f787918e-67b0-4230-b9d0-11bb27bb0066.jpg)|![](https://user-images.githubusercontent.com/33827648/220520765-c6134b87-bccd-468e-9a16-9be488a3a4ba.jpg)|

但是使用amssymb包直接使用\mathbb{}看上去比较合适（见下图）。
|||
|--|--|
|![](https://user-images.githubusercontent.com/33827648/220520890-5a99a38f-b90f-4b24-9832-501357c99fc1.jpg)|![](https://user-images.githubusercontent.com/33827648/220521830-20055439-9bb0-4d91-b563-532b92141c3b.jpg)|

并且该模板中的数学公式中的字体似乎都比较偏粗体一点，实际的粗体的显示并不是那么的明显，不知道是设置的原因还是字体库就是这样。

- 因此是否能够使用将数学公式中的字体使用amssymb中的，毕竟公式多的时候，使用amssymb包中的数学表示看上去比较清晰一点。

主要是公式美观上的考虑。

**Comment by mohuangrui** [comment]
使用 XITS 是为了和Word版本相近（许多人有此诉求）。
如果你想进行修改：

从
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L382
开始注释，直到（包括）
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L417
然后在此后加入你需要的math字体package

**Comment by sikouhjw** [comment]
覆盖一下就好了，你需要的是找到『符合你审美』的字体。
```tex
\documentclass{article}
\usepackage{amsmath,unicode-math}
\setmathfont{XITS Math}
\setmathfont{Latin Modern Math}[range = bb]
\begin{document}
  $\symbb{ABCD}$
\end{document}
```

**Comment by Triumphal** [comment]
> 使用 XITS 是为了和Word版本相近（许多人有此诉求）。 如果你想进行修改：
> 
> 从
> 
> https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L382
> 
> 
> 开始注释，直到（包括）
> https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L417
> 
> 
> 然后在此后加入你需要的math字体package

是的，我将其替换成
\setmathfont{Latin Modern Math}
\setmathfont{TeXGyrePagellaMath-Regular}[range={\mathbb}]
解决了我的问题

**Comment by severus98** [comment]
> > 使用 XITS 是为了和Word版本相近（许多人有此诉求）。 如果你想进行修改：
> > 从
> > 
> >   
> >     
> >       [ucasthesis/Style/artratex.sty](https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L382)
> >     
> >     
> >          Line 382
> >       in
> >       [aec46ba](/mohuangrui/ucasthesis/commit/aec46ba1f621c537404cb631f54f6289b25a97af)
> >     
> >   
> >   
> >     
> > 
> >         
> >           
> >            \setmathfont{XITSMath-Regular}[ 
> >         
> >     
> >   
> > 
> > 
> > 开始注释，直到（包括）
> > 
> >   
> >     
> >       [ucasthesis/Style/artratex.sty](https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L417)
> >     
> >     
> >          Line 417
> >       in
> >       [aec46ba](/mohuangrui/ucasthesis/commit/aec46ba1f621c537404cb631f54f6289b25a97af)
> >     
> >   
> >   
> >     
> > 
> >         
> >           
> >            ] 
> >         
> >     
> >   
> > 
> > 
> > 然后在此后加入你需要的math字体package
> 
> 是的，我将其替换成 \setmathfont{Latin Modern Math} \setmathfont{TeXGyrePagellaMath-Regular}[range={\mathbb}] 解决了我的问题

对于想保留默认花体字母的情况，可以在这之后加上：
    \DeclareFontFamily{OMS}{cmsy}{\skewchar\font48 }
    \DeclareFontShape{OMS}{cmsy}{m}{n}{
    <-6> cmsy5
    <6-8> cmsy7
    <8-> cmsy10
    }{}
    \DeclareSymbolFont{CMcal}{OMS}{cmsy}{m}{n}
    \DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}

<img width="306" height="44" alt="Image" src="https://github.com/user-attachments/assets/82360d29-79f0-4c12-b49f-49ad696b3fe1" />
