### ISSUE TITLE
参考文献排序问题

### ISSUE THREAD

**Issue by SpencerChou** [mohuangrui/ucasthesis#407]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![image](https://user-images.githubusercontent.com/34341763/220631230-bff076e0-78d6-4840-94e0-ac4f6d855eaf.png)

## 最小工作示例(MWE) / Minimal Working Example 

我是在overleaf进行论文写作的，这些参考文献都没有在标题中出现，第一次在文章中引用，但是顺序却不是按照出现顺序的，暂时没在知识小站找到解决办法，里面说的是在 标题中出现引用才导致顺序的问题

**Comment by mohuangrui** [comment]
检查图表标题、多编译两次。我能提供的建议就这么多，这肯定是个人使用的问题。

**Comment by sikouhjw** [comment]
提供模板版本、模板从哪来的、设置了什么选项、编译方式是什么、Overleaf 的 texlive 版本是什么，请给出足以复现问题的信息

**Comment by SpencerChou** [comment]
我发现顺序 是我在ref.bib文件中放的参考文档的 顺序是一致的好像。。
模板是这个git库下载下来的，编译器是xelatex， tex live version 是2019 legacy

**Comment by mohuangrui** [comment]
你再次下载GitHub模版，在 Thesis.tex中改 authoryear 为 number，然后编译。你会发现顺序不会出错，也不是按照ref.bib内文献排序。
由此证明，你需要检查自己是如何引发你说描述的问题的。

**Comment by SpencerChou** [comment]
重新弄了一边还是这样。。。。算了，我也不知道 我具体在哪里弄错了什么。。到时候再调吧。。。

**Comment by sikouhjw** [comment]
> 重新弄了一边还是这样。。。。算了，我也不知道 我具体在哪里弄错了什么。。到时候再调吧。。。

你应该详细解释什么叫『重新弄了一边』。
1. 打开 https://www.overleaf.com/latex/templates/thesis-template-for-the-university-of-chinese-academy-of-sciences/fhbvbjrrgtwx
2. 将 `\usepackage[authoryear,list]{Style/artratex}` 改为 `\usepackage[number,list]{Style/artratex}`

![图片](https://user-images.githubusercontent.com/49770925/220651139-8fa20868-57c4-4241-9c01-a9d3ccabdf2b.png)
