### ISSUE TITLE
国科大新版latex论文模板编译存在的些许小warnings，是否可以忽略这些问题

### ISSUE THREAD

**Issue by yujietao-imp** [mohuangrui/ucasthesis#408]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live <2022>
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
使用了研究所教育处提供的国科大latex模板，文章可以正常编译输出，但是存在部分小问题。涉及模板文件，想咨询一下这些warnings是否可以忽略，是否需要去修正。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
C:\Users\TYJ\OneDrive\paper\Dissertation\Thesis.log

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
报错1：
![image](https://user-images.githubusercontent.com/126281344/221259300-fb09efe4-f60f-4620-a143-009690acfe26.png)
显示的报错位置：
![image](https://user-images.githubusercontent.com/126281344/221259535-eae48123-f90c-4456-b558-e749e734d2dd.png)
报错2：
![image](https://user-images.githubusercontent.com/126281344/221259742-de3c22ff-62a1-4cef-a603-d61a25438745.png)
涉及的位置2：
![image](https://user-images.githubusercontent.com/126281344/221259898-9fb2ef60-a977-418c-a134-454666da25bc.png)
报错3：
![image](https://user-images.githubusercontent.com/126281344/221260122-10f978f3-ac06-4cbe-92b4-e850134deb51.png)
涉及Style中的三个格式文件；
报错4：
(ctable)	Transparency disabled: pdfTeX is not running in PDF mode .

**Comment by sikouhjw** [comment]
1. 这不是报错，这是 warning
2. 都可以忽略

**Comment by yujietao-imp** [comment]
ok，那就不管了，谢谢
