### ISSUE TITLE
关于 \biband 不能输出 ”和“ 的问题

### ISSUE THREAD

**Issue by wzh621** [mohuangrui/ucasthesis#410]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
在 ucasthesis 模板第9页的例子中，在中文环境下，
若使用 \citet*{betts2005aging} 输出为 Betts and Taylor (2005) 无法将 “and” 转换成中文的”和“ 
若使用 \citet{betts2005aging} 输出为 Betts 等 (2005)

如何设置？ 使用 \citet{betts2005aging} 这个命令输出类似 Betts 和 Taylor (2005)这样的结果.

期待您的回复，谢谢！
## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by sikouhjw** [comment]
初步认为问题在于 bst 文件
```tex
\providecommand{\biband}{和}
\bibitem[Betts {\bibetal}(2005)Betts and Taylor]{betts2005aging}
Betts~L~R, Taylor~C~P.
\newblock Aging reduces center-surround antagonism in visual motion processing
  [J].
\newblock Neuron, 2005, 45\penalty0 (3): 361-366.
```
发现并没有使用 `\biband` 命令

**Comment by wzh621** [comment]
谢谢您的回复，我已经尝试将Biblio文件夹中的两个 .bst 文件中的
FUNCTION {bbl.and}
{ ”“ }
修改为
FUNCTION {bbl.and}
{ entry.lang lang.zh =
    { "和" }
    { entry.lang lang.ja =
        { "和" }
        { entry.lang lang.ru =
            { "идр" }
            { "and" }
          if$
        }
      if$
    }
  if$
 }
但是这并不起作用,期待您的回复，谢谢.

**Comment by sikouhjw** [comment]
得请教下 @zepinglee 了

**Comment by mohuangrui** [comment]
另一种方案是使用 biblatex， 见 [biblatex 启用](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#biblatex-%E5%90%AF%E7%94%A8)

默认设定下，即可自动显示2个或以下的全部作者。

如果需要显示3个或更多，见 [biblatex 样式设定](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#biblatex-%E6%A0%B7%E5%BC%8F%E8%AE%BE%E5%AE%9A)

如设定为
```Tex
mincitenames=1,maxcitenames=3
```

**Comment by wzh621** [comment]
十分感谢您的回复，问题已解决，谢谢谢谢谢！

**Comment by zepinglee** [comment]
默认应该跟国标一样，两个以上姓名时只标注第一个著者的姓名，其后附“等”或“et al.”。

如果要显示“A 和 B”可以将这里改成 `#3`。

https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Biblio/gbt7714-author-year.bst#L60

**Comment by lss-len** [comment]
#3 'citation.et.al.min :=

**Comment by lss-len** [comment]
#3 'citation.et.al.min :=使用这个命令解决了，谢谢啦
