### ISSUE TITLE
模板脚注问题

### ISSUE THREAD

**Issue by Weiyinyin11** [mohuangrui/ucasthesis#411]
您好，此模板中使用\footnote生成的脚注是带圆圈的数字，但是圆圈中的数字整体偏上，没有在中间位置。请问这个应该如何解决？
![image](https://user-images.githubusercontent.com/93064473/223010162-cac6edd6-9dae-4a6a-8ce8-4bb78b714c26.png)

**Comment by mohuangrui** [comment]
你好，此模板中\footnote生成的脚注是不带圆圈。如果你使用的带圆圈，应该不是用的该原始模板。此外，你的问题属于LaTeX的一般问题，请查阅你的代码设定及ctex文档。
