### ISSUE TITLE
在Overleaf中使用模板，遇到Overfull \hbox，编译后pdf发现确有文字溢出边界，请问如何处理？

### ISSUE THREAD

**Issue by Zhihaoiee** [mohuangrui/ucasthesis#412]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Linux (Overleaf)

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2022 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
各位前辈好，我在overleaf中尝试使用模板，编译器是XeLaTex，发现编译后的pdf中有些行有文字溢出边界，如下图。请问是否有解决办法？
谢谢帮助！

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：
[output.log](https://github.com/mohuangrui/ucasthesis/files/10942280/output.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![image](https://user-images.githubusercontent.com/92719845/224321534-2e78ee5a-1552-46d3-8718-4f2589961fa6.png)
![image](https://user-images.githubusercontent.com/92719845/224321941-f232d2f3-9126-4cd2-9f10-2e1e482d621e.png)

**Comment by sikouhjw** [comment]
1. 文本部分的溢出一般很少出现，调整语句即可
2. 数学公式的溢出，请适当使用多行公式

**Comment by Zhihaoiee** [comment]
谢谢帮助！
