### ISSUE TITLE
没有对模板做改动，使用numbers编码制，article类型的参考文献编译出来的文献类型是J/OL，是怎么回事？

### ISSUE THREAD

**Issue by chenchenxuexue** [mohuangrui/ucasthesis#413]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [x] CTeX

## 描述问题 / Problem Description

问题描述：没有对模板有修改，使用numbers编码制，Bib文件中引用文献写的都是@article，但是XeLatex+Bibtex+XeLatex+XeLatex编译出来的文献类型都是[J/OL]（理论上是[J]）。尝试过overleaf，texstudio和CTEX都是这样的。请问如何解决？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/10953090/Thesis.log)

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![问题截图](https://user-images.githubusercontent.com/127707842/224597740-dbb9f670-feba-456c-9ced-474a57164003.png)

**Comment by sikouhjw** [comment]
> 都是[J/OL]（理论上是[J]）

这是你的认知错误，`OL` 表示文献载体，跟 `J` 不存在冲突关系。

`OL` 的出现是因为你在 bib 文件里添加了 `doi` 选项，表示可以通过该链接获取文献，这也就出现了 `OL`。

所以，不需要去管，这不是错误。

如果你需要去掉 `OL`，请你阅读 `TEXDOC GBT7714` 或 `TEXDOC BIBLATEX-GB7714`。
