### ISSUE TITLE
如何只改动使得author-year格式英文引用为 et.al 而不改动中文 等 以符合最新要求

### ISSUE THREAD

**Issue by ghost** [mohuangrui/ucasthesis#414]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
目前我的做法是直接替换：
https://raw.githubusercontent.com/zepinglee/gbt7714-bibtex-style/master/gbt7714-2005-author-year.bst
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)

[wki中的方法](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F#%E5%B0%86%E8%8B%B1%E6%96%87%E5%BC%95%E7%94%A8%E4%B8%AD%E7%9A%84-%E5%92%8C%E7%AD%89-%E6%94%B9%E4%B8%BA-andet-al)
会导致全局改为英文而不是双语形式
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`]
## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：当前论文要求引文如下，可参见[原文](http://www.apm.cas.cn/yjsjy/xwgl/xwlw/202208/t20220829_6505171.html)

<img width="817" alt="image" src="https://user-images.githubusercontent.com/106246741/225506962-9d78d749-eda3-41be-91c4-24e3a96ff121.png">

如何只改动使得author-year格式英文引用为 et.al 而不改动中文 等 以符合最新要求

目前我的做法是直接替换：https://raw.githubusercontent.com/zepinglee/gbt7714-bibtex-style/master/gbt7714-2005-author-year.bst
但不知是否有其他问题存在

**Comment by sikouhjw** [comment]
1. `\usepackage[authoryear,list,biber]{Style/artratex}`
2. 将
    https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L587
    改为 `\def\bibetal{\ucas@label@en@bibetal}`
3. 清除辅助文件并使用 `biber`

**Comment by ghost** [comment]
使用biber的做法我不太熟悉，我目前的做法会有冲突吗，最好还是更新一下模板

**Comment by sikouhjw** [comment]
> 使用biber的做法我不太熟悉，我目前的做法会有冲突吗，最好还是更新一下模板

那就熟悉。`texdoc gbt7714` 默认就是中英不同的 `\bibetal`，是模板对其进行了修改才导致现在的问题，你如果有精力，建议你从模板找问题，用 `gbt7714-2005-author-year.bst` 不能保证格式是对的。

**Comment by ghost** [comment]
https://github.com/mohuangrui/ucasthesis/issues/95#issuecomment-453353961
>@zepinglee 已经根据你的建议弄好了，为了降低关联性，我将相关的宏封闭到了 cls 文件里，这样也就挺合理的了。再次感谢你的帮忙，你的维护工作量又增加了一个分支，幸苦了！

对比了一下改动前后的版本差异，应该没问题。

`biber`确实有优势，看有没有人更新一下模板吧

**Comment by mohuangrui** [comment]
方案1： sikouhjw 已经说了，用biber，不熟悉就熟悉一下，有没有冲突就测试一下，具体设定都已经告诉你了。
方案2：改回去 gbt7714 的bst，默认就是中英不同的 \bibetal。
至于更新修复什么的，还是先等等吧，谁知道又会凭空变出个什么问题，在没坑的地方凭空挖个坑，再反复填挖，大多数人可没这个时间陪玩。
