### ISSUE TITLE
图表目录中标题过长，首行带有缩进效果

### ISSUE THREAD

**Issue by cbx812** [mohuangrui/ucasthesis#415]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

使用国科大LaTeX模板[4.LaTeX.zip_20221006.zip](https://github.com/mohuangrui/ucasthesis/files/10997147/4.LaTeX.zip_20221006.zip)
 #324 中进行更改，但仍有图目录缩进问题，请问应该如何更改？

![image](https://user-images.githubusercontent.com/77186033/225793635-db991b57-c9a9-4c43-96e3-334265605ec3.png)

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![image](https://user-images.githubusercontent.com/77186033/225793391-384d17ef-b7b5-43b3-9a92-14faea6bb11e.png)

**Comment by mohuangrui** [comment]
你提到的发布基于ucasthesis进行了修改，其发布我不知情也不负责维护，请咨询相关部门和人员

On Mar 17, 2023, at 10:06 AM, cbx812 ***@***.***> wrote:

﻿

检查 / Check

  *    已阅读 提问流程<https://github.com/mohuangrui/ucasthesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%A6%82%E4%BD%95%E6%9C%89%E6%95%88%E5%9C%B0%E9%97%AE%E9%97%AE%E9%A2%98>
  *    确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
  *    已仔细阅读 LaTeX 知识小站<https://github.com/mohuangrui/ucasthesis/wiki>
  *    已查阅搜索 issues<https://github.com/mohuangrui/ucasthesis/issues?q=> 的 已关闭问题 closed issues<https://github.com/mohuangrui/ucasthesis/issues?q=>

编译环境 / Compilation Environment

  *   操作系统 / Operating System

     *    Windows 7/8/10
     *    macOS
     *    Linux
  *   TeX 发行版 / Tex Distribution

     *    TeX Live
     *    MiKTeX
     *    CTeX

描述问题 / Problem Description

问题描述：

使用国科大LaTeX模板4.LaTeX.zip_20221006.zip<https://github.com/mohuangrui/ucasthesis/files/10997147/4.LaTeX.zip_20221006.zip>
#324<https://github.com/mohuangrui/ucasthesis/issues/324> 中进行更改，但仍有图目录缩进问题，请问应该如何更改？
[image]<https://user-images.githubusercontent.com/77186033/225793391-384d17ef-b7b5-43b3-9a92-14faea6bb11e.png>

[image]<https://user-images.githubusercontent.com/77186033/225793635-db991b57-c9a9-4c43-96e3-334265605ec3.png>

日志文件 / .log file

将编译生成的 .log 文件拖入下行空白处：

问题截图 / Screenshots

将出现的问题或需要实现的效果的 截图照片 拖入下行空白处：

最小工作示例(MWE) / Minimal Working Example

**Comment by changguangsheng** [comment]
请问这个有解决方案么

**Comment by cbx812** [comment]
> 请问这个有解决方案么

我已经修改好了，可以发给你一份

**Comment by changguangsheng** [comment]
感谢您，邮箱是 linyi0430@gmail.com

**Comment by 2024dushaohui** [comment]
麻烦这个也发我一份好吗？谢谢

**Comment by 2024dushaohui** [comment]
我的邮箱是dushaohui@impcas.ac.cn,谢谢

**Comment by lemyx** [comment]
请问这个问题的解决方案是什么呀，感谢~！
