### ISSUE TITLE
bicaption生成的中英文图标标题时，其中一个较短，另一个较长，能否设置为短的居中，长的居左？

### ISSUE THREAD

**Issue by wusq121** [mohuangrui/ucasthesis#416]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live <2021>
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
bicaption生成的中英文图标标题时，其中一个较短，另一个较长，能否设置为短的居中，长的居左？
现在短的居左感觉有些不太好看，但是长的居中也不好看。

**Comment by mohuangrui** [comment]
首先你得给出一个何为长、何为短的严格数学定义，以及检测方式，个人倾向性的设定建议自行修改

**Comment by wusq121** [comment]
> 首先你得给出一个何为长、何为短的严格数学定义，以及检测方式，个人倾向性的设定建议自行修改

bicaption中长的自然是指占据两行以上，会自动居左的。短的就是指一行以内，自动居中的。然而，由于翻译问题，很多时候中文是一行，但是英文是两行，这个时候就会很难看。
自行修改的话，应该怎么修改可以实现bicaption两个括号中的内容自适应居中或者居左，你的文档中没有相关资料。

**Comment by sikouhjw** [comment]
> bicaption中长的自然是指占据两行以上，会自动居左的。短的就是指一行以内，自动居中的。然而，由于翻译问题，很多时候中文是一行，但是英文是两行，这个时候就会很难看。 自行修改的话，应该怎么修改可以实现bicaption两个括号中的内容自适应居中或者居左，你的文档中没有相关资料。

问题在于，学校没有规定当 `\bicaption` 超过一行时该怎么做。
居左、居中都是合理的，因为它们都是『居中』，只不过是标题内部的对齐方式不同。
而这部分内容，由于是『都可以』，那么模板也就没有必要、也没有义务去修改或提供修改的帮助，这纯粹是个人喜好问题。
你不能说因为我喜欢 A 样式，就必须让模板提供修改的方法，模板没有这个义务。

**Comment by wusq121** [comment]
> > bicaption中长的自然是指占据两行以上，会自动居左的。短的就是指一行以内，自动居中的。然而，由于翻译问题，很多时候中文是一行，但是英文是两行，这个时候就会很难看。 自行修改的话，应该怎么修改可以实现bicaption两个括号中的内容自适应居中或者居左，你的文档中没有相关资料。
> 
> 问题在于，学校没有规定当 `\bicaption` 超过一行时该怎么做。 居左、居中都是合理的，因为它们都是『居中』，只不过是标题内部的对齐方式不同。 而这部分内容，由于是『都可以』，那么模板也就没有必要、也没有义务去修改或提供修改的帮助，这纯粹是个人喜好问题。 你不能说因为我喜欢 A 样式，就必须让模板提供修改的方法，模板没有这个义务。

这不是需要模板应该怎么改的问题，而是我想改但是不知道怎么改，所以请教各位。
争论模板和学校的规定是没有意义的，更希望有大佬能给一个解决方案

**Comment by sikouhjw** [comment]
> 这不是需要模板应该怎么改的问题，而是我想改但是不知道怎么改，所以请教各位。 争论模板和学校的规定是没有意义的，更希望有大佬能给一个解决方案

问题在于，你说的是
> 能否设置为短的居中，长的居左？

这个需求并不明确，可以理解为将模板修改，也可以理解为想要一个解决方案。

将你的需求理解为：短的直接居中，长的整体居中、内部居左。
现在的情况为：都为短时，全部居中；有一个为长时，全部居左。

可以通过 `bicaption` 宏包的 `bi-slc=off` 选项来实现两个标题之间判断多行行为的分离。
```tex
\documentclass{article}
\usepackage{caption,bicaption}
\captionsetup{bi-slc=off}
\begin{document}
\begin{figure}
  \bicaption{test}{test test test test test test test test test test test test test test test test test test test test test test test}
\end{figure}
\end{document}
```

在模板中，做了其它处理，因此无法直接通过加选项来达到效果，请自行尝试。
