### ISSUE TITLE
怎么把图目录和表目录分开，而不是图目录下接着生成表目录啊

### ISSUE THREAD

**Issue by liu-123321** [mohuangrui/ucasthesis#417]
## 检查 / Check

- [x ] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ ] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x ] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
国科大最新的latex模板，表目录是紧挨着图目录生成的，怎么让表目录另起一页生成啊？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![1679319726261](https://user-images.githubusercontent.com/57864522/226357716-d1c93435-b6d8-47f2-aa41-ce926f1f90d2.png)

**Comment by sdusdl** [comment]
我是在figuretable.tex里在图目录和表目录中间加了1cm的垂直距离

**Comment by liu-123321** [comment]
> 我是在figuretable.tex里在图目录和表目录中间加了1cm的垂直距离

你好，能让我看下你的代码吗，刚开始用latex，不太熟练

**Comment by sdusdl** [comment]
我看你用的应该是在这个模板的基础上修改的版本，原始模板没有figuretable.tex这个文件。如果你用的模板里有figuretable.tex这个文件，可以做如下修改：
intobmk*{\cleardoublepage}{图表目录}
\thispagestyle{noheaderstyle}
{
\renewcommand*{\addvspace}[1]{}
\let\oldnumberline\numberline%
\renewcommand{\numberline}{\figurename~\oldnumberline}%
\listoffigures%
}
\vspace{1cm}%在表目录前添加1cm的垂直距离
{
\let\cleardoublepage\relax
\let\clearpage\relax
\renewcommand*{\addvspace}[1]{}
\let\oldnumberline\numberline%
\renewcommand{\numberline}{\tablename~\oldnumberline}%
\listoftables%
}

**Comment by sdusdl** [comment]
我看你用的应该是在这个模板的基础上修改的版本，原始模板没有figuretable.tex这个文件。如果你用的模板里有figuretable.tex这个文件，可以做如下修改：
\intobmk*{\cleardoublepage}{图表目录}
\thispagestyle{noheaderstyle}
{
\renewcommand*{\addvspace}[1]{}
\let\oldnumberline\numberline%
\renewcommand{\numberline}{\figurename~\oldnumberline}%
\listoffigures%
}
\clearpage%另起一页
{
\let\cleardoublepage\relax
\let\clearpage\relax
\renewcommand*{\addvspace}[1]{}
\let\oldnumberline\numberline%
\renewcommand{\numberline}{\tablename~\oldnumberline}%
\listoftables%
}

**Comment by liu-123321** [comment]
> 我看你用的应该是在这个模板的基础上修改的版本，原始模板没有figuretable.tex这个文件。如果你用的模板里有figuretable.tex这个文件，可以做如下修改： \intobmk*{\cleardoublepage}{图表目录} \thispagestyle{noheaderstyle} { \renewcommand*{\addvspace}[1]{} \let\oldnumberline\numberline% \renewcommand{\numberline}{\figurename~\oldnumberline}% \listoffigures% } \clearpage%另起一页 { \let\cleardoublepage\relax \let\clearpage\relax \renewcommand*{\addvspace}[1]{} \let\oldnumberline\numberline% \renewcommand{\numberline}{\tablename~\oldnumberline}% \listoftables% }

已经解决，十分感谢！

**Comment by ghost** [comment]
新规word里图表目录也是在一页里的，按照官方模板编译之后，如果图表目录跨页，会出现第一页的页眉是“表目录”，第二页页眉是“图表目录”，这个dirty hack有点问题
<img width="786" alt="image" src="https://user-images.githubusercontent.com/106246741/226923842-4045154f-5191-47bc-b8f5-20aded5ca20b.png">
<img width="796" alt="image" src="https://user-images.githubusercontent.com/106246741/226923869-0bf1cc52-f426-4cc3-98b2-36593b320f65.png">

**Comment by ghost** [comment]
#267 似乎修改模板的人使用了这段代码，
目前我改了一点不会在第一页生成页眉"表目录"了，但是第二页本应该是标题，不知道怎么改，过两天看看
```
\intobmk*{\cleardoublepage}{图表目录}
\fancyhead{} % 清空默认的页眉内容
\fancyhead[C]{\footnotesize 图表目录} % 将页眉设置为“图表目录”
{
\renewcommand*{\addvspace}[1]{}
\let\oldnumberline\numberline%
\renewcommand{\numberline}{\figurename~\oldnumberline}%
\listoffigures%
}
{
\let\cleardoublepage\relax
\let\clearpage\relax
\renewcommand*{\addvspace}[1]{}
\let\oldnumberline\numberline%
\renewcommand{\numberline}{\tablename~\oldnumberline}%
\listoftables%
}
```

**Comment by liu-123321** [comment]
> 新规word里图表目录也是在一页里的，按照官方模板编译之后，如果图表目录跨页，会出现第一页的页眉是“表目录”，第二页页眉是“图表目录”，这个dirty hack有点问题 <img alt="image" width="786" src="https://user-images.githubusercontent.com/106246741/226923842-4045154f-5191-47bc-b8f5-20aded5ca20b.png"> <img alt="image" width="796" src="https://user-images.githubusercontent.com/106246741/226923869-0bf1cc52-f426-4cc3-98b2-36593b320f65.png">

把 thesis.tex 中的\fancyhead[C]{\footnotesize 图表目录}改为\fancyhead[C]{\footnotesize 表目录}就行了

**Comment by ghost** [comment]
现行是这样的，和word是一致的

<img width="668" alt="image" src="https://user-images.githubusercontent.com/106246741/226947121-c31d8e0e-0b0e-4399-9e68-b2456495b50d.png">

我们这里规定是按照新版要求来，但是按照新版只要图表到第二页，页眉就会变，我觉得你可能误解了我的意思，我不确定是不是需要单开一个issue去讨论这个问题。

另外，按照你的设置分页的话，第二页因为已经是偶数页，按照word里的要求，不应该设置为表目录，而是应该设置为标题。应该做的是修改第一页为图表目录。

我不确定管这些格式有没有意义。用tex就是为了省事而已。

目前我想到一个比较脏的方法在修改`figuretable.tex`基础上：
```
\intobmk*{\cleardoublepage}{图表目录}
\fancyhead{} % 清空默认的页眉内容
\fancyhead[C]{\footnotesize 图表目录} % 将页眉设置为“图表目录”
{
\renewcommand*{\addvspace}[1]{}
\let\oldnumberline\numberline%
\renewcommand{\numberline}{\figurename~\oldnumberline}%
\listoffigures%
}
{
\let\cleardoublepage\relax
\let\clearpage\relax
\renewcommand*{\addvspace}[1]{}
\let\oldnumberline\numberline%
\renewcommand{\numberline}{\tablename~\oldnumberline}%
\listoftables%
}
```

修改`thesis.tex `中的`\fancyhead[C]{\footnotesize 图表目录}`为  `\fancyhead[LE]{\centering \footnotesize 中文标题}`%此处填写中文标题`

这样可以在不分页图表目录时正确显示页眉

**Comment by mohuangrui** [comment]
你提到的发布基于ucasthesis进行了修改，其发布我不知情也不负责维护，请咨询相关部门和人员
