### ISSUE TITLE
每章的标题如何取消加粗，例如”第2章 xxxx“这段文本如何取消加粗

### ISSUE THREAD

**Issue by wmathor** [mohuangrui/ucasthesis#418]

**Comment by sikouhjw** [comment]
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L607-L619
在导言区加上
```tex
\ctexset{chapter/format+={\mdseries}}
```

**Comment by wmathor** [comment]
> https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L607-L619
> 
> 
> 在导言区加上
> ```
> \ctexset{chapter/format+={\mdseries}}
> ```

谢谢
