### ISSUE TITLE
中文参考文献中标题和文献标识存在空格

### ISSUE THREAD

**Issue by cbx812** [mohuangrui/ucasthesis#419]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

参考文献样式改为上标顺序编码制（super）后
中文参考文献中标题和文献标识存在空格，而英文参考文献正常紧贴，请问如何修改中文参考文献样式？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

![image](https://user-images.githubusercontent.com/77186033/228151095-89a05e0b-c7d6-41c6-a93f-6f227f41ebdf.png)

**Comment by cbx812** [comment]
非常感谢各位，已经找到解决办法：
#1 'space.before.mark :=改为#0 'space.before.mark :=即可

**Comment by mohuangrui** [comment]
这应该是中英双语排版的内嵌机制，若局部修改，很难找到一条不出错又简单的判定准则，建议不用管这种没用的细节

**Comment by cbx812** [comment]
回复：最后采用了最笨的方法，在每个中文标题后加\hspace{0em}强制取消空格。
