### ISSUE TITLE
这个logo放大不失真，呵呵

### ISSUE THREAD

**Issue by zhanglinbo** [mohuangrui/ucasthesis#42]
[ucas_logo.pdf](https://github.com/mohuangrui/ucasthesis/files/1832150/ucas_logo.pdf)

**Comment by mohuangrui** [comment]
非常感谢！已采用并更新。

**Comment by xiaoyao9933** [comment]
这个logo的作者路过。

**Comment by mohuangrui** [comment]
@zhanglinbo 是这样的？

@xiaoyao9933 谢谢你的工作，我将在下次更新时将：

“更新 ucas_logo.pdf 使得封面中的学校 logo 放大不失真，问题/建议由 zhanglinbo 提出。”

改为

“使用 xiaoyao9933 制作的 ucas_logo.pdf 使得封面中的学校 logo 放大不失真，问题/建议由 zhanglinbo 提出。”

@xiaoyao9933 请问大神你是怎么做到的呢？我Google到的方法，虽然能将位图格式转成矢量图格式，却不能真正矢量化，多谢指教～

**Comment by xiaoyao9933** [comment]
@HuangruiMo 恩，是我做的，链接在这里。
https://github.com/xiaoyao9933/UCASthesis/blob/master/figures/ucaslogo.pdf

左边的中科院圆形logo，在我以前的ucasthesis模板里用过，好多年前了，似乎是从国科大官方的svg资源获取到的。右边的字体是通过super vectorize软件矢量化得到的。然后整体通过Illustrator合并，都是土办法。。

**Comment by mohuangrui** [comment]
@xiaoyao9933 哈哈哈，原来经过这么多道工艺才合成得到，难怪我Google到的快捷方法都不能真正矢量化。谢谢你的付出，我将在下次更新时说明并链接你的工作。谢谢！

**Comment by zhanglinbo** [comment]
是这样的，这个logo来自@xiaoyao9933模板，感谢二位所做的工作！

**Comment by hotchilipowder** [comment]
这个版本的logo的圆矢量化有点问题，可以直接从官网下载原版Ai的图，然后用Ai导出就可以了。

https://www.ucas.edu.cn/site/11?zu=64925

[ucas-logo.pdf](https://github.com/mohuangrui/ucasthesis/files/7385582/ucas-logo.pdf)
