### ISSUE TITLE
论文类别设置

### ISSUE THREAD

**Issue by Diison** [mohuangrui/ucasthesis#420]
## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

<img width="650" alt="微信图片_20230418122130" src="https://user-images.githubusercontent.com/32377341/232662774-16449a76-2e66-4a5a-86be-eb51c059f5fd.png">

仅仅是建议：把论文封面的学位和英文论文学位耦合在一起是没有道理的，反直觉，不利于使用。

**Comment by sikouhjw** [comment]
没太理解你的意思，可以详细点吗

**Comment by Diison** [comment]
不好意思，现在印象不是很清晰了，大概是在选择 硕士论文/博士论文 的时候，需要从论文的英文版里面改，这个不是很直观。如果能在论文开始的部分定义一个指示论文类别的变量，中文中文英文都引用这个变量应该会好点。


此致



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月18日(周二) 中午12:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mohuangrui/ucasthesis] 论文类别设置 (Issue #420)




 
没太理解你的意思，可以详细点吗

**Comment by AroundKiki** [comment]
> 没太理解你的意思，可以详细点吗

论文首页学校logo下面的“硕士/博士学位论文”这行字，具体学位实际上依赖的是定义英文学位的\DEGREE命令，而不是定义中文学位的\degree。因为定义中文信息的代码在英文上面，改完中文之后发现论文的学位不对，是有些反直觉的。比如我一通搜索到了这里，发现把中英文都改了就ok了。
