### ISSUE TITLE
参考文献的姓无法实现全大写

### ISSUE THREAD

**Issue by Tianluo-Qi** [mohuangrui/ucasthesis#421]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2022
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
在自己电脑上试了很多方案都无法实现参考文献列表中的姓全大写（包括在），于是利用readme中提供的overleaf链接在overleaf上试了一下，发现依然无法实现参考文献列表中的姓全大写。在overleaf上同一个文件夹中写了一个很简单的MWE（test.tex），调用xeCJK、biblatex，并且在biblatex中选择style=Biblio/gb7714-2015，编译后发现这个MWE的参考文献列表中的姓是正常全大写的。不知道如何解决这种情况。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

这是我自己overleaf中该项目的链接，添加了前面所说的test.tex文件，其余文件都是直接通过readme中的overleaf链接创建的。
https://www.overleaf.com/9951545111fkmmzmwtbwwb

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by sikouhjw** [comment]
你认为：参考文献列表的作者姓名『需要』大写。

学校规范：『不需要』大写[^1]。
![图片](https://user-images.githubusercontent.com/49770925/233821909-9bcf685f-44fa-43de-b1c0-8dd995137f78.png)

模板实现：『不需要』大写。

[^1]: 中国科学院大学研究生学位论文撰写规范指导意见 http://www.ihep.cas.cn/edu/pyxs/xwsh/202111/P020211125369236788182.pdf

**Comment by mohuangrui** [comment]
见：

https://github.com/mohuangrui/ucasthesis/wiki/文献样式#修改参考文献列表的默认排版行为

修改
```
#0 'uppercase.name :=
```

为 
```
#1 'uppercase.name :=
```
