### ISSUE TITLE
如何取消正文章之间的空白页？

### ISSUE THREAD

**Issue by qwert2333** [mohuangrui/ucasthesis#423]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
您好，我查了一下2022版《国科大研究生学位论文专业规范指导意见》，里面要求“中文摘要、英文摘要、目录、论文正文、参考文献、附录、致谢、作者简历及攻读学位期间发表的学术论文与其他相关学术成果等，均须由另页右页（奇数页）开始。”，“正文内部新章节无序另页右页（奇数页）开始“。
我还是在用twoside格式实现摘要、目录等的右起页，但是我应该如何取消正文各章之间的空白页？
谢谢！

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：

**Comment by fxyha** [comment]
看到有人提出过相同的问题，下面有大佬回复，我试了一下发现是可行的
```
%---------------------------------------------------------------------------%
%->> Main content
%---------------------------------------------------------------------------%
\let\savecleardoublepage\cleardoublepage% save cleardoublepage function
\renewcommand{\cleardoublepage}{\clearpage}% start to deactivate cleardoublepage
\input{Tex/Chap_Intro}
\input{Tex/Chap_Guide}
\let\cleardoublepage\savecleardoublepage% reactivate cleardoublepage
%---------------------------------------------------------------------------%
```

**Comment by mohuangrui** [comment]
就是如上处理
