### ISSUE TITLE
页眉分割线和第一行之间的距离太小了，请问有什么方法可以放大吗？

### ISSUE THREAD

**Issue by cydn** [mohuangrui/ucasthesis#424]
## 检查 / Check

- [ x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [ x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [ x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [ x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ x] TeX Live <2022>
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
页眉分割线和第一行之间的距离太小了，请问有什么方法可以放大吗？

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

[Uploading Thesis.log…]()

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![problem](https://github.com/mohuangrui/ucasthesis/assets/56541408/e2a14ca2-f97e-4336-881d-64ed63bbd137)

**Comment by sikouhjw** [comment]
上海科技大学跟本模板有什么关系吗？

**Comment by mohuangrui** [comment]
修改如下行的head相关的参数：

https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L668
