### ISSUE TITLE
声明页如何插入多段内容

### ISSUE THREAD

**Issue by yujietao-imp** [mohuangrui/ucasthesis#425]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live <2023>
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
根据研究所要求要修改授权声明，修改ucasthesis.cfg文件后要不无法显示两段文字要不两段文字换段后没有首行空两格，且可能存在日期到下一页的问题

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
需要修改成的声明如图所示：
![2d582599c06e8114392c26a8ec81c50](https://github.com/mohuangrui/ucasthesis/assets/126281344/f6d92c15-647c-4264-aa54-2e75bff39ec4)

**Comment by yujietao-imp** [comment]
现在生成的版本
![image](https://github.com/mohuangrui/ucasthesis/assets/126281344/148ccf2c-7248-493a-9d59-70078f1bf1ef)

**Comment by mohuangrui** [comment]
修改：
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cfg#L111
