### ISSUE TITLE
2023版要求更改了参考文献字号，求问如何更改。急

### ISSUE THREAD

**Issue by nnadbb** [mohuangrui/ucasthesis#427]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [x] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：
国科大2023版的参考文献内容字号的要求从2022版的五号改成了小四号，不知道在哪里能够更改该字号的设定。已经善用搜索在ucasthesis.cls里找到了很多zihao，但是不知道改哪个。

## 日志文件 / .log file

将编译生成的 `.log` 文件拖入下行空白处：

## 问题截图 / Screenshots
将出现的问题或需要实现的效果的 `截图照片` 拖入下行空白处：
![image](https://github.com/mohuangrui/ucasthesis/assets/134696045/251fedb0-9df0-45dc-8e33-2bdc854493f0)

**Comment by sikouhjw** [comment]
https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L689
改成
```tex
\renewcommand*{\bibfont}{\zihao{-4}}
```
或者
```tex
\renewcommand*{\bibfont}{}
```
