### ISSUE TITLE
使用algorithm2e包编辑算法

### ISSUE THREAD

**Issue by yoopaan** [mohuangrui/ucasthesis#429]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [x] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [x] TeX Live  2023
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述： 如何在模板中使用algorithm2e
algorithm2e包支持代码竖线对齐功能，但是和模板自带的algorithm包不兼容。

理想格式:
```latex
\documentclass{article}
\usepackage{graphicx} % Required for inserting images

\usepackage[ruled,vlined]{algorithm2e} %带竖线和折线

\title{algo_vlined}
\author{yaopan }
\date{July 2023}

\begin{document}

\maketitle

\section{Introduction}


\begin{algorithm}
%\SetAlgoLined
%\SetAlgoNoLine %去掉竖线
\SetKwData{Left}{left}\SetKwData{This}{this}\SetKwData{Up}{up} \SetKwFunction{Union}{Union}\SetKwFunction{FindCompress}{FindCompress} \SetKwInOut{Input}{input}\SetKwInOut{Output}{output}
	
	\Input{A bitmap $Im$ of size $w\times l$}
	\Output{A partition of the bitmap}
	 \BlankLine
	
	 \emph{special treatment of the first line}\;
	 \For{$i\leftarrow 2$ \KwTo $l$}{
	 	\emph{special treatment of the first element of line $i$}\;
	 	\For{$j\leftarrow 2$ \KwTo $w$}{\label{forins} \Left$\leftarrow$\FindCompress{$Im[i,j-1]$}\;
	 	\Up$\leftarrow$ \FindCompress{$Im[i-1,]$}\;
	 	\This$\leftarrow$ \FindCompress{$Im[i,j]$}\;
	 	\If(\tcp*[h]{O(\Left,\This)==1})
	 		{\Left compatible with \This}{\label{lt}
	 			\lIf{\Left $<$ \This}{\Union{\Left,\This}}
	 			 \lElse{\Union{\This,\Left}} }
 	    \If(\tcp*[f]{O(\Up,\This)==1}){\Up compatible with
 			 	 \This}{\label{ut}
 			 	 \lIf{\Up $<$ \This}{\Union{\Up,\This}}
 			 	 \tcp{\This is put under \Up to keep tree as flat as possible}\label{cmt} \lElse{\Union{\This,\Up}}\tcp*[h]{\This linked to \Up}\label{lelse}
 		 	  }
 	 	   }
 		 \lForEach{element $e$ of the line $i$}{\FindCompress{p}}
 	 }
 	 	  \caption{disjoint decomposition}
 	 	  \label{algo_disjdecomp}
\end{algorithm}


\end{document}

```

效果预览:
![image](https://github.com/mohuangrui/ucasthesis/assets/38783332/86979e79-d8fb-4e83-aaaa-26f0c3e7a9d2)

## 问题截图 / Screenshots

尝试在ucasthesis模板中使用:
1. 注释掉了algorithm.sty中的所有内容
2. 导包后用上面相同的代码进行测试，编译通过，但是格式还有一定的问题:
![image](https://github.com/mohuangrui/ucasthesis/assets/38783332/02786fce-1061-445e-96df-68b11bf77e86)

请教如何正确使用algorithm2e包

**Comment by sikouhjw** [comment]
你所谓的区别在于：
1. 行距较大
2. `\emph` 变下划线

解决方案：
1. 在算法环境内修改
    https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/ucasthesis.cls#L130-L133
    或者谷歌一下
2. 谷歌

**Comment by mohuangrui** [comment]
可对如下行进行替换修改：

https://github.com/mohuangrui/ucasthesis/blob/aec46ba1f621c537404cb631f54f6289b25a97af/Style/artratex.sty#L613
