### ISSUE TITLE
需要在图中添加很长的“注”来对图片进行注释（写在\fignote{}{}里），“注”显示不全不能显示到下一页中且会侵入到页脚，请问大佬这该如何解决。

### ISSUE THREAD

**Issue by harleyhou** [mohuangrui/ucasthesis#436]
## 检查 / Check

- [x] 已阅读 [提问流程](https://github.com/mohuangrui/ucasthesis/wiki/常见问题#如何有效地问问题)
- [ ] 确认问题为关于 ucasthesis 编译和设计的问题，而非 LaTeX 的一般知识性问题
- [x] 已仔细阅读 [LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki)
- [x] 已查阅搜索 [issues](https://github.com/mohuangrui/ucasthesis/issues?q=) 的 [已关闭问题 `closed issues`](https://github.com/mohuangrui/ucasthesis/issues?q=)

## 编译环境 / Compilation Environment

- `操作系统 / Operating System`
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- `TeX 发行版 / Tex Distribution`
  - [ ] TeX Live 
  - [x] MiKTeX 21.20
  - [ ] CTeX

## 描述问题 / Problem Description

问题描述：

Latex模板中插入图片的“注” 这里内内容多，无法显示全也无法自动显示到下一页，我使用的代码是：
```
\begin{figure}[!htbp]
    \centering
    \includegraphics[width=1\textwidth]{Fig31}
    \bicaption{通过筛选，胡萝卜喂食小鼠可有效减脂。
}{Carrot diet can reduce fat in mice effectively.}
	\fignote{这里有着超级多的文字描述……特别多一页放不下}{这里是超级多的英文……很多}
    \label{fig:31}
\end{figure}
```
新的国科大的Latex模板出现了\fignote的使用，我尝试使用了，发现文字显示不全且不会显示到下一页。这样：
![PixPin_2024-02-13_21-17-09](https://github.com/mohuangrui/ucasthesis/assets/159913921/0dfe6e35-4349-410f-ac33-afca25891d5c)

尝试过使用下面的方法,也显示不全：
```
\begin{figure}[htb]
\centering
\includegraphics[width=3.5in]{images/chapter5/hysteresis_rate_different.eps}
\caption[这里的文字显示在list of figures里]{这里的文字显示在图片下方}
\label{ceramic}
\end{figure}
```

## 问题截图 / Screenshots

![PixPin_2024-02-13_21-17-09](https://github.com/mohuangrui/ucasthesis/assets/159913921/0dfe6e35-4349-410f-ac33-afca25891d5c)
请问如何将没有显示完的“注”完整地显示出来？非常感谢

![PixPin_2024-02-13_21-20-55](https://github.com/mohuangrui/ucasthesis/assets/159913921/0e21ceab-8bb1-4ba6-8c3c-3e4b4f0523ee)

## 最小工作示例(MWE) / Minimal Working Example 

```
\begin{figure}[!htbp]
    \centering
    \includegraphics[width=1\textwidth]{Fig31}
    \bicaption{通过筛选，胡萝卜喂食小鼠可有效减脂。
}{Carrot diet can reduce fat in mice effectively.}
	\fignote{这里有着超级超级超级多的文字描述……特别多一页放不下}{这里是超级超级超级多的英文……很多是前面花括号的翻译}
    \label{fig:31}
\end{figure}
```

**Comment by SheffieldWang** [comment]
好像不需要写英文图注吧？

**Comment by harleyhou** [comment]
要求要有英文图注，没办法，我最终的解决方法是：把注写在正文里，行距字体大小修改成要求的样子，至于什么传说的“首行缩进悬挂两个字符”，没看到要求，不理会它了。
