### ISSUE TITLE
请问参考文献引用2个作者的怎么是A et al？怎么改成A和B

### ISSUE THREAD

**Issue by zhurong0107** [mohuangrui/ucasthesis#44]
请问参考文献引用2个作者的怎么是A et al？怎么改成A和B，谢谢

**Comment by mohuangrui** [comment]
使用  \citet*{} 就可以显示所有作者

**Comment by zhurong0107** [comment]
谢谢，但是是A,B and C,请问and能改成‘和’吗

**Comment by zhurong0107** [comment]
我用的\usepackage[authoryear]{Style/artratex}，这样作者就是名字和年份的组合那种，但是最后的参考文献没有序号，这个能让它显示序号吗？

**Comment by mohuangrui** [comment]
那个 and 要改的话只能你自己手动去修改 Biblio 里的 bst 文件了，或者可以考虑求助 zepinglee <https://github.com/zepinglee>/gbt7714-bibtex-style <https://github.com/zepinglee/gbt7714-bibtex-style> 。 至于authoryear的样式，规范就是不加序号的，因为用authoryear必须是通过author来索引而不是序号，这也是authoryear的目的。

**Comment by zhurong0107** [comment]
好的，非常感谢您！另外咨询一下为什么我生成的目录还有小节的标题都不是黑体的，只有正文的章的标题是黑体的。

**Comment by zhurong0107** [comment]
需要我再提问一下，而不是在这个问题下面描述吗？

**Comment by mohuangrui** [comment]
你确定不是黑体？？？根据官方规范，只有章的是黑体加粗，其他的是黑体不加粗，所以，你还是仔细对比下。再有，请确认讨论的是最新版。

**Comment by zhurong0107** [comment]
是最新的版本，我刚运行了您的版本，生成的PDF和您自带的PDF的目录是不一样的字体，不是黑的，是和正文一样的字体，可能和我的运行环境或者编译什么的有关，我也不懂，不知道怎么改

**Comment by mohuangrui** [comment]
请把你的Thesis.log文件发过来

**Comment by zhurong0107** [comment]
[Thesis.log](https://github.com/mohuangrui/ucasthesis/files/1839975/Thesis.log)

**Comment by mohuangrui** [comment]
呃，请用 xelatex 编译，尽量不要考虑 pdflatex 编译

**Comment by zhurong0107** [comment]
另外院里给了个格式要求，是去年底的新要求。顺序是：文献、附录、致谢、简历，但是和您的模板顺序（附录、文献、简历、致谢）不一致，请问您那边的要求是您模板中的顺序吗？

**Comment by zhurong0107** [comment]
xelatex 有错，一直enter也不行，可能我编辑器或者哪里有问题吧，我再看看。

**Comment by mohuangrui** [comment]
这个你自己可以随意调整啊，请花点时间读下使用说明文档吧。至于官方要求的附录放到文献后，我是无法理解的。。。难道附录里不用cite文献？？？反正你可以自己随意调增，随你便

**Comment by zhurong0107** [comment]
是的，我也觉得您的顺序合理！谢谢

**Comment by mohuangrui** [comment]
请读下使用说明文档吧，里面有完全的排错指南，谢谢！再有，xelatex有错就请卸载MikTeX改装Texlive。MikTeX维护的越来越有问题了。

**Comment by zhurong0107** [comment]
好的，谢谢提醒

**Comment by mohuangrui** [comment]
你好，关于黑体失效的问题，仍建议你使用xelatex而不是pdflatex，若MikTeX出错无法解决，就安装Texlive。另外，请查看最新的更新说明，这也可能是潜在的原因之一，而且是一个很偶然的Bug：

回答部分同学遇到的英文标题字体设为 Times New Roman 后目录及节标题黑体失效的问题，并进一步完善说明文档
