### ISSUE TITLE
请问图表采用了\bicaption中英文标题，文章开始创建图表目录的时候，也是中英文都显示，怎么只显示中文目录就行？谢谢

### ISSUE THREAD

**Issue by zhurong0107** [mohuangrui/ucasthesis#45]
请问图表采用了\bicaption中英文标题，文章开始创建图表目录的时候，也是中英文都显示，怎么只显示中文目录就行？谢谢

**Comment by mohuangrui** [comment]
请查看最新版

**Comment by zhurong0107** [comment]
看到了，新版本可以，谢谢！

**Comment by DarcySail** [comment]
您好，我用“英文”，“标题”等关键字搜索了仓库，确实没有找到您说的可以只显示中文标题的设置项。
不是所有使用者都对LaTeX那么熟悉啊，能否请您明示一下我该怎么修改？
