### ISSUE TITLE
章节标题数字字体、footnote编号和url颜色

### ISSUE THREAD

**Issue by ZeroCrystal** [mohuangrui/ucasthesis#46]
您好！
最近使用模板，发现了几个问题。
1. 章节标题中的数字字体看起来很奇怪，而且有时候编译后会上浮一段空间，很奇怪；
2. 使用脚注\footnote的时候，如果在不同章（chap）里，脚注会重新编号，请问能不能按全文顺序编号；
3. url链接红色看着有点花哨。。。

以上，感谢！

**Comment by mohuangrui** [comment]
1. 请阅读说明文档：
若需设置字体库，请选择 xelatex 或 lualatex 编译引擎，并设置需要的字

体库。如用 Times New Roman 作为英文字体，在 artratex.sty 中设置:

\setmainfont{Times New Roman} (设置正文英文字体) 

\setsansfont{Times New Roman} (设置标题英文字体) 

至于你说的上浮一段空间，请给出案例，否则我无法理解。。。

2. 这个请自行查阅资料吧，再者，专业的学术论文不建议使用脚注的形式转递信息，非常低效也不便阅读。

3. 请看说明文档：
档内超链接的颜色及其显示: 

在artratex.sty中修改\hypersetup ，url就改urlcolor就行。

**Comment by ZeroCrystal** [comment]
谢谢~
我用的旧版没注意，sorry~
不过关于“专业的学术论文不建议使用脚注的形式转递信息，非常低效也不便阅读”，不敢苟同，看专业领域吧，一般数据集和项目地址等采用脚注表明在顶会paper经常出现。这个我自己解决~
不过还是感谢~

**Comment by mohuangrui** [comment]
嗯，你的情况确实不一样些，难怪你那么在乎url的颜色。。。
对了，我昨晚再对模板进行了更新，特别是关于设置标题为Times字体的问题，其可能在某些LaTeX版本导致黑体失效，若遇到，请查看更新说明：
回答部分同学遇到的英文标题字体设为 Times New Roman 后目录及节标题黑体失效的问题，并进一步完善说明文档

**Comment by gsp2014** [comment]
> 谢谢~
> 我用的旧版没注意，sorry~
> 不过关于“专业的学术论文不建议使用脚注的形式转递信息，非常低效也不便阅读”，不敢苟同，看专业领域吧，一般数据集和项目地址等采用脚注表明在顶会paper经常出现。这个我自己解决~
> 不过还是感谢~

您好，“使用脚注\footnote的时候，如果在不同章（chap）里，脚注会重新编号，请问能不能按全文顺序编号”这个问题最后是怎么解决的呢？

**Comment by mohuangrui** [comment]
@gsp2014 这个你搜索一下就可以知道，可见 [Continuous footnote numbering
](https://tex.stackexchange.com/questions/10448/continuous-footnote-numbering)

即：

1. 如果你的 LaTeX 编译器早于2018年，可在 `artracom.sty` 中加入：
```
\RequirePackage{chngcntr}
\counterwithout{footnote}{chapter}
```

2. 如果你的 LaTeX 编译器为2018年的甚至更新，只需在 `artracom.sty` 中加入：
```
\counterwithout{footnote}{chapter}
```

**Comment by gsp2014** [comment]
太感谢师兄啦，时间比较紧，就直接求助了: )

**Comment by mohuangrui** [comment]
@gsp2014 没事，祝一切顺利：D

**Comment by gsp2014** [comment]
谢谢师兄(๑•̀ㅂ•́)و✧
