### ISSUE TITLE
使用新模版生成的pdf论文进行知网论文查重问题

### ISSUE THREAD

**Issue by MELCHIOR-1** [mohuangrui/ucasthesis#47]
你好，我是电子所的博士，在写大论文，非常感谢你为我们提供国科大的模版。

我现在遇到一个问题，使用你的新版模版编译出来的pdf到知网查重，正文后的参考文献部分不能被正确识别，也被当成正文处理，导致重复率很高。而我同学使用你的旧版模版就没问题。我看了一下，主要是2个模版使用的bst文献格式不一样。旧版的使用的是gbt-7714-2015-numerical.bst文件，而新版的使用gbt7714-unsrt.bst文件。

你们之前遇到过这种问题没？另外，我想知道使用新版的gbt7714-plain.bst的话是否也有问题？

**Comment by mohuangrui** [comment]
上述 bst 都是 zepinglee 开发的适用 Bibtex 的参考文献国标样式，后者是前者的更新版。不清楚你说的问题是否真是由于bst文件所致，毕竟两者在格式上没有明显区别，更有可能是你的参考文献的特殊性吧。否则，你可以将gbt-7714-2015-numerical.bst重命名为gbt7714-unsrt.bst，然后替换到你的当前文档内试试，个人觉得由于这个的可能性不大。。。
