### ISSUE TITLE
模版小需求

### ISSUE THREAD

**Issue by martin2011** [mohuangrui/ucasthesis#48]
您好，能否添加如下需求，
 1）封面，中文导师信息的单位写在第二行。
 2） 参考文献，英文文献，作者正常格式就行，不要全部都是大写。

谢谢！

**Comment by mohuangrui** [comment]
你好，
1）这个可以啊，比如：

\advisor{刘青泉~研究员}% supervisor
\advisorsec{中国科学院力学研究所}% co-supervisor

若要调整位置，请看使用说明。

2）这个是按照国标走的，若要修改，请查看说明文档内关于bst文件的部分，即查阅bst开发者的Github

祝好！

**Comment by martin2011** [comment]
好的。谢谢!（还是建议把参考文献大写的问题调整一下！）

**Comment by mohuangrui** [comment]
@martin2011 谢谢建议，但官方指导内英文名也是按照国标全部采用大写。
