### ISSUE TITLE
设置数学公式里面的英文字体

### ISSUE THREAD

**Issue by zwyzwy** [mohuangrui/ucasthesis#51]
你好，数学公式里面的英文字体好像不是times new Roman，请问如何设置成改格式？

**Comment by mohuangrui** [comment]
你好，没见这个要求啊，要求的是宋体：

![image](https://user-images.githubusercontent.com/7518165/37978020-061585ea-31b3-11e8-8251-544d5d00c153.png)

如果你想改，请试试在修改英文字体的命令后加：

'''
\setmathrm{⟨font name⟩}
\setmathsf{⟨font name⟩}
\setmathtt{⟨font name⟩
\setboldmathrm{⟨font name⟩}
'''
font name 就是你想要的字体，你可以都设成 Times New Roman，若出问题，就只设置 \setmathrm。

祝好

**Comment by zwyzwy** [comment]
你好，如果表格的长度超过一个页面，如果在下一页继续显示表格，而不是直接截断了？

**Comment by mohuangrui** [comment]
请问你试了数学字体吗？结果如何？我想知道一下你的测试结果，以决定处理方案。
表格如果过长，是会截断，其实官方指导中也建议不要有过长的表格，如果坚持要用，请看 #49

**Comment by zwyzwy** [comment]
数学字体我试了下斜体字比较自然，\mathit{}
不是斜体的话总看起来不自然

**Comment by mohuangrui** [comment]
你好，字体问题已经解决，请测试最新版。
