### ISSUE TITLE
请问致谢的人名有复杂的汉字，如‘玥’ ，编译出来显示的方框里面带个F，请问怎么能显示出这个字？谢谢

### ISSUE THREAD

**Issue by zhurong0107** [mohuangrui/ucasthesis#52]
如题

**Comment by mohuangrui** [comment]
你好，这个问题由于Thesis.tex中的fontset=fandol所导致，因为fandol字库字体不全，请移除此option即可，其潜在的副作用可能为封面宋体加粗变为黑体，请暂时接受封面字体的潜在切换。我将在近期对模版进行再次更新，以期待能够最后给出一个较为理想的解决方案。

**Comment by zhurong0107** [comment]
我把fandol 改成 windows 就可以显示了，确实封面宋体加粗变为黑体了。期待您的改进。谢谢！

**Comment by mohuangrui** [comment]
不用谢，问题的本质还是缺乏一个完整的免费的中文字库。我将在近期改为一个折衷的办法，因为还有其他的字体bug问题，所以需要一点时间把事情理清楚。谢谢你们的耐心。

**Comment by mohuangrui** [comment]
你好，模板已更新，问题已解决，请测试最新版
