### ISSUE TITLE
请问参考文献作者是大写，但是H\"{a}rdle这种，为什么a不能显示大写？

### ISSUE THREAD

**Issue by zhurong0107** [mohuangrui/ucasthesis#53]
我采用的是文中引用也显示作者的那种格式，即\usepackage[authoryear]{Style/artratex}， 如果bib文件此处为H\"{a}rdle，则参考文献显示为H\"{a}RDLE，引用的文中显示为H\"{a}rdle；
如果bib文件改成H\"{A}RDLE，则参考文献显示为H\"{A}RDLE，但是引用的文中显示为H\"{A}rdle，即前两个字母都是大写的。
我希望的结果是参考文献显示为H\"{A}RDLE，引用的文中显示为H\"{a}rdle，请问可以改吗？谢谢！

**Comment by mohuangrui** [comment]
不好意思，最近忙着格式上的更新，没来及关注你的问题，等有时间时我测试一下，但最终若真有问题，还得转移到 https://github.com/zepinglee/gbt7714-bibtex-style

**Comment by zhurong0107** [comment]
我刚试了去掉 { } 的情况，就是我想要的了，已经解决了。麻烦您了，谢谢。

**Comment by mohuangrui** [comment]
那太好了，是的，{} 符号在.bib文件中具有固定输出格式的作用。
