### ISSUE TITLE
subfigure多子图中最后一个图的图中文字会被加粗

### ISSUE THREAD

**Issue by ZeroCrystal** [mohuangrui/ucasthesis#55]
subfigure多子图中最后一个图的图中文字会被加粗
如图

**Comment by ZeroCrystal** [comment]
![bold](https://user-images.githubusercontent.com/21877608/38196226-5b76aa2c-36b4-11e8-9d00-d6d87ecbd534.PNG)

**Comment by mohuangrui** [comment]
不知你的图片是什么格式？

**Comment by ZeroCrystal** [comment]
直接插的pdf，基本每个subfigure环境都会出现一次这样的

**Comment by mohuangrui** [comment]
可以把你的插图代码和一张图片发过来么？

**Comment by mohuangrui** [comment]
问题出在你的图片输出格式上了，你的绘图软件输出图片时不应该启用transparency。见：

“I guess you are using Adobe Reader? If you use transparency in your illustrations, it seems that Adobe Reader renders text incorrectly (something like the wrong gamma correction in anti-aliasing perhaps), which makes the text look a bit too bold. It should look OK if you use other PDF readers, and it should also look OK when printed from Adobe Reader.

A simple solution is to avoid using transparency whenever possible.

You can remove transparency from existing PNG images using graphics editors like GIMP or Photoshop, or with a command-line program like ImageMagick. With ImageMagick, the command `convert image.png  -background white  -alpha off  image_new.png` will remove the transparency”

`https://tex.stackexchange.com/questions/141/why-are-some-pages-in-my-pdf-coming-out-bold`

**Comment by jindongwang** [comment]
@mohuangrui 我也出现了这样的问题。我的图输出格式都是一样的，我也试着交换了一下，发现总是最后一个图被模糊。所以我觉得不是图的问题。请问你现在这个问题解决了吗？谢谢！

**Comment by mohuangrui** [comment]
@jindongwang 你好，关于此问题的详细解决方案，请见 [图中文本渲染错误出现异常加粗](https://github.com/mohuangrui/ucasthesis/wiki/字体配置)

**Comment by jindongwang** [comment]
@mohuangrui 我就是看了这个不行才问的，就很诡异，图都是一起生成的，并不是说加粗了的图是单独生成的。有的子图却是好的。我把好的放到加粗的位置，就加粗了。所以我觉得不是图的问题，模版可能对特定位置就加粗？包括最新我开的那个issue，也是有的地方莫名其妙正文就加粗了

**Comment by mohuangrui** [comment]
解决方案里并没有只是说图的问题，也提供了其他的解决方法，请仔细阅读并尝试

**Comment by jindongwang** [comment]
我确实都试过了不行。。。

**Comment by jindongwang** [comment]
你 看，我这个截图里，下面这两个subfigure是正常的。这时候我如果把这个正常的subfigure放到右上角这个不正常的位置，它就也会不正常。所以我觉得不是图的问题，是不是特定位置有冲突啥的？不好意思，我确实不懂，问题可能有点啰嗦，请多包涵！
![qq 20190307215036](https://user-images.githubusercontent.com/6158206/53961242-14cab300-4123-11e9-8e4c-0c8427a3f899.png)

**Comment by mohuangrui** [comment]
1. 可考虑使用 .jpg 或 .png 等位图格式， 可消除问题。
2. 如果不想修改图本身，则可考虑对每一个 \includegraphics{} 命令进行如下处理：
```
\begingroup
\fontspec{Times New Roman}{\color{white}.}%
\includegraphics{plot}
\endgroup
```

**Comment by jindongwang** [comment]
谢谢！原来用这个不行，现在可以了，非常感谢！
