### ISSUE TITLE
希望参考文献方式除了著者-出版年制，还添加顺序编码制著录的选择

### ISSUE THREAD

**Issue by lyumeng** [mohuangrui/ucasthesis#56]
希望参考文献方式除了著者-出版年制，还添加顺序编码制著录的选择，毕竟后者的方式更适合科技类论文的写作习惯，有些所就要求是顺序编码制著录。
https://github.com/hushidong/biblatex-gb7714-2015便提供了GB7714-2015顺序编码制的biblatex style package。谢谢！

**Comment by mohuangrui** [comment]
你好，当前将authoryear设为默认是应学位办的老师的建议，如果需要将authoryear改为顺序编，只需将 Thesis.tex中的：
```
\usepackage[authoryear,myhdr,list]{Style/artratex}% document settings
```
改为
```
\usepackage[numbers,myhdr,list]{Style/artratex}% document settings
```
如果你需要的是上标顺序编，就是：
```
\usepackage[super,myhdr,list]{Style/artratex}% document settings
```
