### ISSUE TITLE
表达式与编号间用“...”连接

### ISSUE THREAD

**Issue by mnpengjk** [mohuangrui/ucasthesis#57]
![issue](https://user-images.githubusercontent.com/35996868/38225388-40ca48c8-3727-11e8-9a88-f8626b05a263.png)

按“指导意见”，表达式与编号间用“...”连接，我用了如下代码暂时解决这个问题
\usepackage{mathtools}
\newtagform{myequationstyle}{...(}{)}
\usetagform{myequationstyle}

不知道有没更好的方式，或者作者大大顺手修改下？

**Comment by JunhuaPAN** [comment]
The »mathtools« package provides the macros \newtagform and \usetagform which allow to do this quite comfortable.

**Comment by mohuangrui** [comment]
你们好，我也留意到了这个规定，谢谢你们的建议。目前我实不确定这些点号的意义是什么，国科大本科部的陆晴老师在请学位办的丁云云老师多次审核时也没有提这个问题，所以目前暂且不考虑加入这个，而且mathtools会自动启用较多的数学字体宏包，不是很理想，有时默认安装的MikTex还会出现mathtools的宏包错误，所以，目前先这样了～谢谢大家的建议和反馈
