### ISSUE TITLE
老师好 请问这个模板所需要的软件是哪个版本？

### ISSUE THREAD

**Issue by zhao181** [mohuangrui/ucasthesis#58]

**Comment by mohuangrui** [comment]
你好，请尽量使用Miktex或是Texlive的最新版本

**Comment by zhao181** [comment]
谢谢老师， 我后来看到了那个模板pdf说明， 发现了textlive， 谢谢您， 这个模板很漂亮


发自网易邮箱大师
在2018年4月4日 21:15，mohuangrui<notifications@github.com> 写道：

你好，请尽量使用Miktex或是Texlive的最新版本
