### ISSUE TITLE
奇偶页问题

### ISSUE THREAD

**Issue by ahyuan** [mohuangrui/ucasthesis#59]
每一章总是以奇数页开始，偶数页结束。但假如一章是奇数结束，那么偶数页应该是空白页，页眉页脚也不应该出现在这一空白页，而这个模板是空白页也有页眉页脚，请问这个问题怎么解决？谢谢

**Comment by mohuangrui** [comment]
你好，当前ucasthesis的设定与学位办发布的word内的设定一致。如果你想改，请修改 ucasthesis.cls 内的 cleardoublepage 的定义即可。或是参考最新版的致谢部分所提供的样例。
