### ISSUE TITLE
can't use bibtex generated from zotero

### ISSUE THREAD

**Issue by lingdian618** [mohuangrui/ucasthesis#6]
I can run the example code.
But when I use bibtex file generated from zetero, something is wrong.

Below are some log information:

Package natbib Warning: Citation `shapleske_computational_2002' on page 1 undef
ined on input line 16.

! Undefined control sequence.
<argument> \let \@tempa \bibinfo@X@doi
                                       10.1093/cercor/12.12.1331
l.21 ...{\bibinfo{doi}{10.1093/cercor/12.12.1331}}

I guess it's related to \bibliographystyle, but I am not sure.
I need your help.

**Comment by mohuangrui** [comment]
Hi,

"Tools like Zotero are useful to get an overview over the used literature and cited parts.  However, they often produce faulty bib files; for example, Zotero exports the abstact and other parts not usually used in BiBTeX files, containing wrong letters or missed field end sign } or ". "

So you need to delete those extra fields in Zetero before using it for LaTex.
The above answer is from StackExchange:

http://tex.stackexchange.com/questions/269796/problems-to-export-zotero-to-bibtex-natbib-error-and-jabref-error

Cheers,
Mo Huangrui
