### ISSUE TITLE
参考文献[S.l.]的错误问题

### ISSUE THREAD

**Issue by qingsongma** [mohuangrui/ucasthesis#60]
您好，目前模板中的参考文献会出现[S.l.]的错误，我参考一个文档里说明，把gtb7714-unsrt替换成gtb7714-2005，仍然存在这个错误。请问这个问题怎么解决？谢谢！ @mohuangrui @HuangruiMo @minixbeta

**Comment by mohuangrui** [comment]
你好，这不是错误，请见 #28
