### ISSUE TITLE
关于表格标题居中问题

### ISSUE THREAD

**Issue by twn1993** [mohuangrui/ucasthesis#64]
> 正常表格标题都可以居中，但是只是有一章全部左对齐了，代码和其他章节一样，那一章也没有什么特别之处，换成\caption之后中文也能居中，不知道是什么原因，望大神指点，代码如下：
\begin{table}[!htbp]
    \centering
    \footnotesize% fontsize
    \setlength{\tabcolsep}{4pt}% column separation
    \renewcommand{\arraystretch}{1.2}%row space 
    \bicaption{300 K下，几种常见二元化合物半导体材料的能带物理参量}{Energy band physical parameters of several common binary compound semiconductor materials at 300K}
    \begin{tabular}{lcccccc}
        \hline
        \quad& GaAs&AlAs&InAs&AlP&GaP&InP \\
        \hline
        $E_g(\Gamma)$(eV) & $1.423$ & $3.003$&$0.354$&$3.553$&$2.77$&$1.353$ \\
        $E_g(X)$(eV)      & $1.889$ & $2.164$&$1.370$&$2.488$&$2.273$&$2.273$\\
        $E_g(L)$(eV)      & $1.707$ & $2.352$&$1.070$&$3.538$&$2.643$&$1.943$\\
        $\Delta_{so}$(eV)      & $0.341$ & $0.28 $&$0.39 $&$0.07$&$0.08$&$0.108$\\
        \hline
    \end{tabular}
	\label{tab:2}
\end{table}
生成的表格如下：
![123](https://user-images.githubusercontent.com/22016048/38486233-f7ca3718-3c0e-11e8-9e89-76c7a92159c9.JPG)

**Comment by mohuangrui** [comment]
你好，
1. 建议先看下： [ucasthesis 和 LaTeX 知识小站](https://github.com/mohuangrui/ucasthesis/wiki) 的 [LaTeX 写作的思维模式](https://github.com/mohuangrui/ucasthesis/wiki/LaTeX-%E5%86%99%E4%BD%9C%E7%9A%84%E6%80%9D%E7%BB%B4%E6%A8%A1%E5%BC%8F)
2. 然后你遇到的不是问题，而是默认的正常设置：当标题短时居中，当标题长度超过一行时左对齐并悬挂缩进非第一行。如果你想全部居中，可在 artratex.sty中将
```
\RequirePackage[font={small,bf},skip=8pt,labelsep=space]{caption}%
```
改为
```
\RequirePackage[font={small,bf},skip=8pt,labelsep=space,justification=centering]{caption}%

```

祝好
