### ISSUE TITLE
Linux下字体的问题。

### ISSUE THREAD

**Issue by byronwwang** [mohuangrui/ucasthesis#65]
您好！我看到在artratex.sty文件里关于字体的设置，没有linux的。麻烦问下，linux下需要如何进行相应设置。
![image](https://user-images.githubusercontent.com/6510742/38594737-50b79516-3d7a-11e8-9c35-4a4c47dff057.png)

**Comment by mohuangrui** [comment]
Linux下采用ctex的默认配置，ctex在Linux下使用fandol字体，fandol字体字重完备，可以正常显示粗宋体，所以artratex.sty中无需额外配置。

但是fandol字体字库相对较小，所以如果你的论文有较多生僻字，可能无法正常显示。这时，你就要考虑在你的Linux上安装其他字体了，比如Windows的或是MacOS的或是其他来源的比如Adobe中文字体。

**Comment by mohuangrui** [comment]
是的，安装好字体后，只需在 Thesis.tex 中指定 fontset 即可，如 fontset=windows、fontset=mac、 fontset=adobe 等。

顺便提一下，使用Windows 的字体时可能会出现无法正常拷贝PDF中的文本到其他文本编辑器的情况，这个问题好处就是你的论文自动被保护了，如果你想避免这个问题，可以使用MacOS或是Adobe字体。

Adobe 字体的下载只需 google Adobe 字体的各个名字即可找到源，如：

Adobe字体下载源1:

[Adobe Github](https://github.com/mingchen/mac-osx-chinese-fonts/tree/master/Adobe%20Simple%20Chinese%20Fonts)

Adobe 下载源2

[AdobeSongStd](https://cs.fit.edu/code/projects/ndworld/repository/changes/Resources/Fonts/AdobeSongStd-Light.otf?rev=12)
[AdobeHeitiStd-Regular](https://cs.fit.edu/code/projects/ndworld/repository/changes/Resources/Fonts/AdobeHeitiStd-Regular.otf?rev=12)
[ AdobeKaitiStd-Regular](https://cs.fit.edu/code/projects/ndworld/repository/changes/Resources/Fonts/AdobeKaitiStd-Regular.otf?rev=12)
[AdobeFangsongStd-Regular](https://cs.fit.edu/code/projects/ndworld/repository/changes/Resources/Fonts/AdobeFangsongStd-Regular.otf?rev=11)

**Comment by hjr0** [comment]
> 是的，安装好字体后，只需在 Thesis.tex 中指定 fontset 即可，如 fontset=windows、fontset=mac、 fontset=adobe 等。
> 
> 顺便提一下，使用Windows 的字体时可能会出现无法正常拷贝PDF中的文本到其他文本编辑器的情况，这个问题好处就是你的论文自动被保护了，如果你想避免这个问题，可以使用MacOS或是Adobe字体。
> 
> Adobe 字体的下载只需 google Adobe 字体的各个名字即可找到源，如：
> 
> Adobe字体下载源1:
> 
> [Adobe Github](https://github.com/mingchen/mac-osx-chinese-fonts/tree/master/Adobe%20Simple%20Chinese%20Fonts)
> 
> Adobe 下载源2
> 
> [AdobeSongStd](https://cs.fit.edu/code/projects/ndworld/repository/changes/Resources/Fonts/AdobeSongStd-Light.otf?rev=12)
> [AdobeHeitiStd-Regular](https://cs.fit.edu/code/projects/ndworld/repository/changes/Resources/Fonts/AdobeHeitiStd-Regular.otf?rev=12)
> [ AdobeKaitiStd-Regular](https://cs.fit.edu/code/projects/ndworld/repository/changes/Resources/Fonts/AdobeKaitiStd-Regular.otf?rev=12)
> [AdobeFangsongStd-Regular](https://cs.fit.edu/code/projects/ndworld/repository/changes/Resources/Fonts/AdobeFangsongStd-Regular.otf?rev=11)
“使用Windows 的字体时可能会出现无法正常拷贝PDF中的文本到其他文本编辑器的情况”这个问题有取巧的办法可以解决没？刚好遇到这个问题了
