### ISSUE TITLE
something wrong with fontset=times

### ISSUE THREAD

**Issue by byronwwang** [mohuangrui/ucasthesis#67]
抱歉，又发现了新的问题。通过fontset=times，报如下错误：
![image](https://user-images.githubusercontent.com/6510742/38606024-9065a78e-3da7-11e8-988f-ff89a110a3a7.png)
我的系统是linux。
本来是打算解决论文英文首页不是黑体的问题，通过设置fontset=<windows|times>报错，然后测试fontset=times发现上述错误。不知如何解决。

**Comment by mohuangrui** [comment]
你好，如果使用widnows的字体，请只用设定fontset=windows即可。请在安装windows中文字体时，也顺便安装英文字体 Times New Roman。
