### ISSUE TITLE
新版论文指导意见中的一点修改

### ISSUE THREAD

**Issue by htyeim** [mohuangrui/ucasthesis#69]
您好，今年好像改了一些指导意见（http://www.igg.cas.cn/jyyd/xueweiguanli/jy_xuewei_papers/201803/t20180307_4970813.html），其中大部分应该是一样的，不过我目前发现的一点是列参考文献中的问题。
根据指导意见的第13页中的内容：

> 参考文献表中的条目（不排序号），先按语种分类排列，**语种顺序**是：**中文**、日文、**英文**、俄文、其他文种。然后，中文和日文按第一著者的姓氏笔画排序，中文也可按汉语拼音字母顺序排列，西文和俄文按第一著者姓氏首字母顺序排列。

不知道这个是不是需要修改bst文件？

**Comment by mohuangrui** [comment]
你好，请测试下最新版，确认问题存在再问问题，谢谢
