### ISSUE TITLE
每一个章节都会有一个多余的空白页

### ISSUE THREAD

**Issue by xiaoleihuang** [mohuangrui/ucasthesis#7]
每一个章节都会有一个多余的空白页，请问如何去掉？是因为style里使用了\newpage之类的命令吗？

**Comment by xiaoleihuang** [comment]
已经解决···根文件Thesis里换成这个...\documentclass[single-sided]

**Comment by DarcySail** [comment]
再次遇到这种情况，可以烦请作者将相关说明加入到正文的说明文档中吗？

**Comment by mohuangrui** [comment]
@DarcySail 你好，ucasthesis 无法成为一部百科全书。或许你需要的不是一个更祥实的文档，而是更多的冷静思考和获取更多的常识。为何会有那些空白页？请了解下什么是双面排版。

再者，其实这些信息都已给出，只是你自己不愿去花时间认真读读：

```
\documentclass[doublesided]{Style/ucasthesis}%
%- Multiple optional arguments:
%- [<singlesided|doublesided|printcopy>]% set one or two sided eprint or print
```
