### ISSUE TITLE
新版本生成的PDF文字嵌入问题

### ISSUE THREAD

**Issue by bomb2peng** [mohuangrui/ucasthesis#70]
你好，我用新版本生成的PDF文字嵌入有问题，如一句话“然而技术往往是把双刃剑”从PDF中拷贝过来变成了”􂝦􃘼􁢰􁵟􁖰􁖰􁱟􁢺􀧼􀠳􀢁“，看起来像乱码。在PDF中查找一些词也由于这个原因找不到。请问是否遇到该问题？该怎么修复？
谢谢！

**Comment by mohuangrui** [comment]
你好，这个问题似乎是由于PDF对Windows字体的兼容性问题。解决办法请见：[字体配置](https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE)

**Comment by sty1992928** [comment]
我在ubuntu或mac下生成的pdf也遇到这个问题，将内容拷贝到windows下的txt文档中时有些字会显示不出来，都是一些很常见的字，不生僻。这个问题会导致知网查重的时候提示编码错误，请问有解决方法没。

**Comment by mohuangrui** [comment]
@sty1992928 你好，文档在ubuntu 或是 mac 上拷贝应是不会出问题的吧？若拷贝到windows出问题，那就是windows的问题。解决办法仍是使用adobe字体。国内很多系统的开发常局限于windows，这种偏向一时也变不过来，若是查重用，你就在windows上编译吧。。。

不管怎样，这个bug目前的解决只能是依赖adobe字体，具体请见：[字体配置](https://github.com/mohuangrui/ucasthesis/wiki/%E5%AD%97%E4%BD%93%E9%85%8D%E7%BD%AE)

**Comment by Ricemeal** [comment]
windows 用户可能需要右键”为所有用户安装”四个字体
