### ISSUE TITLE
使用fontset = windows / fontset = adobe 时的EPS图片文字渲染问题

### ISSUE THREAD

**Issue by easyfan327** [mohuangrui/ucasthesis#73]
您好，当设置字体为windows或adobe时，文中的EPS格式图片中的文字会部分变成如下图示的样子：
![image](https://user-images.githubusercontent.com/5843794/38726257-387b86ce-3f3c-11e8-854a-ad446f5474ca.png)
（即文字加粗了很多倍）
在使用fandol字体集时没有类似问题

**Comment by mohuangrui** [comment]
你好，这个问题已在 #55 提出，问题的解答在 [tex.se](https://tex.stackexchange.com/questions/141/why-are-some-pages-in-my-pdf-coming-out-bold) 上有。总结如下：

1. 这是当使用Adobe Reader PDF 阅读器时会存在，换其他阅读器或打印时不会有渲染问题。
2. 问题的出现是由于你导出图片时启用了透明度（transparency）。
