### ISSUE TITLE
Appendix中有长表格，表格字体设为\footnotesize时，会影响Backmatter正文字体大小

### ISSUE THREAD

**Issue by weichanglong** [mohuangrui/ucasthesis#77]
附录中的表格，是从正文移到Appendix的，附录表格的字号用\footnotesize命令。结果发现，附表A.1的字号会影响后面的个人简介和致谢部分的正文字号（字号很小）。

当注释掉附表A.1中\footnotesize命令，Backmatter部分的正文字号正常。但这时附表A.1的表题字号远小于表内字号。不知道什么原因。修改附表A.2的\footnotesize命令，对Backmatter部分没有影响。

还请解惑，谢谢！

![image](https://user-images.githubusercontent.com/32944481/39206189-4cba7202-482f-11e8-9ed4-db066d15f2a0.png)
这是有\footnotesize命令

![image](https://user-images.githubusercontent.com/32944481/39206128-23ff3cc6-482f-11e8-8a83-7d09548a3586.png)
这是注释\footnotesize命令后

**Comment by mohuangrui** [comment]
魏同学你好，请把你的代码贴出来

**Comment by weichanglong** [comment]
% Table generated by Excel2LaTeX from sheet '工作表1'
\chapter{}
%\footnotesize% fontsize 	 
\begin{longtable}{ccccccc}
 
\caption[水样采集信息及水质数据]{水样采集信息及水质数据\\Table.~\ref{tab:water_sample} The information of water samples.}
\label{tab:water_sample} \\ % add \\ command to tell LaTeX to start a new line	   
 % Appear table header at the first page as well
   
\hline
\multirow{2}[1]{*}{\textbf{样品名称}} & \multirow{2}[1]{*}{\textbf{经度/˚}} & \multirow{2}[1]{*}{\textbf{纬度/˚}} & \textbf{DO} & \multirow{2}[1]{*}{\textbf{pH}} & \textbf{电导率} & \textbf{取样深度} \\
          &       &       & \textbf{ /(mg/L)} &       & \textbf{/(μs/cm)} & \textbf{(m)} \\    
\hline
\endfirsthead
    
    % Appear the table header at the top of every page
\hline
\multirow{2}[1]{*}{\textbf{样品名称}} & \multirow{2}[1]{*}{\textbf{经度/˚}} & \multirow{2}[1]{*}{\textbf{纬度/˚}} & \textbf{DO} & \multirow{2}[1]{*}{\textbf{pH}} & \textbf{电导率} & \textbf{取样深度} \\
          &       &       & \textbf{ /(mg/L)} &       & \textbf{/(μs/cm)} & \textbf{(m)} \\           
\hline
\endhead
    
\hline
\endfoot 
    
\multicolumn{7}{c}{\textcolor[rgb]{0.016, 0.196, 1.000}{\textbf{江苏省非工业区地下水}}} \\
\hline
    XZ-1  & 117.997246 & 34.47333 & 3.54  & 7.14  & 1028  & 7 \\
    XZ-2  & 117.608158 & 34.065483 & 7.2   & 6.95  & 1233  & 12 \\
    XZ-3  & 117.301944 & 34.328889 & 7.93  & 6.77  & 1181  & 40 \\
    XZ-4  & 117.458611 & 34.428056 & 4.9   & 6.99  & 1381  & 10 \\
    XZ-5  & 116.607821 & 34.575267 & 9.42  & 6.94  & 854   & 10 \\
    XZ-6  & 118.345949 & 34.317655 & 4.14  & 7.18  & 897   & 18 \\
    XZ-7  & 117.028599 & 34.51632 & 1.56  & 7.04  & 2880  & 40 \\
    XZ-8  & 117.028599 & 34.51632 & 3.43  & 7.33  & 1139  & 20 \\
    XZ-9  & 117.33686 & 34.241008 & 5.77  & 7.04  & 1510  & 10 \\
    LYG-1 & 119.151672 & 34.154273 & 7.04  & 6.93  & 1215  & 4 \\
    LYG-2 & 119.163117 & 34.147403 & 6.58  & 7.1   & 894   & 40 \\
    LYG-3 & 118.908786 & 34.574782 & 7.85  & 7.26  & 863   & 3 \\
    LYG-4 & 119.502679 & 34.317442 & 2.01  & 7.48  & 2120  & 2 \\
    LYG-5 & 119.110454 & 34.774217 & 3.05  & 7.46  & 1693  & 8 \\
    LYG-6 & 119.236851 & 34.599728 & 4.06  & 6.68  & 940   & 2 \\
    SQ-1  & 118.95227 & 34.265026 & 4.19  & 7.13  & 1067  & 33 \\
    SQ-2  & 119.007118 & 34.082169 & 3.97  & 7.31  & 964   & 30 \\
    SQ-3  & 118.969062 & 34.09797 & 5.66  & 7.22  & 745   & 30 \\
    SQ-4  & 118.197366 & 33.458218 & 6.58  & 6.97  & 692   & 60 \\
    SQ-5  & 118.177443 & 33.909072 & 4.06  & 7.21  & 613   & 48 \\
    SQ-6  & 118.630157 & 33.694594 & 3.91  & 6.96  & 1466  & 7 \\
    HA-1  & 118.876527 & 33.302497 & 10.19 & 7.77  & 851   & 40 \\
    HA-2  & 119.013519 & 33.520581 & 5.12  & 7.13  & 1230  & 4 \\
    HA-3  & 119.182348 & 33.449796 & 2.09  & 7.19  & 972   & 11 \\
    HA-4  & 119.05828 & 33.774083 & 4.01  & 7.17  & 884   & 17 \\
    HA-5  & 119.208097 & 33.774018 & 6.01  & 7.36  & 951   & 23 \\
    HA-6  & 119.201553 & 33.174541 & 8.53  & 7.81  & 365   & 40 \\
    HA-7  & 118.81422 & 32.991755 & 2.48  & 7.21  & 929   & 18 \\
    YC-1  & 120.625182 & 33.146767 & 5.44  & 6.85  & 1258  & 7 \\
    YC-2  & 120.229741 & 33.235092 & 4.56  & 7.24  & 1118  & 2.5 \\
    YC-3  & 119.760101 & 33.779833 & 8.6   & 7.5   & 5360  & 60 \\
    YC-4  & 119.746756 & 33.495392 & 8.47  & 6.87  & 688   & 18 \\
    YC-5  & 119.793454 & 33.764542 & 6.54  & 6.78  & 1607  & 8 \\
    YC-6  & 119.999065 & 33.971074 & 7.49  & 7.12  & 1658  & 12 \\
    YC-7  & 120.161467 & 32.664419 & 5.02  & 7.06  & 7980  & 8 \\
    YC-8  & 120.199528 & 32.88995 & 4.07  & 7.17  & 933   & 2 \\
    YC-9  & 120.095464 & 33.757809 & 2.54  & 7.22  & 1427  & 2 \\
    YC-10 & 119.643002 & 34.196721 & 1.13  & 7.02  & 3130  & 3 \\
    TZ-1  & 120.037586 & 32.159896 & 6.9   & 6.95  & 1333  & 6 \\
    TZ-2  & 120.218945 & 32.034389 & 3.57  & 7.06  & 863   & 5 \\
    TZ-3  & 120.098419 & 32.429346 & 5.44  & 7.31  & 1234  & 6 \\
    TZ-4  & 119.915084 & 32.409906 & 4.84  & 7.42  & 695   & 4 \\
    TZ-5  & 119.889099 & 32.966566 & 5.38  & 7.52  & 2620  & 40 \\
    YZ-1  & 119.301008 & 32.404407 & 3.54  & 6.67  & 931   & 10 \\
    YZ-2  & 119.562021 & 32.365727 & 2.19  & 7.17  & 194   & 3 \\
    YZ-3  & 119.472144 & 32.359951 & 3.29  & 7.36  & 729   & 2 \\
    YZ-4  & 119.263292 & 33.345682 & 2.83  & 7.06  & 955   & 15 \\
    YZ-5  & 119.788956 & 32.834132 & 3.66  & 7.06  & 695   & 1 \\
    NJ-1  & 118.840455 & 32.342992 & 1.5   & 7.12  & 672   & 3 \\
    NJ-2  & 118.867705 & 31.320991 & 3.13  & 7.16  & 676   & 4 \\
    NJ-3  & 118.927026 & 32.1511399 & 2.09  & 7.17  & 620   & 7 \\
    NJ-4  & 118.627894 & 32.059093 & 4.71  & 7.15  & 769   & 3 \\
    NJ-5  & 118.839685 & 31.953702 & 2.73  & 7.02  & 1002  & 4 \\
    NJ-6  & 119.068741 & 31.675228 & 3.31  & 7.06  & 797   & 5 \\
    ZJ-1  & 119.305278 & 32.172578 & 0.93  & 7.17  & 1059  & 3 \\
    ZJ-2  & 119.456667 & 32.203611 & 0.69  & 7.06  & 855   & 4 \\
    ZJ-3  & 119.429444 & 32.208611 & 5.01  & 6.75  & 864   & 5 \\
    ZJ-4  & 119.270278 & 31.923889 & 5.82  & 7.11  & 374   & 4 \\
    ZJ-5  & 119.172134 & 31.747039 & 2.57  & 6.5   & 688   & 6 \\
    ZJ-6  & 119.426667 & 31.919167 & 4.27  & 7.13  & 1194  & 2 \\
    NT-1  & 121.25435 & 32.223458 & 6.73  & 6.91  & 1544  & 5 \\
    NT-2  & 120.432719 & 32.529288 & 5.91  & 6.77  & 1129  & 6 \\
    NT-3  & 120.33514 & 32.394671 & 5.19  & 6.88  & 1263  & 7 \\
    NT-4  & 120.795501 & 32.108067 & 6.9   & 7.01  & 1215  & 8 \\
    NT-5  & 121.697255 & 31.801357 & 2.34  & 7.16  & 1199  & 5 \\
    NT-6  & 120.478386 & 32.370727 & 7.48  & 6.95  & 1306  & 10 \\
    NT-7  & 120.618057 & 32.402865 & 6.29  & 7.16  & 2028  & 5 \\
    NT-8  & 121.172121 & 31.959301 & 4.45  & 7.34  & 653   & 8 \\
    NT-9  & 120.824753 & 32.094975 & 1.41  & 6.96  & 1375  & 10 \\
    NT-10 & 121.195218 & 32.328978 & 9.99  & 7.67  & 560   & 1.5 \\
    NT-11 & 121.201832 & 32.311669 & 10.24 & 7.78  & 1463  & 1.5 \\
    CZ-1  & 119.93447 & 31.859446 & 7.05  & 6.75  & 765   & 5 \\
    CZ-2  & 119.951894 & 31.762508 & 2.89  & 7.06  & 785   & 5 \\
    CZ-3  & 119.987222 & 31.918333 & 6.27  & 6.83  & 628   & 6 \\
    CZ-4  & 119.949444 & 31.807778 & 5.34  & 7.38  & 556   & 3 \\
    CZ-5  & 119.405556 & 31.766389 & 7.12  & 7.07  & 1667  & 20 \\
    CZ-6  & 119.771667 & 31.682778 & 5.56  & 7.19  & 667   & 10 \\
    CZ-7  & 119.384295 & 31.460052 & 2.15  & 7.16  & 892   & 4 \\
    WX-1  & 120.224722 & 31.425278 & 4.69  & 7.03  & 577   & 3 \\
    WX-2  & 120.465194 & 31.840027 & 4.94  & 7.43  & 691   & 2 \\
    WX-3  & 119.854774 & 31.236615 & 5.58  & 6.54  & 699   & 2 \\
    WX-4  & 120.230839 & 31.617259 & 4.38  & 7.55  & 828   & 6 \\
    WX-5  & 120.305356 & 31.502575 & 3.34  & 6.73  & 597   & 1 \\
    WX-6  & 120.368013 & 31.514941 & 1.33  & 7.41  & 766   & 2 \\
    WX-7  & 120.429553 & 31.590905 & 3.15  & 7.41  & 852   & 2 \\
    SZ-1  & 120.619015 & 31.668775 & 4.09  & 6.75  & 425   & 2 \\
    SZ-2  & 120.34572 & 31.293318 & 4.47  & 6.49  & 759   & 15 \\
    SZ-3  & 120.392976 & 31.282641 & 6.95  & 6.14  & 214   & 4 \\
    SZ-4  & 120.539326 & 30.99954 & 2.69  & 6.51  & 860   & 2 \\
    SZ-5  & 120.513663 & 31.268154 & 5.98  & 6.87  & 572   & 3 \\
    SZ-6  & 120.433611 & 31.962777 & 8.54  & 7.02  & 1138  & 2 \\
    SZ-7  & 120.575652 & 31.336021 & 6.49  & 6.09  & 592   & 8 \\
    SZ-8  & 120.572385 & 31.317662 & 5.02  & /     & 745   & 3 \\
    SZ-9  & 120.589692 & 31.354086 & 2.58  & /     & 988   & 2 \\
    SZ-10 & 120.631536 & 31.436454 & 1.01  & 6.92  & 1314  & 2 \\
    SZ-11 & 120.79079 & 31.358852 & 2.59  & 6.61  & 935   & 3 \\
    SZ-12 & 120.723138 & 31.295224 & 1.84  & 7.16  & 710   & 2 \\
    SZ-13 & 120.747099 & 31.249625 & 1.59  & 6.61  & 931   & 2 \\
    SZ-14 & 121.107038 & 31.449896 & 1.93  & 6.86  & 538   & 3 \\
    SZ-15 & 121.118502 & 31.408126 & 2.26  & 6.89  & 785   & 2 \\
    SZ-16 & 121.024802 & 31.399441 & 0.25  & 9.22  & 262   & 2 \\
    SZ-17 & 120.999554 & 31.267943 & 2.09  & 6.78  & 948   & 2 \\
    \hline
    \multicolumn{7}{c}{\textcolor[rgb]{0.016, 0.196, 1.000}{\textbf{苏州地表水}}} \\
    \hline
    SZ-1S & 120.576501 & 31.339576 & 5.49  & 7.02  & 349   & - \\
    SZ-2S & 120.640799 & 31.287055 & 6.89  & 7.86  & 1378  & - \\
    SZ-3S & 120.640725 & 31.286456 & 4.15  & 6.95  & 445   & - \\
    SZ-4S & 120.642439 & 31.287374 & 3.35  & 6.95  & 438   & - \\
    SZ-5S & 120.64088 & 31.291368 & 2.78  & 6.99  & 445   & - \\
    SZ-6S & 120.636157 & 31.288377 & 11.13 & 7.63  & 408   & - \\
    SZ-7S & 120.573168 & 31.317656 & 2.56  & 6.73  & 388   & - \\
    SZ-8S & 120.589536 & 31.354351 & 16.77 & 7.31  & 557   & - \\
    SZ-9S & 120.700348 & 31.322037 & 6.33  & 7.48  & 410   & - \\
    SZ-10S & 120.791346 & 31.357147 & 8.89  & 7.11  & 455   & - \\
    SZ-11S & 120.722611 & 31.295104 & 11.96 & 7.1   & 416   & - \\
    SZ-12S & 120.747176 & 31.249577 & 7.87  & 6.9   & 465   & - \\
    \hline
    \multicolumn{7}{c}{\textcolor[rgb]{0.016, 0.196, 1.000}{\textbf{苏州某工业场地地下水}}} \\
    \hline
    SZ-1G & 120.639962 & 31.2869614 & 3.65  & 7.88  & 1025  & 1 \\
    SZ-2G & 120.639924 & 31.2870757 & 4.63  & 9.01  & 409   & 1 \\
    SZ-3G & 120.640055 & 31.2871365 & 2.58  & 7.74  & 774   & 1 \\
    SZ-4G & 120.640209 & 31.2872767 & 2.91  & 7.6   & 962   & 1 \\
    SZ-5G & 120.640116 & 31.2873103 & 3.09  & 7.58  & 1105  & 1 \\
    SZ-6G & 120.640038 & 31.2874132 & 2.21  & 7.86  & 901   & 1 \\
    SZ-7G & 120.639964 & 31.2875468 & 2.55  & 7.99  & 753   & 1 \\
    SZ-8G & 120.640095 & 31.2876053 & 3.09  & 8.25  & 592   & 1 \\
    SZ-9G & 120.640216 & 31.2876707 & 2.64  & 7.98  & 637   & 1 \\
    SZ-10G & 120.640374 & 31.2878103 & 3.73  & 8.09  & 463   & 1 \\
    \hline

    \end{longtable}%

**Comment by mohuangrui** [comment]
呃呃呃，一开始就猜到你的大意...你把 \footnotesize 放到了 \begin{} \end{} 之外当然就是全局的作用域。如果想要有限的作用域，就需放到  \begin{} \end{} 之内。

**Comment by weichanglong** [comment]
谢谢😂

**Comment by mohuangrui** [comment]
那你移除 \footnotesize 就可以编译了？可以肯定的是出错的原因肯定不会是因为这个。建议你先休息，明天再弄。经验告诉我疲劳工作时最容易出错

**Comment by weichanglong** [comment]
晃锐，

很感谢你一直以来的LaTeX技术指导，今天下午完成毕业论文的提交，感谢你帮助我们入门、提高。

昨天的\footnotesize等内容（下面阴影的代码）问题确实存在，且仅发生在附表A.1（已发代码），其它附表正常。在其它表格中是放在\begin{landscape}与\end{landscape}之间（其它表格的代码如下，加了个landscape）。



\begin{landscape}
\footnotesize% fontsize
 \setlength{\tabcolsep}{13pt}% column separation
 \renewcommand{\arraystretch}{1.1}%row space
    
\begin{longtable}{ccccccccccccccc}
…………...
\end{longtable}{ccccccccccccccc}

\end{landscape}



>> 
>> 将\footnotesize放在\begin{longtable}和\end{longtable}之间，结果一直报错，等你方便时，请你再帮我测试一下，我发给你的命令。谢谢！


______________________
魏昌龙
中国科学院南京土壤研究所
E-mail：clwei@issas.ac.cn
Tel：15295529335
南京市北京东路71号, 210008




在 2018年4月25日，02:37，mohuangrui <notifications@github.com> 写道：

Closed #77 <https://github.com/mohuangrui/ucasthesis/issues/77>.

**Comment by mohuangrui** [comment]
魏同学你好，恭喜恭喜，祝毕业顺利！

我测试了一下，发现你没错， longtable 的设计确实有很多问题。谢谢你的细心，帮助 ucasthesis 发现了许多意外的问题。我已在 [跨页长表](https://github.com/mohuangrui/ucasthesis/wiki/跨页长表) 提供了解决方案。

再次祝一切顺利！

**Comment by weichanglong** [comment]
谢谢晃锐！👍👍😀😀
______________________
魏昌龙
中国科学院南京土壤研究所
E-mail：clwei@issas.ac.cn
Tel：15295529335
南京市北京东路71号
