### ISSUE TITLE
封面题目中标点符号，会使下划线断掉

### ISSUE THREAD

**Issue by weichanglong** [mohuangrui/ucasthesis#78]
#73 

感谢晃锐给我们提供了一个交流学习LaTeX的平台。谢谢！

![image](https://user-images.githubusercontent.com/32944481/39250532-96537446-48d3-11e8-880d-c5303776cee5.png)

**Comment by mohuangrui** [comment]
这个问题有着更为底层的原因，解决方法是在下划线文本内只是用英文版标点即可。

**Comment by Porominix** [comment]
试过英文标点了，还是出现这个问题。。

**Comment by mohuangrui** [comment]
@Porominix 你确定你使用的是英文标点？可以提供下你的文件或是代码么？

**Comment by Porominix** [comment]
确定。中文冒号、英文冒号、英文冒号后加空格三种情况都会断掉下划线。代码要等我明早到办公室了。

**Comment by mohuangrui** [comment]
我确定英文标点是没有问题的，你再仔细核查确认下吧，问题应该是在你的使用上或是软件安装的问题。下面是我的测试截图：

![screenshot from 2018-09-03 11-41-32](https://user-images.githubusercontent.com/7518165/44994840-7e98b300-af6e-11e8-9e11-e99b406afe8d.png)

**Comment by Porominix** [comment]
![_20180904083825](https://user-images.githubusercontent.com/31784051/45004317-2ae5a280-b01e-11e8-8b1d-b5711ea2997c.png)
![_20180904083958](https://user-images.githubusercontent.com/31784051/45004319-2e792980-b01e-11e8-95d3-df18b27ab6eb.png)
这是我的代码和编译效果。

**Comment by mohuangrui** [comment]
麻烦你把你的frontpage.tex文件发给我吧

**Comment by mohuangrui** [comment]
@Porominix 你好，很可能是你的LaTeX版本过低导致的，在我的系统上编译你发给我的Frontpage.tex没有出现你说的问题：

![image](https://user-images.githubusercontent.com/7518165/45004684-ac0c4d80-afbc-11e8-83cf-ed318b9d73f3.png)
