### ISSUE TITLE
首段不缩进

### ISSUE THREAD

**Issue by zhangxiaoyang** [mohuangrui/ucasthesis#8]
Linux系统，首段不缩进，建议添加`\usepackage{indentfirst}`

**Comment by mohuangrui** [comment]
Hi, I have tested both on Linux (Debian) and Windows, and the paragraphs are all indented properly. May you please provide more information? Thanks.

**Comment by zhangxiaoyang** [comment]
```
> uname -a
Linux USER 3.13.0-45-generic #74~precise1-Ubuntu SMP Thu Jan 15 20:22:28 UTC 2015 i686 i686 i386 GNU/Linux
```

```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

```
> xetex --version
XeTeX 3.1415926-2.2-0.9995.2 (TeX Live 2009/Debian)
kpathsea version 5.0.0
Copyright 2009 SIL International and Jonathan Kew.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 3.8.1 [with modifications for XeTeX]
Compiled with zlib version 1.2.3.4; using 1.2.3.4
Compiled with FreeType2 version 2.4.8; using 2.4.8
Compiled with fontconfig version 2.8.0; using 2.8.0
Compiled with libpng version 1.2.46; using 1.2.46
Compiled with poppler version 0.18.2
```

**Comment by mohuangrui** [comment]
Hi,
Thank you for providing those information. May you please confirm that the indentation is not correct even when you compile the original template without modification?

Thanks

**Comment by zhangxiaoyang** [comment]
I have tested the latest version of ucasthesis. Everything works perfectly.

**Comment by mohuangrui** [comment]
That's great. By the way, ghoshorn from Github helped me find another problem about the page reference on "Table of Contents" for "List of Figures", "List of Tables", and "Reference". I have updated "custom.sty" and "Thesis.tex" to ensure correct page reference for "List of Figures", "List of Tables", and "Reference".  Thank you very much for your feedback and enjoy your thesis writing.
