### ISSUE TITLE
标题过大

### ISSUE THREAD

**Issue by shallyan** [mohuangrui/ucasthesis#80]
你好，我下载模版，指定fontsize为windows，其它没有动，编译出来后发现标题字体比较大，这个要怎么解决呢？
编译环境：Mac，Texpad，Xelatex+Biber

![image](https://user-images.githubusercontent.com/9313045/39682419-522d121e-51e2-11e8-9257-720ae727cc56.png)

**Comment by mohuangrui** [comment]
没在 mac 上测试过 fontset=windows，不确定原因，在 Linux 上测试过，没出现这个很没道理的异常。不知你为何要在 mac 上用 windows 字体？这本身也是一个很奇怪的决定。

**Comment by shallyan** [comment]
fontset=mac看着字体怪怪的，而且一样标题会过大

**Comment by mohuangrui** [comment]
你确定 fontset=mac 一样会标题字体过大？？？请确保你使用了最新版 ucasthesis 并建议你更新你的 Mactex，很可能问题是出在你的系统上而不是模版上。

**Comment by shallyan** [comment]
嗯嗯，谢谢。我使用的是最新版ucasthesis，TexLive是2015的，可能是太老了吧

**Comment by shallyan** [comment]
我升级到2018后，正常了，谢谢啦
