### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by keyofcg** [mohuangrui/ucasthesis#81]
您好，我的论文格式按照author year来的

可是生成的文献，没有括号
![1111](https://user-images.githubusercontent.com/9145147/39986022-054e60d6-5793-11e8-8599-947f5af5714f.png)
![11112](https://user-images.githubusercontent.com/9145147/39986651-e5d9496c-5794-11e8-9f59-cb71bec1ed5d.png)

**Comment by mohuangrui** [comment]
你好，请问可以将你的问题描述地更清晰些么？authoryear有authoryear的规范，如果不是你想要的，就请试试super，不管怎样， 请仔细阅读模板提供的相应说明和资料
