### ISSUE TITLE
没有出版商和出版地址的参考文献，能够不在 bibliography 部分显示占位符？

### ISSUE THREAD

**Issue by jdhao** [mohuangrui/ucasthesis#83]
如果一个参考文献不包含出版商和出版地址信息，目前在文末的参考文献处生成的参考文献，会有占位符显示，具体请看这个链接 https://ibb.co/nHEhFo

**Comment by zepinglee** [comment]
图没传上来？

**Comment by jdhao** [comment]
不知为什么图传不上去，我加了个链接，点击链接可看到图片。

**Comment by zepinglee** [comment]
[GB/T 7714-2015 信息与文献 参考文献著录规则](https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style/files/153951/GBT.7714-2015.pdf) 规定

**Comment by jdhao** [comment]
IEEE 会议的引用 style，不强制要求写出版商和地点，一般只需写 题目，作者，页码，卷期信息。如果没有出版商和地点，就不会有这项的占位符，这可能是更好的选择，供参考。

**Comment by zepinglee** [comment]
看你们学校要求什么

**Comment by mohuangrui** [comment]
@zepinglee  谢谢解答～

**Comment by zepinglee** [comment]
已经有一大堆人问我这个 "s.l., s.n." 怎么去掉，简直了……

后来发现学校的规定是“出版地缺失时可著录为 s.l.”，不是 GBT 标准中强制性的，所以干脆把这玩意删掉了

**Comment by mohuangrui** [comment]
@zepinglee 这些本无所谓的细节是很闹心，本就没有对错，那我也再从你那更新一遍
