### ISSUE TITLE
使用 bicaption 库，如果中文或者英文 caption 过长，那么生成的 caption 将不能居中排版

### ISSUE THREAD

**Issue by jdhao** [mohuangrui/ucasthesis#84]
## 问题描述

发现如果使用 bicaption，不论是图还是表格，如果 caption 的长度超过一行，那么英文和中文的 caption 都会变成左对齐。并且，如果英文 caption 过长，不会自动换行，会一直延伸到 PDF 的边界, 需要使用 `\\` 手动换行，但是中文标题没有这个问题。具体的问题可以参见下图

![image](https://user-images.githubusercontent.com/16662357/40644807-e2417d24-6356-11e8-96a9-3f241fe02e01.png)

对于表格，也是同样的问题，见下图：

![image](https://user-images.githubusercontent.com/16662357/40645863-24980cbc-635a-11e8-86ad-72a454c7c9bc.png)

## Possible fix

在 `artratex.sty` 中，修改 figure 与 table  caption 的设置，增加 `justification=centering` 选项。

```
\captionsetup[figure][bi-first]{format=hang,hangindent=-0.5em, justification=centering}%
\captionsetup[figure][bi-second]{format=hang,hangindent=-2em,name=Figure, justification=centering}%
\captionsetup[table][bi-first]{format=hang,hangindent=-0.5em,justification=centering}%
\captionsetup[table][bi-second]{format=hang,hangindent=-2em,name=Table,justification=centering}%
```

这样的话，标题居中问题解决，并且 table 的英文标题可以自动换行了，但是 figure 的英文标题还是不能自动换行，需要自己在合适的位置手动换行。

**Comment by mohuangrui** [comment]
你好，

1. 长标题左对齐是学位论文要求的，居中本是默认，如果想居中，移除所有对齐命令即可。
2. 你认为的英文不是英文是长字符串，英文是以词而不是字符为单元的。

**Comment by MilletPu** [comment]
> 你好，
> 
>     1. 长标题左对齐是学位论文要求的，居中本是默认，如果想居中，移除所有对齐命令即可。
> 
>     2. 你认为的英文不是英文是长字符串，英文是以词而不是字符为单元的。

原来是这样啊，辛苦作者了。（建议这个issue让更多同学看到

**Comment by cyx669521** [comment]
> > 你好，
> > ```
> > 1. 长标题左对齐是学位论文要求的，居中本是默认，如果想居中，移除所有对齐命令即可。
> > 
> > 2. 你认为的英文不是英文是长字符串，英文是以词而不是字符为单元的。
> > ```
> 
> 原来是这样啊，辛苦作者了。（建议这个issue让更多同学看到

请问应该移除哪里的对齐命令呢

**Comment by mohuangrui** [comment]
@cyx669521 如果你想长短标题皆居中，见：

  图表标题有时不居中？  https://github.com/mohuangrui/ucasthesis/wiki/常见问题

**Comment by amosbird** [comment]
> 1. 长标题左对齐是学位论文要求的

你好，我在 2018 年版本的 中国科学院大学研究生学位论文撰写规范指导意见 中并没有找到这个要求，是不是有所变化呢
