### ISSUE TITLE
Windows 使用 pdflatex 命令编译生成的封面字体有问题

### ISSUE THREAD

**Issue by jdhao** [mohuangrui/ucasthesis#85]
在 Windows 下面，使用 `pdflatex` 命令编译文件，生成的论文封面，`作者姓名` ，`指导老师` 等项目字体是黑体，不是要求的宋体。但是如果使用 `xelatex` 命令编译文件，生成的封面，格式是正确的。具体可以参加下图使用不同命令生成的封面，

![image](https://user-images.githubusercontent.com/16662357/40650207-4baa7ef6-6365-11e8-904c-9dae926b02c2.png)

**Comment by mohuangrui** [comment]
你好，pdflatex 的中文支持有限，这不是ucasthesis要去解决的。如果你想解决这个问题，请开发一个具有完整字库字重的开源的中文字体，谢谢！

**Comment by jdhao** [comment]
你在 Readme 写的该模版兼顾 pdflatex，xelatex 与 lulatex，我以为使用任一引擎都可以，该句话似乎不妥。

**Comment by zepinglee** [comment]
ctex 的 字体配置是 pdflatex、xelatex 分开写的：

https://github.com/CTeX-org/ctex-kit/blob/aa63a6f8ffabb509e0c1f21e497e0cfb66a05344/ctex/ctex.dtx#L9519

可能需要分别配置一遍伪粗

**Comment by jdhao** [comment]
如果 pdflatex 不支持格式的设定，建议去掉去 pdflatex 的说明，否则容易引起误解。怎么感觉作者如此 hostile，我只是提出一个建议而已，我一个人开发一套开源字体显然是不现实的。

**Comment by zepinglee** [comment]
可能最近被伪粗的问题搞得很头大

**Comment by jdhao** [comment]
那么使用 xelalatex 作为唯一支持的编译引擎也是可以的，现在 TeX Live 与 MikTeX 等发行版都是有 xelatex 的，也不用考虑对 pdflatex 的支持了。

**Comment by mohuangrui** [comment]
@zepinglee 重配 pdflatex 字体意义不大，因为即使解决了宋黑问题，却还是无法解决粗体问题。所以最核心的方案还是得走开发一套字体的道路。
@jdhao 呃，当你的心态是hostile时，自然也会觉得我的回复就是hostile的，就当你觉得因为pdflatex编译后因为封面没有粗宋体就认为不能说支持pdflatex一样，一切规则都得按照你的意志来运作才是合理的。支持pdflatex，xelatex，luatex，并推荐xelatex，这样有问题？

至于开发字体的时，不瞒你说，那是我一直想做的一件事而已。

**Comment by jdhao** [comment]
@mohuangrui ，不管怎么说，感谢开发 ucasthesis，其实 issue 可以不用关的那么快的.....
目前对字体处于初级了解阶段，我也缺乏艺术天分，字体开发这种结合技术性与艺术性的活，感觉胜任不了.. :).
