### ISSUE TITLE
文章中的参考文献显示？且最后的参考文献页面没有显示出来

### ISSUE THREAD

**Issue by StephYao** [mohuangrui/ucasthesis#86]
在texpad中显示文献引用如上述出错，可以运行但显示的是：（？？？）

**Comment by mohuangrui** [comment]
你好，应该是你的ref.bib里的参考文献格式与bibtex的格式不一致或存在多余的域或是缺少某些必要的域。请按照ref.bib类的样本给定参考文献格式，如从Google Scholar获取文献的bibtex信息。

**Comment by StephYao** [comment]
你好，我是整个文件下载过来没有做任何修改，原文件上就显示不出来..

**Comment by mohuangrui** [comment]
你是说你下载了ucasthesis然后编译不出参考文献？请问你运行了bibtex么？请阅读下使用说明文档.pdf以进行正确的编译操作
