### ISSUE TITLE
mac下texmaker无法输入全角符号（如，。）可以打中文，但打出的符号都是半角。texmaker for mac can't type full-width punctuation (Chinese punctuation，，。。) but half-width (,,..).

### ISSUE THREAD

**Issue by i-23** [mohuangrui/ucasthesis#88]

**Comment by mohuangrui** [comment]
你好，这个问题如果存在的话，那就请用其他编辑器吧，比如 MacTeX 里自带了一个编辑器 TeXShop，也挺好用的。 如果你习惯 Linux 的话，就可用 Vim。事实上，使用任何文本编辑器都是可以的，因为 TeX 本身只是文本代码，编译可以用脚本或命令行即可。

**Comment by i-23** [comment]
@mohuangrui   只是texmaker界面好用点，显示出结构来。我也尝试了用texshop和vim，没有结构只能分开编辑各章节tex。而且不论用哪个编译，各章节tex单独编译出错，最后要一起编译thesis.tex才行。所以感觉有结构显示各章节tex的texmaker好用。

**Comment by i-23** [comment]
@mohuangrui 我以为是设置的问题，不过搞了半天也没成功打出全角符号，不知道怎么设置。

**Comment by mohuangrui** [comment]
你好，
1) LaTeX 源文件是一个代码集，Thesis.tex 是主函数，其他章节为被主函数调用的子函数，自然需编译主函数。也有可以设置单独编译子文件的方法，但并不会比编译 Thesis.tex 来得有效。

所以问题不是不能单独编译的问题，而是如何正确使用的问题。你只需单独编译各个子文件，编译主文件即可。 artratex.sh 就是为懂得使用 vim 的人打造的。

2）不能打在 Texmaker 内输入全角并不见得就是 Texmaker 的问题。建议你先在 Texshop 或是 vim 内测试看能不能打全角。或是看看如下这个帖子 (macos 无法输入全角)[https://www.zhihu.com/question/263928821]

3）最后若真是 Texmaker 的问题，建议你编译出来看看中文环境内是否会自动切换为全角。

结论就是这个问题需要你自己认真去测试排查 ： D
