### ISSUE TITLE
请问参考文献如何加超链接

### ISSUE THREAD

**Issue by StephYao** [mohuangrui/ucasthesis#89]
在最后的参考文献生成页，希望可以不显示URL但点击文字，跳到相印的pdf网页上，要怎么做到？谢谢！

**Comment by zepinglee** [comment]
在 title 上放链接是吧？

**Comment by mohuangrui** [comment]
请问可以将问题描述得更清楚吗？何为参考文献页不显示URL？何为PDF网页？

如果你是想点击参考文献列表的某个文献可以跳回文章内的引用页，可以在 `artracom.sty` 添加如下命令即可：

```
\RequirePackage[hyperpageref]{backref}
```
然后每个文献后就会有链回文本页的页码：

<img width="940" alt="image" src="https://user-images.githubusercontent.com/7518165/43529480-682cd1be-9579-11e8-8bcf-592b23b73067.png">

**Comment by zepinglee** [comment]
以前有人提过这个需求，我可以加个选项

**Comment by mohuangrui** [comment]
@zepinglee 是不是可以不用考虑这个，学术写作的参考文献规范一般而言无需有这个功能。其实每条后添加的这几个页码数字对于不知道的人来说反而是一种困惑。个人视角，欢迎讨论。

**Comment by zepinglee** [comment]
你理解错了，他的意思是文献的标题上加个超链接；我以前可能加过，但是忘记处于什么原因取消了

**Comment by StephYao** [comment]
下面这个文献引用，写出了URL链接，点击他可以跳到相应的网站。如果不显示URL，直接点击中文文字或者英文文字就可以跳到相应的网站呢？
<img width="577" alt="wx20180801-230700 2x" src="https://user-images.githubusercontent.com/35494200/43530258-b2638f8c-95df-11e8-9ae5-2c7d139a1cc9.png">

**Comment by mohuangrui** [comment]
好吧，那这样的话就得麻烦 @zepinglee 了

**Comment by zepinglee** [comment]
已经 push 到 https://github.com/zepinglee/gbt7714-bibtex-style 。 我现在添加了一个选项，可以编辑 bst 文件 `init.options` 函数，将 `link.title` 前的 `#0` 改为  `#1`，`show.url` 前改为 `#0`，应该就是需要的效果。

原来讨论的 issue 在 https://github.com/zepinglee/gbt7714-bibtex-style/issues/19 和 https://github.com/zepinglee/gbt7714-bibtex-style/issues/21 。

**Comment by mohuangrui** [comment]
@zepinglee 感谢！

**Comment by StephYao** [comment]
谢谢两位！还有个小小的问题，链接的颜色怎么改？我这边显示的是红色的，想变成蓝色的

**Comment by mohuangrui** [comment]
@StephYao @zepinglee 
超链接的颜色设置也在如下页面进行了相应的说明：

 [文献样式的 Wiki ](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F) 

谢谢大家的合作～

**Comment by StephYao** [comment]
@zepinglee 您好，我今天在刷新的时候又出现了URL..
<img width="1582" alt="test" src="https://user-images.githubusercontent.com/35494200/43646800-74ef8db0-9768-11e8-8d7a-e8626249a18b.png">

**Comment by zepinglee** [comment]
@StephYao 把你的 bib 条目发过来让我测试下？

**Comment by zepinglee** [comment]
@StephYao 我刚刚 push 了https://github.com/zepinglee/gbt7714-bibtex-style/commit/0fac8ee57877ed611dc59cae5a8e0f6fd3300f6e ，应该修复了这个问题。现在只有在用户显式地选择声明电子资源的情况下才会强行显示 url。

**Comment by mohuangrui** [comment]
@StephYao 将 url 转换为标题的链接真的是理想的么？论文打印版该如何去准确地找到原链接？

**Comment by StephYao** [comment]
@zepinglee 谢谢！ @mohuangrui 是出于在初稿的时候看起来整洁一点，合作的时候更方便进行文献的查阅的目的。谢谢两位了，很感谢！

**Comment by zepinglee** [comment]
@mohuangrui 我觉得可以像 `ustcthesis` 一样设置两个版本 `print` 和 `electronic`：前者用于打印，后者用于电子阅读，会保留超链接颜色，这种情况下略去参考文献的 url 更合适

**Comment by mohuangrui** [comment]
@zepinglee ucasthesis也有printcopy选项，不过主要针对奇偶页的binding。将会考虑你的建议，不过tex的选项似乎无法直接传递给bst文件，这样就得准备两个版本的bst，不知道有没有更好地办法。对了，你的 gbt 的 ustc 和 master 分支的主要区别是什么呢？我记得不久前由于采用某个特定设置，就用了ustc版的，而你维护的似乎又主要是master，所以有些跟不上了。

**Comment by zepinglee** [comment]
1. 确实没法传给 bst，就让有需要的同学自己修改 bst 吧；
2. USTC 的参考文献在国标的基础上增加了几项要求，比如不显示“[出版地不详]”等信息，以及外文 journal 要斜体，所以新增加了一个 `ustc` 分支，当 master 有大的改动时会 `rebase master`；同样还有 `thu` 分支。所以你们国科大有啥额外的要求，可以整理给我，然后我做一些接口可以在 `bst` 最前面的 'load.config' 里方便地修改。

**Comment by mohuangrui** [comment]
1. 那目前就先让有需要的同学自己改了。如果使用者能够理解我们讨论的设定背后的缘由的话，你建议的方向肯定是对的，我会再想想怎么实施比较理想，若想出来了，就在空闲时实施下。

2. 对对对，就是因为避免那个 `[出版地不详]` 的字段而改用了 `ustc` 。目前国科大似乎对参考文献的这些排版细节没明确要求，所以你的当前工作肯定是够用的。维护那么多分支，已经够幸苦了。

3. 我对 bst 不了解，不知道是否可以像 .sty 文件那样在外部给定调用选项？这样你就可以将所有分支合并，而使用者也不需去关注多个分支了。

**Comment by zepinglee** [comment]
3. 不行，bst 没有 LaTeX 的接口。虽然可以用 LaTeX 宏封装起来，比如 \btxaddress{[出版地不详]}，但是给前后的标点符号处理增加了巨大的麻烦，还不如用 BibLaTeX。所以比较可行的方案是把 bst 的配置合并在一起，比如
```
FUNCTION {load.config}
{
  #1 'uppercase.name :=
  #3 'max.num.authors :=
  #0 'period.between.author.year :=
  #1 'sentence.case.title :=
  #0 'link.title :=
  #1 'show.mark :=
  #0 'italic.jounal :=
  #1 'show.missing.address.publisher :=
  #1 'show.url :=
  #1 'show.doi :=
  #0 'show.note :=
}
```
用户根据自己的需要去修改配置就可以了。

2. 现在只需要把 `'show.missing.address.publisher` 的 `#1` 改成 `#0` 就可以了。其实不同的分支也只是改下配置，比如 https://github.com/zepinglee/gbt7714-bibtex-style/commit/10e54509ba7d6b9c27d2aa5b5e07e70bace5b44b ，其实很简单的，一般 rebase 也没啥冲突。

**Comment by mohuangrui** [comment]
好的，非常感谢，那我将bst更新一下。
那我close这个了。

**Comment by yunyun2019** [comment]
> @yunyun2019 你好，链接颜色的问题曾在此issue进行了讨论，请见：
> 
> ![screenshot from 2019-01-02 11-24-28](https://user-images.githubusercontent.com/7518165/50601104-325c7180-0e81-11e9-9fe1-e9df218cfccd.png)
> 具体设定方法，请见：
> 
> [文献样式的 Wiki ](https://github.com/mohuangrui/ucasthesis/wiki/%E6%96%87%E7%8C%AE%E6%A0%B7%E5%BC%8F)

按照要求修改，的确把参考文献后面的颜色变为红色了，但是前面目录部分，所有的内连接都变成红色，比较难看，有没有只变文献后面的颜色为红色，而其他仍然为黑色？
![image](https://user-images.githubusercontent.com/46296872/50633887-d29cbe00-0f87-11e9-80f2-e285aa89ed5c.png)
![image](https://user-images.githubusercontent.com/46296872/50633917-ee07c900-0f87-11e9-9eb8-c71a71899f4b.png)

**Comment by mohuangrui** [comment]
你好，以下不同的命令条目会修改不同的链接颜色，请耐心测试～
    linkcolor=black,% color of internal links
    citecolor=blue,% color of links to bibliography
    %filecolor=magenta,% color of file links
    urlcolor=red,% color of external links
