### ISSUE TITLE
section标题前与前文重叠

### ISSUE THREAD

**Issue by halois** [mohuangrui/ucasthesis#9]
直接通过.bat编译后的文档与自带的文档，在section标题处前后段落没有间隙

**Comment by mohuangrui** [comment]
Hi, may you please explain more about the problem? Sorry that I can not identify what is wrong. Thanks.

**Comment by mohuangrui** [comment]
Hi, I have found the problem. This is really a weird situation, which only happens with Windows. I have fixed the problem by modifying the ucasthesis.cfg. May you please have a try with the updated file? Thank you very much for your feedback!
