### ISSUE TITLE
关于脚注和尾注

### ISSUE THREAD

**Issue by Porominix** [mohuangrui/ucasthesis#90]
模板的正文部分好像不能加上脚注或者尾注？需要随写随引的话，是不是要用“(袁训来, 2012a)”这样的格式？谢谢。

**Comment by zepinglee** [comment]
注释和引用是两码事，你说的事哪个？

**Comment by Porominix** [comment]
是note

**Comment by mohuangrui** [comment]
@Porominix note是什么意思？如果是脚注，命令是  
```
\footnote{这是一个脚注}
```
LaTeX 应没有一个 `note` 的命令

**Comment by Porominix** [comment]
那就用脚注了，谢谢

**Comment by mohuangrui** [comment]
好的，建议你在使用 LaTeX 可以一边使用用一边多查阅资料 ：）

**Comment by zepinglee** [comment]
@Porominix endnote 需要调用 `endnote` 宏包去生成，另外“(袁训来, 2012a)”这样的一般是参考文献的引用
