### ISSUE TITLE
请问有国科大官方的相关通知吗？

### ISSUE THREAD

**Issue by Rex-Diego** [mohuangrui/ucasthesis#93]
模版本身没问题，特别好用，赞！

我是大气物理研究所的博士生，问题是问了所里研究生部的老师，说这个模版不是官方的，不可以提交。。很纠结，不想切回word，特来求助。希望有国科大相关的通知或者认可、相关文件，十分感谢！

**Comment by drmagithub** [comment]
18年毕业的有一部分人就是拿这个写的，放心用吧。

**Comment by mohuangrui** [comment]
@Rex-Diego 你好，此模板并无官方的正式认可和背书，但当前模板遵从2018版《中国科学院大学研究生学位论文撰写规范指导意见》，并且国科大本科部的陆晴老师与本科部学位办丁云云老师对当前模板进行了审核和校对。

LaTeX与Word皆只是写作排版软件而已，使用当前LaTeX模板与官方发布的Word模板写出的论文在排版格式上是无差异的，从而不应影响论文的提交与审核。如果不放心，你可以请求贵所学位办的老师审阅一下你的当前初稿，以请教不可提交的具体原因～

**Comment by Rex-Diego** [comment]
> @Rex-Diego 你好，此模板并无官方的正式认可和背书，但当前模板遵从2018版《中国科学院大学研究生学位论文撰写规范指导意见》，并且国科大本科部的陆晴老师与本科部学位办丁云云老师对当前模板进行了审核和校对。
> 
> LaTeX与Word皆只是写作排版软件而已，使用当前LaTeX模板与官方发布的Word模板写出的论文在排版格式上是无差异的，从而不应影响论文的提交与审核。如果不放心，你可以请求贵所学位办的老师审阅一下你的当前初稿，以请教不可提交的具体原因～

好的，十分感谢您的回复以及对项目的维护！这两天我再问问相关的老师！
