### ISSUE TITLE
国科大论文撰写规范中：公式序号前需要添加“...”

### ISSUE THREAD

**Issue by mczhouwei** [mohuangrui/ucasthesis#94]
7. 表达式（公式）
论文中的表达式需另行起，原则上应居中。如有两个以上的表达式，应用从“1”开始的阿拉伯数字进行编号，并将编号置于括号内。编号采用右端对齐，表达式与编号间用“...”连接。表达式较多时可分章编号。

"..."需贴着公式编号的左侧。

最近我们所里提交论文，突然要求我们按这个格式要求来，把里面的公式编号前加"..."，网上搜了很久，也没找到解决方案。希望您更新一下这块，帮帮忙。

**Comment by mohuangrui** [comment]
你好，这个问题已进行了解答，请看 ucasthesis 和 LaTeX 知识小站的 [琐屑细节](https://github.com/mohuangrui/ucasthesis/wiki/%E7%90%90%E5%B1%91%E7%BB%86%E8%8A%82)

**Comment by Mikumikunisiteageru** [comment]
我试着修改了 `amsmath` 包对 `\tagform@` 和 `\eqref` 的定义：
~~~latex
\makeatletter
\def\tagform@#1{\maketag@@@{\ensuremath{\ldots\,}(\ignorespaces#1\unskip\@@italiccorr)}}
\def\tagform@original#1{\maketag@@@{(\ignorespaces#1\unskip\@@italiccorr)}}
\renewcommand{\eqref}[1]{\textup{\tagform@original{\ref{#1}}}}
\makeatother
~~~
之后一切如常使用即可。

**Comment by mohuangrui** [comment]
@Mikumikunisiteageru 你好，你的方案在 [texse](https://tex.stackexchange.com/questions/28903/changing-the-appearance-of-equation-numbers-with-amsmath) 上有，不利的影响详见讨论部分。

**Comment by nihaomiao** [comment]
您好，这个[琐屑细节](https://github.com/mohuangrui/ucasthesis/wiki/%E7%90%90%E5%B1%91%E7%BB%86%E8%8A%82)的网址好像打开后什么都没有 @mohuangrui

**Comment by mohuangrui** [comment]
你好，已经合并到 https://github.com/mohuangrui/ucasthesis/wiki/常见问题

On Apr 22, 2019, at 8:34 PM, Haomiao Ni <notifications@github.com<mailto:notifications@github.com>> wrote:


您好，这个琐屑细节<https://github.com/mohuangrui/ucasthesis/wiki/%E7%90%90%E5%B1%91%E7%BB%86%E8%8A%82>的网址好像打开后什么都没有 @mohuangrui<https://github.com/mohuangrui>
