### ISSUE TITLE
文内引用英文文献时需要把“et al”变为“等”，但是同时后面的参考文献不变

### ISSUE THREAD

**Issue by zepinglee** [mohuangrui/ucasthesis#95]
Forward from CTeX-org/gbt7714-bibtex-style/issues/33 by @yunyun2019

直接编译时：文中引用：Walls et al. (1995) 和 (Walls et al., 1995)；这样在2017年及以前的规定，但是从2018年以后，规定变为Walls 等 (1995) 和 (Walls 等., 1995)，同时，后面的参考文献格式还是需要用英文et al.
PS：年代现在又变到后面了。

**Comment by yunyun2019** [comment]
@zepinglee 主要语言是中文，很少很少用英文写学位论文的。

**Comment by yunyun2019** [comment]
@zepinglee 根据最新学位论文写作要求中的规定：“除外国来华留学生及外语专业研究生外，学位论文一律用国家正式公布实施的简化汉字书写。标点符号的用法以GB/T 15834—2011《标点符号用法》为准。数字用法以GB/T 15835—2011《出版物上数字用法》为准。”所以99%都是中文书写。

**Comment by zepinglee** [comment]
《撰写要求》里说：
> 引用多位著者的文献时，对欧美著者只需标注第一个著者的姓，其后附“等.”……对中文著者应该标注第一著者的姓名，其后附“等”字

前面给的例子是：
> Michael等（1995）根据……的研究，首次提出……。其中关于……（Michael等.，1995），是当前中国……

这个很混乱啊。另外“et al.”后面加点是表示拉丁文“et alii”的缩写，但是中文的“等”后面加点是什么用法？

**Comment by zepinglee** [comment]
> 引用多位著者的文献时，对欧美著者只需标注第一个著者的姓，其后附“等.”，仅两位作者的全部注出，中间用“和”；对中文著者应该标注第一著者的姓名，其后附“等”字，姓名与“等”字之间留一个空格。例如：（张永 等，2005）。

我的理解是如果两个欧美著者就全部注出，如果是两个中文著者只标注第一著者的姓名？

另外后面给的例子为何是“（Wang，2010；Simon and Feenberg，2003）”，两个姓名到底用什么连接？

**Comment by yunyun2019** [comment]
> 《撰写要求》里说：
> 
> > 引用多位著者的文献时，对欧美著者只需标注第一个著者的姓，其后附“等.”……对中文著者应该标注第一著者的姓名，其后附“等”字
> 
> 前面给的例子是：
> 
> > Michael等（1995）根据……的研究，首次提出……。其中关于……（Michael等.，1995），是当前中国……
> 
> 这个很混乱啊。另外“et al.”后面加点是表示拉丁文“et alii”的缩写，但是中文的“等”后面加点是什么用法？

我也觉得很怪，但是今天翻阅了4本去年的毕业论文大家都改成了“等.”，询问了学位办的老师，也是让按这个要求来。不知道按照其实现起来会不会很麻烦？

**Comment by zepinglee** [comment]
> > 《撰写要求》里说：
> > > 引用多位著者的文献时，对欧美著者只需标注第一个著者的姓，其后附“等.”……对中文著者应该标注第一著者的姓名，其后附“等”字
> > 
> > 
> > 前面给的例子是：
> > > Michael等（1995）根据……的研究，首次提出……。其中关于……（Michael等.，1995），是当前中国……
> > 
> > 
> > 这个很混乱啊。另外“et al.”后面加点是表示拉丁文“et alii”的缩写，但是中文的“等”后面加点是什么用法？
> 
> 我也觉得很怪，但是今天翻阅了4本去年的毕业论文大家都改成了“等.”，询问了学位办的老师，也是让按这个要求来。不知道按照其实现起来会不会很麻烦？

这样的用法是不对的，建议反馈一下。不过目前我可以先按照这个要求来写

**Comment by yunyun2019** [comment]
> > > 《撰写要求》里说：
> > > > 引用多位著者的文献时，对欧美著者只需标注第一个著者的姓，其后附“等.”……对中文著者应该标注第一著者的姓名，其后附“等”字
> > > 
> > > 
> > > 前面给的例子是：
> > > > Michael等（1995）根据……的研究，首次提出……。其中关于……（Michael等.，1995），是当前中国……
> > > 
> > > 
> > > 这个很混乱啊。另外“et al.”后面加点是表示拉丁文“et alii”的缩写，但是中文的“等”后面加点是什么用法？
> > 
> > 
> > 我也觉得很怪，但是今天翻阅了4本去年的毕业论文大家都改成了“等.”，询问了学位办的老师，也是让按这个要求来。不知道按照其实现起来会不会很麻烦？
> 
> 这样的用法是不对的，建议反馈一下。不过目前我可以先按照这个要求来写

我很想反驳他们，因为我也觉得怪怪的，很拧巴，但奈何现在写毕业论文时间太紧，另外，我对排版知识知之甚少，就说自己觉得怪怪的，他们是不会理我的。但今天跟您学到的**”“et al.”后面加点是表示拉丁文“et alii”的缩写**”这个知识点，我估计编要求的老师未必知道，他们只是要自己好看罢了。等我先按照它们规定的毕业论文要求弄完，再整理这些知识点，有理有据的给他们反馈！相信会带来改变！再次感谢您的付出，方便了我们上万学生！

**Comment by mohuangrui** [comment]
@zepinglee @yunyun2019 建议不做修改，而是保持国标样式。原因如下：

1. 国科大学位论文撰写要求明确提到：

“根据《学位论文编写规则》（GB/T 7713.1—­2006）和《信息与文献 参考文献著录规则》（GB/T 7714—­2015）等国家有关标准，结合《中国科学院大学研究生学位论文撰写规定》，特制定本指导意见。”

因此，国标就应是最核心的规范。

2. 撰写要求中对于et al. 和 等 的规定本就不甚清晰，如下例子用了 等：

“Michael等（1995）根据……的研究，首次提出……。其中关于……（Michael等.，1995），是当前中国……得到迅速发展的研究领域（张永，2003）。”

但在后面的“参考文献标注的注意事项”中又提道：

“编著者为3人以下时全部著录，用逗号分隔；3人以上可只著录前3人，后加“，等”，外文用“, et al.”，“et al.”不必用斜体。”

结论就是，坚持国标的合理规范即可，无须为此等无谓的问题去烦扰所学位办的老师们。人生有太多其他更有意义的问题去烦扰。。。

**Comment by mohuangrui** [comment]
> @mohuangrui 你们的模板要不要考虑英文的情况？如果主要语言是英文的话，“Walls 等 (1995) introduced a new method...” 这样会很突兀

要考虑英文的，现在有越来越多来自东南亚和东欧的国家在中科院的体系内做博士，时而会收到他们对于ucasthesis使用的问询。所以建议你优先考虑国标的样式，毕竟将 et al. 替换为 等 实为有些牵强。若是这般，是不是要将所有老外的名字也都中文化呢。。。

让这个问题多次劳烦到你，实在是幸苦了～若有更好的建议，请告知～

**Comment by yunyun2019** [comment]
解释一下：
第一，@mohuangrui同学似乎搞混了文内引用用中文，后面参考文献继续用英文，所以这并不矛盾啊，所以我的问题才是“文内引用英文文献时需要把“et al”变为“等”，但是同时后面的参考文献不变”。
第二，国标就应是最核心的规范。我也承认国标是核心，但是科学院大学不是也说了要结合《中国科学院大学研究生学位论文撰写规定》吗？所以做一些修改是难以避免的，况且其变化也是隔几年一变，这也是事实啊。
第三，有些东南亚和东欧的留学生需要英文的引用，我觉得坚持国标的确有利于方便留学生，扩大ucasthesis的影响力，不知道能否实现按照语言自动选择“et al”还是“等”，让ucasthesis可以更多福泽国内毕业生。谢谢！



zhuyunyun2010@126.com
 
发件人： mohuangrui
发送时间： 2019-01-03 00:49
收件人： mohuangrui/ucasthesis
抄送： yunyun2019; Mention
主题： Re: [mohuangrui/ucasthesis] 文内引用英文文献时需要把“et al”变为“等”，但是同时后面的参考文献不变 (#95)
@zepinglee @yunyun2019 建议不做修改，而是保持国标样式。原因如下：
国科大学位论文撰写要求明确提到：
“根据《学位论文编写规则》（GB/T 7713.1—­2006）和《信息与文献 参考文献著录规则》（GB/T 7714—­2015）等国家有关标准，结合《中国科学院大学研究生学位论文撰写规定》，特制定本指导意见。”
因此，国标就应是最核心的规范。
撰写要求中对于et al. 和 等 的规定本就不甚清晰，如下例子用了 等：
“Michael等（1995）根据……的研究，首次提出……。其中关于……（Michael等.，1995），是当前中国……得到迅速发展的研究领域（张永，2003）。”
但在后面的“参考文献标注的注意事项”中又提道：
“编著者为3人以下时全部著录，用逗号分隔；3人以上可只著录前3人，后加“，等”，外文用“, et al.”，“et al.”不必用斜体。”
结论就是，坚持国标的合理规范即可，无须为此等无谓的问题去烦扰所学位办的老师们。人生有太多其他更有意义的问题去烦扰。。。

**Comment by yunyun2019** [comment]
> @zepinglee @yunyun2019 建议不做修改，而是保持国标样式。原因如下：
> 
> 1. 国科大学位论文撰写要求明确提到：
> 
> “根据《学位论文编写规则》（GB/T 7713.1—­2006）和《信息与文献 参考文献著录规则》（GB/T 7714—­2015）等国家有关标准，结合《中国科学院大学研究生学位论文撰写规定》，特制定本指导意见。”
> 
> 因此，国标就应是最核心的规范。
> 
> 1. 撰写要求中对于et al. 和 等 的规定本就不甚清晰，如下例子用了 等：
> 
> “Michael等（1995）根据……的研究，首次提出……。其中关于……（Michael等.，1995），是当前中国……得到迅速发展的研究领域（张永，2003）。”
> 
> 但在后面的“参考文献标注的注意事项”中又提道：
> 
> “编著者为3人以下时全部著录，用逗号分隔；3人以上可只著录前3人，后加“，等”，外文用“, et al.”，“et al.”不必用斜体。”
> 
> 结论就是，坚持国标的合理规范即可，无须为此等无谓的问题去烦扰所学位办的老师们。人生有太多其他更有意义的问题去烦扰。。。

请允许我解释一下：
第一，@mohuangrui同学似乎搞混了文内引用用中文，后面参考文献继续用英文，所以这并不矛盾啊，所以我的问题才是“**文内引用英文文献时需要把“et al”变为“等”，但是同时后面的参考文献不变**”。
第二，国标就应是最核心的规范。我也承认国标是核心，但是科学院大学不是也说了要结合《中国科学院大学研究生学位论文撰写规定》吗？所以做一些修改是难以避免的，况且其变化也是隔几年一变，这也是事实啊。
第三，有些东南亚和东欧的留学生需要英文的引用，我觉得坚持国标的确有利于方便留学生，扩大ucasthesis的影响力，不知道能否实现按照语言自动选择“et al”还是“等”，让ucasthesis可以更多影响国内的毕业生。谢谢！

**Comment by mohuangrui** [comment]
@yunyun2019 “文内引用英文文献时需要把“et al”变为“等”，但是同时后面的参考文献不变”， 这一规则很大程度上是根据撰写要求中所提供的一个关于Michael的模糊例子所推导出来的，至今都未有明确解释为何会在那样的一个例子里将 et al. 替换成了 等。规范很重要的一个特征就是自洽性，实不明白 “文内引用英文文献时需要把“et al”变为“等”，但是同时后面的参考文献不变”这样一个违背国标所给出的合理规范并只是通过模糊揣测出来的”规则“有何价值。。。若坚持觉得这一”规则“是有价值的不可逾越的，请自便 :)

**Comment by yunyun2019** [comment]
> 我觉得这样规定也没啥问题，但是等字后面加点就完全不对了

我也觉得奇怪，但是我翻阅去年的毕业论文，有一个直接写的“等”，其他人都是“等.”，也就是说大家都按照研究生部发的规范来，2018年11月30日开毕业生会议时，研究生部还专门给每个人发了一份撰写要求，里面这么规定的。@zepinglee 不知道改成“等.”工作量会不会比“等”大很多，或者内部逻辑就不协调？反正至少得是中文字，不知道修改的难度怎么样，期盼您能帮助我们广大毕业生，毕竟这变扭的要求就是掌握我们毕业命运的人定的啊！

**Comment by mohuangrui** [comment]
@zepinglee @yunyun2019 好吧，既然如此，那就麻烦 @zepinglee  提供一个可行的版本吧。至于要用”等.“还是”等“，我也不清楚了。

**Comment by yunyun2019** [comment]
> @zepinglee @yunyun2019 好吧，既然如此，那就麻烦 @zepinglee 提供一个可行的版本吧。至于要用”等.“还是”等“，我也不清楚了。

麻烦 @zepinglee 了，希望更多人可以用latex写完论文，再次感谢！

**Comment by yunyun2019** [comment]
> 我 push 到了 [ucas 分支](https://github.com/CTeX-org/gbt7714-bibtex-style/tree/ucas)。
> 
> 另外还需要在模板中定义 \biband 和 \bibetal 两个宏，参考 https://github.com/CTeX-org/gbt7714-bibtex-style/blob/ucas/test/test.tex

谢谢您的修改，我要在需要在ucasthesis的哪个文件中修改 \biband 和 \bibetal 两个宏？

**Comment by mohuangrui** [comment]
> 我 push 到了 [ucas 分支](https://github.com/CTeX-org/gbt7714-bibtex-style/tree/ucas)。
> 
> 另外还需要在模板中定义 \biband 和 \bibetal 两个宏，参考 https://github.com/CTeX-org/gbt7714-bibtex-style/blob/ucas/test/test.tex

非常感谢你的修改，这几天感冒得重，不好意思现在才出现。我已对如何使用你所提供的样式在[文献样式](https://github.com/mohuangrui/ucasthesis/wiki/文献样式)进行了如下说明：

### 英文的 “et al.” 改为中文 “等”

1. 将 ``Biblio`` 文件夹下的 ``gbt7714-plain.bst`` 和 ``gbt7714-unsrt.bst`` 国标参考文献样式文件用 zepingli 为 ucas 此特殊设定所建立的 [ucas文献样式分支](https://github.com/CTeX-org/gbt7714-bibtex-style/tree/ucas)的 ``gbt7714-plain.bst`` 和 ``gbt7714-unsrt.bst``进行替换。
2. 在 ``Style`` 文件下的 ``artracom.sty`` 中添加如下两条命令：
```
\newcommand\bibetal{等}
\newcommand\biband{和}
```

**Comment by zepinglee** [comment]
不是这样用的，我的设计是你在模板里直接
```
\if@chinese
  \newcommand\bibetal{等}
  \newcommand\biband{和}
\else
  \newcommand\bibetal{et al.}
  \newcommand\biband{ and }
\fi
```
你的意思是官方只提供“et al.”，需要改为“等”人都自行修改？

**Comment by mohuangrui** [comment]
@zepinglee 请问可不可以像英文名大小写那样通过在bst里设定 load.config 选项来转换？以前我们都希望像你现在实现的这样，通过宏包的选项来直接控制bst样式，但是否还是避免将这么多文件关联起来的好？文件之间的关联调用将造成不适当的依赖性，限制使用和维护。你觉得呢？

**Comment by zepinglee** [comment]
> 以前我们都希望像你现在实现的这样，通过宏包的选项来直接控制bst样式

通过 LaTeX 宏来控制 BibTeX 的格式还是有很多限制的。比如要输出“Name. Title.”的格式，如果 Name 是以“.”结尾的（如“Michael et al.”）就不再添加多余的句点，如果用 LaTeX 宏来控制格式，通常把每一项都包在一个宏里（`\bibname{Name}`）就得判断 Name 是不是以“.”结尾，比较麻烦。所以如果你希望用 LaTeX 代码完全控制文献列表的格式最好使用 biblatex。

我的思路是：
1. 首先要尊重官方的格式规定，不管是标准还是学校的；
2. 方便用户使用，比如用英文写作时只需要改 `language=english` 一个地方的设置，而不必修改几个 `bst` 文件。如果有必要的话可以考虑拆分成多个 `bst` 文件，因为 ucas 的情况比较简单，就直接包在一个 LaTeX 宏里处理了。
3. 对于有定制需求的同学，只提供有限的支持（只能手动修改 `bst`）。

至于多个文件之间的关联，我觉得这个不是很重要，毕竟模板还是只供学校内部的同学使用，又不会被其他宏包或模板依赖。

**Comment by mohuangrui** [comment]
@zepinglee 已经根据你的建议弄好了，为了降低关联性，我将相关的宏封闭到了 cls 文件里，这样也就挺合理的了。再次感谢你的帮忙，你的维护工作量又增加了一个分支，幸苦了！

**Comment by mohuangrui** [comment]
@yunyun2019 请测试一下更新后的模版吧，若没问题，就可以关闭此issue了～

**Comment by yunyun2019** [comment]
不好意思，最近一直在准备考试，明天考完就测试，谢谢！



zhuyunyun2010@126.com
 
发件人： mohuangrui
发送时间： 2019-01-11 10:46
收件人： mohuangrui/ucasthesis
抄送： yunyun2019; Mention
主题： Re: [mohuangrui/ucasthesis] 文内引用英文文献时需要把“et al”变为“等”，但是同时后面的参考文献不变 (#95)
@yunyun2019 请测试一下更新后的模版吧，若没问题，就可以关闭此issue了～

**Comment by PNMZR** [comment]
我觉得问题在于他们根本没有交代清楚，撰写要求给的太粗心了，不知道还要坑多少届毕业生啊。国标GB/T 7714 -2015上清楚的这样规定：“10.2.2 正文引用多位著者的文献时，对欧美著者只需标注第一个著者的姓，其后附“et al.”; 对中文著者应该标注第一著者的姓名，其后附“等”字。姓氏与“et al.”“等”之间留适当空隙。”
所以说英文文献的就是 et al. 中文文献的就是等，不是统一et al.或者等。撰写要求给的太粗心了，所以大家都产生了误解，唉。

**Comment by zepinglee** [comment]
> 我觉得问题在于他们根本没有交代清楚，撰写要求给的太粗心了，不知道还要坑多少届毕业生啊。国标GB/T 7714 -2015上清楚的这样规定：“10.2.2 正文引用多位著者的文献时，对欧美著者只需标注第一个著者的姓，其后附“et al.”; 对中文著者应该标注第一著者的姓名，其后附“等”字。姓氏与“et al.”“等”之间留适当空隙。” 所以说英文文献的就是 et al. 中文文献的就是等，不是统一et al.或者等。撰写要求给的太粗心了，所以大家都产生了误解，唉。

国内大部分高校的学位论文要求是在 GB/T 7714 的基础上有所修改，所以也能说得过去。
