### ISSUE TITLE
关于artratex.bat脚本的使用请教

### ISSUE THREAD

**Issue by yunyundong** [mohuangrui/ucasthesis#96]
我想问一下，我刚下载下来，win10环境，运行artratex.bat一次后，它设置的环境变量仅仅是针对Thesis.tex这一个tex文件吗？我的担心是，我电脑上还有其它tex文件，他们需要的编译器是pdflatex。我运行artratex.bat会更改我其他地方的tex文件配置吗？
另外，我重启电脑后，想使用Thesis.tex文件，是不是还得再运行一次artratex.bat?

> 关于artratex.bat里的一个知识点请教
```set TEXINPUTS=.//;%TEXINPUTS%
set BIBINPUTS=.//;%TEXINPUTS%
set BSTINPUTS=.//;%TEXINPUTS%

我想问一下，这个设置的环境变量是啥？在电脑系统变量处能查到这些新建的变量吗？
另外，%TEXINPUTS%，%TEXINPUTS%和%TEXINPUTS%的值是啥？

谢谢。

**Comment by yunyundong** [comment]
此外，还有这句命令是啥意思？
> start  " " /max "./Tmp/%FileName%.pdf"

这句中，start的是啥程序？ `/max` 大概指的的是啥？

**Comment by mohuangrui** [comment]
你好，artratex.bat 只在脚本本身的运行时设定相应的环境变量，不会修改系统全局的环境变量。 artratex.bat 的作用就是自动搜索并编译同一目录下的某一个.tex文件，因此，每次重新编译都需运行一次。你也可以不用脚本编译，详细信息请见 使用说明.pdf。 至于命令的详细解释，建议系统阅读关于 Dos 系统和Tex编译系统的书籍，否则，实难以在此解释清楚。
