### ISSUE TITLE
Got some error while add another Chapter into Mainmatter

### ISSUE THREAD

**Issue by shipleyxie** [mohuangrui/ucasthesis#97]
i am doing a simple test ,in which i want to add the same content as Chap_Guide ,append to the end 
%---------------------------------------------------------------------------%
%->> Main content
%---------------------------------------------------------------------------%
\input{Tex/Chap_Intro}
\input{Tex/Chap_Guide}
\input{Tex/Chap_Guide}
%---------------------------------------------------------------------------%
 while typing ./artratex.sh xa i got some error,
Did I missing some step?
Hope to get your kind help.

**Comment by mohuangrui** [comment]
Hello, sorry that I do not know the exact cause of your errors unless you can provide the .log file. However, you may consider creating a new Chap_Test.tex file instead of just adding a \input{Tex/Chap_Guide}, which could be a problem. Cheers.
