### ISSUE TITLE
pdf和latex源码无法关联？

### ISSUE THREAD

**Issue by yunyundong** [mohuangrui/ucasthesis#98]
通过点击生成的pdf不能链接到对应的生成pdf的latex源码，是设置的问题吗？

**Comment by zzxihep** [comment]
这种是IDE的问题，看你用的是什么IDE了

**Comment by zepinglee** [comment]
需要加 `-synctex=1` 参数

**Comment by yunyundong** [comment]
我如果是纯英文的话，没有问题。
我是觉得我是不是通过`\input{Tex/Frontpages}`这种方式编译的，所以才会导致pdf与latex源码链接不上？

**Comment by mohuangrui** [comment]
应该主要取决你所使用的IDE，Texmaker 应该是可以的。

**Comment by yunyundong** [comment]
我用的是texlive2017+texstudio
我猜没有关联的原因是不是这样的：我的代码主体放在了Tex/Frontpages, 直接编译的是Thesis.tex文件，在Thesis.tex文件内容是这样的`\input{Tex/Frontpages}`。 现在我点击生成的pdf，但是链接不到Tex/Frontpages.tex。 在这种情况下可以实现关联吗？

**Comment by mohuangrui** [comment]
你好，对于texstudio，导致出现链接失败的潜在原因有很多，如Google 搜索“Go to source code” function with texstudio”即可找到很多类似的问题。我没有使用过texstudio，也从不用这类链接功能。但个人猜测潜在原因可能是texstudio的功能局限性，无法连接 Tex 文件夹下的源文件。解决方案可能为将所有Tex下的子文件移动到和Thesis.tex的同一目录下进行索引和编译。当然，如果你还是倾向于将子文件放置于Tex文件夹下，那就可以考虑改用Texmaker，它应该是可以正确处理这一结构的。
祝好

**Comment by mohuangrui** [comment]
@yunyundong 希望你的问题也解决，那我先关闭此issue了。若坚持使用LaTeX，其实不必为这类辅助功能所束缚困扰，通过不断编写和阅读LaTeX源文件，你会发现到后来即是是写完一整篇大论文，也少有错误存在，更无须借用这类链接功能来帮助写作。纠结外器终不如打磨自身，以后你会发现，用至简的Vim来写LaTeX才最是畅快～
